### ISSUE TITLE
0.4.3.88 check_pdh warn and crit thresholds are not respected

### ISSUE THREAD

**Issue by feisenko** [mickem/nscp#100]
Hi,
I have tried different counter and threshold values, all are saying "OK:..." (return code 0).
Example:
check_nrpe -H 192.168.2.1 -p 5666 -c check_pdh -a "counter=\\700(_Total)\\702"  "warn=value>80" "crit=value>90"
OK: |'\700(_Total)\702_value'=99;0;0
also tested with NSClient++ 0.4.3.127, output is verbose now, but warn and crit for value is still not respected:
OK: \700(_Total)\702 = 99|'\700(_Total)\702_value'=99;0;0

It is working with warning and critical, but isn't that only a synonym for warn and crit?
check_nrpe -H 192.168.2.1 -p 5666 -c check_pdh -a "counter=\\700(_Total)\\702" "warning=value>80" "critical=value>90" 
CRITICAL: \700(_Total)\702 = 99|'\700(_Total)\702_value'=99;80;90

**Comment by mickem** [comment]
Resolved in next build (out later tonight)

**Comment by mickem** [comment]
Fixed in 0.4.3.128 (found under nightly, of here on github)
