### ISSUE TITLE
Check_os_version returning critical?

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#102]
Hello,

I was just testing the check_os_version on 0.4.3.127 adn it seems it retruns CRITICAL when no arguments are passed. Is this intentional. I would have assumed an OK should be returned when no arguments are passed?

/usr/local/nagios/libexec/check_nrpe -H srv2012test -c check_os_version                                                                                                        [15-02-05 22:42:02]
CRITICAL: Windows 2012 (6.2.9200)|'version'=62;50;50

Grtz

**Comment by mickem** [comment]
Humm, should return ok unless os is less then XP which means NSClient++ does not run...

**Comment by mickem** [comment]
*sigh* there swapped... sorry...

**Comment by mickem** [comment]
Fixed, will be in next build...

**Comment by mickem** [comment]
Fixed in 0.4.3.129

**Comment by willemdh** [comment]
Thanks Michael, I will test this next week and let you know if it works as expected.
