### ISSUE TITLE
Incorrect check_memory output

### ISSUE THREAD

**Issue by der-eismann** [mickem/nscp#104]
Hi,

I just tried to setup a check_memory service, but the output doesn't follow your wiki. I entered:
`./check_nrpe -H 172.17.21.22 -c check_memory -a "top-syntax=${list}" "detail-syntax=${type} free: ${free} used: ${used} size: ${size}"
OK memory within bounds.|'committed'=0.5094GB;1.49876;1.68611;0;1.87345 'committed %'=27%;79;89;0;100 'physical'=0.48839GB;1.49876;1.68611;0;1.87345 'physical %'=26%;79;89;0;100`

According to your Wiki the output should be something like 
`page free: 16G used: 7.98G size: 24G, physical free: 4.18G used: 7.8G size: 12G`

What could be the problem here? Is there a way to achieve a clean output like:
`Physical: Free: 312 MB (21%) | Used 781 MB (69%) | Size: 1024 MB`

This would be really awesome. 
Greetings from Germany!

**Comment by mickem** [comment]
I don't update all the examples when I build new version so they are more "examples" of command line arguments and not exact output.

And that syntax should be pretty simple to achieve

The "old" command gives you:
```
D  w32system Created command: "detail-syntax=%(type): Total: %(size) - Used: %(used) (%(used_pct)%) - Free: %(free) (%(free_pct)%)"
L        cli OK: OK: committed: Total: 26.357GB - Used: 8.309GB (31%) - Free: 18.048GB (68%), physical: Total: 11.982GB - Used: 5.559GB (46%) - Free: 6.423GB (53%)
L        cli  Performance data: 'committed'=8.30948GB;21.08559;23.72128;0;26.35698 'committed %'=31%;79;89;0;100 'physical'=5.5586GB;9.58558;10.78378;0;11.98198 'physical %'=46%;79;89;0;100
```

Notice the "changed command line" which is what gives a good idea how to customize the output
