### ISSUE TITLE
0.4.3.88 - CheckServiceState and check_service do not work

### ISSUE THREAD

**Issue by gitmopp** [mickem/nscp#105]
CheckServiceState and check_service do not work with the latest version.
Example for 0,4,1,105:
<pre>
# ./check_nrpe -H MyOldHost -c CheckServiceState -a ShowAll COMSysApp CertPropSvc "dhcp=stopped"
CRITICAL: COMSysApp: started, CertPropSvc: started, dhcp: started (critical)
</pre>
Same check for 0.4.3.88
<pre>
# ./check_nrpe -H MyNewHost -c CheckServiceState -a ShowAll COMSysApp CertPropSvc "dhcp=stopped"
OK: COMSysApp: running, CertPropSvc: running, dhcp: running|

# ./check_nrpe -H MyNewHost -c check_service -a service=COMSysApp service=CertPropSvc service=dhcp "crit=not state_is_perfect()"
OK: , delayed ()|
</pre>

I alway get OK, even when I stop services.

**Comment by mickem** [comment]
Should be resolved in next build

**Comment by gitmopp** [comment]
Thank you for the quick fix.
Some information for the new command check_service:
The crit= not state_is_perfect() does not work the way I expected it to work. I simply want to get a critical alert if one of my defined services are stopped for some reason.
Maybe you can add this example to the documentation. The check will get critical if one of the services has the status not running. Instead of "crit=state != 4" it is also possible to use "crit=state != 'running'", but this requires nasty meta chars. The Windows command "sc query" shows the available states and numbers.
<pre>
./check_nrpe -H MyNewHost -c check_service -a service=COMSysApp service=CertPropSvc service=dhcp "crit=state != 4"
</pre>

**Comment by mickem** [comment]
There are non nasty syntaxes as well along the following lines...

```
"crit=state ne str(running)",
```
