### ISSUE TITLE
pb with checkServiceState command with "on-demand" services on 2012r2 server - 0.4.3.77

### ISSUE THREAD

**Issue by o2technique** [mickem/nscp#106]
Hello,
On a Windows server 2012 r2, the remote registry service has an automatic type of starting with "on-demand". This service stops after 10 minutes. 
I would like to monitor the services of this server. 
The following configurations of nsclient gives me an alert when the service stops (CRITICAL: RemoteRegistry: stopped delayed () - and this service is NOT delayed it is only on-demand)

Configuration 1:
[/settings/check/system/windows/service mapping]
DEMAND_START=ignored
AUTO_START=started
DELAYED=started

Configuration2:
[/settings/system/windows/service mapping]
DEMAND_START=ignored
AUTO_START=started
DELAYED=started

What's wrong in my configuration ?

Regards,
Patricia Renault

**Comment by mickem** [comment]
That configuration is not used anymore in 0.4.3...
You can write expressions instead...

// MIchael Medin

**Comment by o2technique** [comment]
Thanks for your really quick reply.
I tried check_service with expression but I did'nt find the expression for not taking into acccount the services with "on demand" starting type.
I have tried:
[root@]# ./check_nrpe -H XXX -c check_service -a "filter=start_type not in ('demand')"  
CRITICAL: RemoteRegistry=stopped (auto), TrustedInstaller=stopped (auto), delayed (sppsvc=stopped (delayed))|
The remoteregistry service is shown as auto starting but when I look at the services on the server it says something like  'automatic (start on demand)'. Do nsclient manage this kind of starting type ?
Regards,
Patricia Renault
PS: here is a link to a brief description of this starting type: http://news.thewindowsclub.com/windows-8-introduce-services-startup-type-start-demand-35708/

**Comment by mickem** [comment]
Does it say automatic delayed start maybe?
Demand and delayed in not the same...

You can use the sc tool to see details on services
```
sc qc efs
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: efs
        TYPE               : 20  WIN32_SHARE_PROCESS
        START_TYPE         : 3   DEMAND_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : C:\WINDOWS\System32\lsass.exe
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : Encrypting File System (EFS)
        DEPENDENCIES       : RPCSS
        SERVICE_START_NAME : LocalSystem
```

**Comment by mickem** [comment]
please reopen this with more information if the issue still presists...
