### ISSUE TITLE
Problem with MinWarn on CheckFiles 0.4.3.88

### ISSUE THREAD

**Issue by Marc--** [mickem/nscp#107]
Hi,

I'm using CheckFiles to check if at least a file was created in less than 1d.

Windows 2008 server, NSCP 0.4.3.88.

Syntax is:
check_nrpe -H xxx -c CheckFiles -a path="F:\_SAVEPATH" pattern="save*.cod" filter="creation gt -1d" "syntax=%filename%: %size%" MinWarn=1

Result is :
save032a_cat_beaulieu.cod: 6240183452|'count'=1;1;0

Filter is OK, but "MinWan=1" is not working. There is no exit code with result.

On the target server, "nscp test" shows :
D       nrpe Accepting connection from: xxx, count=1
D       disk Created command: warn=count<=1 "filter=creation gt -1d" pattern=save*.cod "detail-syntax=%(filename): %(size)" top-syntax=${list} path=F:\_SAVEPATH empty-state=ok
D       disk Input is: F:\_SAVEPATH / 16
D       disk File pattern: F:\_SAVEPATH\save*.cod
D       disk File pattern: F:\_SAVEPATH\*.*

I'm maybe wrong, but looks like a bug ?

Thanks a lot for your job.

Regards,
Marc

**Comment by mickem** [comment]
This is a know issue, will be fixed in 0.4.4

**Comment by mickem** [comment]
The first release of 0.4.4. is out on github now https://github.com/mickem/nscp/releases/tag/0.4.4.2 PLEASE BEWARE this is the very very first alpha release of 0.4.4 so use with caution, a lot of testcases still fail...

**Comment by mickem** [comment]
This is resolved in 0.5.0, if not please reopen
