### ISSUE TITLE
Performance data warning/critical incorrect

### ISSUE THREAD

**Issue by awiddersheim** [mickem/nscp#111]
I have noticed some weird issues with the warning/critical levels in the performance data. Specifically, I was doing things with `check_memory()` but other modules may be affected also.

I am using the following version:

```NSClient++, Version: 0.4.3.130 2015-02-11, Platform: x64```

I am running the following:

```check_memory show-all "filter=type = 'physical'" "warning=used > 90%"```

Here is the performance data I get back:

```Performance data: 'physical'=1.13817GB;3.5996;3.5996;0;3.99956 'physical %'=28%;89;89;0;100```

The first problem I see is that I only specified a warning level yet both a warning AND a critical level were specified in the performance data. So I'd expect the following:

```'physical %'=28%;89;;0;100```

Second problem is the actual number of the warning level which is ```89```. I'd expect this to be ```90```. Even if I do ```"warning=used >= 90%"``` I sill get ```89```.

Perhaps this is by design... but I'm hoping it is a bug. Seems off to me.

**Comment by mickem** [comment]
This is due to the fact that the 90% is calculated over to a real size i.e. 3.5996 gb and then calculated back to a %:age.
Fixing this would probably not be simple and not sure it is worth fixing. So is it an issue or something we can live with?

**Comment by awiddersheim** [comment]
Thanks for the explanation. If you are asking my opinion I'd say that this is an issue. Let me explain why. When we graph the performance data (using pnp4nagios) we will more times than not also graph the warning/critical thresholds as well and put the number at which those thresholds are configured on the graphs. We have a lot of people look at and use those graphs.

If that number is different than what my clients/customers/users are expecting they will think the checks and thresholds have been misconfigured. At which point I'd need to explain that it's just an "oddity" with the system or whatever.

Not only is the number slightly off but it's also throwing back a critical threshold when I'm not actually setting one, which again will get graphed. This will inevitably bring up the same conversation when people look at the graphs and think "this check shouldn't have a critical level" and will come to me thinking there is some kind of configuration issue. It is not uncommon that we configured checks to not having warning/critical levels by design and for the graph to represent them would throw people off.

I get how one can think it's a small issue and can understand that it is probably a pain to fix. Hopefully, I did an okay job of making a case as to why it's an issue coming from someone who has a lot of checks and a lot of users who will notice this type of thing.

**Comment by mickem** [comment]
right, will fix for 0.4.4

**Comment by awiddersheim** [comment]
I'd like to start using a newer version of NSClient++ but can't really do so until this particular issue is fixed. Unfrotunately, it is somewhat difficult to go back through my environment and retrofit installs easily when a version gets released with this bug fixed.

How can I help move this along faster. If you point me in the right direction I might be able to help with some of the work.

**Comment by davmik** [comment]
Hi,

same problem here. Furthermore there seems to be a problem in the transfer of individual thresholds for drives into performance data.

Example arguments for check_drivesize:
> "perf-config=free(unit:M)" filter="type in ('fixed','remote')" "drive=all-drives" warn="(free<15% and drive not in ('H:\\')) or (free<2G and drive in ('H:\\') )" crit="(free<5% and drive not in ('H:\\')  or (free<1G and drive in ('H:\\ ')))"

After executing with those argumentes it returns:
> OK All 4 drive(s) are ok|'C:\ free'=83525.70312M;36613.51992;12204.50664;0;244090.13281 'C:\ free %'=34%;14;4;0;100 'F:\ free'=185599.99218M;35616.29941;11872.0998;0;237441.99609 'F:\ free %'=78%;14;4;0;100 'G:\ free'=810.77734M;153.59941;51.1998;0;1023.99609 'G:\ free %'=79%;14;4;0;100 'H:\ free'=153607.58203M;35770.04941;11923.3498;0;238466.99609 'H:\ free %'=64%;14;4;0;100

As you can see alle perf-data values are based on the first warn or crit condition but not the special defined one for 'H:\'.
For drive H:\ perf-data should be something like:
> 'H:\ free'=153607.58203M;1024.0;2048.0;0;238466.99609

shouldn't it?

**Comment by mickem** [comment]
This issue is relating to the rounding of performance data
Please open a new ticket for the other issue.

As for the other issue it is a known issue and you need to migrate your checks to use the new syntax (manually) in such cases.
The reason for it being a manual migration is the ambiguity of how it worked in the previous versions.
Then bounds were position based which have been removed in 0.4.2 (and subsequent versions).
But as I said, please open new tickets for new issues, it gets difficult for me to keep tracks of things...

**Comment by awiddersheim** [comment]
Any comments on what I can do to help move this along?

https://github.com/mickem/nscp/issues/111#issuecomment-77386585

**Comment by mickem** [comment]
The Rounding issue or the migration issue ?

**Comment by awiddersheim** [comment]
The rounding issue.

**Comment by mickem** [comment]
Well, it is on my todo list for 0.4.4 so expect it fall maybe (will probably try to release 0.4.4 for OSMC) ? But it depends, currently I am rather busy but hopefully things will slow down in a week or so...

And not much to do really, I always accept pull request and if you want to sponsor the feature I could probably expidite things a bit...

But the loose TODO looks something like this (main reason for ordering is dependencies): 

* New client interface (almost done)
* Metrics collection
* Cache module with check support
* floating point support
* various other bug fixes and enhancements

**Comment by mickem** [comment]
This (the rounding issue) has been fixed in the next build.
