### ISSUE TITLE
Am hoping I'm just doing something wrong here...

### ISSUE THREAD

**Issue by BubbaOpus** [mickem/nscp#112]
just installed core NSClient++ 0.4.3.88 2015-01-11 x64.
calling from Nagios via NRPE commands... 

../../libexec//check_nrpe -H servername.com -p 5666 -c CheckCounter -a "Counter=\\Web Service(_Total)\\Current Connections" MinWarn=5 MinCrit=0 MaxWarn=50 MaxCrit=100 ShowAll
OK: |'\Web Service(_Total)\Current Connections'=160;0;0

By previous usage, this should've raised a flag.
am also not seeing perf data being stored from the above call...
am able to reproduce in the Windows client in test mode.

**Comment by mickem** [comment]
Pretty sure having multiple different bounds (i.e. Max/Min) is currently not supported in the compatibility layer...
I'll see if I can add it in then...

i.e.
```
...MinWarn=5 MinCrit=0... # works
...MaxWarn=50 MaxCrit=100... # Works
...MinCrit=0 MaxWarn=50... # Does not work I think...
```

**Comment by BubbaOpus** [comment]
My original version was a simply warn and critical for higher numbers.

here's a live shot.

check_nrpe -H {servername} -p 5666 -c CheckCounter -a "Counter=\\Web Service(_Total)\\Current Connections" MaxWarn=150 MaxCrit=200

OK: |'\Web Service(_Total)\Current Connections'=267;0;0

**Comment by mickem** [comment]
That should work, could you paste me the debug log from that invocation?

**Comment by BubbaOpus** [comment]
And now its working. Am going to chalk this up to sunspots...
