### ISSUE TITLE
CHECK_NRPE: Invalid packet type received from server.

### ISSUE THREAD

**Issue by cvanaxel** [mickem/nscp#115]
I saw in one of your post that you fixed this bug.

Im running the latest version and I get this issue.

Nagios:
./check_nrpe -n -H 1XX.X.X.X -c check_citrix_sessies

script(check_sessies.ps1):
$SPAdmin = "DOMAIN\USER" 
$Password = Get-Content C:\Temp\securestring.txt | convertto-securestring 
$Credential = new-object -typename System.Management.Automation.PSCredential -argumentlist $SPAdmin, $Password 

Add-PSSnapin Citrix.*
$Active = (Get-BrokerSession -MaxRecordCount 1100 -SessionState Active).count
$Disconnected = (Get-BrokerSession -MaxRecordCount 1100 -SessionState Disconnected).count
echo "Total active sessions: $Active & disconnected sessions: $Disconnected"
exit 0

nsclient.ini:
[/settings/external scripts/scripts]
check_citrix_sessies = cmd /c echo scripts\check_sessies.ps1; exit ($lastexitcode) | powershell.exe -command -

[/settings/external scripts]
allow arguments = true
allow nasty characters = true

**Comment by mickem** [comment]
Define latest version (please use version numbers)...

Please provide output of check_nrpe as well as debug log from NSClient++

**Comment by cvanaxel** [comment]
Version: NSCP-0.4.3.88-x64

There is no debug log from nsclient++

The only bug i get is: CHECK_NRPE: Invalid packet type received from server.

**Comment by mickem** [comment]
There we have it, the comment about me fixing it in #83 read: "0.4.3.102 should fix this issue, please reopen if issue still persists..." so if you are on 0.4.3.88 you are not using the latest (and fixed) version...

Pleas reopen if you still have this issue with a more recent version.
