### ISSUE TITLE
Settings not ready on Win2008 Server, 32 Bit

### ISSUE THREAD

**Issue by miodo2010** [mickem/nscp#116]
Hi,
we are monitoring among others several Win2008-Server (32Bit) with NagiosXI. NSClient++ Version is 0.4.3.77. Only on one machine we are facing the issue, that no check is executed. Running "nscp test" shows up the following:

    C:\Program Files\NSClient++>nscp test
    L     client Module: CommandClient
    L     client Command:
    L     client Extra Query:
    L     client Mode: 3
    L     client Boot: 1
    L     client Load All: 0
    L     client Warning module and boot specified only THAT module will be loaded
    L     client Arguments:
    D       core NSClient++ 0,4,3,77 2015-01-04 w32 Loading settings and logger...
    D       core Settings not ready so we cant lookup: base-path
    D       core Settings not ready so we cant lookup: exe-path
    D   settings No entries found looking in (adding default): C:\Program Files\NSCl
    ient++/boot.ini
    D       core Settings not ready so we cant lookup: exe-path
    D       core Settings not ready so we cant lookup: shared-path
    D   settings Activating: ini://${shared-path}/nsclient.ini
    D   settings Creating instance for: ini://${shared-path}/nsclient.ini
    D       core Settings not ready so we cant lookup: shared-path
    D   settings Loading: C:\Program Files\NSClient++/nsclient.ini
    D       core NSClient++ 0,4,3,77 2015-01-04 w32 booting...
    D       core Booted settings subsystem...
    D       core booting::loading plugins
    D       core Found: CheckDisk
    D       core Found: CheckEventLog
    D       core Found: CheckExternalScripts
    D       core Found: CheckHelpers
    D       core Found: CheckNSCP
    D       core Found: CheckSystem
    D       core Found: NRPEServer
    D       core Found: NSClientServer
    D       core C:\Program Files\NSClient++/modules\CheckDisk.dll.dll
    D       core adding C:\Program Files\NSClient++/modules\CheckDisk.dll
    D       core C:\Program Files\NSClient++/modules\CheckEventLog.dll.dll
    D       core adding C:\Program Files\NSClient++/modules\CheckEventLog.dll
    D       core C:\Program Files\NSClient++/modules\CheckExternalScripts.dll.dll
    D       core adding C:\Program Files\NSClient++/modules\CheckExternalScripts.dll
    D       core C:\Program Files\NSClient++/modules\CheckHelpers.dll.dll
    D       core adding C:\Program Files\NSClient++/modules\CheckHelpers.dll
    D       core C:\Program Files\NSClient++/modules\CheckNSCP.dll.dll
    D       core adding C:\Program Files\NSClient++/modules\CheckNSCP.dll
    D       core C:\Program Files\NSClient++/modules\CheckSystem.dll.dll
    D       core adding C:\Program Files\NSClient++/modules\CheckSystem.dll
    D       core C:\Program Files\NSClient++/modules\NRPEServer.dll.dll
    D       core adding C:\Program Files\NSClient++/modules\NRPEServer.dll
    D       core C:\Program Files\NSClient++/modules\NSClientServer.dll.dll
    D       core adding C:\Program Files\NSClient++/modules\NSClientServer.dll
    D       core Loading plugin: CheckDisk
    D       core Loading plugin: CheckEventLog
    D       core Loading plugin: CheckExternalScripts
    D       core Loading plugin: CheckHelpers
    D       core Loading plugin: CheckNSCP
    D check_nscp Crash folder is: C:\Program Files\NSClient++
    D       core Loading plugin: CheckSystem
    D       core Loading plugin: NRPEServer
    D       nrpe Allowed hosts definition: 10.90.1.86(255.255.255.255), 10.90.210.19
    9(255.255.255.255), 10.90.1.90(255.255.255.255), 10.90.1.92(255.255.255.255)
    D       nrpe Binding to: [::]:5666(ipv6)
    D       nrpe Attempting to bind to: [::]:5666(ipv6)
    D       nrpe Binding to: 0.0.0.0:5666(ipv4), reopen: true, reuse: true
    D       nrpe Attempting to bind to: 0.0.0.0:5666(ipv4)
    D       core Loading plugin: NSClientServer
    D   check_nt Allowed hosts definition: 10.90.1.86(255.255.255.255), 10.90.210.19
    9(255.255.255.255), 10.90.1.90(255.255.255.255), 10.90.1.92(255.255.255.255)
    D   check_nt Binding to: [::]:12489(ipv6)
    D   check_nt Attempting to bind to: [::]:12489(ipv6)
    D   check_nt Binding to: 0.0.0.0:12489(ipv4), reopen: true, reuse: true
    D   check_nt Attempting to bind to: 0.0.0.0:12489(ipv4)
    D       core NSClient++ - 0,4,3,77 2015-01-04 Started!
    D       core C:\Program Files\NSClient++/modules\CommandClient.dll.dll
    D       core adding C:\Program Files\NSClient++/modules\CommandClient.dll
    D       core Loading plugin: CommandClient.dll...
    D        cli Enter command to execute, help for help or exit to exit...

Looks qute good apart from the "Settings not ready" messages... Any ideas?

BR,

Michael

**Comment by mickem** [comment]
Might wanna paste the content of boot.ini and the [/paths] section in nsclient.ini but I would not worry to much about it.
It means that someone is requesting a configurable key before the configuration is loaded and thus get the default value...

**Comment by miodo2010** [comment]
In the installation path of NSClient there is no boot.ini. Also there is no [/paths] section in my nsclient.ini.

The problem is that only on this machine nsclient is not answering to any check-commands.

**Comment by mickem** [comment]
the problem is probably related to something else.

How does "not answering to any check-commands" manifest it self?

**Comment by mathieuchateau** [comment]
Hello,

Also check for firewall issue, like Windows one
does telnet to nsclient port (5666) works from monitoring?


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-03-03 9:40 GMT+01:00 Michael Medin <notifications@github.com>:

**Comment by miodo2010** [comment]
Sorry guys! I just wanted to reproduce the error message to answer mickem's last question but suddenly everything looks good and running... Will check out what happened and come back with the result later this day.

**Comment by miodo2010** [comment]
It looks like the installation of NagiosClient++ got corrupted somehow. Our software-distribution-service made a re-install last night and everything works fine again.

It up to me to say sorry for bothering and many thanks for your help! :-)

**Comment by mickem** [comment]
No worries... glad it worked out...
