### ISSUE TITLE
0.4.3.131 - listCounterInstances - Unknown command(s)

### ISSUE THREAD

**Issue by mathieuchateau** [mickem/nscp#117]
I don't know since which version, but on this one it's not working from check_nrpe and using nscp test

any clue ?

**Comment by mickem** [comment]
check_nrpe? No, has never been a check nrpe command, it is a check_nt command.
There is a command line interface for listing them, do you need to do so remotely?

**Comment by mickem** [comment]
To claerify check_nt has a list instances option, has never been (except maybe by accident?) a check_nrpe command which does that.

**Comment by mathieuchateau** [comment]
Hello,
sorry i made bad asumption using bad bash_history check_nrpe test, a shame.

Everything works as expected, i just notice the string "none" is added to performance counter data:

OK: LogicalDisk_free_space = 42|'LogicalDisk_free_spacenone'=42;30;20

issued command:
check_nrpe -H 1.2.3.4 -t 30 -c checkCounter -a Counter:'LogicalDisk_free_space'="\LogicalDisk(C:)\% Free Space"
MinWarn=30 MinCrit=20 ShowAll
