### ISSUE TITLE
0.4.3.88 - Check_nt uptime returns wrong value

### ISSUE THREAD

**Issue by skeith92** [mickem/nscp#118]
I found this bug on nscp version 0.4.3.88 that doesn't appear on any 0.3.x version, I opened a ticket on the nagios support for this [here](http://support.nagios.com/forum/viewtopic.php?f=34&t=31774&sid=7665473ab9ca9170772dbdb885022e37)

The uptime check will return a wrong value, seconds are like a floating numbers, here's my tests:

```
./check_nt -H host -p 12489 -s password -v UPTIME -l seconds
```

results:

```
System Uptime - 392 day(s)  6 hour(s) 8 minute(s) |uptime=33890897
System Uptime - 392 day(s) 6  hour(s) 8 minute(s) |uptime=33890898
System Uptime - 392 day(s) 6  hour(s) 8 minute(s) |uptime=33890899
System Uptime - 3   day(s) 22 hour(s) 8 minute(s) |uptime=338909
```

**Comment by mickem** [comment]
This is handled by the check_nt plugin NSCLient++ only returnes a value so this should be raiset at nagios. https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_nt.c#L198-L234
