### ISSUE TITLE
NSClient version 0.4.3.136-x63 always returns zero

### ISSUE THREAD

**Issue by csantanabr** [mickem/nscp#119]
I am using the following command

./check_nrpe -H IP_HOST -c CheckCounter -a "Counter=\LogicalDisk(C:)\Disk Transfers/sec"

always returns
OK: \LogicalDisk(C:)\Disk Transfers/sec = 0|'\LogicalDisk(C:)\Disk Transfers/secnone'=0;0;0

And using the zabbix agent, I know that these values are fractionated example 1.15 sec

![averages](https://cloud.githubusercontent.com/assets/11429190/6604206/b05cc22c-c805-11e4-9a71-9487250be974.png)

**Comment by mathieuchateau** [comment]
you are missing argument
working one (:LogicalDiskTransferPerSec):
./check_nrpe -H IP_HOST -c CheckCounter -a
"Counter:LogicalDiskTransferPerSec=\LogicalDisk(C:)\Disk Transfers/sec"

Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-03-11 19:46 GMT+01:00 csantanabr <notifications@github.com>:

**Comment by mathieuchateau** [comment]
the was wrong, i set the name but it's not mandatory.
Your command works too even if i often get 0;0;0 too (idle server)


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-03-11 19:58 GMT+01:00 Mathieu Chateau <mathieu.chateau@lotp.fr>:

**Comment by mickem** [comment]
Currently nsclient++ does not support floating points values when checking values so int is indeed used (and roundingtruncation occures)

**Comment by mickem** [comment]
This has been implemented now...
