### ISSUE TITLE
NSClient++ 0.4.3.131 Memory usage returns Double the real amount.

### ISSUE THREAD

**Issue by HeinHurter** [mickem/nscp#121]
NSClient++ 0.4.3.131 Memory usage returns Double the real amount.

I have just installed this new version on a few new servers and on all of them all the memory usage info returned to Nagios is double the real values,

eg this is the values returned:
Memory usage: total:24556.50 MB - used: 2252.89 MB (9%) - free: 22303.60 MB (91%)
Total should be 12gb and the rest is also double.

Thanks for a great plugin.

**Comment by mickem** [comment]
There are several memory metrics, if you are using check_nt you are limited to commited bytes which is ram+page, if you use check_nrpe you can customize this (default is to check all)

**Comment by HeinHurter** [comment]
Thanks Michael, I will have a look,
