### ISSUE TITLE
check_files not correctly reporting matches in 0.4.3.131

### ISSUE THREAD

**Issue by box293** [mickem/nscp#124]
When using the critical or warning argument and the conditions have been met, it still reports 0/x files. The CRITICAL state is correctly returned as 2.

Here's when no files have been matched (working correctly):
```
Command:
check_nrpe -H win2008r2-01 -c check_files -a file="c:\\Program Files\\NSClient++\\nsclient.log" "critical=size>1000k" "perf-config=size(unit:M)"

Output:
OK: All 1 files are ok|'nsclient.log size'=0.35725M;0;0.97656
```

Here's when the file has been matched (broken):
```
Command:
check_nrpe -H win2008r2-01 -c check_files -a file="c:\\Program Files\\NSClient++\\nsclient.log" "critical=size>100k" "perf-config=size(unit:M)"

Output:
CRITICAL: 0/1 files (nsclient.log)|'nsclient.log size'=0.35826M;0;0.09765
```

It should start with CRITICAL: <b>1</b>/1 files

**Comment by mickem** [comment]
Will be resolved in the next build

**Comment by mickem** [comment]
Build 136 fixes this issue: http://www.nsclient.org/download/nightly/
