### ISSUE TITLE
No output from Check_Memory (0.4.3.131)

### ISSUE THREAD

**Issue by DokuKaefer** [mickem/nscp#127]
Hello,

i have two servers where nothing in the Output. 
On the console and Nagios the performance data is showing.

See the attached prictures.

Server One = Hyper-V Host
Server Two = VM

On all other 40 Hosts/VMs it works correctly.

Server One:
![server_one_web](https://cloud.githubusercontent.com/assets/11537653/6708293/4097cdbe-cd6f-11e4-9f7e-2ebb01198a70.png)
![server_one_console](https://cloud.githubusercontent.com/assets/11537653/6708295/409a6326-cd6f-11e4-92e5-eefe2917f851.png)

Server Two:
![server_two_web](https://cloud.githubusercontent.com/assets/11537653/6708296/409ad0f4-cd6f-11e4-84e8-3514d79aea29.png)
![server_two_console](https://cloud.githubusercontent.com/assets/11537653/6708294/409a0b4c-cd6f-11e4-8421-09043be37623.png)

Greats

**Comment by DokuKaefer** [comment]
The percent output with %(free_pct) and %(used_pct) also unaccurate.

![percent](https://cloud.githubusercontent.com/assets/11537653/6708774/ad77f78e-cd73-11e4-97e3-066f94810a19.png)

**Comment by DokuKaefer** [comment]
Oh sorry, i have seen on both hosts the nsclient version is 0.4.3.88
I updated to 0.4.3.131 and it works. :)

But the percent inaccurate is still existent.

**Comment by DokuKaefer** [comment]
With commandline:

check_memory "type=physical" "detail-syntax=Total: %(size) Used: %(used) (%(used_pct)%) Free: %(free) (%(free_pct)%)" "warn=used > 85%" "crit=used > 95%" 

There is no output when i used warn and critical.

**Comment by mickem** [comment]
What your looking for is show-all.

By default the output does not include "ok" statuses...

This has changed in recent builds of 0.4.3 BTW so if you upgrade you should see the output

**Comment by mickem** [comment]
And sorry for the late reply, but has been very very busy at work last week...

**Comment by mickem** [comment]
Closing this, please reopen if this solution did not work...
