### ISSUE TITLE
0.4.3.131 and check_drivesize - Performance data is missing "used" when both warning and critical are used

### ISSUE THREAD

**Issue by box293** [mickem/nscp#129]
Warning by itself:
```
Command:
check_nrpe -H 10.25.254.142 -c check_drivesize -a drive=C: 'warning=free < 60G' show-all

Output:
WARNING warning(C:: 9.891GB/59.9GB used)|'C: free'=50.00968GB;60;0;0;59.90038 'C: free %'=83%;100;0;0;100 'C: used'=9.8907GB;0;53.91034;0;59.90038 'C: used %'=16%;0;89;0;100
````

Critical by itself:
```
Command:
check_nrpe -H 10.25.254.142 -c check_drivesize -a drive=C: 'critical=free < 60G' show-all

Output:
CRITICAL critical(C:: 9.924GB/59.9GB used)|'C: free'=49.97672GB;0;60;0;59.90038 'C: free %'=83%;0;100;0;100 'C: used'=9.92366GB;47.9203;0;0;59.90038 'C: used %'=16%;79;0;0;100
```

Both used together:
```
Command:
check_nrpe -H 10.25.254.142 -c check_drivesize -a drive=C: 'warning=free < 60G' 'critical=free < 5G' show-all

Output:
WARNING warning(C:: 9.924GB/59.9GB used)|'C: free'=49.97644GB;60;5;0;59.90038 'C: free %'=83%;100;8;0;100
```
Notice how the two "used" metrics are now missing.

Same applies if critical is the state:
```
Command:
check_nrpe -H 10.25.254.142 -c check_drivesize -a drive=C: 'warning=free < 70G' 'critical=free < 60G' show-all

Output:
CRITICAL critical(C:: 9.924GB/59.9GB used)|'C: free'=49.97618GB;70;60;0;59.90038 'C: free %'=83%;116;100;0;100
```

Also, one other observation is the duplication of the state:

WARNING warning
CRITICAL critical

**Comment by mickem** [comment]
This is due to the implicit arguments.

```
check_drivesize  show-default
L        cli OK: "warning=used > 80%" "critical=used > 90%" "empty-state=unknown" "top-syntax=${status} ${problem_list}" "ok-syntax=%(status) All %(count) drive(s) are ok" "empty-syntax=%(status): No drives found" "detail-syntax=${drive_or_name}: ${used}/${size} used" "perf-syntax=${drive_or_id}"
```
Thus the default (if you do not specify one) is:
```
..."warning=used > 80%" "critical=used > 90%"...
```

SO what happens when you run:
```
check_nrpe -H 10.25.254.142 -c check_drivesize -a drive=C: 'warning=free < 60G' show-all
```

Is actually this:
```
check_nrpe -H 10.25.254.142 -c check_drivesize -a drive=C: 'warning=free < 60G' show-all "critical=used > 90%"...
```

And the performance data is seeded from your bounds so if you check used you get used bounds, if you check free you get free bounds, and so on and so forth...

**Comment by box293** [comment]
So how do you ONLY provide a warning OR critical threshold? How do you prevent "critical=used > 90%" being inherited by the implicit arguments?

Also, I noticed above in my two examples, the non-supplied argument is added to the performance data string as 0 when it should be omitted:

```
WARNING warning(C:: 9.891GB/59.9GB used)|'C: free'=50.00968GB;60;0;0;59.90038 'C: free %'=83%;100;0;0;100 'C: used'=9.8907GB;0;53.91034;0;59.90038 'C: used %'=16%;0;89;0;100
```
This should be:
```
'C: free'=50.00968GB;60;;0;59.90038 'C: free %'=83%;100;;0;100
```

**Comment by mickem** [comment]
Ahh, like setting warn=none you mean?

**Comment by box293** [comment]
Yes that could be a viable solution.

Personally I don't like default thresholds being defined on checks. Some people simply wish to collect performance data and not be worried about warning or critical states.

As an alternative solution that could be used with many different checks, something like:

```
default-thresholds=false
```

So using that by itself could allow a check to run without any warning or critical thresholds being processed.

Or if you only wanted critical you could have:

```
default-thresholds=false 'critical=free < 60G'
```

**Comment by mickem** [comment]
For 0.4.4 the default values will be configurable (thats the plan anyways).
That in conjunction with "modules" will allow you to simply load a module which has the defaults you like.

**Comment by mickem** [comment]
(as for the warn=none that works already BTW)

**Comment by box293** [comment]
Ahh right sorry I didn't realise warn=none was a real argument LOL
