### ISSUE TITLE
0.4.3.131 and check_service - state_is_ok() does not work as expected

### ISSUE THREAD

**Issue by box293** [mickem/nscp#130]
Lets say I have a service that I want to be in a stopped state. So it's OK when it's stopped and Critical when it's running.

Here is the output when the service is running:
```
Command:
check_nrpe -H 10.25.254.142 -c check_service -a 'service=spooler' 'critical=state_is_ok()'

Output:
CRITICAL: spooler=running (auto), delayed ()
```
This is correct, it should be critical because it is running.

Here is the output when the service is stopped:
```
Command:
check_nrpe -H 10.25.254.142 -c check_service -a 'service=spooler' 'critical=state_is_ok()'

Output:
WARNING: , delayed (spooler=stopped (auto))
```
This is wrong in reporting WARNING, it should be reporting OK.

Am I using the syntax correctly? I've also tried:
```
Command:
check_nrpe -H 10.25.254.142 -c check_service -a 'service=spooler' 'critical=state_is_ok()' 'ok=not state_is_ok()'

Output:
WARNING: , delayed (spooler=stopped (auto))
```

**Comment by mickem** [comment]
state_ok and state_perfect are in essence macros for working with delayed services. so a service which is delayed is not a critical state.

If you want to check if a service is started use the started and running and such values instead.

```
... critical=state = 'stopped' ...
```

**Comment by box293** [comment]
```
Command:
check_nrpe -H win2008r2-01 -c check_service -a 'service=spooler' critical=state = 'stopped'

Output:
CHECK_NRPE: Invalid packet type received from server.
```
or
```
Command:
check_nrpe -H win2008r2-01 -c check_service -a 'service=spooler' 'critical=state = stopped' debug

Output:
Failed to validate filter see log for details|
```

Which logs this:
```
2015-04-09 07:54:41: debug:D:\source\nscp\include\nrpe/server/protocol.hpp:74: Accepting connection from: 10.25.254.50, count=1
2015-04-09 07:54:41: debug:D:\source\nscp\include\parsers\filter\modern_filter.cpp:18: Parsing: not state_is_perfect()
2015-04-09 07:54:41: debug:D:\source\nscp\include\parsers\filter\modern_filter.cpp:18: Parsing succeeded: ? ( (string)fun:state_is_perfect ) 
2015-04-09 07:54:41: debug:D:\source\nscp\include\parsers\filter\modern_filter.cpp:18: Type resolution succeeded: ? ( (string)fun:state_is_perfect ) 
2015-04-09 07:54:41: debug:D:\source\nscp\include\parsers\filter\modern_filter.cpp:18: Binding succeeded: ? ( (string)fun:state_is_perfect ) 
2015-04-09 07:54:41: debug:D:\source\nscp\include\parsers\filter\modern_filter.cpp:18: Static evaluation succeeded: ? ( (string)fun:state_is_perfect ) 
2015-04-09 07:54:42: debug:D:\source\nscp\include\parsers\filter\modern_filter.cpp:18: Parsing: state = stopped
2015-04-09 07:54:42: debug:D:\source\nscp\include\parsers\filter\modern_filter.cpp:18: Parsing succeeded: (tbd){(int)var:state = (i){0}}
2015-04-09 07:54:42: debug:D:\source\nscp\include\parsers\filter\modern_filter.cpp:11: Invalid types: Variable not found: stoppedVariable not found: stopped
```

**Comment by mickem** [comment]
Command should be:

    check_nrpe -H win2008r2-01 -c check_service -a 'service=spooler' "critical=state = 'stopped'"

The filter needs 'qoute' around strings

**Comment by box293** [comment]
OK great that's the key thing I was missing, thanks for that.

Is there a way to disable the performance data being returned by check_service ? 
```
OK: All 1 service(s) are ok.|'spooler'=4;0;1

CRITICAL: spooler=stopped (auto), delayed ()|'spooler'=1;0;1
```

I tested with 0.5.0.17 and I get the same output.

**Comment by mickem** [comment]
sort of...

something along the lines of: "perf-config=*(ignored:true)"

**Comment by mickem** [comment]
Interestingly enough when testing this I got no performance data... wonder if I have broken something...

Here you hva it for check_spu (should work the same):

    check_cpu
    L        cli OK: OK: CPU load is ok.
    L        cli  Performance data: 'total 5m'=4%;80;90 'total 1m'=4%;80;90 'total 5s'=4%;80;90

    check_cpu "perf-config=*(ignored:true)
    L        cli OK: OK: CPU load is ok.

**Comment by box293** [comment]
Got it, works a treat thanks very much.

```
check_nrpe -H win2008r2-01 -c check_service -a 'service=spooler' "critical=state = 'stopped'" "perf-config=*(ignored:true)"

OK: All 1 service(s) are ok.|

CRITICAL: spooler=stopped (auto), delayed ()|
```

I did check the manual first but perf-config is in a to-do state.

I just double checked and the perfdata comes out (in 0.4.3.121 or 0.5.0.17) however using the perf-config stops it anyway.

**Comment by box293** [comment]
FYI it seems as though when you add the "critical=state = 'stopped'" it adds the performance data.

```
check_nrpe -H win2008r2-01 -c check_service -a 'service=spooler'
CRITICAL: spooler=stopped (auto), delayed ()|

check_nrpe -H win2008r2-01 -c check_service -a 'service=spooler' "critical=state = 'stopped'"
CRITICAL: spooler=stopped (auto), delayed ()|'spooler'=1;0;1
```

**Comment by mickem** [comment]
perfdata should be there always I think... Ill reopen for now...
