### ISSUE TITLE
Threshold transfer to perfdata incorrect

### ISSUE THREAD

**Issue by davmik** [mickem/nscp#132]
It seems that there is a problem in the transfer of individual thresholds for drives into performance data.

Example arguments for check_drivesize:

"perf-config=free(unit:M)" filter="type in ('fixed','remote')" "drive=all-drives" warn="(free<15% and drive not in ('H:\')) or (free<2G and drive in ('H:\') )" crit="(free<5% and drive not in ('H:\') or (free<1G and drive in ('H:\ ')))"
After executing with those argumentes it returns:

OK All 4 drive(s) are ok|'C:\ free'=83525.70312M;36613.51992;12204.50664;0;244090.13281 'C:\ free %'=34%;14;4;0;100 'F:\ free'=185599.99218M;35616.29941;11872.0998;0;237441.99609 'F:\ free %'=78%;14;4;0;100 'G:\ free'=810.77734M;153.59941;51.1998;0;1023.99609 'G:\ free %'=79%;14;4;0;100 'H:\ free'=153607.58203M;35770.04941;11923.3498;0;238466.99609 'H:\ free %'=64%;14;4;0;100
As you can see alle perf-data values are based on the first warn or crit condition but not the special defined one for 'H:\'.
For drive H:\ perf-data should be something like:

'H:\ free'=153607.58203M;1024.0;2048.0;0;238466.99609
shouldn't it?

Furthermore, is there a parameter to define that perfdata should only be returned only in free megabytes (no percentage and no used)?

**Comment by mickem** [comment]
Yes, this is probably right... Will try to fix it for 0.4.4
