### ISSUE TITLE
CheckCPU is not returning CPU Load is ok for Windows 2003

### ISSUE THREAD

**Issue by asesino4u** [mickem/nscp#133]
the plugin is only returning "OK: |" and then the performance counters
if i check a Win 2003 Server it shows
root@qsc-nagios:/usr/lib/nagios/plugins# ./check_nrpe -H 192.168.1.10 -c CheckCPU
OK: |'total 5m'=1%;80;90 'total 1m'=1%;80;90 'total 5s'=1%;80;90
for a Win 2012 Server it shows
root@qsc-nagios:/usr/lib/nagios/plugins# ./check_nrpe -H 192.168.1.25 -c CheckCPU
OK: CPU load is ok.|'total 5m'=0%;80;90 'total 1m'=0%;80;90 'total 5s'=0%;80;90
missing the "CPU Load is ok" is showing the service as critical

**Comment by mickem** [comment]
Probably different versions

**Comment by asesino4u** [comment]
Hi Michael,

what do you mean with different versions?

The NSClient is the same on all servers, as I installed them 3 days ago, do I have to use an older client for the Win 2003 servers.

I have this for all of my Win 2003 servers.

[cid:image001.png@01D066DA.E04EAAE0]

[cid:image004.png@01D066DB.1AE65CC0]

The 192.168.1.10 is a Win 2003 server, the 192.168.1.25 is a Win 2012 server.

Regards

Oliver Lopez
IT - Manager / Webmaster

[cid:image002.jpg@01D066DB.1AE8A6B0]

ad pepper media International N.V.
The e-Advertising Network
Frankenstraße 150c
D-90461 Nürnberg
phone +49 (0) 911 929 057 132
mobile +49 (0) 162 2345 617
fax +49 (0) 911 929 057 157
e-mail: olopez@adpepper.com<mailto:olopez@adpepper.com>
internet: www.adpepper.com<http://www.adpepper.com/>

The information contained in this email and any attachments is confidential and may be subject to copyright or other intellectual property protection.
If you are not the intended recipient, you are not authorized to use or disclose this information, and we request that you notify us by reply mail or telephone and delete the original message from your mail system.

Von: Michael Medin [mailto:notifications@github.com]
Gesendet: Dienstag, 24. März 2015 20:05
An: mickem/nscp
Cc: Oliver Lopez
Betreff: Re: [nscp] CheckCPU is not returning CPU Load is ok for Windows 2003 (#133)


Probably different versions

**Comment by mickem** [comment]
No the syntax has changed in various version so the output will be different if you check different versions of NSClient++.
Not 100% sure which versions you have,m if you run:
```
root@qsc-nagios:/usr/lib/nagios/plugins# ./check_nrpe -H 192.168.1.10
root@qsc-nagios:/usr/lib/nagios/plugins# ./check_nrpe -H 192.168.1.25
```
You will see the versions

**Comment by asesino4u** [comment]
Hi Michael,

thank you a lot, i must have chosen the wrong client, because they are not sorted by date ;)

The Win 2003 are x32 and the rest ix x64, so I had the wrong client for the x32 servers

root@qsc-nagios:/usr/lib/nagios/plugins# ./check_nrpe -H 192.168.1.10
I (0.4.3.88 2015-01-11) seem to be doing fine...
root@qsc-nagios:/usr/lib/nagios/plugins# ./check_nrpe -H 192.168.1.25
I (0.4.3.131 2015-02-15) seem to be doing fine...
root@qsc-nagios:/usr/lib/nagios/plugins# ./check_nrpe -H 192.168.1.10
I (0.4.3.131 2015-02-15) seem to be doing fine...
root@qsc-nagios:/usr/lib/nagios/plugins#

now everything is running fine, thanks a lot for all the effort you are putting in this project.

Regards

Oliver Lopez
IT - Manager / Webmaster

[cid:image003.jpg@01D066F4.D397D1E0]

ad pepper media International N.V.
The e-Advertising Network
Frankenstraße 150c
D-90461 Nürnberg
phone +49 (0) 911 929 057 132
mobile +49 (0) 162 2345 617
fax +49 (0) 911 929 057 157
e-mail: olopez@adpepper.com<mailto:olopez@adpepper.com>
internet: www.adpepper.com<http://www.adpepper.com/>

The information contained in this email and any attachments is confidential and may be subject to copyright or other intellectual property protection.
If you are not the intended recipient, you are not authorized to use or disclose this information, and we request that you notify us by reply mail or telephone and delete the original message from your mail system.

Von: Michael Medin [mailto:notifications@github.com]
Gesendet: Mittwoch, 25. März 2015 10:54
An: mickem/nscp
Cc: Oliver Lopez
Betreff: Re: [nscp] CheckCPU is not returning CPU Load is ok for Windows 2003 (#133)


No the syntax has changed in various version so the output will be different if you check different versions of NSClient++.
Not 100% sure which versions you have,m if you run:

root@qsc-nagios:/usr/lib/nagios/plugins# ./check_nrpe -H 192.168.1.10

root@qsc-nagios:/usr/lib/nagios/plugins# ./check_nrpe -H 192.168.1.25

You will see the versions
