### ISSUE TITLE
check_files count "<" doesn´t work with count greater than 1

### ISSUE THREAD

**Issue by Diddel** [mickem/nscp#137]
i want to check an Folder if there are less then 29 files. 

i use check_files with pattern and warn=Count< 29
Version: 0.4.3.131.
it doesn´t work, "<" or "lt" with numbers greater then 1, 

"Count < 0" -> works
"Count < 1" -> works
"Count < 2" -> doesn´t work
"Count with >" works ever.

**Comment by mickem** [comment]
Yes, this is a "known" issue which will be resolved in 0.4.4 (workaround for 0.4.3 is to use a lua script)

**Comment by garnier-quentin** [comment]
Could you give us an example of lua script usage ? Thanks!

**Comment by mickem** [comment]
This is probably the best option: http://www.medin.name/blog/2013/12/04/check_cpu-with-top-consumers-in-nsclient-part-1-of-2/

This has been fied though and once I resolve some compile issues with visual studio 2014 I will publish a nightly build which will fix this issue...

**Comment by garnier-quentin** [comment]
I don't find the script "check_cpu_ex.lua".

**Comment by mickem** [comment]
The script can be found in the second part: http://www.medin.name/blog/2013/12/16/check_cpu-with-top-consumers-in-nsclient-part-2-of-2/

**Comment by mickem** [comment]
But this is not a turnkey solution more like giving people an idea how to write script in lua

**Comment by Diddel** [comment]
Hi, thanks for the script.
my next idea was to check with an "ok=filter" instead of "crit= or warn=", but how Can i use this?
the option  "ok=count=13" will not work, for an Folder with 13 files matches the filter!
