### ISSUE TITLE
0.4.3.131 check_nt USEDDISKSPACE crash

### ISSUE THREAD

**Issue by pixnion** [mickem/nscp#138]
Running check_nt USEDDISKSPACE checks towards NSClient++ results in a crash. NSClient++ is running on Windows 8 in this case and the system has no other drives than C:. The same behaviour was seen in 0.4.2.114.

Full debug output of NSClient++: http://bit.ly/1G7b2KD
The crash dump file: http://bit.ly/1CeQs3p
... and its txt: http://bit.ly/1MG96g5

#### check_nt queries

$ ./check_nt -H 127.0.0.1 -p 12489 -v USEDDISKSPACE -l C
C:\ - total: 63.66 Gb - used: 13.54 Gb (21%) - free 50.12 Gb (79%) | 'C:\ Used Space'=13.54Gb;0.00;0.00;0.00;63.66
$ ./check_nt -H 127.0.0.1 -p 12489 -v USEDDISKSPACE -l D
Free disk space : Invalid drive
$ ./check_nt -H 127.0.0.1-p 12489 -v USEDDISKSPACE -l E
Free disk space : Invalid drive
$ ./check_nt -H 127.0.0.1 -p 12489 -v USEDDISKSPACE -l F
Free disk space : Invalid drive
$ ./check_nt -H 127.0.0.1 -p 12489 -v USEDDISKSPACE -l G
Free disk space : Invalid drive
$ ./check_nt -H 127.0.0.1 -p 12489 -v USEDDISKSPACE -l H
NSClient - Incorrect data received from snmp server

#### NSClient++ debug output snippet

D   check_nt Accepting connection from: 127.0.0.1
D   check_nt Accepting connection from: 127.0.0.1
D   check_nt Accepting connection from: 127.0.0.1
D       disk Error: Failed to get size for: 3: The system cannot find the path specified.

D   check_nt Accepting connection from: 127.0.0.1
D       disk Error: Failed to get size for: 3: The system cannot find the path specified.

D   check_nt Accepting connection from: 127.0.0.1
D       disk Error: Failed to get size for: 3: The system cannot find the path specified.

D   check_nt Accepting connection from: 127.0.0.1
D       disk Error: Failed to get size for: 3: The system cannot find the path specified.

INF: Detected crash...
INF: Running: "C:\Program Files\NSClient++\reporter.exe" "archive" "C:\Users\OP5SUP~1\AppData\Local\Temp\\6fb2ca09-ba3c-46ea-8de1-3ab97bd6b032.dmp" "NSClient++" "0.4.3.131" "2015-02-15" "C:\Program Files\NSClient++/crash-dumps"
Created folder: C:\Program Files\NSClient++/crash-dumps
INF: Running: "C:\Program Files\NSClient++\reporter.exe" "restart" "NSCP"

**Comment by mickem** [comment]
I think this is fixed in build 0.4.3.138 http://www.nsclient.org/download/nightly/

**Comment by pixnion** [comment]
Indeed, this seems to work in 0.4.3.139. :)

**Comment by mickem** [comment]
Thank you for reporting back, I will release a RC for the next 0.4.3 on monday (was to busy this week) and then it will ship a few days later...
