### ISSUE TITLE
NSClient++: CheckFile2 reported a 'futuristic' file and flagged it old

### ISSUE THREAD

**Issue by Klang0340** [mickem/nscp#139]
Good morning Support,

     I am using CheckFile2 to report when a directory contains a file over 60 minutes old. We had an instance where a file was reported with a time stamp in the future and was flagged for being over 60 minutes old. The check has been working fine in the past and still appears to be working today. Not sure if such an issue was reported before. We do not have the file as Admins delete these files when an issue in detected. The files I am monitoring indicate a problem with a job and are deleted upon resolving a further issue.

Two issues I am reporting
1) File time stamp was in the future
2) A futuristic date reported to be 60 minutes old or older

CMD Name: check_nrpe_windows_checkFile_age-export-mru
CMD Line: $USER1$/check_nrpe -u -s -H $HOSTADDRESS$ -c CheckFile2 -a path=e:/export/mru/ pattern=*.*tmp "filter+creation=gt:60m" "syntax=%filename%: %creation%" MaxWarn=1

Bonus Question: Any way to watch only files and ignore directories?

![github pic](https://cloud.githubusercontent.com/assets/11839144/7028413/58682d2e-dd1b-11e4-9b3f-4a23a113d9f3.png)

**Comment by mickem** [comment]
CheckFile2 was replaced by CheckFiles some 3-4 years ago as it had a lot of issues so I would probably recommend upgrading to a newer version and a newer check...

**Comment by Klang0340** [comment]
Michael,

                Thank you for this information, I have changed over to the new check but can’t seem to get the proper dates to show still. The timestamps being reported for the files are still in the future.

Below is an example of me looking for any files which are older than 60 minutes.

$USER1$/check_nrpe -u -s -H $HOSTADDRESS$ -c CheckFiles -a path=e:/export/mru/test/ pattern=*.*tmp "filter=creation < -60m" "syntax=%filename%: %creation%" MaxWarn=1

[cid:image006.png@01D072C6.97FAEE00]


[cid:image001.jpg@01D072C7.47991EE0]

**Comment by mickem** [comment]
It could not be a timezone issue maybe?

**Comment by Klang0340** [comment]
Michael,

                I wanted to believe that but the times are not consistent. Time zones would change by the hour and these files are off by Hours and Minutes with no set pattern. We got a file ~5hrs and 3 minutes in the future and another 6 hours and 35 minutes in the future. I don’t believe this is a time zone issue. The output is being skewed by a mistake in variable work or math being performed on this the creation varaible.


[cid:image002.png@01D075CC.B492C480]

[cid:image003.png@01D075CC.B492C480]

**Comment by mickem** [comment]
Another though that springs to mind is that there are more then one date on a file, so are you checking the correct one?

![image](https://cloud.githubusercontent.com/assets/1434697/7118391/2e976d5a-e1ff-11e4-862d-04d2bf20bc7a.png)

// Michael Medin

If not please send me the check_files command your using and I shall investigate.
But I actually have unit tests for the check_files so presumably it works...

// Michael Medin

**Comment by Klang0340** [comment]
Michael,

                After looking deeper into it, you were right from the start. It was a time zone issue. The dates I see in Windows are the ‘Modified’ date when I was thinking it was the ‘Created date’. When comparing the created date on the file with the date being reported, the output shows times exactly 5 hours ahead of the current time. Is there a way to get the script to not use time zones? The Time zone on the Windows Server is set to Central Time (UTC-06:00) which is appropriate for my area but it’s still evaluating against a far different one.

[cid:image001.png@01D075D6.4A7DBD70]

**Comment by mickem** [comment]
What do you think about adding a new keyword which has the date in local time?

```
check_files path=D:\\source\\nscp\\include\\parsers\\expression warn=creation>-24h show-all "detail-syntax=%(name) standard: %(creation) local: %(creation_l) utc: %(creation_u)"
L        cli OK: OK: 0/2 files (expression.cpp standard: 2013-feb-04 06:39:25 local: 2013-feb-04 07:39:25 utc: 2013-feb-04 06:39:25, expression.hpp standard: 2013-feb-04 06:39:25 local: 2013-feb-04 07:39:25 utc: 2013-feb-04 06:39:25)
```

creation gives time (current solution).
creation_l gives time in local time
creation_u gives time in UTC (current solution).

**Comment by Klang0340** [comment]
Michael,

                Adding a local time zone option would allow the %creation% output to display the proper time for us so I believe this would be a great add to the existing plugin.  As long as you are able to take the local time zone from the Operating System, a ‘local time’ flag like ‘time=local’ of some sort could be added and be very helpful. You could also make it the default time output if no ‘time’ option is selected.

I like the idea of being able to select manually input a time zone but I only need the local option. Setting a time zone manually would be a nice feature but I can’t think of a use case outside of a server having an improper time zone configuration.

Formatting:
                I’m sure you did it to provide an example (Appreciated), I am guessing the actual output would just contain the local output if selected.

example
cli OK: OK: 0/2 files (expression.cpp standard: 2013-feb-04 06:39:25 local: 2013-feb-04 07:39:25 utc: 2013-feb-04 06:39:25, expression.hpp standard: 2013-feb-04 06:39:25 local: 2013-feb-04 07:39:25 utc: 2013-feb-04 06:39:25)
preferred
cli OK: OK: 0/2 files (expression.cpp local: 2013-feb-04 07:39:25 local: 2013-feb-04 07:39:25)

**Comment by mickem** [comment]
If you grab build 141 from here you can use the new syntax go get date in local time: http://www.nsclient.org/download/nightly/

Please reopen if you have issues or want some further enhancements

**Comment by Klang0340** [comment]
Michael,

                Awesome! I will have to wait for a full release of NSClient++ unfortunately as I use Op5-Monitor and they repackage your client. I can certainly download and use NSClient on the test server and attempt to test your new change. Thank you for taking the time to add this feature.
