### ISSUE TITLE
check_ping.bat - does not return correct status for hosts on the same subnet as client

### ISSUE THREAD

**Issue by box293** [mickem/nscp#140]
In summary, the Windows ping command returns an ERRORLEVEL of 0 for devices on the same subnet that it cannot contact.

I have provided an alternate command to use in the check_ping.bat script to overcome this problem.

The check_ping.bat script included with NSClient++ executes the following command:
```
ping -n 1 %1 -w 20000 > NUL
```
So lets see that in action:
```
ping -n 1 10.25.4.1 -w 20000

Pinging 10.25.4.1 with 32 bytes of data:
Reply from 10.25.4.1: bytes=32 time=3ms TTL=64

Ping statistics for 10.25.4.1:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 3ms, Maximum = 3ms, Average = 3ms

echo %ERRORLEVEL%
0
```
Great, working as expected.

Now let me test against a device on another subnet that does not exist.
```
ping -n 1 10.26.4.1 -w 20000

Pinging 10.26.4.1 with 32 bytes of data:
Request timed out.

Ping statistics for 10.26.4.1:
    Packets: Sent = 1, Received = 0, Lost = 1 (100% loss),

echo %ERRORLEVEL%
1
```
Great, working as expected.

Now let me test against a device on the SAME subnet that does not exist.
```
ping -n 1 10.25.4.2 -w 20000

Pinging 10.25.4.2 with 32 bytes of data:
Reply from 10.25.14.2: Destination host unreachable.

Ping statistics for 10.25.4.2:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),

echo %ERRORLEVEL%
0
```
So you can see that ping returns an ERRORLEVEL of 0.

Here is the check_ping.bat script testing that address:
```
check_ping.bat 10.25.4.2
OK: Ping succeded

echo %ERRORLEVEL%
0
```

I propose the following command be used instead:
```
ping -n 1 10.25.4.2 -w 20000|findstr /I /C:"TTL"

echo %ERRORLEVEL%
1
```

Which would be implemented in the script as follows, replacing the existing line 2 with this:
```
ping -n 1 %1 -w 20000|findstr /I /C:"TTL" > NULL
```

Which gives the result:
```
check_ping.bat 10.25.4.2
CRITICAL: Ping check failed

echo %ERRORLEVEL%
1
```

**Comment by box293** [comment]
Also, on line 16, "succeded" should be spelt "succeeded".

**Comment by mickem** [comment]
What would you think about this as a replacement for check_ping.bat?

```
check_ping host=192.168.0.3 host=www.google.com
L        cli CRITICAL: CRITICAL: 2/2 ( Packet loss = 100%, RTA = 0ms, 74.125.143.103 Packet loss = 50%, RTA = 10ms)
L        cli  Performance data: '192.168.0.3_loss'=100;5;10 '192.168.0.3_time'=0;60;100 'www.google.com_loss'=50;5;10 'www.google.com_time'=10;60;100
```


```
check_ping show-default
L        cli OK: "warning=time > 60 or loss > 5%" "critical=time > 100 or loss > 10%" "empty-state=unknown" "top-syntax=${status}: ${problem_count}/${count} (${problem_list})" "ok-syntax=%(status): All %(count) hosts are ok" "empty-syntax=No hosts found" "detail-syntax=${ip} Packet loss = $(loss}%, RTA = ${time}ms" "perf-syntax=${host}" "count=1" "timeout=500"
```

**Comment by box293** [comment]
I think this looks great. The additional performance data is good.
One thing I like about NSClient++ is some of the included checks which don't rely on external scripts, it's a good feature.

**Comment by mickem** [comment]
Ok, great...

An early prototype of this command will be added to 0.4.2 in the next build (expect it in a day or so)

**Comment by mickem** [comment]
Have you had any chance to test the new command?
Does it work better and if so can e close this ticket?

**Comment by box293** [comment]
Just had a play, looks good, great work :)

Tested with "dead' hosts on the same subnet and also other subnets and it correctly reports their status.

One thing needs correcting. When using show-all and the result is OK it says 0/1 when it should say 1/1

```
Command:
check_nrpe -H win2008r2-01 -c check_ping -a host=10.25.254.50 show-all

Output:
OK: 0/1 (10.25.254.50 Packet loss = 0%, RTA = 0ms)|'10.25.254.50_loss'=0;5;10 '10.25.254.50_time'=0;60;100
```

**Comment by mickem** [comment]
Ok will investigate...  Thanks for reporting back...
