### ISSUE TITLE
0.4.3.x - is ok-syntax really depreciated?

### ISSUE THREAD

**Issue by box293** [mickem/nscp#141]
http://docs.nsclient.org/reference/windows/CheckDisk.html#check-files

 ok-syntax (CheckDisk, check_files)
    ok syntax.
    DEPRECATED! This is the syntax for when an ok result is returned.

However from tests it still works:
This test goes critical because the threshold is exceed:
```
Command:
check_nrpe -H E4300 -c check_files -a path='C:\\NO BACKUP' pattern=*.* 'warning=count>100' 'critical=count>500' 'top-syntax=${status}: ${count} files found (${problem_count} > than defined thresholds)' 'ok-syntax=%(status): %(count) files'

Output:
CRITICAL: 18921 files found (18821 > than defined thresholds)|'count'=18921;100;500
```

This test is OK because the threshold is NOT exceed:
```
Command:
check_nrpe -H E4300 -c check_files -a path='C:\\NO BACKUP' pattern=*.* 'warning=count>100000' 'critical=count>500000' 'top-syntax=${status}: ${count} files found (${problem_count} > than defined thresholds)' 'ok-syntax=%(status): %(count) files'

Output:
OK: 18921 files|'count'=18921;100000;500000
```
As you can see, the ok-syntax was used.

If ok-syntax is depreciated, how do I define my OK message (because I want a different message to the pre-defined one)?

**Comment by mickem** [comment]
ok syntax was an ugly work around added to 0.4.3 to resolve just such issues.
In 0.4.4. the normal syntax will get some sort of if statements which will replace ok-syntax.

So yes it works (it was added in 0.4.3) but they will probably not work in a future version...

So (and this is speculation since I havent developed it yet) 0.4.4.will add something along the lines of:

```
'top-syntax=${status}: ${count} files found %(if problem_count > 0)) (${problem_count} > than defined thresholds)%(endif)'
```

**Comment by mickem** [comment]
Closing this, please reopen if you have further questions...
