### ISSUE TITLE
nrdp_submit returns: Paradigm shift currently not supported

### ISSUE THREAD

**Issue by Kookabura** [mickem/nscp#143]
Tested different builds on  Win OS 2008R and 2012. The result:
NSCP-0.4.1.102-x64 – nrdp_submit works
NSCP-0.4.2.88-x64 – nrdp_submit doesn’t work (Paradigm shift currently not supported)
NSCP-0.4.2.114-x64 – nrdp_submit doesn’t work (Paradigm shift currently not supported)
NSCP-0.4.3.131-x64 – nrdp_submit doesn’t work (Paradigm shift currently not supported)
I use the same config file.

**Comment by mickem** [comment]
This is something I am currently reworking and it will be much improved in 0.4.4

**Comment by mickem** [comment]
should have been fixed 0.5.0, if not reopen
