### ISSUE TITLE
checkFiles - Can't exclude '.' and '..' folders (Or fodlers in general)

### ISSUE THREAD

**Issue by Klang0340** [mickem/nscp#145]
Good morning support,

     I am using CheckFiles but have a need to exclude 'folder/directories'. I have a request which is "Notify me if ANY file shows up in directory 'x' " but I am unable to do this without again causing a little confusion. I could perform a filter and say '3' or more files must exist but then I would always report more files exist than there really does.

I am attaching an example but if I perform a search for everything (*) within a directory, it always returns the two folders '.' and '..'. I can't see these hidden folders and I personally don't even know if they are really folders. In the Unix world they would be folders but am not sure what they are for Windows.

Perhaps I have it wrong but I am not sure why the checks returns matches for '.' and '..', perhaps is something I just don't understand.

![checkfiles - exclude folders](https://cloud.githubusercontent.com/assets/11839144/7322836/3af05746-ea70-11e4-94f6-f4d069a3b22b.GIF)

1) Why does the check return '.' and '..'?
2) Can we exclude '.' and '..' somehow?
3) Is it also possible to exclude folders/directories?

**Comment by mickem** [comment]
It shouldn't and it did not before, perhaps I have meesed something up...

You can technically exclude them using filters but that is painfull...

**Comment by Klang0340** [comment]
Michael,

                If I can exclude the two below folders then I would like to find a way to do that. I have modified the command to use ‘file’ instead of path and get the same results.

$USER1$/check_nrpe -u -s -H 10.212.238.234 -c CheckFiles -a "file=I:\\DIP\\ERROR_FILES\\" "pattern=*" "filter=creation < -60m" "syntax=%filename%" MaxWarn=1

_USER1_/check_nrpe -u -s -H 10.212.238.234 -c CheckFiles -a "file=I:\\DIP\\ERROR_FILES\\" "pattern=*" "filter=creation < -60m" "syntax=%filename%" MaxWarn=1
Result code: 1
., .., found files: 2 > warning|'found files'=2;1;0

**Comment by mickem** [comment]
Excluding them should be as simple as "filter=creation < -60m and file != '.' and file != '..'" not 100% sure if the syntax of my head, but you can find that in the docs.

**Comment by Klang0340** [comment]
Michael,

                It’s good to hear I may create exclusions but I do not see this information on your documentation, but I am a new user and am most likely looking in the wrong spot. The combination of ‘!=’ provides me with errors and when I use ‘and’ for multiple statements, I also get errors. I will keep looking on-line for some kind of explanation or examples.

Source: http://docs.nsclient.org/reference/CheckDisk.html#CheckDisk.check_files.pattern

[cid:image001.jpg@01D0832F.25B19140]

**Comment by mickem** [comment]
Which version do you have?
I just conformed that it does not seem to return any matches for . and ..

**Comment by Klang0340** [comment]
Michael,

                I am currently on a re-packaged version of 3.9.327.

**Comment by mickem** [comment]
Ohh... then I would recommend you to upgrade...

0.3.9 is very very very very old (I mean like several years old)....

If you are interested I could (for a fee) help you create a configuration on top of modern vanilla NSClient++ that works with your monitoring server and looks the same (i.e custom scripts/config/*).

Depending on the complexity of the packaged version I would say between 1-5 hours. For details of payed support refer to this page: https://www.nsclient.org/support/

If it is ok I will close this ticket as it it (from what I can tell) fixed in recent version of NSClient++?

**Comment by Klang0340** [comment]
Michael,

                I appreciate the help in identifying the issues and helping me with a solution. I use the product Op5-Monitor and I am waiting for them to re-package your latest NSClient++ but from what I’m told they prefer to stay on older stable versions. All I can do it open another ticket with them giving them another reason to update their agent package.

                I was told I may use the latest version of NSClient++ instead of the current Op5 re-packaged version but I don’t have time to test this yet. I am still in the middle of deploying the actual monitoring product itself.

                Please feel free to close this ticket, I will make another note to the Vendor I need the latest version re-packaged to assist me in gaining further functionality and accuracy in my Windows based monitoring environment.

                Again, thank you for your assistance in identifying my issue.
