### ISSUE TITLE
check_drivesize and filter options

### ISSUE THREAD

**Issue by itsul** [mickem/nscp#147]
While configuring NSCP we have massive problems since the new v4.x version was released.

A command should check all drives on windows hosts. On Windows 2012 Server there are different drives like \\?\ which should be filtered. It does not work, have tried different variants.

root@ces-test:~#./check_nrpe -H xx.xxx.xx.xx
I (0.4.3.131 2015-02-15) seem to be doing fine...

root@ces-test:~# ./check_nrpe -H xx.xxx.xx.xx -c check_drivesize -a show-all
OK C:\: 209.582GB/465.26GB used, D:\: 46.828MB/12.061GB used, F:\: 0B/0B used, S:\: 22.583GB/45.771GB used, Boot: 293.137MB/511.996MB used|'C:\ used'=209.5816GB;372.2078;418.73378;0;465.25976 'C:\ used %'=45%;80;90;0;100 'D:\ used'=0.04573GB;9.64843;10.85448;0;12.06054 'D:\ used %'=0%;79;89;0;100 'F:\ used'=0B;0;0;0;0 'S:\ used'=22.58301GB;36.61718;41.19432;0;45.77147 'S:\ used %'=49%;79;89;0;100 '\\?\Volume{1f3d5adb-4aaf-11e3-824f-806e6f6e6963}\ used'=293.13671MB;409.59687;460.79648;0;511.99609 '\\?\Volume{1f3d5adb-4aaf-11e3-824f-806e6f6e6963}\ used %'=57%;79;89;0;100

root@ces-test:~#./check_nrpe -H xx.xxx.xx.xx -c check_drivesize -a "filter=name not like '\\?\'"
Invalid command line: unrecognised option 'not'
help                                                    Show help screen (this screen)
help-pb                                         Show help screen as a protocol buffer payload
show-default                                            Show default values for a given command
help-short                                              Show help screen (short format).
debug                                           Show debugging information in the log
show-all                                                Show debugging information in the log
filter=                                         Filter which marks interesting items.
warning=used > 80%                                      Filter which marks items which generates a warning state.
warn=                                           Short alias for warning
critical=used > 90%                                     Filter which marks items which generates a critical state.
crit=                                           Short alias for critical.
ok=                                                     Filter which marks items which generates an ok state.
empty-state=unknown                                     Return status to use when nothing matched filter.
perf-config=                                            Performance data generation configuration
top-syntax=${status} ${problem_list}                    Top level syntax.
ok-syntax=%(status) All %(count) drive(s) are ok        ok syntax.
empty-syntax=%(status): No drives found         Empty syntax.
detail-syntax=${drive_or_name}: ${used}/${size} used    Detail level syntax.
perf-syntax=${drive_or_id}                              Performance alias syntax.
drive=                                          The drives to check.
ignore-unreadable                                       Ignore drives which are not reachable by the current user.
magic=                                          Magic number for use with scaling drive sizes.
exclude=                                                A list of drives not to check
total                                           Include the total of all matching drives

on windows nscp debug mode:
check_drivesize "filter=name not like '\\?\'"
L        cli Exception: unknown escape sequence

**Comment by mickem** [comment]
Looks like a unix escape issue to me?

The arguments should arrive as-is- so be sure you are esacping tings correctly.

I prefer ' over " for instance, and I would be careful with \ as well for the same reason.

**Comment by itsul** [comment]
Escaping is a big point in linux but i do not agree with you in this case.

Testing in debug mode (on my Windows 8.1 notebook) is not working:
check_drivesize filter=name not like '\\?\'
L        cli Exception: unknown escape sequence
check_drivesize "filter=name not like '\\?\'"
L        cli Exception: unknown escape sequence

Maybe you can test it on your side? Or is there another way to exclude the partitions with "\?" ? To filter with the option fixed is not enough.

**Comment by mickem** [comment]
I would say once again escaping is the culprit as you in to escape in the test client as well:

But this: 
```
"Invalid command line: unrecognised option 'not'"
```
is a very good indication of escaping issues as what has happened is the command turned into this:
```
#this command:
..."filter=name not like"...
# turned into this:
...filter=name not like ...
```

If you run in test mode try:
```
check_drivesize "filter=name not like '\\?\\'"
```

Or better yet try something simple to start with:
```
check_drivesize "filter=name not like 'a'"
```

Please note that there are multiple "keys" for the drive as well, drive, id, name...

http://docs.nsclient.org/reference/windows/CheckDisk.html#CheckDisk.check_drivesize.filter

**Comment by itsul** [comment]
check_drivesize "filter=name not like '\\?\\'" is working.

In the past (previous version) i have tested it without problems and without escaping. So I was a little confused about that in the new version. Thanks a lot for you support.

**Comment by mickem** [comment]
ohh...
I thought when you said new that you mean from pre 0.4.x as in 0.3.9.
From which version did you upgrade?

**Comment by itsul** [comment]
The "problem" is solved so all fine :)

Here is the result from my private system from april this year:
root@monitoring:~# /usr/local/nagios/libexec/check_nrpe -H 192.168.x.xx
I (0.4.3.131 2015-02-15) seem to be doing fine...
root@monitoring:~# /usr/local/nagios/libexec/check_nrpe -H 192.168.x.xx -c check_drivesize
OK All 6 drive(s) are ok|'C:\ used'=39.91152GB;47.99999;53.99999;0;59.99999 'C:\ used %'=66%;79;89;0;100 'D:\ used'=1.03204TB;1.45547;1.63741;0;1.81934 'D:\ used %'=56%;80;90;0;100 'E:\ used'=0.47584GB;138.2289;155.50751;0;172.78612 'E:\ used %'=0%;79;89;0;100 'F:\ used'=0B;0;0;0;0 'G:\ used'=0.01246TB;1.45547;1.63741;0;1.81934 'G:\ used %'=0%;80;90;0;100 '\\?\Volume{3fec3032-0b18-11e2-93e8-806e6f6e6963}\ used'=33.9375MB;79.99687;89.99648;0;99.99609 '\\?\Volume{3fec3032-0b18-11e2-93e8-806e6f6e6963}\ used %'=33%;79;89;0;100
root@monitoring:~#
root@monitoring:~#
root@monitoring:~# /usr/local/nagios/libexec/check_nrpe -H 192.168.x.xxx -c check_drivesize -a "filter=name not like '\\?\'"
OK All 2 drive(s) are ok|'D:\ used'=1.03204TB;1.45547;1.63741;0;1.81934 'D:\ used %'=56%;80;90;0;100 'G:\ used'=0.01246TB;1.45547;1.63741;0;1.81934 'G:\ used %'=0%;80;90;0;100
root@monitoring:~#

**Comment by mickem** [comment]
Right, I shall look into it...

**Comment by itsul** [comment]
Is it possible to add a feature or extend an existing one (e.g. fixed storage?) to igonore the \\? drives by default?

The spaces are a problem on unix site - spent hours in escaping now ...

**Comment by mickem** [comment]
sure, please add a new ticket dhough, or I will probably forget... 
Question is if there is some "better criteria" then "?" drives, what kind of drives is it?

**Comment by mickem** [comment]
Errr... thought this was the new ticket, sorry... :)

**Comment by itsul** [comment]
https://github.com/mickem/nscp/issues/149 <= for other users
