### ISSUE TITLE
Feature: check_drivesize Option

### ISSUE THREAD

**Issue by itsul** [mickem/nscp#149]
Hi mickem,

as desired, here as a separate ticket. Please add an option für check_drivesize to exclude Systemdrives "\?\":

check_drivesize "filter=name not like '\?\'"
L cli OK: OK All 3 drive(s) are ok
L cli Performance data: 'C:\ used'=209.58849GB;372.2078;418.73378;0;465.
25976 'C:\ used %'=45%;80;90;0;100 'D:\ used'=0.04573GB;9.64843;10.85448;0;12.06
054 'D:\ used %'=0%;79;89;0;100 '\?\Volume{1f3d5adb-4aaf-11e3-824f-806e6f6e6963
}\ used'=293.13671MB;409.59687;460.79648;0;511.99609 '\?\Volume{1f3d5adb-4aaf-1
1e3-824f-806e6f6e6963}\ used %'=57%;79;89;0;100

Far as i know, the \? is a system drive with some boot data. 

Thank you.

**Comment by mickem** [comment]
Next version will feature a "mounted" option which will filter out any drives which is not mounted. 

    check_drivesize
    L        cli CRITICAL: CRITICAL : 385.504MB/467.996MB used, Windows Images: 12.4GB/12.742GB used
    L        cli  Performance data: 'C:\ used'=201.15642GB;361.8706;407.10443;0;452.33826 'C:\ used %'=44%;79;89;0;100 'D:\ used'=16.15509GB;372.6039;419.17939;0;465.75487 'D:\ used %'=3%;79;89;0;100 'E:\ used'=96.38871GB;372.60546;419.18114;0;465.75683 'E:\ used %'=20%;79;89;0;100 '\\?\Volume{eab0c4fd-f984-48a1-b679-da7a6284dad3}\ used'=385.5039MB;374.39687;421.19648;0;467.99609 '\\?\Volume{eab0c4fd-f984-48a1-b679-da7a6284dad3}\ used %'=82%;79;89;0;100 '\\?\Volume{d96b7ab5-846c-4c1a-ba91-b0f1dd7caa98}\ used'=12.40044GB;10.19374;11.46796;0;12.74218 '\\?\Volume{d96b7ab5-846c-4c1a-ba91-b0f1dd7caa98}\ used %'=97%;79;89;0;100

    check_drivesize mounted
    L        cli OK: OK All 3 drive(s) are ok
    L        cli  Performance data: 'C:\ used'=201.15642GB;361.8706;407.10443;0;452.33826 'C:\ used %'=44%;79;89;0;100 'D:\ used'=16.15509GB;372.6039;419.17939;0;465.75487 'D:\ used %'=3%;79;89;0;100 'E:\ used'=96.38871GB;372.60546;419.18114;0;465.75683 'E:\ used %'=20%;79;89;0;100
