### ISSUE TITLE
Call to context.use_certificate_chain_file instead of context.use_certificate_file in NRPEServer

### ISSUE THREAD

**Issue by arathai** [mickem/nscp#150]
Hi,

in socket_helpers.cpp there's a call to `context.use_certificate_file`, if it were `context.use_certificate_chain_file` the Server would be able supply the whole chain and the client wouldn't need to know the intermediate certificates.

It's also the [recommended method](https://www.openssl.org/docs/ssl/SSL_CTX_use_certificate_chain_file.html#NOTES) in the underlying openssl:
>SSL_CTX_use_certificate_chain_file() should be used instead of the SSL_CTX_use_certificate_file() function in order to allow the use of complete certificate chains even when no trusted CA storage is used or when the CA issuing the certificate shall not be added to the trusted CA storage.

See [context.use_certificate_file](http://www.boost.org/doc/libs/1_53_0/doc/html/boost_asio/reference/ssl__context/use_certificate_file/overload2.html) and [context.use_certificate_chain_file](http://www.boost.org/doc/libs/1_53_0/doc/html/boost_asio/reference/ssl__context/use_certificate_chain_file/overload2.html)

Best Regards,
Alex

Ps.: This is a followup to [Certificate pinning in NSClient++ (NRPEServer)](https://forums.nsclient.org/t/certificate-pinning-in-nsclient-nrpeserver/3661).

**Comment by mickem** [comment]
Closing this: will be in next 0.5.0 build...
