### ISSUE TITLE
CheckEventLog - CHECK_NRPE: Invalid packet type received from server - NSClient++ 0.4.3.143

### ISSUE THREAD

**Issue by monshyn** [mickem/nscp#153]
I'm running version 0.4.3.143 on Windows 2012 R2 and I receive the following error when using CheckEventLog. "CHECK_NRPE: Invalid packet type received from server"

After troubleshooting the issue, I found that if an eventlog error message is more than 990 characters, I receive the error message. I did try using the truncate option, but that did not work.

Test Pass: This eventlog alert had 990 characters in the message body. It worked as expected. I did snipped the output...

./check_nrpe -t 120 -H X.X.X.X -c CheckEventLog -a "file=application" "file=system" "MaxWarn=1" "MaxCrit=5" "unique" "descriptions" "truncate=900" "syntax=%(type): %(id): %(source): %(message): "EOM"" "filter=generated gt -5m AND type NOT IN ('success', 'info', 'warning',   'auditSuccess')"

error: 1: WSH: This is a test message from VBScript. This is a test message from VBScript. This is a test message from VBScript. This is a test message from VBScript....  EOM |'count'=2;1;5 

Test Failed: The event log alert has 991 characters in the message body.

./check_nrpe -t 120 -H X.X.X.X -c CheckEventLog -a "file=application" "file=system" "MaxWarn=1" "MaxCrit=5" "unique" "descriptions" "truncate=900" "syntax=%(type): %(id): %(source): %(message): "EOM"" "filter=generated gt -5m AND type NOT IN ('success', 'info', 'warning',   'auditSuccess')"

CHECK_NRPE: Invalid packet type received from server.

**Comment by saifuddinrangwala** [comment]
I have the same problem with windows 2008 R2

C:\Program Files\NSClient++>nscp eventlog --validate
Command not found:

**Comment by mickem** [comment]
It should work in latest build of 0.4.3, if not please reopen

**Comment by XiaoHans** [comment]
Hi, I I have the same problem with windows 2016 R2. While I check out that answer by Google as below:
>>> use version 2 to avoid this invalid packet version.
Like this:
/usr/local/nagios/libexec/check_nrpe -2 -H Remote_Server IP -c check_test -a $ARG1$

then,  check_nrpe working okay!

Hope this help you! 

thx!
