### ISSUE TITLE
Info Request - Muliple NSClient Services (Single Server)

### ISSUE THREAD

**Issue by Klang0340** [mickem/nscp#155]
Good afternoon Mickem,

     We are attempting to execute some SQL Queries with NSClient for a service check but we require the scripts to be executed as a specific user (Authentication reasons for SQL Server). I have been having a very difficult time getting a PowerShell script to be executed as a specific user so another approach is to install an additional NSClient++ service using a different configuration file (So it listens on a different port) and having the services owned by the elevated user account. This would allow me to issue my SQL service checks to the new priviledged NSClient service. Do you know if NSClient support a 'sc create' command allowing it to point to a new configuration file? (Example Below)

sc create NSClientpp_mssql binPath= "C:\Program Files\op5\NSClient++\nsclient++.exe -cfgfile= ’c:\Program Files\op5\NSClient++\NSC-SQL.ini’" start= auto DisplayName= "OP5 NSClient++ Win SQL Agent(x64)"

Perhaps the only option is to install NSClient to a new location then update the configuration files? It would be nice to just create a new service pointing to the new confiugration files versus having duplicae binaries on the same server. Please let me know what you think.

**Comment by mathieuchateau** [comment]
Hello,

why not just mkaing the current nsclient running directly with a domain
account ? So you could use 1 nslient for all usages.

Or you can autorize localsystem in SQL server if on same node than nsclient
(that's what I do for SQL server boxes)


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-05-29 21:32 GMT+02:00 Klang0340 <notifications@github.com>:

**Comment by mickem** [comment]
Just for the record you can install multiple services running the same binary, with 0.4.x (which I guess your not using) you can specify the config store on command line so you can have different configs.
Ans using config include you have one base config only overriding the relevant bits in each config...

For 0.3.9 you need to have multiple locations though...
