### ISSUE TITLE
CDROM included as fixed drive

### ISSUE THREAD

**Issue by zyberpunker** [mickem/nscp#157]
In the old version 0.3.9 check_nt DISKUSAGE does not include CDROM, 0.4.3 does. Please see log below:
(D: is CDROM on both servers)

root@monitor plugins]# /opt/plugins/check_nt -H 172.27.86.195 -v USEDDISKSPACE -l D
D:\ - total: 0.03 Gb - used: 0.03 Gb (100%) - free 0.00 Gb (0%) | 'D:\ Used Space'=0.03Gb;0.00;0.00;0.00;0.03

[root@monitor plugins]# /opt/plugins/check_nt -H 172.27.86.109 -v USEDDISKSPACE -l D
NSClient - UNKNOWN: Drive is not a fixed drive: D: (it is a CDROM drive)

**Comment by mickem** [comment]
Switching to the nrpe (and the regular command) you can easily via: "filter=type='fixed' and mounted = 1" but I have updated the values used by check_nt as well
