### ISSUE TITLE
0.4.3.131 ( nscp nrpe / check_nrpe ) Argument parsing changed compared to legacy check_nrpe

### ISSUE THREAD

**Issue by m-kraus** [mickem/nscp#158]
I am currently starting to migrate an huge setup from legacy nrpe with nsclient 0.3.9 to nscp nrpe with nsclient 0.4.3 and ran into some issues regarding argument parsing:

My test setup consists of an NSClient-0.4.3.131-Server running on Windows7 and check_nrpe running on Centos7, each installed from your official msi/rpm packages.

Running **legacy check_nrpe** from an recent OMD install against the NSClient-Server in insecure mode seems to work as in earlier releases:
```
/omd/versions/default/lib/nagios/plugins/check_nrpe -H 10.0.2.2 -p 5666 \
-c check_cpu \
-a "warn=load>88" "crit=load>99" "time=20m"
OK: CPU load is ok.|'total 20m'=0%;88;99
```

When trying to run the same command with your more secure **check_nrpe** or **nscp nrpe** it seems, that only the first arguemnt is taken into account:
```
/bin/check_nrpe --host 10.0.2.2 --port 5666 \
--ca /vagrant/nscp_certs/myca.pem \
--certificate /vagrant/nscp_certs/mycert.pem \
--certificate-key /vagrant/nscp_certs/mycert_key.pem \
--verify peer-cert  \
--ssl \
--command check_cpu \
--arguments "warn=load>88" "crit=load>99" "time=20m"                                                                                 
OK: CPU load is ok.|'total 5m'=0%;88;90 'total 1m'=0%;88;90 'total 5s'=0%;88;90
```

Only when suppliying multiple **--arguments** the command shows the same behaviour as the legacy check_nrpe:
```
 /bin/check_nrpe --host 10.0.2.2 --port 5666 \
...
--command check_cpu \
--arguments "warn=load>88" \
--arguments "crit=load>99" \
--arguments "time=20m"
OK: CPU load is ok.|'total 20m'=0%;88;99
```

Trying other escaping options result in error messages:
```
 /bin/check_nrpe --host 10.0.2.2 --port 5666 \
...
--command check_cpu \
--arguments '"warn=load>88" "crit=load>99" "time=20m"'
Invalid command line: unrecognised option '"warn=load>88" "crit=load>99" "time=20m"'
```

```
 /bin/check_nrpe --host 10.0.2.2 --port 5666 \
...
--command check_cpu \
--arguments "warn=load>88 crit=load>99 time=20m"
Failed to validate filter see log for details
D  w32system Parsing failed of 'load>88 crit=load>99 time=20m' at: crit=load>99 time=20m
```

Is this behaviour of **check_nrpe** / **nscp nrpe** intended or am i missing something? Hopefully not, because otherwise i would have to make huge changes in my configuration generator logic :smiley:

**Comment by mickem** [comment]
You mean -a does not di what --arguments does? (which is what is expected, will look into it)
Looks like an oversight on my part

**Comment by m-kraus** [comment]
Hi Michael,

i just installed NSClient 0.5.0.16 msi and compiled the 0.5.0.16 rpm for Centos 7 from your provided vagrant box.

I can confirm, that ```-a``` now works as expected (compared to leagcy check_nrpe) using your check_nrpe:
```
/bin/check_nrpe --host 10.0.2.2 --port 5666 \
--ca /vagrant/nscp_certs/myca.pem \
--certificate /vagrant/nscp_certs/mycert.pem \
--certificate-key /vagrant/nscp_certs/mycert_key.pem \
--verify peer-cert --ssl \
--command check_cpu \
--argument "warn=load>88" "crit=load>99" "time=20m"
OK: CPU load is ok.|'total 20m'=1%;88;99
```

**But heads up!** The plural form ```--arguments``` as used above seems to be dropped. You now have to use the **singular** form ```--argument``` or the **short** form ```-a```.

Thank you!
Michael
