### ISSUE TITLE
Scheduler: ‘Failed to submit’ in 0.4.3.143

### ISSUE THREAD

**Issue by kkzinger** [mickem/nscp#160]
I am recieving 'Failed to submit' when I call the Graphite Client from the Scheduler. Intresting is that the values are sent to graphite and displayed right.

It seems that this Problem is not that new. I found this on the Forums
http://forums.nsclient.org/t/scheduler-failed-to-submit-in-0-4-2-93/3538

I am testing with this config:

``` 
[/modules]

CheckSystem = 1
CheckExternalScripts = 1
GraphiteClient = 1
Scheduler = 1


; Undocumented section
[/settings/default]

; Undocumented key
password = test

; Undocumented key
allowed hosts = 127.0.0.1


[/settings/external scripts/alias]
alias_cpu = check_cpu 

; Scheduler Settings

;[/settings/scheduler/schedules/default]
;interval = 10s
;channel = GRAPHITE  


[/settings/scheduler/schedules/CPU_Load]
interval = 10s
channel = GRAPHITE  
command = alias_cpu

;Graphite Client Settings

[/settings/graphite/client]
channel = GRAPHITE
hostname = HOSTNAME


[/settings/graphite/client/targets/default]
address = 192.168.1.1
port = 2013
path=test.nscp.HOSTNAME.${check_alias}.${perf_alias}
```
Following Output is in the logfile:

```
2015-06-11 16:34:26: error:D:\source\nscp\modules\Scheduler\Scheduler.cpp:122: Failed to submit CPU_Load: 
```

**Comment by mickem** [comment]
Will rework this in the next update...

**Comment by mickem** [comment]
This has been fixed in NIGHTLY BUILD 0.5.0.9 https://github.com/mickem/nscp/releases/tag/0.5.0.9

**Comment by kkzinger** [comment]
I tested and can confirm that it is fixed on my setup too.
Thanks!

Are there plans when you will releas 5.0.x 
Looking forward to renew our Monitoring System and want to ship to Graphite and Icinga with one tool.

**Comment by mickem** [comment]
I would say 0.5 will be "offically released" befor the end of the year, but I have made such claims many times before and often not delivered so cant promise anything.
But the plans now is to fix the CollectD stuff and then it is just testing left (and fixing any bugs) so end of year seems reasonable actually...
