### ISSUE TITLE
GraphiteClient Bug

### ISSUE THREAD

**Issue by groskinsky** [mickem/nscp#161]
It appears as far as I can tell in version 4.x the Graphite Client portion has a bug.
It either dosent read the configuration setting for the client targets or they are being passed wrong.
Regardless of what you use in the configuration it will try to write to 127.0.0.1:2003  AND report a connection refused error.
It be nice if the module reported what its trying when loaded like the nsca module as well.

D       core Loading plugin: NSCAServer
D       nsca Allowed hosts definition: 127.0.0.1(255.255.255.255)
D       nsca Binding to: [::]:5667(ipv6)
D       nsca Attempting to bind to: [::]:5667(ipv6)
D       nsca Binding to: 0.0.0.0:5667(ipv4), reopen: true, reuse: true
D       nsca Attempting to bind to: 0.0.0.0:5667(ipv4)
D       core Loading plugin: Scheduler

Thanks, Randy

**Comment by mickem** [comment]
Can you provide the config your using?

**Comment by mickem** [comment]
This has been fixed in NIGHTLY BUILD 0.5.0.9 https://github.com/mickem/nscp/releases/tag/0.5.0.9
