### ISSUE TITLE
Socket ERROR

### ISSUE THREAD

**Issue by wh1test** [mickem/nscp#165]
I use NRPE (NSCP-0.4.1.101) to monitor Windows hosts. These hosts connected through slow links (GPRS and DSL). Very often I recieve Critical errors in Nagios "Connection refused by host" and "CHECK_NRPE: Socket timeout after 180 seconds.". These errors perists until I restart nscp service on the hosts.

Here is tail of nsclient.log when NRPE hungs up:
2015-07-28 14:30:56: d:D:\source\nscp\trunk\include\nrpe/server/protocol.hpp:66: Accepting connection from: 10.3.11.51
2015-07-28 14:30:56: d:..\..\..\trunk\service\NSClient++.cpp:960: Injecting: check_fan_speed_by_ohm...
2015-07-28 14:30:56: d:..\..\..\..\trunk\modules\CheckExternalScripts\CheckExternalScripts.cpp:249: Command line: scripts\check_fan_speed.bat 1000
2015-07-28 14:30:56: d:..\..\..\trunk\service\NSClient++.cpp:985: Result check_fan_speed: OK
2015-07-28 14:33:41: e:D:\source\nscp\trunk\include\socket/server.hpp:212: Socket ERROR: 

Netstat -na shows a number of unclosed connections (CLOSE_WAIT) to port 5666.

NSCP service is in working state. 
Telnet to port 5666 is able to connect, but nagios checks cannot work until I restart nscp service =(

The same hosts and checks on fast links (ethernet, fiber) works fine... 

Could somebody help me or advice solution?

**Comment by mathieuchateau** [comment]
Hello,

Is network interface shut down on server after network outage (like gprs
modem reboot) ?
I would do a script or task scheduler trigger that restart nrpe service
after network change, waiting to see if someone can make nrpe survive that


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-07-29 21:17 GMT+02:00 wh1test <notifications@github.com>:

**Comment by wh1test** [comment]
Mathieu, thank you for response.

Probably packet loss accured, but modem or netowork interface didn't shutdown/rebooted. 
I belive that NRPE Socket doesn't work correctly on the links with high RTA and packet loss.
I tried to use NRPE without SSL, but issue still apears.

**Comment by wh1test** [comment]
Hello.
Mathieu, is there any news about our problem?
I think only you can halp me.

**Comment by mathieuchateau** [comment]
Hello,

does interface change ip address (dhcp lease) ?

When hang, is tcp port still listening (netstat -an | findstr 5666) ?


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-08-03 13:24 GMT+02:00 wh1test <notifications@github.com>:

**Comment by wh1test** [comment]
Hello,
We use static IP address assigment for these hosts.

Yes, as I mentioned above, when NSCP service is hunged up "netstat -na shows a number of unclosed connections (CLOSE_WAIT) to port 5666". Telnet to the host works also.

**Comment by wh1test** [comment]
Hello, may be apeared same news how to fix this issue?((

**Comment by mickem** [comment]
I would upgrade to a more recent version, 0.4.1 is rather old and improvements to the sockets were made in 0.4.2/3

**Comment by mickem** [comment]
Please reopen this if you can reprodue it with 0.4.3 (or later)
