### ISSUE TITLE
Since 0.4.2 realtime eventlog filter no longer returns useful message

### ISSUE THREAD

**Issue by dafyddj** [mickem/nscp#166]
Hi,

I have a realtime event log filter configured as follows:
```
[/settings/eventlog/real-time/filters/SRP Events]
severity=CRITICAL
log=application
filter=id=865 OR id=866 OR id=867 OR id=868
syntax=%strings%
```

I have just checked 0.4.1.102, and nscp returns a useful message containing the name of a program e.g.

    C:\Windows\System32\notepad.exe

However since 0.4.2 (also 0.4.3) nscp returns the following non-useful message:

    application: 1 (error: )

Has the configuration changed in some way, or is it possible to get the old behaviour back?

**Comment by mickem** [comment]
Syntax has been changed into: top syntax and detail syntax.

The default for these are:

    top syntax=${file}: ${count} (${list})
    detail syntax=${level}: ${message}

Sorry about this as the varius modules were diferent I harmonized them to "be the same".
