### ISSUE TITLE
No handler error on NSCP-0.4.1.73-x64

### ISSUE THREAD

**Issue by dickheth** [mickem/nscp#167]
This seems like a trivial issue but I am not able to get this thing to work.
 I am using NSCP-0.4.1.73-x64 from source forge. I believe I have all of the switches set correctly in nsclient.ini at the bottom are all of my nsclient.ini settings.
I have created an alias defined as follows:

ok1="C:\\Program Files\\NSClient++\\scripts\\check_ok.bat"

when I run nscp test from the dos command line and then try to execute my alias, 'ok1', I get the following message:

d rvice\NSClient++.cpp:958 Result ok1: WARNINGl ce\simple_client.hpp:80 WARNING:No handler for command: C:\Program Files\NSClient++\scripts\check_ok.bat

When I run check_ok I get:
d rvice\NSClient++.cpp:933 Injecting: check_ok...
d rvice\NSClient++.cpp:958 Result check_ok: OK
l ce\simple_client.hpp:80 OK:OK: Lets pretend everything is going to be ok.
Which is reasonable

so there is something I am doing wrong with respect to running things out of the scripts directory. Do you have a clue what that may be
Thanks
Dick
--- nsclient.ini ---
# If you want to fill this file with all avalible options run the following command:
# nscp settings --generate --add-defaults --load-all
# If you want to activate a module and bring in all its options use:
# nscp settings --activate-module <module name=""> --add-defaults
# For details run: nscp settings --help
; Undocumented section
[/modules]
; CheckDisk - CheckDisk can check various file and disk related things. The current version has commands to check Size of hard drives and directories.
CheckDisk = 1
; Event log Checker. - Check for errors and warnings in the event log. This is only supported through NRPE so if you plan to use only NSClient this wont help you at all.
CheckEventLog = 1
; Check External Scripts - A simple wrapper to run external scripts and batch files.
CheckExternalScripts = 1
; Helper function - Various helper function to extend other checks. This is also only supported through NRPE.
CheckHelpers = 1
; Check NSCP - Checkes the state of the agent
CheckNSCP = 1
; CheckSystem - Various system related checks, such as CPU load, process state, service state memory usage and PDH counters.
CheckSystem = 1
; CheckWMI - CheckWMI can check various file and disk related things. The current version has commands to check Size of hard drives and directories.
CheckWMI = 1
; NRPE server - A simple server that listens for incoming NRPE connection and handles them.
NRPEServer = 1
; NSCAClient - Passive check support over NSCA.
NSCAClient = 1
; NSClient server - A simple server that listens for incoming NSClient (check_nt) connection and handles them. Although NRPE is the preferred method NSClient is fully supported and can be used for simplicity or for compatibility.
NSClientServer = 1
; Undocumented section
[/settings/default]
; ALLOWED HOSTS - A comaseparated list of allowed hosts. You can use netmasks (/ syntax) or * to create ranges.
allowed hosts = 127.0.0.1
; PASSWORD - Password used to authenticate againast server
password = [fake passwor]
; A list of aliases available. An alias is an internal command that has been "wrapped" (to add arguments). Be careful so you don't create loops (ie check_loop=check_a, check_a=check_loop)
[/settings/external scripts/alias]
ok1="C:\\Program Files\\NSClient++\\scripts\\check_ok.bat"
ping1="C:\\Program Files\\NSClient++\\scripts\\check_ping.bat"
; alias_cpu - Alias for alias_cpu. To configure this item add a section called: /settings/external scripts/alias/alias_cpu
alias_cpu = checkCPU warn=80 crit=90 time=5m time=1m time=30s
; alias_cpu_ex - Alias for alias_cpu_ex. To configure this item add a section called: /settings/external scripts/alias/alias_cpu_ex
alias_cpu_ex = checkCPU warn=$ARG1$ crit=$ARG2$ time=5m time=1m time=30s
; alias_disk - Alias for alias_disk. To configure this item add a section called: /settings/external scripts/alias/alias_disk
alias_disk = CheckDriveSize MinWarn=10% MinCrit=5% CheckAll FilterType=FIXED
; alias_disk_loose - Alias for alias_disk_loose. To configure this item add a section called: /settings/external scripts/alias/alias_disk_loose
alias_disk_loose = CheckDriveSize MinWarn=10% MinCrit=5% CheckAll FilterType=FIXED ignore-unreadable
; alias_event_log - Alias for alias_event_log. To configure this item add a section called: /settings/external scripts/alias/alias_event_log
alias_event_log = CheckEventLog file=application file=system MaxWarn=1 MaxCrit=1 "filter=generated gt -2d AND severity NOT IN ('success', 'informational') AND source != 'SideBySide'" truncate=800 unique descriptions "syntax=%severity%: %source%: %message% (%count%)"
; alias_file_age - Alias for alias_file_age. To configure this item add a section called: /settings/external scripts/alias/alias_file_age
alias_file_age = checkFile2 filter=out "file=$ARG1$" filter-written=>1d MaxWarn=1 MaxCrit=1 "syntax=%filename% %write%"
; alias_file_size - Alias for alias_file_size. To configure this item add a section called: /settings/external scripts/alias/alias_file_size

**Comment by dafyddj** [comment]
If you are new to nsclient++ then you should probably start with the latest version 0.4.3.143 from http://www.nsclient.org/download/

Anyway, I think you have misinterpreted the docs on external scripts. I have just tested the following and it works fine:

```
[/settings/external scripts/scripts]
foo=scripts\check_ok.bat

[/settings/external scripts/alias]
alias_foo=foo
```

**Comment by dickheth** [comment]
Thank you so much I was staring right at it missed the section [/settings/external scripts/scripts] everything works great now

 

 

Description: Description: avatar132_6

Dick and Diane Heth

321 Dawson Drive

Castle Rock, CO 80102

303-688-9098 H

303-941-5176 C

dick@hethnet.com

**Comment by mickem** [comment]
closing this, as it is answered, please reopen if you have further issues...
