### ISSUE TITLE
check_cpu returning values outside 0-100% 0.4.3.143

### ISSUE THREAD

**Issue by edolon** [mickem/nscp#168]
check_cpu returning values outside 0-100%.
I am running NSCP-0.4.3.143-x64.msi on Windows 2012 (6.2.9200)
(i also had this issue on 0.4.3.88, I skipped/didn't test versions in between)

I am calling nsclient++ from Icinga2 with 'insecure' NRPE.
The windows server that these checks are running on is very idle.

I define two check cpu aliases in nsclient.ini
[/settings/external scripts/alias]
alias_po_cpu = check_cpu "filter=core eq 'total'" "warn=kernel > 15 or load > 80" "crit=kernel > 20 or load > 90" "top-syntax=${status}: ${detail_list}" "detail-syntax=%(time) %(kernel)%/%(load)%" "time=1m" "time=5m" "time=15m"

alias_po_cpu-core = check_cpu "filter=core ne 'total'" "warn=kernel > 15 or load > 80" "crit=kernel > 20 or load > 90" "top-syntax=${status}: ${detail_list}" "detail-syntax=%(time) %(kernel)%/%(load)%" "time=1m" "time=5m" "time=15m"

I get the following returned sometimes
for alias_po_cpu: CRITICAL: critical(5m 3074457345%/0%, 15m 1024819115%/0%), 1m 0%/0%
for alias_po_cpu-core CRITICAL: critical(5m 6148914691%/0%, 15m 2049638230%/0%), 1m 0%/1%, 1m 0%/0%, 5m 0%/1%, 15m 0%/1%

after a few check cycles, (checks run once per minute) the values become in range again.
for alias_po_cpu: OK: 1m 0%/0%, 5m 0%/0%, 15m 0%/0%
for alias_po_cpu-core OK: 1m 0%/2%, 1m 0%/0%, 5m 0%/1%, 5m 0%/0%, 15m 0%/1%, 15m 0%/0%

**Comment by mickem** [comment]
Do you get any errors on the log?
Sounds like something fishy is going on with the collection so errors are probably in log and not check

**Comment by edolon** [comment]
I edited nsclient.ini to have
[/settings/log]
level = debug

Unfortunately I didn't see anything in the nsclient logs (besides the icinga2 server connecting to the nrpe server), do I need to set to level to 'trace' to maybe collect something useful?

In the data collection could this maybe be some edge case division by 0 error?
It seems like there is some sort of collection error/data corruption that gets propagated up though each time range.  There is two cores in this server, the error/corruption seems to only effect one core.

For some more info, in my icinga2 check history I see (newest log line at top, oldest log line at bottom)
sample1a-cores eq total
Service Ok[2015-08-31T10:52:44] SERVICE ALERT: management.corp.printeron.local;nrpe-cpu;OK;HARD;1;OK: 1m 0%/0%, 5m 0%/0%, 15m 0%/0%
Service Critical[2015-08-31T10:37:59] SERVICE ALERT: management.corp.printeron.local;nrpe-cpu;CRITICAL;HARD;1;CRITICAL: critical(5m 3074457345%/0%, 15m 1024819115%/0%), 1m 0%/0%
Service Critical[2015-08-31T10:37:44] SERVICE ALERT: management.corp.printeron.local;nrpe-cpu;CRITICAL;SOFT;3;CRITICAL: critical(5m 3074457345%/0%, 15m 1024819115%/0%), 1m 0%/0%
Service Critical[2015-08-31T10:36:44] SERVICE ALERT: management.corp.printeron.local;nrpe-cpu;CRITICAL;SOFT;2;CRITICAL: critical(1m 15372286728%/0%), 5m 0%/0%, 15m 0%/0%

sample1b-cores eq total
Service Ok[2015-08-31T15:45:44] SERVICE ALERT: management.corp.printeron.local;nrpe-cpu;OK;HARD;1;OK: 1m 0%/0%, 5m 0%/2%, 15m 0%/0%
Service Critical[2015-08-31T15:30:59] SERVICE ALERT: management.corp.printeron.local;nrpe-cpu;CRITICAL;HARD;1;CRITICAL: critical(5m 3074457345%/0%, 15m 1024819115%/0%), 1m 0%/0%
Service Critical[2015-08-31T15:30:44] SERVICE ALERT: management.corp.printeron.local;nrpe-cpu;CRITICAL;SOFT;3;CRITICAL: critical(5m 3074457345%/0%, 15m 1024819115%/0%), 1m 0%/0%
Service Critical[2015-08-31T15:29:44] SERVICE ALERT: management.corp.printeron.local;nrpe-cpu;CRITICAL;SOFT;2;CRITICAL: critical(1m 15372286728%/0%), 5m 0%/0%, 15m 0%/0%

sample2a-cores ne total
Service Ok[2015-08-31T10:52:58] SERVICE ALERT: management.corp.printeron.local;nrpe-cpu-core;OK;HARD;1;OK: 1m 0%/0%, 1m 0%/0%, 5m 0%/0%, 5m 0%/0%, 15m 0%/0%, 15m 0%/0%
Service Critical[2015-08-31T10:38:13] SERVICE ALERT: management.corp.printeron.local;nrpe-cpu-core;CRITICAL;HARD;1;CRITICAL: critical(5m 6148914691%/0%, 15m 2049638230%/0%), 1m 0%/0%, 1m 0%/0%, 5m 0%/0%, 15m 0%/0%
Service Critical[2015-08-31T10:37:58] SERVICE ALERT: management.corp.printeron.local;nrpe-cpu-core;CRITICAL;SOFT;3;CRITICAL: critical(5m 6148914691%/0%, 15m 2049638230%/0%), 1m 0%/0%, 1m 0%/0%, 5m 0%/0%, 15m 0%/0%
Service Critical[2015-08-31T10:36:58] SERVICE ALERT: management.corp.printeron.local;nrpe-cpu-core;CRITICAL;SOFT;2;CRITICAL: critical(1m 30744573456%/0%), 1m 0%/0%, 5m 0%/0%, 5m 0%/0%, 15m 0%/0%, 15m 0%/0%

sample2b-cores ne total
[2015-08-31T15:45:58] SERVICE ALERT: management.corp.printeron.local;nrpe-cpu-core;OK;HARD;1;OK: 1m 0%/0%, 1m 0%/0%, 5m 1%/3%, 5m 0%/1%, 15m 0%/1%, 15m 0%/0%
Service Critical[2015-08-31T15:31:13] SERVICE ALERT: management.corp.printeron.local;nrpe-cpu-core;CRITICAL;HARD;1;CRITICAL: critical(5m 6148914691%/0%, 15m 2049638230%/0%), 1m 0%/0%, 1m 0%/0%, 5m 0%/0%, 15m 0%/0%
Service Critical[2015-08-31T15:30:58] SERVICE ALERT: management.corp.printeron.local;nrpe-cpu-core;CRITICAL;SOFT;3;CRITICAL: critical(5m 6148914691%/0%, 15m 2049638230%/0%), 1m 0%/0%, 1m 0%/0%, 5m 0%/0%, 15m 0%/0%
Service Critical[2015-08-31T15:29:58] SERVICE ALERT: management.corp.printeron.local;nrpe-cpu-core;CRITICAL;SOFT;2;CRITICAL: critical(1m 30744573456%/0%, 5m 6148914691%/0%, 15m 2049638230%/0%), 1m 0%/0%, 5m 0%/0%, 15m 0%/0%

**Comment by mickem** [comment]
Fixed in next build of 0.4.3 (i think)

**Comment by edolon** [comment]
upgraded to 0.4.4.15 2015-11-25, issue still present.
I am unsure if this build contains the needed fixes

**Comment by mickem** [comment]
And no errors in the log?

**Comment by edolon** [comment]
with
[/settings/log]
level = info

the only lines I was getting in the log are (witch I believe to be unrelated):
2015-12-14 14:45:52: error:c:\source\nscp\modules\CheckDisk\check_drive.cpp:432: Failed to get volume information \\?\Volume{069f12ae-63a0-11e4-80b0-806e6f6e6963}\: 87: The parameter is incorrect.
2015-12-14 19:55:52: error:c:\source\nscp\modules\CheckDisk\check_drive.cpp:432: Failed to get volume information \\?\Volume{069f12ae-63a0-11e4-80b0-806e6f6e6963}\: 87: The parameter is incorrect.
2015-12-15 00:30:51: error:c:\source\nscp\modules\CheckDisk\check_drive.cpp:432: Failed to get volume information \\?\Volume{069f12ae-63a0-11e4-80b0-806e6f6e6963}\: 87: The parameter is incorrect.
2015-12-15 01:25:51: error:c:\source\nscp\modules\CheckDisk\check_drive.cpp:432: Failed to get volume information \\?\Volume{069f12ae-63a0-11e4-80b0-806e6f6e6963}\: 87: The parameter is incorrect.


I am trying to see if more lines are logged with 'level = trace'

**Comment by mickem** [comment]
Yes, those are unrelated...

Is it a virtual machine?
Do you get similar values in the perfmon?
