### ISSUE TITLE
[check_tasksched] ok-syntax and %(status)

### ISSUE THREAD

**Issue by garnier-quentin** [mickem/nscp#170]
Hi,

I have the following result with nsclient 0.4.3-143:
```
# check_nrpe -H xxxx -p 5666 -t 30 -u -c check_tasksched -a "filter=enabled eq 1" "warning=exit_code > 4" "critical=" "perf-config=*(ignored:true)" 'ok-syntax=%(status): All tasks are ok'
: All tasks are ok
```

As you can see, i don't have the 'OK' before ':'. Is it a bug ? Moreover, is it useful to use macro '%(status)' for the ok-syntax ? (it should be 'ok' in some logic no ?)

Thanks.

**Comment by mickem** [comment]
In my "infinite wisdom" I thought that starting the status with the same value which comes in the status did not make sense so I started to remove them... this was probably a bad idea on my part.

I will probably be adding back the %(status) to the messages at some point...
