### ISSUE TITLE
[check_tasksched] problem with exit_code != 0

### ISSUE THREAD

**Issue by garnier-quentin** [mickem/nscp#171]
Hi,

I'm using NSClient 0.4.3-143.
When i'm executing the following command with the 'exit_code > 0', it's working:
```
# check_nrpe -H xxxx -p 5666 -t 30 -u -c check_tasksched -a "filter=enabled eq 1" "warning=exit_code > 0" "critical=" "perf-config=*(ignored:true)" 'ok-syntax=%(status): All tasks are ok'
/TestTask: 4567 != 0
```

But with the following command and 'exit_code != 0', it don't work ??!!
```
# check_nrpe -H xxxx -p 5666 -t 30 -u -c check_tasksched -a "filter=enabled eq 1" "warning=exit_code != 0" "critical=" "perf-config=*(ignored:true)" 'ok-syntax=%(status): All tasks are ok'
: All tasks are ok
```

Thanks.

**Comment by mickem** [comment]
Works for me in 0.5.0.


    check_tasksched "filter=enabled eq 1" "warning=exit_code > 0" "critical=none" "perf-config=*(ignored:true)" "ok-syntax=%(status): All tasks are ok"
    L        cli WARNING: /ASUS Splendid ACMON: 267009 != 0, /RtHDVBg: 267009 != 0, /RTKCPL: 267009 != 0
    check_tasksched "filter=enabled eq 1" "warning=exit_code != 0" "critical=none" "perf-config=*(ignored:true)" "ok-syntax=%(status): All tasks are ok"
    L        cli WARNING: /ASUS Splendid ACMON: 267009 != 0, /RtHDVBg: 267009 != 0, /RTKCPL: 267009 != 0

**Comment by mickem** [comment]
Could it be an escaing issue maybe?

**Comment by garnier-quentin** [comment]
'!= 0' works if my exit code task is 1 (but not 2, 3). I don't think it's a escaping issue. I see the '!= 0' in the output of nrpe when my task exit code is 1.

**Comment by mickem** [comment]
Could you give this a spin with 0.5.0?

There is a fix for aggregated results in there which I think should not be affected but that all I can think of.

I just started to add a unit test for this and it seems to work for me unless I am missing somethng?

task with exitcode 0:

    check_tasksched "filter=title = 'NSCPSample_OK'" "warn=exit_code != 0"
    L        cli OK: : All tasks are ok
    L        cli  Performance data: 'NSCPSample_OK_exit_code'=0;0;0
    check_tasksched "filter=title = 'NSCPSample_OK'" "warn=exit_code != 1"
    L        cli WARNING: /NSCPSample_OK: 0 != 0
    L        cli  Performance data: 'NSCPSample_OK_exit_code'=0;1;0
    check_tasksched "filter=title = 'NSCPSample_OK'" "warn=exit_code != 2"
    L        cli WARNING: /NSCPSample_OK: 0 != 0
    L        cli  Performance data: 'NSCPSample_OK_exit_code'=0;2;0
    check_tasksched "filter=title = 'NSCPSample_OK'" "warn=exit_code != 3"
    L        cli WARNING: /NSCPSample_OK: 0 != 0
    L        cli  Performance data: 'NSCPSample_OK_exit_code'=0;3;0


task with exitcode 2:

    check_tasksched "filter=title = 'NSCPSample_CRIT'" "warn=exit_code != 0"
    L        cli WARNING: /NSCPSample_CRIT: 2 != 0
    L        cli  Performance data: 'NSCPSample_CRIT_exit_code'=2;0;0
    check_tasksched "filter=title = 'NSCPSample_CRIT'" "warn=exit_code != 1"
    L        cli WARNING: /NSCPSample_CRIT: 2 != 0
    L        cli  Performance data: 'NSCPSample_CRIT_exit_code'=2;1;0
    check_tasksched "filter=title = 'NSCPSample_CRIT'" "warn=exit_code != 2"
    L        cli OK: : All tasks are ok
    L        cli  Performance data: 'NSCPSample_CRIT_exit_code'=2;2;0
    check_tasksched "filter=title = 'NSCPSample_CRIT'" "warn=exit_code != 3"
    L        cli WARNING: /NSCPSample_CRIT: 2 != 0
    L        cli  Performance data: 'NSCPSample_CRIT_exit_code'=2;3;0

**Comment by mickem** [comment]
0.5.0.16 does not have this issue what I can see, if you can reprouce with 0.5.0.16 please reopen. As the filters have been changed in 0.5.0 I will probably not backport his change to 0.4.xbut please do let me know if you still have this issue in 0.5.0.16: https://www.nsclient.org/download/0.5.0/
