### ISSUE TITLE
0.4.3.143 - check_process and detail-syntax cannot be changed

### ISSUE THREAD

**Issue by box293** [mickem/nscp#175]
I was playing with this today and I found some issues I think.

Here's the baseline.
```
Command:
check_nrpe -H win2008r2-01 -c check_process -a "process=*" warning='count > 40' critical='count > 100'

Output:
WARNING: Tail.exe=started, vds.exe=started, TrustedInstaller.exe=started, Geany.exe=started, nscp.exe=started|'count'=45;40;100
```

I wanted to change the output just so it would report that the threshold has been exceeded, I did not care about the names of the exe and the state. I had a lot of problems, so I thought I would try expressing the detail-syntax as it's explained in the manual:

```
Command:
check_nrpe -H win2008r2-01 -c check_process -a "process=*" warning='count > 40' critical='count > 100' detail-syntax="${exe}=${state}"

Output:
WARNING: =, =, =, =, =, =|'count'=46;40;100
```

I have a feeling that most of the xxx-syntax options are not working.

**Comment by mickem** [comment]
I would bet your running that command from linux right?

In which case the shell escapes the ${hello} into empty strings unless you have set them.
That is why I also added support for %() which is simpler in a unix environment.
Try:

    check_nrpe -H win2008r2-01 -c check_process -a "process=*" warning='count > 40' critical='count > 100' detail-syntax="%(exe)=%(state)"

**Comment by box293** [comment]
You're spot on, that’s exactly what it was. With single quotes the $ sign works ... can't believe I didn't try the single quotes before posting here!
