### ISSUE TITLE
legacy nrpe: escape expressions not working

### ISSUE THREAD

**Issue by upietz** [mickem/nscp#176]
Hello,

the replacement expression s(..) for '..' (as described here: http://docs.nsclient.org/0.4.3/faq/index.html#nasty-metacharacters) is not working for me. When "allow nasty characters = false" is set in nsclient.ini and the following command is issued on the client:

```/usr/lib/nagios/plugins/check_nrpe -H <hostname> -c "check_service" -a "service=*" "filter=name not regexp s(clr_opt.*)"
Failed to validate filter see log for details```

And on the server:
```D w32system Parsing failed of 'name not regexp s(clr_opt.*)' at: (clr_opt.*)```

Using "allow nasty characters = true" and s(..) replaced by '..', everything works as expected. Substitution of ${..} by %(..) is working. 

nscp version: 0.4.3.143
check_nrpe: 2.15

Regards,

upietz

**Comment by mickem** [comment]
Could you try str() instead of s() ?
Reading the grammar seems that is what is used (but havent tried it myself)

**Comment by upietz** [comment]
Hello Michael,

thanks for the information. str(..) works perfectly! Maybe you can correct this in the docs?

**Comment by mickem** [comment]
Indeed do you know where in the docs you found it?

**Comment by upietz** [comment]
Oh I just saw the link above isn't working, should be https:
https://docs.nsclient.org/0.4.3/faq/index.html#nasty-metacharacters
