### ISSUE TITLE
How access webserver?

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#179]
Hello,
Following this:
https://www.nsclient.org/2014/05/18/web-and-rest-updates
```
[/modules]
WEBServer = 1
[/settings/WEB/server]
; PORT NUMBER - Port to use for WEB server.
port = 8443
; CERTIFICATE - Ssl certificate to use for the ssl server
certificate = ${certificate-path}/certificate.pem
```
Browsing to http://localhost:8443/ or http://localhost:8080/
gives 'error connection reset' in browser

Anything else needed to use the webbrowser?

**Comment by mickem** [comment]
That ought to work, anything in the log?
Could possibly be allowed hosts though I was under the impression it was not implemented.

A good way to see the config is this:

    $ nscp web install
    Enabling WEB from (currently not supported): 127.0.0.1
    HTTP(s) is enabled using C:\source\build\x64\dev/security/certificate.pem.
    Point your browser to: 8443

**Comment by willemdh** [comment]
c:\Program Files\NSClient++>nscp web install
Enabling WEB from (currently not supported): 212.71.234.84,127.0.0.1,::1
Point your browser to: 8443

Browsing to http://localhost:8443 => ERR_CONNECTION_RESET

**Comment by mickem** [comment]
Really strange... is there anythign in the nsclient++ log?

(and I assume you have 0.4.3 right?)

**Comment by willemdh** [comment]
I'm at 0.4.3.143 atm. When i try nscp test, I get this info:

```
2015-10-25 13:58:04: debug:D:\source\nscp\service\NSClient++.cpp:736: Loading plugin: WEBServer
2015-10-25 13:58:04: debug:D:\source\nscp\modules\WEBServer\WEBServer.cpp:652: Using certificate: C:\Program Files\NSClient++/security/certificate.pem
2015-10-25 13:58:04: debug:D:\source\nscp\modules\WEBServer\WEBServer.cpp:661: Loading webserver on port: 8443
2015-10-25 13:58:04: debug:D:\source\nscp\service\NSClient++.cpp:504: NSClient++ - 0.4.3.143 2015-04-29 Started!
```
Not really sure what else I can do. Tired disabling firewall / antivirus, but didn't help. Also read through this:
http://forums.nsclient.org/t/webui/3602/5
I have a password set in [/settings/default]

**Comment by willemdh** [comment]
Michael, Just wanted to say I just tested your 5.0.7 and the web server is working properly now:

https://localhost:8443

It looks very neat by the way. Nice work.
