### ISSUE TITLE
powershell arguments always extend with -- NSCP.EXE file Version: 0.4.3.143 (32Bit)

### ISSUE THREAD

**Issue by RonnyBunke** [mickem/nscp#180]
Hi, I'm trying a PowerShell script with arguments.

Unfortunately, the argument always  extend with "--".

How can I use arguments without this "--" is Extended?

 **The entry in the nsclient.ini .:**

    [/settings/external scripts/scripts]
    check_updates=cmd /c echo scripts\check_windows_updates.ps1 -maxcrit $ARG1$; exit $LastExitCode | "%systemroot%\System32\WindowsPowerShell\v1.0\powershell.exe" -command -

**My test command:**

 

    nscp.exe client -q check_updates -a 30

**The Output:**<br>
Here are the argument "--30" its must be 30.

    C:\Program Files (x86)\ICINGA2\NSClient++\scripts\check_windows_updates.ps1 : C
    annot process argument transformation on parameter 'maxcrit'. Cannot convert va
    lue "--30" to type "System.Int32". Error: "Input string was not in a correct fo
    rmat."
    At line:1 char:43
    + scripts\check_windows_updates.ps1 -maxcrit <<<<  --30; exit $LastExitCode
        + CategoryInfo          : InvalidData: (:) [check_windows_updates.ps1], Pa
       rameterBindin...mationException
        + FullyQualifiedErrorId : ParameterArgumentTransformationError,check_windo
       ws_updates.ps1|

**Comment by mickem** [comment]
Not sure I follow:


    [/modules]
    CheckExternalScripts = enabled
    
    [/settings/external scripts/wrapped scripts]
    check_test=check_test.ps1 10 20 30



    check_test
    D ext-script Command line: cmd /c echo scripts\\check_test.ps1 10 20 30; exit($lastexitcode) | powershell.exe -command -
    L        cli OK: Test arguments are: (10 "20" "30")

**Comment by RonnyBunke** [comment]
Many thanks for your help.
It was my fault.
The correct test command is as follows: "nscp.exe Client -q check_updates 30"
And now it works well.

Many thanks

**Comment by mickem** [comment]
Great it worked out!
