### ISSUE TITLE
0.4.3.143 check_eventlog: "Failed to convert: auditFailure" level for Security log

### ISSUE THREAD

**Issue by ShaggyPG** [mickem/nscp#181]
It seems that there is problem with auditFailure and auditSuccess in filter argument for check_eventlog.

While executing:
check_eventlog file=Security filter="written > -10m AND (level eq 'auditFailure')"
I get:
D   eventlog Error: Failed to convert: auditFailure

Same behavior when using auditSuccess. 
When using Error/Warning/Info everything is ok but obviously nothing is returned.
Numeric replacement is not working (I guess it should be 6 or 7) - no error but also no events.

BTW made typo in Reference Manual for Check_eventlog at level description (auditSucess) ;)

**Comment by mickem** [comment]
Hmm, not sure auditSuccess is a level actually, can you give me the XML for the eventlog record your looking for?

**Comment by ShaggyPG** [comment]
Well, I used such level for nsclient 0.3 with success using filter as follows:
"filter=generated gt -10m AND type='auditFailure'"

xml for event that I'm looking for (failed login):
<System>
  <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{}" /> 
  <EventID>4656</EventID> 
  <Version>1</Version> 
  <Level>0</Level> 
  <Task>12800</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8010000000000000</Keywords> 
  <TimeCreated SystemTime="2015-10-23T13:57:07.549437500Z" /> 
  <EventRecordID>2931847</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="684" ThreadID="692" /> 
  <Channel>Security</Channel> 
  <Computer></Computer> 
  <Security /> 
  </System>

I may alternatively use an EventID but I think it isn't best solution...

**Comment by mickem** [comment]
Well, with vista microsoft change how the eventlog works. So gone are all the old "special flags" ans instead there are generic ones. Might want to look at task, eventid and provider and see if you can come up with a good way to filter these.

please do let me if you figure something out.

**Comment by mickem** [comment]
This will be resolved soon... I have added support for task (and keyword) to check_eventlog.

The way this works is you need to first lookup the task name using your provider (Microsoft-Windows-Security-Auditing):

    nscp eventlog list --tasks --publisher "Microsoft-Windows-Security-Auditing"
    Microsoft-Windows-Security-Auditing
    Tasks:
     * SE_ADT_SYSTEM_SECURITYSTATECHANGE (12288)
     * SE_ADT_SYSTEM_SECURITYSUBSYSTEMEXTENSION (12289)
     * SE_ADT_SYSTEM_INTEGRITY (12290)
    ...
     * SE_ADT_LOGON_CLAIMS (12553)
     * SE_ADT_LOGON_GROUPS (12554)
     * SE_ADT_OBJECTACCESS_FILESYSTEM (12800)
     * SE_ADT_OBJECTACCESS_REGISTRY (12801)
     * SE_ADT_OBJECTACCESS_KERNEL (12802)
     * SE_ADT_OBJECTACCESS_SAM (12803)
     * SE_ADT_OBJECTACCESS_OTHER (12804)
     * SE_ADT_OBJECTACCESS_CERTIFICATIONAUTHORITY (12805)
     * SE_ADT_OBJECTACCESS_APPLICATIONGENERATED (12806)
     * SE_ADT_OBJECTACCESS_HANDLE (12807)
     * SE_ADT_OBJECTACCESS_SHARE (12808)
    ...
     * SE_ADT_ACCOUNTLOGON_CREDENTIALVALIDATION (14336)
     * SE_ADT_ACCOUNTLOGON_KERBEROS (14337)
     * SE_ADT_ACCOUNTLOGON_OTHERS (14338)
     * SE_ADT_ACCOUNTLOGON_KERBCREDENTIALVALIDATION (14339)
     * SE_ADT_UNKNOWN_SUBCATEGORY (65280)

No you can find the task name for 12800 which is SE_ADT_OBJECTACCESS_FILESYSTEM.

Then you can add the following to your filter: 

    ... task = 'SE_ADT_OBJECTACCESS_FILESYSTEM' ...

Like so:

    check_eventlog "filter=task = 'SE_ADT_OBJECTACCESS_FILESYSTEM'"

Another way to find the task for a given event is to change the display option temporarily like so:

    check_eventlog filter=id=4656 "detail-syntax=task=%(task)"

As that will display the task for all your message (this only gives you tasks which you have in the log though).

**Comment by mickem** [comment]
(This will come in the next 0.5.0 build)
