### ISSUE TITLE
SSL encryption by default

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#193]
It seems NCPA is using a self signed certificate by default, which seems more secure then the DH encryption of NSClient. (please correct me if I'm wrong) Is there any chance that NSClient will get a similar feature?
Check https://assets.nagios.com/downloads/ncpa/docs/html/configuration.html

I read through this: http://www.medin.name/blog/2012/12/02/securing-nrpe-with-certificate-based-authentication/
But as I don't have a root ca and it does seem quite some work.

**Comment by mickem** [comment]
It already does both for the WEBUi (which was a bit buggy i 0.4.3) as well as NRPE (which is why we have the --insercure option).

**Comment by willemdh** [comment]
Ah sorry Michael, I didn't knew. So my NRPE server setting in the nsclient.ini looks like this now on my Windows desktop. I'm monitoring it from a Linode server I'm renting.

```
[/settings/NRPE/server]
use ssl = 1
allow nasty characters = 1
allow arguments = 1
port = 5666
extended response = 1
ssl options = no-sslv2,no-sslv3
insecure = true
verify mode = none
timeout = 300
```

When I set insecure to false, I get "CHECK_NRPE: Error - Could not complete SSL handshake." on my Nagios checks.

**Comment by mickem** [comment]
Problem is that check_nrpe does not support proper SSL; so you need to install nsclient++ on linux as well. IN the next version the plan is to create a light weight package with only check_nrpe to make transition easier

**Comment by willemdh** [comment]
I installed nsclient on my centos server.
/usr/bin/check_nrpe
/usr/local/nagios/libexec/check_nrpe
/usr/local/nrdp/plugins/Linux/i386/check_nrpe
/usr/local/nrdp/plugins/Linux/x86_64/check_nrpe

/usr/bin/check_nrpe is the 'new' check_nrpe? Can I safely replace the old check_nrpe with new one? Will my checks_using the old check_nrpe still work?

**Comment by willemdh** [comment]
I tried replacing it and get 
```
Failed to parse command line re-run with help to get help: the required argument for option '--host' is missing
```
So when replacing -H server with --host server I get:
```
/usr/local/nagios/libexec/check_nrpe --host server -c check_memory
Failed to load certificate /usr/local/nagios/libexec/security/certificate.pem: No such file or directoryFailed to load certificate (as key) /usr/local/nagios/libexec/security/certificate.pem: system libSSL handshake failed: short readError: Failed to connect to: server:5666 :short read%
```
It seems
```
ls /usr/local/nagios/libexec/security/certificate.pem
ls: cannot access /usr/local/nagios/libexec/security/certificate.pem: No such file or directory
➜  ~  ls /usr/local/nagios/libexec/security
ls: cannot access /usr/local/nagios/libexec/security: No such file or directory
```
that the certificate.pem and security folder don't exist?

**Comment by willemdh** [comment]
Ok, found it here /usr/share/nsclient/security/certificate.pem
But the error I get was cannot access /usr/local/nagios/libexec/security/certificate.pem

```
/usr/bin/check_nrpe --host f1rebase.ddns.net -c check_memory
Failed to load certificate /usr/bin/security/certificate.pem: No such file or directoryFailed to load certificate (as key) /usr/bin/security/certificate.pem:
```


Do I need to change a setting somewhere?

**Comment by mickem** [comment]
No thats a bug in 0.4.3 certificate will be created by NRPE module (if used) otherwise you have to create it by hand.
This is fixed in 0.4.4

You can also disable ssl as well...

**Comment by willemdh** [comment]
I downloaded 0.4.4 here => https://github.com/mickem/nscp/releases 
Is there an rpm available?
How would I best upgrade on Linux to 0.4.4?

**Comment by mickem** [comment]
First off 0.4.4 is very very alpha... so use with caution...

But not sure what your trying to do, if your looking for a NRPE client with supports ssl 0.4.4. will be the same as 0.4.3.
If you looking for the WEB:UI I guess that makes "more sense on windows"...

// Michael

**Comment by willemdh** [comment]
I'm looking to monitor a computer over the Internet over a secure ssl connection. I will keep 0.4.3 then for now. So  I tried copying the /usr/share/nsclient/security/certificate.pem to /usr/bin/security/certificate.pem
After which I no longer get "Failed to load certificate" error, but now I get:
```
/usr/bin/check_nrpe --host server -c check_memory
SSL handshake failed: short readError: Failed to connect to: f1rebase.ddns.net:5666 :short read%
```

**Comment by mickem** [comment]
If you want to monitor securely then you do not want self signed certificate as that removes all trust. You can still use your own cert but you have do so from a CA so you establish trust. Now setting up ssl is a bit of pain (especially if you dont know the details of ssl). 

If you follow my blog post please do let me know where it failes and relevant config but please do notice you need to configure bith nsclient++ the same in both ends.

A good idea is to use check_nrpe from the nsclient++ command line on windows as that will put certs and such in the same place...

**Comment by willemdh** [comment]
Michael,

I'm not an expert, but I have some knowledge about PKI / SSL. I tried to follow your guide, but it seems some data is missing:
```
To create a certificate with openssl we can use the bundles CA.pl perl script. 
```
I can find some info about CA.pl here => https://www.openssl.org/docs/manmaster/apps/CA.pl.html
But although I have OpenSSL installed, I can't find CA.pl on my server.
```
In my case I start from scratch so I need to generate the CA using the following command (it will ask for CA password as well as some meta information):
```
The command you refer to to generate the CA seems to be missing here?
```
Then we can request the first certificate and sign it:
```

The plan was to install a VirtualBox CentOS 7 server on an USB stick, make it a CA, create the required certificates and then shut it down and keep the USB stick somewhere safe. If you could add the missing command to the procedure, I will continue trying to get this working.

**Comment by mickem** [comment]
A quick google pointed to a package called "openssl-perl" so might wanna try :

    yum install openssl-perl

Havent tried at all so cant really say if it is correct or not...

**Comment by box293** [comment]
I have a suggestion. Instead of "check_nrpe" in your linux version of NSClient++, perhaps call it "check_nscp" ... this would save a lot of confusion in the future and helps promote your nscp brand.

**Comment by willemdh** [comment]
it is indeed confusing.

**Comment by mickem** [comment]
Thats a point, maybe check_nrpe_ssl ?
There will also be a check_nscp which will use the rest API hence I wanted to have the one for nrpe called nrpe...

**Comment by willemdh** [comment]
check_nrpe_ssl is fine for me :)

**Comment by box293** [comment]
check_nrpe_ssl sounds great

**Comment by mickem** [comment]
Is renamed now unless I am mistaken...
