### ISSUE TITLE
0.4.4.3: No command or alias found matching

### ISSUE THREAD

**Issue by Tux12Fun** [mickem/nscp#196]
Hi,

the new Test Client, can't find any Alias

Config:
...
[/settings/external scripts/alias]
check__HDD_C = CheckDriveSize MaxWarn=80% MaxCrit=90% FilterType=FIXED Drive=c:
...

Command:
./check_nrpe -H 10.1.6.6 -c check__HDD_C
No command or alias found matching: check__hdd_c

Is this a Upper/Lowercase problem?

The next thing I noticed is:
============================
./check_nrpe -H 10.1.6.6
I () seem to be doing fine...                                                 << New Client
./check_nrpe -H 10.1.3.186
I (0.4.3.131 2015-02-15) seem to be doing fine...               << Old Client

**Comment by nagwindmon** [comment]
hello, I believe the definitions are case sensitive, so I would say yes, most likely Upper/Lowercase issue
HTH

**Comment by mickem** [comment]
Which version is the new client? 0.4.3.131 is not "old" per and latest (0.4.3.14?) should have have much in way of changes...

If it is 0.4.4 (hence fort known as 0.5.0) then Id say it could be a bug...

Regarding case, 0.4.3 (and 0.4.2.) I think lower cases everything so case should not be an issue...

**Comment by mickem** [comment]
This is fixed in the last 0.5.0 build
