### ISSUE TITLE
Issue with CHECK_NRPE

### ISSUE THREAD

**Issue by drooid** [mickem/nscp#197]
Hello,

I'm having an issue running checks on a Windows machine. I am running Nagios 4.1.1 on CentOS 7 and have NRPE installed as well. I'm not sure if my issue is because of incorrect syntax or something else.

On the Windows machine's nsclient.ini file I have:
alias_mem = check_memory
alias_cpu = check_cpu "warn=load >80" "crit=load > 90" time=5m time=1m time=30s
alias_check_c = check_drivesize "crit=free_pct<10%" "warn=free_pct<20%" drive=all-drives

On the Nagios server I have services defined with their check_command's being:
check_command   check_nrpe!alias_mem
check_command   check_nrpe!alias_cpu
check_command   check_nrpe!alias_check_c

When viewing the Windows host on the Nagios web client, I see that all of these checks are failing and giving the error:
CHECK_NRPE: Error - Could not complete SSL handshake

Thank you very much for any and all help. I'd be happy to provide any other information needed.

**Comment by box293** [comment]
If this is NSClient++ 0.4.3.x onwards you'll need to:
```
cd "\Program Files\NSClient++\" 
nscp settings --path /settings/NRPE/server --key insecure --set true
```
Then restart the NSClient++ service.

**Comment by drooid** [comment]
I entered those commands on the Windows host and also restarted the NSClient service. After checking the Nagios web client again, the same error remains.

**Comment by mickem** [comment]
Check the log on the nsclient++ side.

SSL issues are usualy due to two things:

1, "secure mode" (this is what @box293 mentioned above)
2, check_nrpe not compiled with ssl (or ssl disable on command line)

**Comment by drooid** [comment]
On checking the client log, I see some things have changed after running the above command. Around 18:29 is when I ran that command.

Log:

2015-11-05 18:21:04: error:D:\source\nscp\include\nrpe/server/protocol.hpp:80: Rejected connection from: 222.174.46.250
2015-11-05 18:25:19: error:D:\source\nscp\include\nrpe/server/protocol.hpp:80: Rejected connection from: 222.174.46.250
2015-11-05 18:28:04: error:D:\source\nscp\include\nrpe/server/protocol.hpp:80: Rejected connection from: 222.174.46.250
(Above command ran)
2015-11-05 18:31:04: error:D:\source\nscp\include\socket/connection.hpp:243: Failed to establish secure connection: sslv3 alert unexpected message: 1010
2015-11-05 18:32:06: error:D:\source\nscp\include\check_nt/server/protocol.hpp:67: Rejected connection from: 222.174.46.240
2015-11-05 18:32:06: error:D:\source\nscp\include\check_nt/server/protocol.hpp:67: Rejected connection from: 222.174.46.240
2015-11-05 18:33:58: error:D:\source\nscp\include\check_nt/server/protocol.hpp:67: Rejected connection from: 222.174.46.240

**Comment by drooid** [comment]
After running the above command, I'm not sure why the hpp port changed or the IP it was trying to connect to changed. I am trying to copy old host config files (that were on .240) to a new Nagios server which is .250.

Both the client nsclient.ini and server nrpe.cfg files have only the .250 labeled as allowed hosts.

**Comment by mickem** [comment]
Rejected connection from: 222.174.46.240 means you need to add your server to allowed hosts.

**Comment by drooid** [comment]
I'm not sure why this thread is closed. In my above post I stated that the nagios server I'm trying to use 222.174.46.250, not .240. I'm not sure where it's seeing .240, as both the client's nsclient.ini and server's nrpe.cfg files have only the .250 labeled as allowed hosts.

**Comment by mickem** [comment]
Sorry, I missed that bit...

Are you sure there is no nat/multi homed if, etc etc which can cause an issue?

I have never heard anyone report an issue regarding the IP being wrong (which is all handled by the boost library).

**Comment by drooid** [comment]
How would I be able to check this? I can provide any logs necessary as well.

**Comment by mickem** [comment]
Well, that would be a question for a network technician I guess...

**Comment by drooid** [comment]
Well, are there any other config files that might have that different IP address listed? Also, how can I revert the changes from the command @box293 posted?

**Comment by mickem** [comment]
The command he posted sets a value in the settings file, resetting that will revert the change.

As for the ip address it reports the ip your using so you need to figure out why your coming from the wrong IP.

My guess is this is related to network topology or something along those lines...

I am pretty skeptical that this is an issue with NSClient++ so unless you have some details on why it would be the wrong IP I am considering closing this...

**Comment by drooid** [comment]
You stated: SSL issues are usualy due to two things:
1, "secure mode" (this is what @box293 mentioned above)
2, check_nrpe not compiled with ssl (or ssl disable on command line)

If we've taken care of #1, let's move onto #2. What commands can I run to make sure check_nrpe is compiled with ssl?

**Comment by mickem** [comment]
But your issue is "Rejected connection from: 222.174.46.240" which is not related to ssl, this is related to using or configuring the wrong ip...

**Comment by drooid** [comment]
The wrong IP is not an issue anymore.The old server (.240) was still trying to talk to the host for some reason. The original issue with ssl still remains.

On my windows host's nsclient.log I'm now getting this error:
Error:D:\source.....\socket/connection.hpp:243: Failed to establish secure connection: sslv3 alert unexpected message: 1010

When I compiled nrpe I ran "./configure --enable-ssl". What commands can I run to make sure check_nrpe is compiled with ssl?

**Comment by box293** [comment]
Most likely openssl-devel is not installed on the server executing check_nrpe (which it needs to be before compiling).

Here's a quick guide on compiling it with ssl enabled:

http://sites.box293.com/nagios/guides/nrpe/plugin-on-core-4-0-x/centos-6-5

Generally speaking, look at the entire configure output, it will detect if the ssl components do or don't exist.

**Comment by drooid** [comment]
Openssl-devel is already installed on the server.

I followed the steps in the link you shared and after compiling I see that there are no errors and SSL headers are found in /usr and SSL libraries are found in /usr/lib64.

After running "make all" and "make install", there are no errors, but then trying the test "check_nrpe -H <hostip>" fails with "Could not complete SSL handshake". Do I need to delete any files before recompiling or will it do a rewrite?

**Comment by box293** [comment]
It should do a rewrite. Do you have a linux machine running nrpe that you could test against? This would rule out NSClient++ being the problem or it will confirm if check_nrpe is compiled correctly.

What is the output of:
```
ldd /usr/local/nagios/libexec/check_nrpe
```

**Comment by drooid** [comment]
I will try to add a linux machine. The output is:

        linux-vdso.so.1 =>  (0x00007fff69187000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007f6280572000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f628018b000)
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f627ff71000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f627fbb0000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f627f964000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f627f680000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f627f47c000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f627f24a000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f627f045000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f627ee2f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f62807e8000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f627ec20000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f627ea1b000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f627e801000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f627e5e5000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f627e3bf000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f627e15e000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f627df39000)

**Comment by drooid** [comment]
I moved a linux host from my old Nagios server to the new one and am getting this error on several checks: "Return code of 255 is out of bounds". Only check_ping is working.

I added the new nagios server's IP to the client's nrpe.cfg as well as to /etc/xinetd.d/nrpe. I added accept rules to iptables for both ssh and nrpe for the new nagios IP (copying the two rules concerning the old nagios server's IP that I saw)

Also, on the new nagios server, I tried running: /usr/local/nagios/libexec/check_nrpe -H localhost
and received the "Could not complete SSL handshake error".

**Comment by box293** [comment]
What happens if you try without ssl (-n)

```
/usr/local/nagios/libexec/check_nrpe -H localhost -n
```

**Comment by drooid** [comment]
/usr/local/nagios/libexec/check_nrpe -H localhost -n

CHECK_NRPE: Error receiving data from daemon.

**Comment by box293** [comment]
I suggest bringing this over to the Nagios support forums where it can be handled better than here. 

https://support.nagios.com/forum/viewforum.php?f=7

**Comment by drooid** [comment]
Brought there and resolved. Issue was with "verify mode" option in nsclient.ini
https://support.nagios.com/forum/viewtopic.php?f=7&t=35753&start=10

**Comment by rhyven** [comment]
@drooid I came here from the future to thank you for including a link to the solution for your problem.  _<*tips hat*>_
