### ISSUE TITLE
5.0.9 => Negative values for check_drivesize

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#201]
Hello,

I was testing the new webserver and noticed that check_drivesize is showing negative values:

![image](https://cloud.githubusercontent.com/assets/6462991/11092600/eacc30c4-8884-11e5-966e-a6e2f070629e.png)

Also the percentages used seem to be all 0.

**Comment by mickem** [comment]
strange, shall look into it (hoping it is parsing perfdata in the web ui which is brokn).
Or do you get the same from your monitoring?

**Comment by willemdh** [comment]
Michael,

I seem to get the same from my monitoring:
```
/usr/local/nagios/libexec/check_nrpe -H server -c check_drivesize -a drive=c: "warning=used > 90%" "critical=used > 95%" "top-syntax=%(status) {%(detail_list)}" "detail-syntax= {Drive %(drive) Total: %(size), Used: %(used), Free: %(free)}" "perf-config=*(unit:G) used %(ignored:true)"
OK { {Drive c: Total: 418.668GB, Used: 262.1GB, Free: 156.568GB}}|'c: used'=-1.90019G;0.80116;1.73456;0;418.66796`
```
It seems the values in the detail syntax are correct, but it's the perfdata that is incorrect.

Grtz

**Comment by mickem** [comment]
But they are wrong in the perf data... well need to check that (perf data has been changed a bit in 0.5.x)

**Comment by mickem** [comment]
Fixed in next build
