### ISSUE TITLE
5.0.9 => Invalid return for check_nt

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#202]
It seems I'm getting errors for check_nt checks in 5.0.7+

NSClient - ERROR: Invalid return from command: check_drivesize
NSClient - ERROR: Invalid return from command: check_cpu

NSClientServer = enabled

and 
``` 
[/settings/NSClient/server]

; ENABLE SSL ENCRYPTION - This option controls if SSL should be enabled.
use ssl = 0

; PERFORMANCE DATA - Send performance data back to Nagios (set this to 0 to remove all performance data).
performance data = 1

; PORT NUMBER - Port to use for check_nt.
port = 12489
```

So

```
/usr/local/nagios/libexec/check_nt -H server -s "tpn4ESblabla" -p 12489 -v USEDDISKSPACE -l C -w 80 -c 95
NSClient - ERROR: Invalid return from command: check_drivesize
```

**Comment by mickem** [comment]
Yes, check_nt is currently broken in 0.5.x will be fixed "soon" (but probably not till after OSMC next week)

**Comment by willemdh** [comment]
This seem still broken in 0.5.0.16:

```
/usr/local/nagios/libexec/check_nt -H f1rebase.ddns.net -s password -p 12489 -v USEDDISKSPACE -l C -w 80 -c 95
NSClient - ERROR: Invalid return from command: check_drivesize
```

**Comment by mickem** [comment]
will investigate... I ran some disk checks which was fine but might have missed something...

**Comment by mickem** [comment]
Do you have the chekdisk module loaded?

The above command works for me:

    mickem@felix:~$ /usr/lib/nagios/plugins/check_nt -H 192.168.0.201 -p 12489 -v USEDDISKSPACE -l C -w 80 -c 95
    C:\ - total: 452.34 Gb - used: 378.31 Gb (84%) - free 74.02 Gb (16%) | 'C:\ Used Space'=378.31Gb;361.87;429.72;0.00;452.34

**Comment by willemdh** [comment]
Yes I have the checkdisk, checksystem nd nsclientserver module loaded. Checked in the nsclient.ini and the webclient.

The weird thing is that CLIENTVERSION seems to work but all the rest doesn't..

    /usr/local/nagios/libexec/check_nt -H f1rebase.ddns.net -p 12489 -v CLIENTVERSION -s "password"
    NSClient++ 0.5.0.16 2015-11-21

But UPTIME results in:

    /usr/local/nagios/libexec/check_nt -H f1rebase.ddns.net -p 12489 -v UPTIME -s "password"
    NSClient - ERROR: Invalid return from command: check_uptime

USEDDISKSPACE still:

    /usr/local/nagios/libexec/check_nt -H f1rebase.ddns.net -p 12489 -v USEDDISKSPACE -l C -w 80 -c 95 -s "password"
    NSClient - ERROR: Invalid return from command: check_drivesize

Grtz

**Comment by mickem** [comment]
What does the nsclient log say?

**Comment by willemdh** [comment]
NSclient.log only says:

    2015-11-29 17:12:25: debug:c:\source\master\include\check_nt/server/protocol.hpp:58: Accepting connection from: 212.71.234.84

**Comment by mickem** [comment]
Sorry: my bad...

The fixes where not in build 16 they are in 17 (which is out now)

**Comment by willemdh** [comment]
Confirmed to work again! Thanks.

**Comment by mickem** [comment]
Great! and again: sorry for the confusion...
