### ISSUE TITLE
New NRPE version coming up

### ISSUE THREAD

**Issue by jfrickson** [mickem/nscp#203]
Hi Michael,

I didn't know where else to put this, so I'm putting it here. I'm in the process of updating NRPE. I updated the SSL/TLS process and added a new version 3 packet type that supports variable length packets up to 64K. I suspect NSClient++ will already handle the new SSL stuff, but you'll need to make changes for the new packets.

Grab https://github.com/NagiosEnterprises/nrpe/tree/nrpe-2-16-RC2 and/or email me if you have questions.

**Comment by mickem** [comment]
I'll happily accept a PR adding support for this.

**Comment by box293** [comment]
You can probably close this ticket. NRPE v3 has now been released and it supports the defining a packet size so it matches "payload length" in the config file. KB article explaining how to utilize the "payload length" in NSClient++ and NRPE v3 is here: https://support.nagios.com/kb/article.php?id=518

**Comment by mickem** [comment]
great, thanks for letting me know...
