### ISSUE TITLE
counter multiple time frames and wrong documentation

### ISSUE THREAD

**Issue by garnier-quentin** [mickem/nscp#206]
Hi,

I use nsclient 0.4.3.143. The first problem is in the doc. You write:
[/settings/system/windows/counters/foo]
collection strategy=rrd
type=large
counter=counter=\Processor(_total)\% Processor Time

But it s:
[/settings/system/windows/counters/foo]
collection strategy=rrd
type=large
counter=\Processor(_total)\% Processor Time

Eventually, how can i get multiple values for the same check. I have tried but it doesn't work:
check_nrpe -H xxxx -c check_pdh -a "counter=foo" "warning=value > 70" "critical=value > 80" time=30s time=1m time=5m

Best regards!

**Comment by mickem** [comment]
I get:  option '--time' cannot be specified more than once

So I guess you cant currently. I will fix this...

**Comment by mickem** [comment]
I guess this is what you expected right?

    check_pdh counter=net time=5m time=5s
    L        cli OK: OK: net = 98890, net = 235222
    L        cli  Performance data: 'net-5m_value'=98890;0;0 'net-5s_value'=235222;0;0

**Comment by garnier-quentin** [comment]
Why does it works for you and not for me ? I use the same options no ? :)

**Comment by mickem** [comment]
It is fixed in the code (and will be avalible in the next build of 0.5.x, out when I get back from OSMC sunday)

**Comment by garnier-quentin** [comment]
ok. thanks!

**Comment by mickem** [comment]
0.5.0.16 is out (will be refresh on the site in a bit: https://www.nsclient.org/download/0.5.0/ or ju can grab it now from guthub releases)

**Comment by garnier-quentin** [comment]
It's working with nsclient 0.5.x. But i have the same perfdata name...
OK: memory_committed_charge = 62, memory_committed_charge = 62, memory_committed_charge = 62.3233|'memory_committed_charge_30s_value'=62;70;80 'memory_committed_charge_1m_value'=62;70;80 'memory_committed_charge_5m_value'=62;70;8

I have use following option: perf-syntax="%(alias)_%(time)" but i still have '_value'. How can i remove it ? Thanks

**Comment by mickem** [comment]
I thought _value was removed default for 0.5.0 need to check...

You can remove it with perf-config: http://docs.nsclient.org/manual/checks.html#performance-data-configuration

**Comment by box293** [comment]
For example:
```
Command:
check_nrpe -H 10.25.14.2 -c check_pdh -a 'counter:C: % Read Time=\LogicalDisk(C:)\% Disk Read Time' 'warning=value>50' 'critical=value>75' 'perf-config=*(suffix:none)'

Output:
OK: C: % Read Time = 0|'C: % Read Time'=0;50;75
```
