### ISSUE TITLE
check_files returning zero when filter total used; problem getting only total values

### ISSUE THREAD

**Issue by wojtek-dit** [mickem/nscp#210]
I'd like to check if a total directory size is above a certain level. I've came up (after a long fiddling with parameters) with a command that correctly cheks the total size and reports warn and crit. However it also by default lists all the files in perfdata (along with the total). if i try to filter it to total only, it displays correctly but the size is zero. As if the filter would cancel all the components of the total. Also i can't get it to display total size in top-syntax nor detail-syntax. I'd like to check for the total size and report the total size in return text and performance data (total only). Please advise. The docs lack examples, even the basic ones. NSClient used is 4.3.143

command with total :
check_files path=C:\\LogSh-ImportDoDB2\\  warn=size>100m "top-syntax=${status} %
(size)" total filter=name='total'
L        cli OK: OK: All 1 files are ok
L        cli  Performance data: 'total size'=0MB;100;0

command without total :
check_files path=C:\\LogSh-ImportDoDB2\\  warn=size>100m total "top-syntax=${sta
tus} "
L        cli WARNING: WARNING
L        cli  Performance data: 'SF_20151124072001.trn size'=7.4497MB;(all the files listed...);0 'total size'=202.6206MB;100;0
check_files path=C:\\LogSh-ImportDoDB2\\  warn=size>100m total "top-syntax=${sta
tus} ${crit_list}"

**Comment by mickem** [comment]
the values for totals are everything matching the filter I noticed this is sometimes what you want but often not so I will consider a way to make a everything regardless of filter match as well as total...

**Comment by wojtek-dit** [comment]
Thanks Michael. 
I did it with powershell script in the end. I'll be glad to see this working in next version.
