### ISSUE TITLE
Unable to connect from NSClient to central Nagios server

### ISSUE THREAD

**Issue by mmrtech** [mickem/nscp#211]
NSClient++ returns an error when I use "nscp test".

The service checks succeed, but when it tries to send data to my central server, I see this:

Connection details: host: [IP address and port], buffer_length: 512, time_delta: 0, password: [password], encryption: aes(16), hostname: [hostname], ssl: ssl disabled
Error: Failed to connect to [IP address and port]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

The monitored server is part of a point-to-point VPN, but the client who owns the server requested that we set up network address translation (NAT) on both ends. I configured my central Nagios server with the translated IP address and am able to see in the Nagios dashboard that that host is "Up". I've tried configuring nsclient.ini with both the actual server IP or the translated IP (of the central Nagios) server, but I always get the above error. 

Anyone have experience troubleshooting this kind of connectivity? The network teams on both ends say the traffic is passing and that this is an "application" issue.

**Comment by mickem** [comment]
Well, telnet would be my first option.
But I doubt this belongs as a defect here, probably better to ask over on the forums...

**Comment by mmrtech** [comment]
Argh, sorry about that. I meant this to be a forum question, but ended up here after going through the registration process. I'll re-post in the forums. Thank you.
