### ISSUE TITLE
Documentation for special syntax, like crit=state ne str(running)

### ISSUE THREAD

**Issue by gitmopp** [mickem/nscp#212]
Hello,

I cannot find any documentation about special syntax like "crit=state ne str(running)".
The keywords "ne", "eq" exists, but where is it documented? Also the "str()" syntax is very helpful. Are there more keywords available?

In my case I' d like to filter for all services which start with an n*.
The following does not work:
-c check_service -a "filter=name eq str(n*)" "crit=state ne str(running)"
-c check_service -a service=n* as described in the documentation does not work, too.

**Comment by mickem** [comment]
Ahh, saw that the section was TODO will add it the best option currently is probably my slides I guess...

**Comment by gitmopp** [comment]
Can you give me the link to the slides?

**Comment by mickem** [comment]
These are last years slides about writing filters: http://www.slideshare.net/MichaelMedin/nsclient-workshop-05-monitoring the one from this year will be posted sometime this week (but not much has changed really).

**Comment by gitmopp** [comment]
Just in case somebody else is looking for a similar issue, here is my solution:
-c check_service -a "filter=name like str(ns)" "crit=state ne str(running)"
Searching for "n" returns too many services and fails.

Valid operators for filter:
eq
ne
gt
lt
ge
le
like
not like
regexp
not regexp

**Comment by mickem** [comment]
FIY: this is now live on the site: https://docs.nsclient.org/manual/checks.html#expressions

**Comment by gitmopp** [comment]
Thank you for the good documentation
I found some typos, here are the words:
an expression**-**.
will s**r**at
an o**e**rator
allow ex**å**pression
arguments **ir** not 
be useful**l**
each **eh**ck
**where as** the
only f**i**r size
default fi**tl**er 
check_**s**pu
shows **ius**
wo**nt** cover **ht**at again

**Comment by mickem** [comment]
sorry, swapped editor and apparently atom did not spell check all files...
