### ISSUE TITLE
external scripts

### ISSUE THREAD

**Issue by dheenamadesh** [mickem/nscp#213]
Hello
I am trying to monitor External scripts using NSClient. Script file available in my Windows server. Already I am monitoring some of the basic services using check_nt plugin for the same server. Also I can able to run the external command using nscp through CMD. But Output I am not bring to Nagios Dash board. I  followed this link
http://docs.nsclient.org/howto/external_scripts.html#how-to-external-scripts . but no more solution available. Please give some suggestion on this

**Comment by mickem** [comment]
You cant use external scripts with check_nt. In essence check_nt is very limited for most features of nsclient++ you need NRPE or similar.
