### ISSUE TITLE
[checktasksched] Failed to fetch tasks

### ISSUE THREAD

**Issue by cmeschin** [mickem/nscp#215]
Hi,
I use NSC 0.4.2.93 on many hosts with WinXP to Win2012 "32 and 64bits".
On some servers running W2008 32bits, checktasksched don't work with this error:

     UNKNOWN: Failed to fetch tasks: Failed to get folder : unknown error: 1: Fonction incorrecte.

the syntax is same on every hosts.

    ./check_nrpe  -H X.X.X.X -p 5666 -t 90 -c CheckTaskSched -a "filter=status ne 'disabled' AND exit_code ne 0" "syntax=%title% [code d'erreur:%exit_code%]" "crit=>0"

I try to use nscp 0.4.4.15 but it's same result.
I also try to execute same check in "nscp test --debug" session but there is no more informations to debug.

regards,

**Comment by mickem** [comment]
I can confirm I get the same result... I will need to investigate why... works on other os:es so seems 2008 related...

**Comment by jvigna** [comment]
Hello Michael,

any news on this I have the same problem when executing nscp as a non privileged user.  As system user it is working correctly. I'm on a Windows 2012R2. Thanks for any hint :)

**Comment by mickem** [comment]
NSClient++ needs to read the task to "see it" this is what Microsoft says about tasks in windows:

>By default, a user who creates a task can read, update, delete, and run the task. A user must have file write permission on a task file to update a task, file read permission on a task file to read a task, delete permission on a task file to delete a task, and file execute permission on a task to run a task using the IRegisteredTask::Run or RunEx methods (RegisteredTask.Run and RunEx for scripting). 
>Members of the Administrators group or the SYSTEM account can read, update, delete, and run any tasks. 
> Members of the Users group, the LocalService account, and the NetworkService account can only read, update, delete, and run the tasks that they have created. This default behavior is changed when the DACL of the task file is changed, in which case the DACL defines which users have file write, read, execute, and delete permission. 
> To set permissions for a task file, use the IRegisteredTask.SetSecurityDescriptor method (RegisteredTask.SetSecurityDescriptor for scripting) or set the security descriptor when you register the task using the RegisterTask or RegisterTaskDefinition methods.

**Comment by cmeschin** [comment]
Hi michael,
the problem related by jvigna seems to be different from my original post, isn't it?

regards,

**Comment by mickem** [comment]
sorry, I should read before I post :)

**Comment by mickem** [comment]
Not super happy news...

Seems there is something fishy with windows 2008.

In essence the "connect" call fails with E_OUTOFMEMORY. This makes you go WTF?!?! untill you read the docs for Connect:https://msdn.microsoft.com/en-us/library/windows/desktop/aa381833(v=vs.85).aspx

> The application does not have enough memory to complete the operation or the user, password, or domain has at least one null and one non-null value.

Notice the second half: "or the user, password, or domain has at least one null and one non-null value"

Now in this case this is not true, but it at least let me down the right path.

Specifying the user/password and connecting to localhost works.
Not ideal, but maybe that the best we can do?

```
check_tasksched computer=127.0.0.1 user=Administrator password=******
L        cli WARNING: OK: No tasks found
```

**Comment by mickem** [comment]
https://github.com/mickem/nscp/releases/tag/0.5.0.29

**Comment by mickem** [comment]
Reopen if you still has issues
