### ISSUE TITLE
0.5.0.17 - problem_count and problem_list not populated

### ISSUE THREAD

**Issue by box293** [mickem/nscp#216]
I was playing with check_files and I found that problem_count and problem_list not populated. For example:
```
check_nrpe -H 10.25.254.4 -t 30 -c check_files -a path='C:\\NO BACKUP' pattern=*.* 'warning=count>500' 'critical=count>1000'

or

check_nrpe -H 10.25.254.4 -t 30 -c check_files -a path='C:\\NO BACKUP' pattern=*.* 'warning=count>500' 'critical=count>1000' top-syntax='${status}: ${problem_count}/${count} files (${problem_list})'

CRITICAL: 0/22278 files ()|'count'=22278;500;1000
```
On 0.4.4.15 I was having issues because the amount of output for this many files was more than the nrpe buffer could handle:
```
check_nrpe -H 10.25.254.4 -t 30 -c check_files -a path='C:\\NO BACKUP' pattern=*.* 'warning=count>500' 'critical=count>1000'

CHECK_NRPE: Invalid packet type received from server.
```
This is when I played with the top-syntax to remove problem_list:
```
check_nrpe -H 10.25.254.4 -t 30 -c check_files -a path='C:\\NO BACKUP' pattern=*.* 'warning=count>500' 'critical=count>1000' top-syntax='${status}: ${problem_count}/${count} files'

CRITICAL: 21778/22278 files|'count'=22278;500;1000
```
And then that is when I tried the top-syntax command on 0.5.0.17 and found nothing being populated.

So you can see that on 0.4.4.15 (even back to 0.4.3.138) the problem_count and problem_list was being correctly calculated, this seems to be something introduced in 0.5.x.

**Comment by mickem** [comment]
Well, this was a "bug" in 0.4.3 which was fixed in 0.5.0.

But in essence: problem_count is the number of items which matched you warning filter.
Count does not match an "item" thus the number is not updated..  count is a match "done in post" (i.e. on the result).

This become a bit more obvious when you do things like this:

```
"warning=count > 5 or count < 10"
```
What would you expect the problem_count to be then?

So I guess the "best route forward" would be to add an option to include perf data in the message then you can interpret the count  "as you want" now this is nothing that will make it into 0.5.0.
But is this something which would be helpful?

**Comment by box293** [comment]
Your example ...
```
"warning=count < 5 or count > 10"
```
... really throws my head into a spin, but it's perfectly valid logic.

I think basically what I am trying to achieve is to let the person know why it's in a critical or warning state. Looking back at my logic, using the problem_count didn't really make sense.

Is there a way of outputting the status to be something like:

```
CRITICAL: 22278 files found which triggered xxx threshold of count < 5 or count > 10
```
Where xxx would be the warning or critical word and the "count < 5 or count > 10" was pulled from the warning or critical threshold.

I'm assume  "count < 5 or count > 10" would be inserted into the perdata string like:

```
|'count'=22278;5:10
```

**Comment by mickem** [comment]
That would be top-syntax.

(something along the lines of this)

```
... "top-syntax=%(status): %(problem_count) found which triggered xxx threshold of count < 5 or count > 10"
```

**Comment by mickem** [comment]
Pleas reopen if you still face issues...
