### ISSUE TITLE
Filter in check_version via check_nrpe

### ISSUE THREAD

**Issue by jdejongh** [mickem/nscp#217]
Hello,

I'm decommsioning the old check_nt commands.
The last command I use is the CLIENTVERSION with the argument -l "NSClient++ 0.4.3.143 2015-04-29".

The replacement via nrpe is check_version.
Is it possible to also add arguments so that you get a warning if the version is older then the specified value?

For example with check_os_version I added -a "warn=version < 60" as an argument to get a warning for an old operating system.

Thanks for your help.
Johan

**Comment by mickem** [comment]
Might be good idea I guess, wont work for older version though...

**Comment by mickem** [comment]
New command check_nscp_version in next 0.5.0 build.
