### ISSUE TITLE
NSCP 0.4.4.15 win32  install problem

### ISSUE THREAD

**Issue by plessier** [mickem/nscp#219]
Installation failed  on Windows xp and Windows 2003 system

 log error from mis install
DEBUG: Error 2769:  Custom Action WixSchedInternetShortcuts did not close 3 MSIHANDLEs.
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2769. The arguments are: WixSchedInternetShortcuts, 3, 
Action ended 12:41:04: WixSchedInternetShortcuts. Return value 3.

**Comment by ftass** [comment]
http://wixtoolset.org/issues/4902/

**Comment by mickem** [comment]
Yes, noticed that issue, I have compiled boost without "xp mode", am trying to rebuild that now (but possible I have to do it with other things as well so will probably take a while) hopefully in a day or so...

**Comment by plessier** [comment]
Thanks for your update, If I remember correctly, the problem Is the same with 5.0 

Off topic, just for your information, I think there is a mistake in the  nsclient-sample.ini you wrote ${filename] in section alias_file_size

**Comment by mickem** [comment]
Yes, 044 and 050 has the same build environment...

**Comment by mickem** [comment]
sample.ini? where is that?
0.4..4.19 (on github) should fix this, will run some tests and then publish it on the webiste as well in a bit...

**Comment by mickem** [comment]
This seems to resolve it for me, so closing this, reopen (or comment) if you still have issues

**Comment by plessier** [comment]
Off topic, C:\Program Files\NSClient++\nsclient-sample.ini on 64 bits client

**Comment by mickem** [comment]
That file is actually generated, so probably the default alias which is wrong, feel free to open a ticket for that...

**Comment by plessier** [comment]
The problem has been solved in the version 50.19
Thanks a lot

**Comment by mickem** [comment]
thanks for reporting back!

**Comment by riztron** [comment]
I downloaded the latest version 0.4.4.19, but still I am facing the same issue.
![nsclient error](https://cloud.githubusercontent.com/assets/18100053/14065497/37431e12-f43d-11e5-8654-72e0c61f3efa.jpg)

**Comment by riztron** [comment]
I am facing the issue on windows 2003 with 5.0.31 version also
![nsclient error](https://cloud.githubusercontent.com/assets/18100053/14065518/2da571ba-f43e-11e5-9e83-b426a9f63d05.jpg)
