### ISSUE TITLE
0.5.0.17 => Webpage not loading on IE on Windows 2008 R2

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#220]
The NSClient++  webpage is working perfect on Chrome at home. But at work on Windows 2012 R2 servers (didn't try other OS'es) we don't want Google Chrome. On IE11 the NsClient++ webpage doesn't seem to work properly. The page partially loads but then keeps loading ( check the loading icon on the screenshot) I'm also not getting the authentication page to log in.

![image](https://cloud.githubusercontent.com/assets/6462991/11590166/a37ed408-9a8e-11e5-8da2-8f8345125b18.png)

**Comment by mickem** [comment]
resolved in next build

**Comment by willemdh** [comment]
Confirmed to work perfectly now in IE11 on Windows 2012 R2. Thanks!

**Comment by mickem** [comment]
Thanks for reporting back!
