### ISSUE TITLE
0.5.0.18 => check_cpu warn and crit only for 5m time

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#222]
Hello,

I was wondering if it was possible to use check_cpu for collecting several timeperiods, such as 1m and 5m, but only generate a warning / critical when the 5m time is exceeded. So I made a command using check_cpu with this as argument:

    "filter=core = 'total'" time=1m time=5m "warn=time = 5m and load > 20" "crit=time = 5m and load > 40"  'top-syntax=%(status): CPU Stats {%(list)}' 'detail-syntax=(%(core), avg %(time): %(load)%)'

and used stresstest.exe to generate some load.

![image](https://cloud.githubusercontent.com/assets/6462991/11663006/17b40804-9dda-11e5-8393-8133a92dc6c0.png)

So am I using check_cpu wrong or so? Because with the load in the screenshot, I should have got a warning?

Grtz

**Comment by mickem** [comment]
Pretty sure the time here is a string expression (it is the name of the time series) so yu probably want a string I think:

    "filter=core = 'total'" time=1m time=5m "warn=time = '5m' and load > 20" "crit=time = '5m' and load > 40"  'top-syntax=%(status): CPU Stats {%(list)}' 'detail-syntax=(%(core), avg %(time): %(load)%)'

**Comment by mickem** [comment]
Just verifying that it work with '':

    # time = '5m' > OK
    check_cpu "filter=core = 'total'" time=1m time=5m "warn=time = '5m' and load > 2%" "crit=time = '5m' and load > 40"  "top-syntax=%(status): CPU Stats {%(list)}" "detail-syntax=(%(core), avg %(time): %(load)%)"
    L        cli OK: OK: CPU Stats {(total, avg 1m: 3%), (total, avg 5m: 2%)}
    L        cli  Performance data: 'total 1m'=3%;2;40 'total 5m'=2%;2;40

    # time = '1m' > warning
    check_cpu "filter=core = 'total'" time=1m time=5m "warn=time = '1m' and load > 2%" "crit=time = '5m' and load > 40"  "top-syntax=%(status): CPU Stats {%(list)}" "detail-syntax=(%(core), avg %(time): %(load)%)"
    L        cli WARNING: WARNING: CPU Stats {(total, avg 1m: 3%), (total, avg 5m: 2%)}
    L        cli  Performance data: 'total 1m'=3%;2;40 'total 5m'=2%;2;40

**Comment by willemdh** [comment]
Thanks Michael.
