### ISSUE TITLE
alias became broken by introducing %ARGS%

### ISSUE THREAD

**Issue by azotov** [mickem/nscp#223]
This code is broken:
		BOOST_FOREACH(const std::string &str, src_args) {
			strEx::replace(arg, "$ARG" + strEx::s::xtos(i++) + "$", str);
			strEx::replace(arg, "%ARG" + strEx::s::xtos(i++) + "%", str);
		}
It tries to replace $ARG1$ with first argument, then %ARG2%, then tries to replace $ARG3$ and %ARG4% with second argument and so on. $ARG2$ never has a chance to be replaced due to excessive i++ in first replace().
In 's == "help-pb"' code section there are also too many 'i++' instead of ordinary 'i'.

**Comment by mickem** [comment]
So sorry will fix asap
