### ISSUE TITLE
NSClient++ Registry Configuration Assistance

### ISSUE THREAD

**Issue by Klang0340** [mickem/nscp#224]
Good afternoon all,
      Looking for assistance to configure our Windows registry for the NSClient agent. I have looked for a guide with some examples to help me configure the agent but I'm lost based on what I found. Simply put, I have my custom settings which work in the nsclient.ini file, I just need some examples to make them work for a 'registry' configuration of NSClient. I'm using NSCP 0.4.1.102.

Resource:
http://docs.nsclient.org/manual/settings.html

Below is a list of the 'custom' settings I would like to 'convert'.

[/settings/NRPE/server]
allow arguments = true
allow nasty characters = true
port = 5666
timeout= 120
use ssl = 1
command_timeout= 120

[/settings/external scripts]
allow arguments = true
allow nasty characters = true
timeout = 120

[/settings/external scripts/scripts]
check_FileAdd= cmd /c echo scripts\check_FileAdd.ps1 | powershell.exe -command -
check_procKillTimer= cmd /c echo scripts\processKillTimer.ps1 "$ARG1$" "$ARG2$"; exit($lastexitcode) | powershell.exe -command -
check_service= cmd /c echo scripts\check_service.ps1 "$ARG1$" "$ARG2$" "$ARG3$" "$ARG4$"; exit($lastexitcode) | powershell.exe -command -
get_adapter_v1= cmd /c echo scripts\get_adapter_info-v1.ps1; exit($lastexitcode) | powershell.exe -command -
get_adapter_v2= cmd /c echo scripts\get_adapter_info-v2.ps1; exit($lastexitcode) | powershell.exe -command -
imaging_hsi_query= cmd /c echo scripts\Op5-SQL_Query.ps1; exit($lastexitcode) | powershell.exe -command -
processCpu-top5= cmd /c echo scripts\processCpu-top5.ps1; exit($lastexitcode) | powershell.exe -command -
processMem-top5= cmd /c echo scripts\processMem-top5.ps1; exit($lastexitcode) | powershell.exe -command -
serviceStatus= cmd /c echo scripts\serviceStatus.ps1 "$ARG1$" "$ARG2$"; exit($lastexitcode) | powershell.exe -command -
start_service= cmd /c echo scripts\start_service.ps1 "$ARG1$"; exit($lastexitcode) | powershell.exe -command -
volumeCapacity= cmd /c echo scripts\volumeCapacity.ps1 $ARG1$ $ARG2$ $ARG3$; exit($lastexitcode) | powershell.exe -command -

[/settings/log/file]
; Set log file size to 10Mb
max size = 10485760
debug = false

**Comment by Klang0340** [comment]
Closing the issue, I just needed to understand the content better. Once I have the agent configured to use the updated nsclient.ini file, I just execute the command below from C:\Program Files\NSClient++

nscp settings --migrate-to registry

The registry now reflects my changes and I have more than enough examples to understand what should be added in the future. Sorry for the false alarm.

**Comment by willemdh** [comment]
@Klang0340 Didn't even knew this feature existed. :open_mouth:

**Comment by Klang0340** [comment]
At first, I looked at the very 'default' registry tree for NSClient and I thought to myself 'How am I supposed to just know how to structure this?'. As you see in my initial post I have a lot of custom settings and I will be adding many more scripts as I get better with PowerShell. I have like 100 scripts in bash for NRPE.

The command was VERY helpful in configuring the registry but the documentation could be a lot better in guiding new user's in how to use this.

I just configured my agent to use the nsclient.ini file and with everything working then ran the migrate command. I exported the NSCLient++ registry and now I have all my registry settings.

Uninstalled the agent, removed the scripts directory and did a clean re-install. Reloaded the registry and restarted the agent; everything works great.

**Comment by willemdh** [comment]
Personally I prefer using nsclient.ini for storing my settings. Check my blog for a list of some of the Powershell scripts I created and using with NSClient:

https://outsideit.net

**Comment by Klang0340** [comment]
I will certainly check it out!

For me I'm not a Windows Admin so registry or file didn't matter much. I just Administer the Op5 installation and my role here is a monitoring Admin (All my back end work is RHEL6). I need to manage and maintain the windows agents, however and our Windows Admins whom perform the changes I need said they would prefer registry changes over files work. I'm just glad I could accommodate their request once I did some more testing.

**Comment by mickem** [comment]
In 0.4.3 and beyond also has a web interface where you can edit the config. This is much improved in 0.5.0 though...
