### ISSUE TITLE
NSClient: GUI for Server 2012 doesn't prompt for registry config.

### ISSUE THREAD

**Issue by Klang0340** [mickem/nscp#225]
Afternoon all,
     Trying to install NSCP-0.4.4.15-x64.msi (Using the GUI) on Windows Server 2012 but the page asking for 'Registry based config' or 'INI based config' doesn't show up like it does for Server 2008. Due to this, my initial install always requires an updated nsclient.ini file.

I have exported a working registry config but this won't work as the 'boot.ini' file is still set to...
[settings]
1=ini://${shared-path}/nsclient.ini
[main]
write=ini://${shared-path}/nsclient.ini

so updating the registry does nothing, even after an agent restart. Meanwhile in the Server 2008 install I can select to use a 'registry configuration' and the boot.ini file looks like the below after the install...

[settings]
1=registry://HKEY_LOCAL_MACHINE/software/NSClient++
[main]
write=registry://HKEY_LOCAL_MACHINE/software/NSClient++

As you can see, the Server 2008 file is correct and thus my registry configuration is loaded and works. Why doesn't the Server 2012 installer allow me to point to the registry? Currently, I have to add a step in my bulk deployment procedure to update the boot.ini file which I would LOVE to avoid.

**Comment by mickem** [comment]
Most likely your upgrading in which case you already have a configuration then you cannot change this...

You can run the command line tools to move the settings or remove the existing configuration before you run the installer... 
Look for boot.ini in the nsclient++ folder...


from the command line you can run the following to copy your configuration and switch to registry:

    nscp settings --migrate-to registry


or you can run this to just switch (not copy the existing configuration):

    nscp settings --switch registry


(or you can edit boot.ini by hand)

**Comment by Klang0340** [comment]
Mickem,

      After more testing you're correct, an upgrade was occurring when my intent was a clean install. I experienced my conflict if the following were true...
     +An existing c:\Program Files\NSClient++ folder was left over - I have custom plugins so the scripts folder was left behind after an uninstall.
     +A registry entry HKEY_LOCAL_MACHINE\SOFTWARE\NSClient++ was left over - This appears to not get deleted from the uninstaller

**Comment by Klang0340** [comment]
Mickem,

     Please note one item for enhancement in the 'upgrade' process. When you 'upgrade' from the Op5 version to the NSClient++ (Original) version, the firewall rules being updated need one more additional step.
     Currently, you remove the UDP firewall rule then update the TCP rule for all Profiles. This is good.
     You don't however, update the 'Program Path' of the TCP rule so the port 5666 is never actually applied to the new executable.

Old Path: C:\Program Files\op5\NSClient++\nsclient++.exe
New Path: C:\Program Files\NSClient++\nsclient++.exe

**Comment by mickem** [comment]
The firewall exception is done using wix tooling so not sure I can do anything about it...
Does it work the way it is now or do you need to change it manually?

**Comment by Klang0340** [comment]
It has to be changed manually, the firewall rule points to a nonexistent executable so the rule is doing nothing. I would recommend when performing an 'upgrade' to just remove the existing rules and have the wix tooling to just create a new rules versus trying to update them. This way the rule is pointed to the correct binary. 

Again, the Op5 version of the install points to a different path and the executable name differs from that of an 'original' NSClient++ install (See below). If the firewall rules are to be updated, the executable location must be updated.

Op5 Path: C:\Program Files\op5\NSClient++\nsclient++.exe
NSClient++ Path: C:\Program Files\NSClient++\nscp.exe

**Comment by mickem** [comment]
Well, as I said,m the firewall rule is not "me doing anything" it is wix (the installer framework) but perhaps I have miss configured something... We probably should have a separate issue for that though...
