### ISSUE TITLE
check_drivesize passing threshold as argument

### ISSUE THREAD

**Issue by veenamnaik** [mickem/nscp#226]
I have below entry in my ini file . 
check_all_other_drives = check_drivesize "warn=used<$ARG1$" "crit=used<$ARG2$"exclude=C:\\ "filter=type in ('fixed')" exclude="System Reserved" "empty-state=ok" "empty-syntax=%(status): No drives found"

But when i call same with from nagios by passing argument i get below error, let me know the soln
./check_nrpe -H <host IP> -c check_all_other_drives -a 80 90
Failed to validate filter see log for details

**Comment by willemdh** [comment]
What version of NSClient? What happens if you execute on the client with nscp test?

**Comment by veenamnaik** [comment]
NSClient version is 4.3.143 and i get the same error "Failed to validate filter see log for details"

**Comment by mickem** [comment]
seems to be missing a space before exlude right?

**Comment by mickem** [comment]
apart fro, that it works for me (though with a different version)

**Comment by mickem** [comment]
Next build will have some improvements in exclude so:
* exclude=c
* exclude=C
* exclude=c:
* exclude=C:

All should add up to:
* exclude=C:\

Please reopen if you still have issues.
