### ISSUE TITLE
When updating a setting with "nscp settings" op5.ini is loaded into the registry

### ISSUE THREAD

**Issue by mkop5** [mickem/nscp#227]
Let's say I install NSClient >= 0.4.4 and chose op5  Monitor as monitoring tool during the install process. In the next step (Choose setup type) I select "Typical" and the rest I leave as default.
Now I open up the registry with regedit.exe and navigate to:
computer\HKEY_LOCAL_MACHINE\SOFTWARE\NSClient++\

Below that one I can now see:

```
includes\op5 -> op5.ini
settings\default\allowed hosts -> 127.0.0.1,::1
```

Now I update "allowed hosts" with the following command:

```
nscp settings --path /settings/default --key "allowed hosts" --set 127.0.0.1,::1,10.10.10.0/24
```

After I have executed the command above I switch back to regedit and update the view (F5) and then I have all settings from the op5.ini file loaded in the registry. Is this really correct behaviour?

**Comment by mickem** [comment]
No, indeed it is not...

**Comment by mkop5** [comment]
Hi!
Do you have any idea when this will be solved?

**Comment by mickem** [comment]
I will start working on this (and others) now that 0.5.0 is out the door...
SO can probably look into this and give you an estimate in the next week or so...
