### ISSUE TITLE
[check_service] Failed to enumerate services

### ISSUE THREAD

**Issue by klaypigeon** [mickem/nscp#229]
Running NSCP-0.4.3.143-x64  via OpsView Enterprise. 

If I run check_service with no args or with a filter that looks for service name, I have 2 hosts that return the following. Everywhere else it works fine. I have not been able to get to the bottom of it. Debug isn't giving me much from 'nscp test --log debug'.

FAIL - no args
$ check_nrpe -H '10.10.10.01' -c check_service
MONITORED BY: myslave.int.cdphp.com
RETURN CODE: 3 (UNKNOWN)
OUTPUT:
 Failed to process command : Failed to enumerate services|

FAIL - Example with the name in the filter:
$ check_nrpe -H '10.10.10.1' -c check_service -a "filter=start_type = 'auto' and name='vmtools'" empty-state='OK'
MONITORED BY: slave.int.cdphp.com
RETURN CODE: 3 (UNKNOWN)
OUTPUT:
 Failed to process command : Failed to enumerate services|

OK - Calling a service specifically by name works without issue.
$ check_nrpe -H '10.10.10.1' -c check_service -a "service=snmp" "filter=start_type = 'auto'"
MONITORED BY: slave.int.cdphp.com
RETURN CODE: 0 (OK)
OUTPUT:
 OK: All 1 service(s) are ok.

**Comment by klaypigeon** [comment]
Any thoughts on this or how I might triage?

**Comment by mickem** [comment]
Does the NSClient++ log say anything?
Usually errors are reported in the nsclient log file

**Comment by klaypigeon** [comment]
No. I ran the log in debug as well and it gives me nothing. Just a bunch of lines that look like this after testing.

2016-01-19 17:08:05: debug:D:\source\nscp\include\nrpe/server/protocol.hpp:74: Accepting connection from: 10.100.10.145, count=1
2016-01-19 17:08:05: debug:D:\source\nscp\include\nrpe/server/protocol.hpp:74: Accepting connection from: 10.100.10.145, count=1
2016-01-19 17:08:20: debug:D:\source\nscp\include\nrpe/server/protocol.hpp:74: Accepting connection from: 10.100.10.145, count=1
2016-01-19 17:08:21: debug:D:\source\nscp\include\nrpe/server/protocol.hpp:74: Accepting connection from: 10.100.10.145, count=1
2016-01-19 17:08:29: debug:D:\source\nscp\include\nrpe/server/protocol.hpp:74: Accepting connection from: 10.100.10.145, count=1
2016-01-19 17:08:36: debug:D:\source\nscp\include\nrpe/server/protocol.hpp:74: Accepting connection from: 10.100.10.145, count=1
2016-01-19 17:08:36: debug:D:\source\nscp\include\nrpe/server/protocol.hpp:74: Accepting connection from: 10.100.10.145, count=1

**Comment by mickem** [comment]
Ok, I will look into the code and see if I can extend logging a bit.

**Comment by klaypigeon** [comment]
If my company purchases commercial support can we expect more expedited assistance?

**Comment by mickem** [comment]
I do not run some extortion business of that's what your asking... 
In this case it is not something I can reproduce but I will go through the code and make sure any errors are caught and hopefully have a newer build with some more error messages for you in the next few days of that is agreeable?

**Comment by mickem** [comment]
next 0.5.x build will have improved error handling

**Comment by mickem** [comment]
Try with 0.5.0.20 here https://github.com/mickem/nscp/releases/tag/0.5.0.20 and see if you get a better error message.

**Comment by klaypigeon** [comment]
I'll give it a shot in the AM! You certainly don't look like an extortionist...but looks aren't everything! Our purchasing manager is trying to get OpsView to support the client code since they are distributing it with their package. I am frankly surprised they are not enterprise partners of of yours. Either way, we are running about 600 nsclient++ nodes so we will get support one way or another.

**Comment by klaypigeon** [comment]
Well this is horribly inconclusive. I got the new 5. client installed. Running nscp test --log debug. Nothing to show in logs, probably because there is not an error anymore. It just returns empty.

All fine here...
check_service "service=vmtools"
L        cli OK: OK: All 1 service(s) are ok.

not so much here. no error though. it just finds nothing. Syntax?
check_service "filter=start_type='auto' and name='vmtools'" "empty-state='OK'"
L        cli UNKNOWN: OK: No services found

vmtools is definitely installed.
PS > get-service vmtools
Status   Name               DisplayName
------   ----               -----------
Running  vmtools            VMware Tools

**Comment by mickem** [comment]
check_service top-syntax=%(list)

Should give you a list of all services

**Comment by klaypigeon** [comment]
It does. I see all my services and their start type.

**Comment by klaypigeon** [comment]
Update. The new client seems to have fixed the issue. I did have a Syntax error in the vmtools service check. With check_service service=vmtools is not case sensitive. However, if you use name='VMTools' within a filter, that IS case sensitive. I have updated the client on these 2 machines and all is well. I do not know what you changed in between 0.4.3.143 but it seems to have addressed the issue I was having with "failed to enumerate service". The other 3 checks I had that were having a similar issue are also responding correctly now. You can close this issue (though it still does exist in 0.4.3.143).

**Comment by mickem** [comment]
I will see about back porting it to 0.4.4

**Comment by mickem** [comment]
0.4.4. is the same as 0.4.3 except with a new improved installer

**Comment by klaypigeon** [comment]
> I will see about back porting it to 0.4.4

Just curious about what you are back porting. Was there some code change in the way you are enumerating the services?

**Comment by mickem** [comment]
That would be this change: https://github.com/mickem/nscp/commit/e4c42b0cce3b9d9c60eccfa635ed8eaa65ab94ba

**Comment by mickem** [comment]
Closing this as it is backported, reopen if you have further issues
