### ISSUE TITLE
[check_files] Capability to filter on the type ? Directory or file

### ISSUE THREAD

**Issue by garnier-quentin** [mickem/nscp#231]
Hi,

I use nsclient 0.4.3-143 and i don't find an attribute to filter file only (can exclude directory) : filter=type in ('file')

Best regards,

**Comment by mickem** [comment]
Humm... not sure I follow...

check_files should never find directories right?

Do you get folders back in the result or?

**Comment by garnier-quentin** [comment]
When i check a path, in the variable '%(count)', you have sub-directories in it.

**Comment by mickem** [comment]
That sounds like a bug...

**Comment by garnier-quentin** [comment]
I don't think it's a problem to have directories. It could be useful. But it would be great if we can filter on the type : directory or file

**Comment by garnier-quentin** [comment]
It works well with 0.5.x. But can i have it (type attribute) also in warning, critical criterias ?

**Comment by mickem** [comment]
Yes that should be possible...
