### ISSUE TITLE
checkMem - perfdata

### ISSUE THREAD

**Issue by s3ta** [mickem/nscp#234]
Hi,

sorry, if this is just my lack of understanding or it has been discussed before:

We got some machines monitored by icinga/nsclient++
On most machines checkmem (e.g. called with checkMem MaxWarn=97% MaxCrit=99% ShowAll type=physical type=page perf-unit=M) are reporting along the lines of:
```
'physical memory %'=87%;97;99 'physical memory'=21535.551M;23838.288;24329.799;0;24575.555 'page file %'=54%;97;99 'page file'=23415.578M;41715.562;42575.677;0;43005.734
```
where I interpret the perfdata value given as 'pagefile', as the sum of ram and pagefile - so I can compute in pnp4nagios the values I'm interested in (actual ram - actual use of swapfile).

On some machines however the result is like e.g.:
```
'physical memory %'=39%;94;95 'physical memory'=3246.867M;7700.061;7781.977;0;8191.555 'page file %'=10%;94;95 'page file'=2129.785M;19249.07;19453.848;0;20477.734
```
The value for pagefile is LOWER than the used ram .... the machine has actually 8G RAM and a 12 GB page-file - so the max (20477.734M) seems to be correct.

We are using mainly an older version of nsclient++ (4.1.105) but I tested the 
current stable version  (4.4.19) as well - now the label is "commited" (my assumption ram+pagefile seems correct) but the result is still strange:
( I omitted the perf-unit - since this seems to work differently on that version - didn't dig into since the mentioned problem persists)
```
   checkMem MaxWarn=97% MaxCrit=99% ShowAll type=physical type=page
   D  w32system Created command: warn=used>=97% crit=used>=99% show-all "detail-syntax=%(type): Total: %(size) - Used: %(used) (%(used_pct)%) - Free: %(free) (%(free_pct)%)" type=physical type=committed
   L        cli OK: OK: physical: Total: 31.879GB - Used: 2.115GB (6%) - Free: 29.764GB (93%), committed: Total: 79.877GB - Used: 2.052GB (2%) - Free: 77.825GB (97%)
   L        cli  Performance data: 'physical'=2.1147GB;30.92237;31.55994;0;31.87873 'physical %'=6%;96;98;0;100 'committed'=2.0515GB;77.48067;79.07821;0;79.87698 'committed %'=2%;96;98;0;100
```
I read that 2.1147G/31.87873G ram is used - OK - 
but "only" 2.0515G/79.87698G of the commited (still assuming ram+pagefile) is used.

While perfmon shows me actually 0% of the page file is used.

How can there be less commited memory than ram used? 
(And if this is really possible ...) how can I fetch/compute the absolute values for page usage (used and total - not percentages)

**Comment by s3ta** [comment]
The machines have all Win2k8r2 as OS .. if this is relevant

**Comment by mickem** [comment]
check_memory dos not check pagefile it checks various memory metrics...

check_pagefile checks the page file utilization...

**Comment by s3ta** [comment]
OK - but this leaves open the question:
How can there be less commited memory than ram used? 
Any pointer/reference for this?

And why does the check provide different results like described above?

(This is not really problematic since we're already rolling out 0.4.4.19 and we use check_pagefile w/ it, 
which is working fine btw. but being curious by nature...)

**Comment by mickem** [comment]
Now I am no memory expert but: "...the commit limit is the sum of physical memory and the sizes of the paging files. In reality, not quite all of physical memory counts toward the commit limit since the operating system reserves part of physical memory for its own use."

So if your not using much swap space I guess that could be it right? i.e. the used physical ram is system + used memory where as committed is only used memory.

https://blogs.technet.microsoft.com/markrussinovich/2008/11/17/pushing-the-limits-of-windows-virtual-memory/

**Comment by mickem** [comment]
Closing for now, Please reopen if you still have issues.
