### ISSUE TITLE
check_files documentation: Erroneous example

### ISSUE THREAD

**Issue by fmikker** [mickem/nscp#235]
NSClient++ version: 0.4.4.15 2015-11-25 

The documentation for check_files has a couple of examples, which at least one of them does not work
check_files path=D:\tmp pattern=*.txt "filter=size gt 20" "syntax=%filename%: %size%" MaxWarn=1
WARNING:test.txt: 26B, found files: 1 > warning|'found files'=1;0;0;

1. Using a single backslash does not work.

2. The agent does not recognize the following as valid input: "syntax=%filename%: %size%" MaxCrit=1.
By running the complete example command, the following error message is presented:
UNKNOWN: Invalid command line: unrecognised option 'syntax=%filename%: %size% (and also the help text)

Ref:http://docs.nsclient.org/0.4.4/reference/windows/CheckDisk.html?highlight=check_files#CheckDisk.check_files

**Comment by mickem** [comment]
Yes, looks like I only converted half of the command... will fix...

**Comment by flingo64** [comment]
NSClient++ version: 0.4.4.15 2015-12-09,

there is another small documentation error:
`check_files "path=c:/tmp" "pattern=*.log" "filter=create > -1d"`
won't work, but: 
`check_files "path=c:/tmp" "pattern=*.log" "filter=creation > -1d"`
works as expected.

**Comment by mickem** [comment]
Fixed
