### ISSUE TITLE
Is memory leakage issue fixed in 0.4.4.19 version and known bugs/issue with the versions 0.4.4.15 or 0.4.4.19

### ISSUE THREAD

**Issue by praveenponugoti** [mickem/nscp#236]
Hi,

Thanks for the post on memory leakage bug in version 0.4.3.143.

I had faced similar memory leakage issue with 0.4.3.143 version. From one of the post(https://github.com/mickem/nscp/issues/199) I  got t know that memory leakage is fixed in version 0.4.4.15.

@mickem , is this bug fixed in latest release 0.4.4.19? 

I have configured the below checks on y windows servers.

Free Disk Space (-c check_drivesize) with check_nt
 Several Windows event log checks (-c check_eventlog) with check_nrpe
 several performance counters ( Counter) with check_nrpe
 NSCP memory usage (-c check_process)

may I know from anyone using this checks with out any issue? and can I get NSClient.ini configuration file for these checks.

**Comment by mickem** [comment]
Not sure I understand, the memory leaks is fixed in all subsequent versions yes (unless something goes bad) so if your issue was fixed in 0.4.4.15 then it should also be fixed in 0.4.4.19.

Are you facing a memory leak issue?

**Comment by mickem** [comment]
Please reopen if you still have issues.
