### ISSUE TITLE
checkCounter - how to provide localized name?

### ISSUE THREAD

**Issue by mathieuchateau** [mickem/nscp#240]
Hello,

I am trying to get pdh counters from a remote windows 2003 in french.
I know that english counter names are only available to vista & up.

But how to provide french name of counter ?

nsclient keep replying:
Failed to poll counter: PdhAddEnglishCounter is only avalible on Vista and later you need to use localized counters

Any trick to tell nsclient it's localized name?

thanks

**Comment by mathieuchateau** [comment]
The only way I found so far to get something is this:
````
check_pdh -a "counter=\4\24" expand-index
```

These numbers can be guessed out from:
````
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Perflib\009
```

I am afraid there is no other smarter way for these old Windows :'(

**Comment by willemdh** [comment]
I'm not 100 % sure if this could help you, but I'm using two PS functions you can find in the Powershell script in this repo: https://github.com/willemdh/check_ms_win_disk_load to get the id and vice versa.

**Comment by mickem** [comment]
Localized counters is what is "failing" so just do what your doing but do it right.
I.e. specify the correct counter name.

**Comment by mickem** [comment]
Closing this, reopen if there are further need of answers...
