### ISSUE TITLE
CheckCounter Performance Data is affixed with 'none'

### ISSUE THREAD

**Issue by Klang0340** [mickem/nscp#242]
Good afternoon all,
    Just upgraded our agents to 0.4.4.15 and I noticed all my performance data disappeared for a lot of checks involving 'CheckCounter'. It appears the name of the performance data is being affixed with the word 'none', any thoughts?

Example from CLI:
/opt/plugins/check_nrpe -u -H <ServerIP> -t 20 -c CheckCounter -a 'Counter=\Processor(_Total)\% Processor Time' ShowAll MaxCrit=99
OK: \Processor(_Total)\% Processor Time = 2|'\Processor(_Total)\% Processor Time**none**'=2;0;9

Below is an example of what my performance data directory looks like for a typical server now. All the old data stayed, but new .rrd files are created with the new name.

-rw-rw-r--.   1 monitor apache 2132344 Feb  1 15:18 Disk_IO_Avg._sec_Read_-_C__PhysicalDisk(0_C_)_Avg._Disk_sec_Read**none**.rrd
-rw-rw-r--.   1 monitor apache 2132344 Jan 31 08:09 Disk_IO_Avg._sec_Read_-_C__PhysicalDisk(0_C_)_Avg._Disk_sec_Read.rrd
-rw-rw-r--.   1 monitor apache    2252 Feb  1 15:27 Disk_IO_Avg._sec_Read_-_C.xml
-rw-rw-r--.   1 monitor apache 2132344 Feb  1 15:07 Disk_IO_Avg._sec_Read_-__Total__PhysicalDisk(_Total)_Avg._Disk_sec_Read**none**.rrd
-rw-rw-r--.   1 monitor apache 2132344 Jan 31 08:09 Disk_IO_Avg._sec_Read_-__Total__PhysicalDisk(_Total)_Avg._Disk_sec_Read.rrd
-rw-rw-r--.   1 monitor apache    2293 Feb  1 15:36 Disk_IO_Avg._sec_Read_-__Total.xml
-rw-rw-r--.   1 monitor apache 2132344 Feb  1 14:54 Disk_IO_Avg._sec_Write_-_C__PhysicalDisk(0_C_)_Avg._Disk_sec_Write**none**.rrd
-rw-rw-r--.   1 monitor apache 2132344 Jan 31 08:09 Disk_IO_Avg._sec_Write_-_C__PhysicalDisk(0_C_)_Avg._Disk_sec_Write.rrd
-rw-rw-r--.   1 monitor apache    2256 Feb  1 15:23 Disk_IO_Avg._sec_Write_-_C.xml
-rw-rw-r--.   1 monitor apache 2132344 Feb  1 15:18 Disk_IO_Avg._sec_Write_-__Total__PhysicalDisk(_Total)_Avg._Disk_sec_Write**none**.rrd
-rw-rw-r--.   1 monitor apache 2132344 Jan 31 08:09 Disk_IO_Avg._sec_Write_-__Total__PhysicalDisk(_Total)_Avg._Disk_sec_Write

**Comment by mickem** [comment]
This is fixed in 0.5.0 and can be fixed with a command line option in 0.4.x not 100% sure something along the lines of ... "perf-syntax=*(suffix:none)" ...

Should be another ticker here with the same information if I am not misstaken

**Comment by Klang0340** [comment]
Mickem,
     I have downloaded 5.18 and this appears to resolve the issue, thank you for the response. I will be performing some more tests to ensure the rest of the item we use work but the performance counters swapped back over the previous files. I would have investigated you alternative solution with the command line but I have so many wrappers written it would take longer to change them and test than it would be to upgrade the agents. Thank you sir for the timely response.
