### ISSUE TITLE
Building on Linux 0.5.0.19

### ISSUE THREAD

**Issue by egonrassi** [mickem/nscp#244]
I've been trying to build the latest version of nscp on linux these last few weeks without success.

I keep stalling on:
[ 33%] Building CXX object modules/CheckSystemUnix/CMakeFiles/CheckSystemUnix.dir/filter.cpp.o
In file included from /usr/include/boost/tuple/tuple.hpp:33:0,
                 from /usr/include/boost/assign/list_of.hpp:22,
                 from /usr/include/boost/assign.hpp:20,
                 from /home/eythori/nscp/modules/CheckSystemUnix/filter.cpp:5:
/usr/include/boost/tuple/detail/tuple_basic.hpp: In instantiation of ‘boost::tuples::cons<HT, TT>::cons(const boost::tuples::cons<HT2, TT2>&) [with HT2 = long long int; TT2 = boost::tuples::cons<double, boost::tuples::cons<std::basic_string<char>, boost::tuples::null_type> >; HT = long long int; TT = boost::tuples::cons<std::basic_string<char>, boost::tuples::null_type>]’:
/usr/include/boost/tuple/detail/tuple_basic.hpp:572:45:   required from ‘boost::tuples::tuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>::tuple(const boost::tuples::cons<HT2, TT2>&) [with U1 = long long int; U2 = boost::tuples::cons<double, boost::tuples::cons<std::basic_string<char>, boost::tuples::null_type> >; T0 = long long int; T1 = std::basic_string<char>; T2 = boost::tuples::null_type; T3 = boost::tuples::null_type; T4 = boost::tuples::null_type; T5 = boost::tuples::null_type; T6 = boost::tuples::null_type; T7 = boost::tuples::null_type; T8 = boost::tuples::null_type; T9 = boost::tuples::null_type]’
/home/eythori/nscp/modules/CheckSystemUnix/filter.cpp:35:109:   required from here
/usr/include/boost/tuple/detail/tuple_basic.hpp:310:62: error: no matching function for call to ‘boost::tuples::cons<std::basic_string<char>, boost::tuples::null_type>::cons(const tail_type&)’
   cons( const cons<HT2, TT2>& u ) : head(u.head), tail(u.tail) {}

I followed the guide found here:
https://docs.nsclient.org/0.4.4/manual/build.html#linux

And did the building on an Ubuntu 15.04.

Has anyone been successful in building the nscp on a recent Linux OS?

**Comment by egonrassi** [comment]
I found the following page with some additional info:
http://sites.box293.com/nagios/guides/nrpe/installing-nrpe-client-agent/unix-linux/ubuntu-14-04---nsclient-from-github

Adding those packages as well as checking out the 0.5.0.16 version I was able to build.

**Comment by mickem** [comment]
Easiest to build is to use the vagrant images, just run vagrant up --provision and it should build itself for you...

**Comment by egonrassi** [comment]
Thanks for the hint to the right direction, and an excellent NSclient :)
And indeed Vagrant has now created this nice rpm package for version 0.5.0.16 for me.

But I want to bring to your attention that building 0.5.0.19 on Centos 7 is giving me an error with Vagrant.

==> default: Building CXX object modules/CheckSystemUnix/CMakeFiles/CheckSystemUnix.dir/filter.cpp.o
==> default: In file included from /usr/include/boost/tuple/tuple.hpp:33:0,
==> default:                  from /usr/include/boost/assign/list_of.hpp:22,
==> default:                  from /usr/include/boost/assign.hpp:20,
==> default:                  from /source/nscp/modules/CheckSystemUnix/filter.cpp:5:
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp: In instantiation of ‘boost::tuples::cons<HT, TT>::cons(const boost::tuples::cons<HT2, TT2>&) [with HT2 = long long int; TT2 = boost::tuples::cons<double, boost::tuples::cons<std::basic_string<char>, boost::tuples::null_type> >; HT = long long int; TT = boost::tuples::cons<std::basic_string<char>, boost::tuples::null_type>]’:
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:571:45:   required from ‘boost::tuples::tuple<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>::tuple(const boost::tuples::cons<HT2, TT2>&) [with U1 = long long int; U2 = boost::tuples::cons<double, boost::tuples::cons<std::basic_string<char>, boost::tuples::null_type> >; T0 = long long int; T1 = std::basic_string<char>; T2 = boost::tuples::null_type; T3 = boost::tuples::null_type; T4 = boost::tuples::null_type; T5 = boost::tuples::null_type; T6 = boost::tuples::null_type; T7 = boost::tuples::null_type; T8 = boost::tuples::null_type; T9 = boost::tuples::null_type]’
==> default: /source/nscp/modules/CheckSystemUnix/filter.cpp:35:109:   required from here
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:309:62: error: no matching function for call to ‘boost::tuples::cons<std::basic_string<char>, boost::tuples::null_type>::cons(const tail_type&)’
==> default:    cons( const cons<HT2, TT2>& u ) : head(u.head), tail(u.tail) {}
==> default:                                                               ^
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:309:62: note: candidates are:
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:387:3: note: template<class HT2> boost::tuples::cons<HT, boost::tuples::null_type>::cons(const boost::tuples::cons<HT2, boost::tuples::null_type>&)
==> default:    cons( const cons<HT2, null_type>& u ) : head(u.head) {}
==> default:    ^
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:387:3: note:   template argument deduction/substitution failed:
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:309:62: note:   mismatched types ‘boost::tuples::null_type’ and ‘boost::tuples::cons<std::basic_string<char>, boost::tuples::null_type>’
==> default:    cons( const cons<HT2, TT2>& u ) : head(u.head), tail(u.tail) {}
==> default:                                                               ^
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:309:62: note:   ‘const tail_type {aka const boost::tuples::cons<double, boost::tuples::cons<std::basic_string<char>, boost::tuples::null_type> >}’ is not derived from ‘const boost::tuples::cons<HT, boost::tuples::null_type>’
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:380:3: note: boost::tuples::cons<HT, boost::tuples::null_type>::cons(const boost::tuples::null_type&, const boost::tuples::null_type&, const boost::tuples::null_type&, const boost::tuples::null_type&, const boost::tuples::null_type&, const boost::tuples::null_type&, const boost::tuples::null_type&, const boost::tuples::null_type&, const boost::tuples::null_type&, const boost::tuples::null_type&) [with HT = std::basic_string<char>]
==> default:    cons(const null_type&,
==> default:    ^
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:380:3: note:   candidate expects 10 arguments, 1 provided
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:375:3: note: template<class T1> boost::tuples::cons<HT, boost::tuples::null_type>::cons(T1&, const boost::tuples::null_type&, const boost::tuples::null_type&, const boost::tuples::null_type&, const boost::tuples::null_type&, const boost::tuples::null_type&, const boost::tuples::null_type&, const boost::tuples::null_type&, const boost::tuples::null_type&, const boost::tuples::null_type&)
==> default:    cons(T1& t1, const null_type&, const null_type&, const null_type&,
==> default:    ^
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:375:3: note:   template argument deduction/substitution failed:
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:309:62: note:   candidate expects 10 arguments, 1 provided
==> default:    cons( const cons<HT2, TT2>& u ) : head(u.head), tail(u.tail) {}
==> default:                                                               ^
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:370:3: note: boost::tuples::cons<HT, boost::tuples::null_type>::cons(typename boost::tuples::access_traits<typename boost::tuples::detail::wrap_non_storeable_type<HT>::type>::parameter_type, const boost::tuples::null_type&) [with HT = std::basic_string<char>; typename boost::tuples::access_traits<typename boost::tuples::detail::wrap_non_storeable_type<HT>::type>::parameter_type = const std::basic_string<char>&]
==> default:    cons(typename access_traits<stored_head_type>::parameter_type h,
==> default:    ^
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:370:3: note:   no known conversion for argument 1 from ‘const tail_type {aka const boost::tuples::cons<double, boost::tuples::cons<std::basic_string<char>, boost::tuples::null_type> >}’ to ‘boost::tuples::access_traits<std::basic_string<char> >::parameter_type {aka const std::basic_string<char>&}’
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:368:3: note: boost::tuples::cons<HT, boost::tuples::null_type>::cons() [with HT = std::basic_string<char>]
==> default:    cons() : head() {}
==> default:    ^
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:368:3: note:   candidate expects 0 arguments, 1 provided
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:347:8: note: boost::tuples::cons<std::basic_string<char>, boost::tuples::null_type>::cons(const boost::tuples::cons<std::basic_string<char>, boost::tuples::null_type>&)
==> default:  struct cons<HT, null_type> {
==> default:         ^
==> default: /usr/include/boost/tuple/detail/tuple_basic.hpp:347:8: note:   no known conversion for argument 1 from ‘const tail_type {aka const boost::tuples::cons<double, boost::tuples::cons<std::basic_string<char>, boost::tuples::null_type> >}’ to ‘const boost::tuples::cons<std::basic_string<char>, boost::tuples::null_type>&’
==> default: make[2]: *** [modules/CheckSystemUnix/CMakeFiles/CheckSystemUnix.dir/filter.cpp.o] Error 1
==> default: make[1]: *** [modules/CheckSystemUnix/CMakeFiles/CheckSystemUnix.dir/all] Error 2
==> default: make: 
==> default: *** [all] Error 2
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by mickem** [comment]
Thank for letting me know, I will fix these.
I really need to schedule builds of all linuxes not just the travis stuff...

**Comment by mickem** [comment]
Should work now, both master and 0.4.4 build on linux, pleas reopen if you still have issues
