### ISSUE TITLE
nsclient "network metrics"

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#245]
Michael,

Could you give me more information about how to use the nsclient "network metrics" you added recently? I can't find any documentation about this. Can it automaitcally find and query the 'active network adapter'? Does it work with teamed network adapers? 'Active - Active' and 'Active - Failover'?
At the moment I'm using my check_ms_win_network_load (https://github.com/willemdh/check_ms_win_network_load) which is easy as I don't need to specify which adapter I want metrics for. But it does tend to generate a small cpu spike. I know your C++ checks are generally faster and require less cpu cycles then Powershell.

Thanks for any info on this.

Willem

**Comment by mickem** [comment]
It is built for metrics currently which means it will report data to graphite etc. But I guess I could also add some check for it.

As for teemed interfaces I think it wont work as they are found else where, but that is definetly planned...
The primary goal now was to add network graphs in the webui as well as add collectd network data...

**Comment by mickem** [comment]
If you want to see the data you can open the "metrics view" in the webui, they will display in the grid...

**Comment by willemdh** [comment]
Ok, thanks!
