### ISSUE TITLE
Failed to read data : End of file on check_nt command

### ISSUE THREAD

**Issue by kantechtsptest** [mickem/nscp#247]
Hello, 

I am trying to setup the ns client ++ to answer the check_nt commands from my Nagios Server. Everytime i send a command (for example: check_nt -H 2.3.5.7 -p Password -v CLIENTVERSION), Nagios responds : "No data was received from host". On the NS Client ++ side, if i run NSCP in test mode, i get the response : "Failed to read data : End of file ; c:\source\nscp\include\socket/connection.hpp:137.

I tried to find some explanation online about that particular error but i haven't had any luck so far.

I have attached my nsclient.ini file for reference. (Modified to txt format due to GitHub restrictions )

[nsclient.txt](https://github.com/mickem/nscp/files/134932/nsclient.txt)

Thanks.

**Comment by box293** [comment]
The password is send using -s and -p is for the port. 
Try:
```
check_nt -H 2.3.5.7 -s Password -p 12489 -v CLIENTVERSION
```

**Comment by kantechtsptest** [comment]
I just tried the suggested command with -s Password and i am still getting the same result with the same error message on the nsclient side.

**Comment by mickem** [comment]
Which version?
Seems to work for me...

```
mickem@felix:~$ /usr/lib/nagios/plugins/check_nt -H 192.168.0.201 -s XXX -p 12489 -v CLIENTVERSION
NSClient++ 0.5.0.19 2015-12-10
```

**Comment by kantechtsptest** [comment]
I am using version 0.4.4.15.

**Comment by kantechtsptest** [comment]
Will version 0.5.0.19 be available soon ?

I would like to try it to resolve my issue.

Thanks

**Comment by willemdh** [comment]
https://github.com/mickem/nscp/releases/tag/0.5.0.24

**Comment by kantechtsptest** [comment]
Thanks !!

I will try it as soon as possible and update the thread.

**Comment by mickem** [comment]
0.4.4 should be working as well...

**Comment by kantechtsptest** [comment]
For some strange reasons, i am getting the same error with version 0.5.0.24. Is there anything i can do to help me troubleshoot ?

Any assistance is greatly appreciated.

**Comment by mickem** [comment]
I'll give it a go on my machine and see if I can come up with something...

**Comment by kantechtsptest** [comment]
Did you had any change to try it on your end ?

**Comment by mickem** [comment]
The problem is that you in your config set the nrpe port to the checknt port and tried to use check_nt with it... which wont work.

```
[/settings/NRPE/server]
; ...

; PORT NUMBER - Port to use for NRPE.
port = 12489

```

Removing the above port line works for me.
