### ISSUE TITLE
[check_service] Service "TCP/IP NetBIOS Helper" (lmhosts) is detected as stopped but give me OK

### ISSUE THREAD

**Issue by garnier-quentin** [mickem/nscp#249]
Hi,

I have tested with NSClient 0.4.3-143 on Windows 2008 R2 and 2012.
The command:
```
# /usr/lib/nagios/plugins/check_centreon_nrpe -H xxxxx -p 5666 -t 30 -u -c  check_service -a "filter=start_type in ('auto') or delayed" "service=lmhosts"  "exclude=" "warning=" "critical=not state_is_perfect()" 'top-syntax=${problem_list}'  'detail-syntax=${name}=${state} (${start_type})'
OK: All 1 service(s) are ok.
```

And if i want the current state !!!!?? Weird no ? Oo
```
#  /usr/lib/nagios/plugins/check_centreon_nrpe -H xxxxx -p 5666 -t 30 -u -c  check_service -a "filter=start_type in ('auto') or delayed" "service=lmhosts"  "exclude=" "warning=" "critical=not state_is_perfect()" 'top-syntax=${problem_list}'  'detail-syntax=${name}=${state} (${start_type})'  show-all
lmhosts=stopped (auto)
```

**Comment by mickem** [comment]
Not weird at all...


If we start off with the service bit you have:

```
check_service "service=lmhosts" show-all
L        cli OK: lmhosts=running (demand)
```

Then we add the filter:
```
check_service "service=lmhosts" "filter=start_type in ('auto') or delayed" show-all
L        cli UNKNOWN: OK: No services found`
```

And therwe we have it.
You check one service, then you filter it out... and Tada: check is always ok.

**Comment by garnier-quentin** [comment]
Your 'lmhosts' service is 'demand'. Mine is 'auto'. My filter is good :)
It's not the same no ?

**Comment by mickem** [comment]
Run the same commands, adding a lot of options makes it difficult to see... Break them apart untill you find the problem...

**Comment by garnier-quentin** [comment]
I have added the option to narrow the problem.

**Comment by mickem** [comment]
Try this:

```
check_service "service=lmhosts" "detail-syntax=${name}=${state} (${triggers})" show-all
L        cli OK: lmhosts=stopped (3)
```

Trigger services are always "Ok"...

**Comment by mickem** [comment]
Reason being that triggered services are started based on when things happen and thus the state_is_perfect() macros treat them as manual start

**Comment by mickem** [comment]
((to circumvent this you can check the state instead of the macros))

**Comment by mickem** [comment]
Closing this for now please reopen if you still have issues

**Comment by garnier-quentin** [comment]
I don't understand. I have the trigger at 2 (means auto no ?). So the command should give me a 'critical' because it shouldn't be stopped ?
```
lmhosts=stopped (auto) (2)
```

I have tested with nsclient 0.5.0.35. The same issue.

If i use following filter, it's working: 
```
state not in ('running') and start_type in ('auto')
```

But i prefer to use methods. because i missing some stuffs in my filter.
