### ISSUE TITLE
[check_pdh] nsclient crash when call check_pdh 

### ISSUE THREAD

**Issue by garnier-quentin** [mickem/nscp#250]
Hi,

NSClient++ 0.4.3-143 crashes when i try to get the following counter on Windows 2003 32 bits:
```
[/settings/system/windows/counters/memory_committed_charge]
collection strategy=rrd
type=large
counter=\Memory\% Committed Bytes In Use
```

It works well with the same NSClient on Windows 2008 (surely 64 bits). Maybe it's the same problem than #248 

Thanks for the help

**Comment by mickem** [comment]
Crash dumps would be helpfull...

**Comment by mickem** [comment]
Found an issue which "might" be fixed in the next build of 0.5.x

**Comment by mickem** [comment]
Try this build and let me know if the issue is resolved: https://github.com/mickem/nscp/releases/tag/0.5.0.24

**Comment by mickem** [comment]
Closing this, please reopen if this is still an issue.

**Comment by garnier-quentin** [comment]
It's ok with 0.5.x. Thanks!
