### ISSUE TITLE
NSClient and Loading a PowerSHell Profile

### ISSUE THREAD

**Issue by Klang0340** [mickem/nscp#252]
Good afternoon all,

      I'm looking for assistance in having NSClient load a PowerShell profile when it calls PowerShell. The profile is needed as it comes with a 'Get-ADUser' cmdlet allowing me to easily query Active Directory for account information. The problem is, I never attempted to have NSClient load a profile or IF this is possible. Below I have provided the profile line to be loaded with the PowerShell executeable and my best attempt at a registry setting for the NRPE command.

**Profile to be loaded:** -psconsolefile "C:\Program Files\Quest Software\Management Shell for AD\ConsoleSettings.psc1" -noexit -command ". 'C:\Program Files\Quest Software\Management Shell for AD\qsft.ps1'"

**Registry Entry**: cmd /c echo scripts\get_AD_account_info.ps1 $ARG1$ exit($lastexitcode) | powershell.exe -psconsolefile "C:\Program Files\Quest Software\Management Shell for AD\ConsoleSettings.psc1" -noexit -command ". 'C:\Program Files\Quest Software\Management Shell for AD\qsft.ps1'" -command -

**Comment by Klang0340** [comment]
So my latest attempt from the CLI leaves me with output indicating the profile is loaded but it's like the command isn't being executed.

**Registry Entry**: cmd /c echo scripts\get_AD_account_info.ps1 $ARG1$ exit($lastexitcode) | powershell.exe -psconsolefile "C:\Program Files\Quest Software\Management Shell for AD\ConsoleSettings.psc1" -command ". 'C:\Program Files\Quest Software\Management Shell for AD\qsft.ps1'"

**Output (From the Monitoring Server)**:
/opt/plugins/check_nrpe -u -t 60 -H <IP_ADDRESS> -c get_acct_info -a <Account_Name>

         Welcome to ActiveRoles Management Shell 1.5.1, a part of Quest ActiveRoles Server 6.7

 View ActiveRoles Server product page:     Get-QARSProductInfo
 Visit ActiveRoles Server community site:  Get-QARSCommunity
 List all cmdlets:                         Get-Command
 List only Management Shell cmdlets:       Get-QCommand
 View help:                                Get-Help
 View help about a cmdlet:                 Get-Help <cmdlet-name> or <cmdlet-name> -?
 View full output for a cmd:               <cmd> |'Format-List'=0

**Comment by Klang0340** [comment]
![profile_1](https://cloud.githubusercontent.com/assets/11839144/13300706/07ebe1b6-db07-11e5-816e-e9f546b1da38.GIF)

It appears the output I receive is the initial content presented when a profile is loaded. Perhaps the command is being ran but the first output is the profile page so this is what nrpe returns.

**Comment by mickem** [comment]
Havent read the thread but are you looking for info on how to configure how powershell scripts are started?

It would depend on whether you using "wrapped" or not.

I recently did this change to the default wrapping to make it not use the default profile: https://github.com/mickem/nscp/commit/11d759f5d8d6a1dd16a87599b644eefc923a1e4c

So that might give you some details on how to configure nsclient++ correctly.

There is also a guide in the docs for how to setup powershel lscript IIRC.

**Comment by Klang0340** [comment]
Mickem,

                Yes, I’m looking for information on how I can execute a PowerShell script via NRPE (Which I already can) but have PowerShell session load a profile. In your linked example you have the code below…

| powershell.exe -noprofile -command -

                I’m actually interested in loading a profile, not preventing one from loading. This is so I can use the ‘Get-qADUser’ cmdlet not originally included in PowerShell. Below is the profile I need to add to NSClient.

powershell.exe -psconsolefile "C:\Program Files\Quest Software\Management Shell for AD\ConsoleSettings.psc1" -noexit -command ". 'C:\Program Files\Quest Software\Management Shell for AD\qsft.ps1'"

                I have attempted to add the following registry entry but when I execute the command my output basically shows the data you would see when you load this profile. I have attached screenshots to show you what I mean.

cmd /c echo scripts\get_AD_account_info.ps1 $ARG1$ exit($lastexitcode) | powershell.exe -psconsolefile "C:\Program Files\Quest Software\Management Shell for AD\ConsoleSettings.psc1" -command ". 'C:\Program Files\Quest Software\Management Shell for AD\qsft.ps1'"

                Screenshots:
                                Profile 1 – What you would see when you start PowerShell with the intended profile
                                Profile 2 – What you get as output from NRPE (Essentially what’s in the first screenshot but all on a single line)

So my problem is I am getting the profile loaded but it appears the code does not execute? I am still investigating what to do.

**Comment by mickem** [comment]
My point was more along the lines of using that but specifying a profile.
I am not a powershell export, if you could provide a stand alone example I could try it out myself but greping some of the stuff in this tread I would imagine something along the lines of:

```
cmd /c echo If (-Not (Test-Path \"scripts\\%SCRIPT%\") ) { Write-host \"Script not found\"; exit(3) }; scripts\\%SCRIPT% %ARGS%; exit($lastexitcode) | powershell.exe psconsolefile "C:\Program Files\Quest Software\Management Shell for AD\ConsoleSettings.psc1" -command -
```

**Comment by mickem** [comment]
Closing this for now, please reopen with a concrete non working example...
