### ISSUE TITLE
WMI (and others maybe) - returning only values that are used in filter

### ISSUE THREAD

**Issue by wojtek-dit** [mickem/nscp#253]
Hello.

I'm checking for example an UPS through WMI. I would like to check some values, for example EstimatedRunTime and get performance data for others (ie. EstimatedChargeRemaining, Name, FullChargeCapacity).
Despite listing some items in WMI select query, performance data only shows numeric values and only those that appear in crit/warn criteria. 
I gather performance data and plot graphs from them. They give a great insight on what's going on over time. 
Also, is it possible to get a value in top-syntax ? 
Like when I know that there is only one result and, in case of the UPS, return the name of the device in check result text ?
An example of what I would like to get :
checking for runtime value only
OK: APC1000XL runtime 14min|'fullchargecapacity'=1000 'runtimeremaining'=14 'somethingelse'=123

**Comment by mickem** [comment]
Simplest way to get stuff into perf data is to check fr obvious things like fullchargecapacity > -1234567 as that adds the perfdata and will never be true.

here is also some option to add some extra perfdata which is a bit "odd":

perf-conf=extra(runtimeremaining)

**Comment by wojtek-dit** [comment]
Thank You Michael.
perf-config=extra seems like a reasonable choice and I think it's less odd than performing always-false checks. Please document it, so others can use it!
As for my other question, about getting a value into check result text - what do You think ?

**Comment by mickem** [comment]
For the top value not as such, but is it really needed?
If the list only has one entry you should get the same result with the detail syntax right?

i.e.:

```
top-syntax="Wicked: %(list)" "detail-syntax=Charge: %(FullChargeCapacity) %"
... Wicked: Charge 45%...
```

**Comment by wojtek-dit** [comment]
Hello and thanks for the reply!
Yes I needed that. For my WMI queries the returned text was just values from WMI separated with commas without any description. Like this : "4, 1, Error". I needed it to be something meaningful like "Status: Error, statuscode: 4".
Thanks for the example with detail-syntax - that's exactly what I needed!
All is good then, I'm closing this. Have a nice weekend!
