### ISSUE TITLE
checkeventlog command not found

### ISSUE THREAD

**Issue by bvi1998** [mickem/nscp#254]
Hi, I am receiving command not found when attempting to run CheckEventLog. I have added this to my nsclient.ini and have restarted the nscp service:

; CheckEventLog - Check for errors and warnings in the event log. 
CheckEventLog = 1

**Comment by willemdh** [comment]
Please give the full command you are trying to run from Nagios....

**Comment by bvi1998** [comment]
check_nrpe -u -H myhost -p 5666 -c CheckEventLog -a file=system MaxWarn=1 MaxCrit=1 "filter=generated > -1h AND severity = 'error' OR severity = 'informational'"
Unknown command(s): checkeventlog

**Comment by willemdh** [comment]
For me it work with NSClient 0.5.0.24:

    /usr/local/nagios/libexec/check_nrpe  -H hostname -p 5666 -c CheckEventLog -a file=system MaxWarn=1 MaxCrit=1 "filter=generated > -1h AND severity = 'error'"
OK: No entries found|'count'=0;1;1

What NSClient version are you using? Maybe there are some dependencies on other modules..? This is my list of activated modules:

``` 
[/modules]
CheckExternalScripts = 1
CheckHelpers = 1
CheckNSCP = 1
CheckDisk = 1
CheckSystem = 1
CheckEventLog = 1
NSCAClient = 1
NRPEServer = 1
SyslogClient = 0
NRDPClient = 0
NRPEClient = 0
WEBServer = 1
GraphiteClient = 0
DotnetPlugins = 0
CheckWMI = 0
CheckTaskSched = 0
CommandClient = 0
Scheduler = 1
SMTPClient = 0
PythonScript = 0
SimpleCache = 1
NSCAServer = 0
CheckLogFile = 1
SimpleFileWriter = 1
NSClientServer = 1


[/settings/eventlog]
buffer size = 131072
debug = 0
lookup names = 1
```

**Comment by mickem** [comment]
The relevant part of the config is:


```
[/modules]
; ...
CheckEventLog = 1
```

**Comment by bvi1998** [comment]
Thanks! ....still not working, here is my nsclient.ini... 

; Undocumented section
[/modules]

CheckSystem=enabled
CheckDisk=enabled
CheckExternalScripts=enabled
NRPEServer=enabled
WEBServer=disabled

[/settings/NRPE/server]
allow arguments = true
allow nasty characters = true
allow arguments=true

allowed hosts = blah blah
port = 5666
insecure=1

; ENABLE SSL ENCRYPTION - This option controls if SSL should be enabled.
use ssl = true

[/settings/default]
;allowed hosts = 
;cache allowed hosts = true

; PASSWORD – Password used to authenticate against server
;password = blah

; Undocumented key
;Scheduler = 0

; Undocumented key
;NRPEServer = 1

; CheckSystem - Various system related checks, such as CPU load, process state, service state memory usage and PDH counters.
;CheckSystem = 1

; CheckExternalScripts - Execute external scripts
;CheckExternalScripts = 1

; CheckHelpers - Various helper function to extend other checks.
;CheckHelpers = 1

; CheckEventLog - Check for errors and warnings in the event log.
CheckEventLog = 1

; CheckDisk - CheckDisk can check various file and disk related things.
;CheckDisk = 1

; CheckNSCP - Use this module to check the healt and status of NSClient++ it self
;CheckNSCP = 1

[/settings/eventlog]
buffer size = 131072
debug = 0
lookup names = 1

[/settings/external scripts/scripts]

PSCheckCertificate=cmd /c echo scripts\file.ps1; exit($lastexitcode) | powershell.exe -command - 

; A list of templates for wrapped scripts.
%SCRIPT% will be replaced by the actual script an %ARGS% will be replaced by any given arguments.
[/settings/external scripts/wrappings]

; POWERSHELL WRAPPING - 
ps1 = cmd /c echo scripts\\%SCRIPT% %ARGS%; exit($lastexitcode) | powershell.exe -command -


; BATCH FILE WRAPPING - 
bat = scripts\\%SCRIPT% %ARGS%

; VISUAL BASIC WRAPPING - 
vbs = cscript.exe //T:30 //NoLogo scripts\\lib\\wrapper.vbs %SCRIPT% %ARGS%

**Comment by bvi1998** [comment]
Just found it - the checkeventlog was no under modules, it was under settings/default.. 
Thanks all!
