### ISSUE TITLE
Installer deletes configuration and logs

### ISSUE THREAD

**Issue by Daniel-Beardsmore** [mickem/nscp#256]
When running any version of the installer, the existing software installation is completely obliterated, including nsclient.log and nsclient.ini. Losing the log isn't a huge concern, but the configuration should be preserved.

The installer has little awareness of the configuration, and prompts you for fresh configuration even when installing over an existing version. In these circumstances, the prompt should be skipped and the existing configuration preserved.

Scenarios confimed: 0.4.2.114 to 0.4.4.19, and 0.4.4.19 to 0.5.0.25, on Server 2003. Configuration originally would have been "exe-path", although "shared-path" does the same thing as "exe-path" anyway.

**Comment by mickem** [comment]
The installer should import the old configuration and make changes to it. There was an issue prior to 0.4.x with this...

Can you confirm that you have this issue while installing 0.4.4.x over 0.4.4.x (older build)?

**Comment by Daniel-Beardsmore** [comment]
Server 2012 R2 64-bit. Upgrade process from 0.4.4.15 to 0.4.4.19:

Custom:
Documentation == no: forgotten (no need to install this on every server!)
Firewall Exception == no: forgotten
OP5 Monitoring system == no: appears to have been remembered (the installer was setting this to yes even in Generic mode)

Allowed hosts: correctly remembered
Password: <random string> (should be: blank)

[Old nsclient.ini.txt](https://github.com/mickem/nscp/files/163841/Old.nsclient.ini.txt)
[New nsclient.ini.txt](https://github.com/mickem/nscp/files/163844/New.nsclient.ini.txt)

The server is now showing as completely down in Nagios.

Even the allowed hosts entry was not written into the new file, even though the IP address was showing correctly in the installer dialog box. The entire of C:\Program Files\NSClient++ was obliterated, but since nothing was in custom scripts, I can't say if anything survived.

When I was testing with 0.5 earlier, I did check this briefly and the configuration and custom scripts survived, so this appears to be an issue just with the current stable series (0.4.4).

**Comment by Daniel-Beardsmore** [comment]
I've just tried two separate SBS 2011 servers (unrelated organisations), and in both cases, the installer deadlocked on "Validating install", unable to continue, and unable to cancel. Very odd. I suspect this is something SBS-related that clogs up the server.

Eventually I reconnected both RDP sessions (sometimes there are issues with RDP and consent) and one server did recover and upgraded the software (ignoring all the attempts to cancel the installation).

The custom scripts were preserved, but the configuration was not (per above files). Since nsclient.ini was wiped and recreated, the custom permissions set on that file to bypass UAC when saving to it, were also lost.

**Comment by Daniel-Beardsmore** [comment]
As a note, going from 0.5.0.26 to 0.5.0.28, in Server 2003 R2 SP2 32-bit:

Documentation = no: forgotten
Firewall Exception == no: forgotten
OP5 Monitoring system == no: forgotten

Password: new random password generated instead of leaving it as blank

The only change to the .INI file (aside from adding spaces either side of "=") was that logging was changed from trace to info.

The log file was correctly preserved.

0.5 series just needs to remember the MSI configuration settings for next time. I also don't understand why the installer keeps enabling OP5 Monitoring System when selecting "Generic" instead of "OP5" as the installation method.

**Comment by mickem** [comment]
There is a bug in the new installer so you need to set MONITORING_TOOL=ignored on silent installes...

**Comment by mickem** [comment]
ANd forgetting settings this is "normal behavior" for MSI packages I think (at least that annoys me all the time).

**Comment by mickem** [comment]
This has been much improved (and most likely fixed) in 0.5.1
