### ISSUE TITLE
NRPE forwarding/relaying not working in 0.5

### ISSUE THREAD

**Issue by Daniel-Beardsmore** [mickem/nscp#258]
Forwarding host: Server 2003 R2 SP2, NSClient++ 0.5.0.19 and 0.5.0.25

Target host: Server 2003 R2 SP2, NSClient++ 0.5.0.25

Example command:
$ ./check_nrpe -n -H external.host.addr -c check_nrpe -a host="internal.host.addr" no-ssl command="check_uptime"

Expected output:
OK: uptime: …

Actual output:
CHECK_NRPE: Invalid packet type received from server.

Local checks on the forwarding host do work:

$ ./check_nrpe -n -H external.host.addr -c check_uptime
OK: uptime: …

Due to the nature of the logging (issue 255) I can't offer much in the way of clues. The forwarding host literally just logs:

2016-03-07 09:47:27: debug:c:\source\master\include\nrpe/server/protocol.hpp:72: Accepting connection from: xxx.xxx.xxx.xxx, count=1

The target server does not log any incoming connections, so this error is occurring on the forwarding server.

Using 0.4.4 series on the forwarding host works just fine — this seems to be a bug in 0.5.0 series. I upgraded the forwarding host to 0.5.0.25 to test the new "argument" parameter to check_nrpe/nrpe_query as it looks like I'll be needing this to forward arbitrary numbers of parameters.

**Comment by mickem** [comment]
Works for me...

Could you provide config of repective machines?

I would guess either ssl/insecure or multi packets issue.
Unfortunetly NRPE is not friendly in terms of errors.


My config:
```
[/modules]
CheckSystem = enabled
NRPEServer = enabled
NRPEClient = enabled

[/settings/default]
allowed hosts=::1, 127.0.0.1
```

Running check_cpu
```
check_nrpe --host 127.0.0.1 --command check_cpu
D       nrpe Connecting to: host: 127.0.0.1:5666, buffer_length: 1024, ssl: ssl enabled: none, cert: C:\source\build\x64\dev/security/certificate.pem (), , dh: , ciphers: ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH, ca: , options:
D       nrpe Accepting connection from: 127.0.0.1, count=1
L        cli OK: OK: CPU load is ok.
L        cli  Performance data: 'total 5m'=0%;80;90 'total 1m'=0%;80;90 'total 5s'=1%;80;90
```

Showing version
```
check_nrpe --host 127.0.0.1
D       nrpe Connecting to: host: 127.0.0.1:5666, buffer_length: 1024, ssl: ssl enabled: none, cert: C:\source\build\x64\dev/security/certificate.pem (), ,  , ciphers: ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH, ca: , options:
D       nrpe Accepting connection from: 127.0.0.1, count=1
L        cli OK: I (0.5.0.25 2016-03-03) seem to be doing fine...
```
// Michael Medin

**Comment by Daniel-Beardsmore** [comment]
[nsclient (target host).ini.txt](https://github.com/mickem/nscp/files/161829/nsclient.target.host.ini.txt)
[nsclient (forwarding host).ini.txt](https://github.com/mickem/nscp/files/161830/nsclient.forwarding.host.ini.txt)

The configuration for the forwarding host is literally identical to how it was under 4.4.* as I just opened it in Notepad, upgraded the program, and then saved the file and restarted the service.

SSL is switched off everywhere for now, as I've not had chance to figure out what incantations are required to reactivate it.

**Comment by mickem** [comment]
Stripped out some "unrelated stuff" and change the port:

nsclient.forwarding.host.ini.txt
```
[/settings/log]
level = trace

[/settings/default]
allowed hosts = ::1, 127.0.0.1

[/settings/NRPE/server]
; SSL may take a while to get working, so for now, let's leave it off
use ssl = false
; Required for CRM-generated central configuration
allow arguments = true
; Required for CRM-generated requests for WMI performance counters (check_pdh)
allow nasty characters = true

; Default SSL settings, just for reference
ssl options = no-sslv2,no-sslv3
verify mode = peer-cert
insecure = false

[/modules]
NRPEServer = 1
NRPEClient = 1
```

nsclient.target.host.ini.txt
```

[/settings/log]
level = trace

[/settings/default]
allowed hosts = ::1, 127.0.0.1

[/settings/NRPE/server]
port = 5668
; SSL may take a while to get working, so for now, let's leave it off
use ssl = false
; Required for CRM-generated central configuration
allow arguments = true
; Required for CRM-generated requests for WMI performance counters (check_pdh)
allow nasty characters = true

; Default SSL settings, just for reference
ssl options = no-sslv2,no-sslv3
verify mode = peer-cert
insecure = false

[/modules]
CheckSystem = 1
NRPEServer = 1
```

Running the command:
```
check_nrpe host=127.0.0.1 port=5668 ssl=false
D       nrpe Connecting to: host: 127.0.0.1:5668, buffer_length: 1024, ssl: ssl disabled
L        cli OK: I (0.5.0.25 2016-03-03) seem to be doing fine...
```

Noticed a major snag though, and the ssl=false option does not work in 0.5.x, will be fixed in the next build.

**Comment by mickem** [comment]
Build 0.5.0.26 is out now: https://github.com/mickem/nscp/releases/tag/0.5.0.26

**Comment by Daniel-Beardsmore** [comment]
Right, I see the problem now — it's another backwards-compatibility break between 0.4 and 0.5. The option no-ssl has been unexpectedly removed. This causes a parse error, and nscp.exe responds to parse errors with something that the Nagios check_nrpe client doesn't understand.

I suggest that nscp.exe respond with "CRITICAL Invalid command received, please check the logs" and put a log entry in nsclient.log indicating the syntax error. (If it's feasible to return the syntax error directly from nscp.exe (as a simple string) then that would be even better, but so long as it's logged, that's enough.)

The fact that the "ssl" parameter is not documented as being boolean means that anyone looking at it will still see it as the old "enable SSL" parameter, and not realise that you can set it to false. Also, you've listed the Default Value for "ssl" to "N/A" which is now incorrect: the default value is "true", another clue that this is now what you set to "false". (In general, each parameter should have its data type listed: boolean, string, integer, numeric etc)

Also, I suggest that the reference page for NRPEClient contain, at the top, a panel listing the compatibility changes, e.g. removal of "no-ssl", and replacement of misnamed "arguments=" with "argument". This way, people are actually alerted to these changes — anyone coming to 0.5 at any point will see what needs to be changed.

Since switching to 0.5 is going to break everything using NRPEClient anyway, I suggest you use "arguments" to set off the arguments string, for grammatical correctness. Using the old method of arguments= causes "CHECK_NRPE: Invalid packet type received from server." anyway, so anyone using it will be forced to change, so you may as well get the grammar right the second time around.
