### ISSUE TITLE
“Failed to get network metrics” logged repeatedly

### ISSUE THREAD

**Issue by Daniel-Beardsmore** [mickem/nscp#260]
“Failed to get network metrics” is being logged repeatedly.

This is occurring even on a server that is not receiving any checks, and even after the service has been started and no manual checks have been received.

Both affected servers run 0.5.0.26 32-bit, Windows Server 2003 R2 SP2.

(I reverted both servers in question—the ones where I’ve been testing relaying—back to “info” logging level, and the log entries still get created. I wondered previously if the fact that I was seeing these errors in 0.5.0.25—where you claimed it was fixed—was due to using trace-level logging, but clearly that is not the case either.)

**Comment by mickem** [comment]
What os/architecture is it?

**Comment by Daniel-Beardsmore** [comment]
32-bit Windows Server 2003 R2 SP2 as noted above :)

**Comment by mickem** [comment]
Saw I had implemented this badly, will try to push a fix in the next few days...

// Michael Medin

**Comment by Daniel-Beardsmore** [comment]
It's not an urgent issue, but it does make logs hard to read :)

**Comment by mickem** [comment]
This might be fixed here: https://github.com/mickem/nscp/releases/tag/0.5.0.27 (havent had time to test it) but even if it is not fixed error reporting will be better so it will show actual error message...

**Comment by mickem** [comment]
This has been fixed in latest build (verified on XP), please reopen if you still have this issue

**Comment by Daniel-Beardsmore** [comment]
I now see a single log entry: 2016-03-14 10:42:56: error:c:\source\master\modules\CheckSystem\pdh_thread.cpp:250: Failed to get network metrics: Failed to fetch network metrics, disabling...

This appears to be the correct behaviour, so the issue appears to be fixed. Thank you.
