### ISSUE TITLE
under linux the return code of check_nrpe.cpp is always 99

### ISSUE THREAD

**Issue by FI5CHER** [mickem/nscp#261]
int main(int argc, char* argv[]) {
...
...
                        if (!tmp.empty())
                                std::cout << '|' << tmp;
                 }
        }
        return 99; // return response.result();
}

i would say that it should be changed to :

int main(int argc, char* argv[]) {
...
...
                        if (!tmp.empty())
                                std::cout << '|' << tmp;
                        return response.result();
                }
        }
        return 99;
}

After i changed my check_nrpe.cpp  it returns 0 .

**Comment by mickem** [comment]
Sorry, when I did refactoring a while back I did this as a temp fix...
