### ISSUE TITLE
Clarification on running multiple instances (re: issue 155)

### ISSUE THREAD

**Issue by JohnZ-H** [mickem/nscp#263]
Good afternoon,
  in issue 155 it was written:
"
mickem commented on 30 Aug 2015
Just for the record you can install multiple services running the same binary, with 0.4.x (which I guess your not using) you can specify the config store on command line so you can have different configs.
Ans using config include you have one base config only overriding the relevant bits in each config...

For 0.3.9 you need to have multiple locations though...
"

Can anyone clarify how you specify the config store on the command line, I've not managed to find / guess the appropriate switch, can't spot it in the help files or on the documentation site!   Apologies if I've missed something obvious!

Many thanks,
John

**Comment by mickem** [comment]
```
$ nscp service --help
Allowed options (service):

Common options:
  --settings arg                    Override (temporarily) settings subsystem
                                    to use
  --debug                           Set log level to debug (and show debug
                                    information)
  --log arg                         The log level to use
  --define arg                      Defines to use to override settings. Syntax
                                    is PATH:KEY=VALUE

Common options:
  --help                            Show the help message for a given command
  --no-stderr                       Do not report errors on stderr
  --version                         Show version information

Service Options:
  --install                         Install service
  --uninstall                       Uninstall service
  --start                           Start service
  --stop                            Stop service
  --restart                         Stop than start service
  --info                            Show information about service
  --run                             Run as a service
  --name arg                        Name of service
  --pid [=arg(=/var/run\nscp.pid)]  Create a pid file
  --description arg                 Description of service
```

In this case we are looking for --settings

Thus you can change the service definition like so:
```
"C:\Program Files\NSClient++\nscp.exe" service --run --name nscp --settings ini://${shared-path}/nsclient-2.ini
```

The setting is found under: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\nscp

And installing the service can be done using:
```
nscp service --install --name nscp2
```

But you need to change the command line manually.

**Comment by mickem** [comment]
Please reopen if this does not answer your question.
