### ISSUE TITLE
check_drivesize: ability to distinguish between internal and external drives

### ISSUE THREAD

**Issue by micsco** [mickem/nscp#265]
Unless I'm missing something there is currently no way to determine and/or filter internal vs external drives (such as USB disks).

I'm looking to be able to filter out external drives when doing check_drivesize check, the particular use case is a fleet of branch servers at various branches have rotating external hard drives for backups. Unfortunately the hard drive names are not consistent, and we've struggled to identify a quick easy way to filter these drives out from our core checks.

**Comment by mickem** [comment]
Type comes to mind but that is a bit crude and not sure it handled USB drives...

**Comment by mickem** [comment]
Should be possible now: https://github.com/mickem/nscp/releases/tag/0.5.0.32

This works for me (with usb drives):
```
check_drivezie "filter=mounted=1 and removable = 0"
```

**Comment by micsco** [comment]
Thank you Mickem!
