### ISSUE TITLE
Multiple nsclient in programs Win10

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#267]
Is it normal that when installing a new version of NSClient, the old one stays in the Programs overview. Just noticed this on Windows 10.

![image](https://cloud.githubusercontent.com/assets/6462991/13905506/cc729174-eec1-11e5-925f-3f648d5da3a8.png)

**Comment by mickem** [comment]
Unfortunately the "Old" installer had some issues which might cause this yes...

**Comment by willemdh** [comment]
So 0.5.0.23 still had the old installer?

**Comment by mickem** [comment]
No, the old installer did not uninstall properly...

**Comment by mickem** [comment]
Can we close this or how do you want to precede?

**Comment by mickem** [comment]
Please reopen if you need help resolving this...

**Comment by willemdh** [comment]
Well just updated again and seems I'm experiencing the same problem trying to update from 0.5.0..32 to 0.5.0.41

![image](https://cloud.githubusercontent.com/assets/6462991/14434920/a7b40d9e-0015-11e6-9071-b7675c1edd2d.png)

How do you suggest solving this?

**Comment by mickem** [comment]
Fixed in .42/.43 as always when it comes to MSI you cant really change old packages so this is hence forth, but upgrading from 42 to 43 should work.
