### ISSUE TITLE
Manually add readable = 0 to your filter.

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#268]
Just installed latest release (0.5.0.32) and I seem to get an unknown on this command which has worked for months.

    ignore-unreadable drive=* "filter=(type in('fixed') AND drive NOT LIKE '\\?\')" "warn=( used > 90% )" "crit=( used > 95% )" 'top-syntax=%(status): Drivesizes {%(detail_list)}' 'detail-syntax= {Drive %(drive) Total: %(size), Used: %(used), Free: %(free)}' "perf-config=*(unit:G) used %(ignored:true)"

So now I get an unknown:

    Manually add readable = 0 to your filter.

Instead of:

    OK: Drivesizes { {Drive D:\ Total: 931.51GB, Used: 222.547GB, Free: 708.963GB}, {Drive E:\ Total: 931.511GB, Used: 20.468GB, Free: 911.043GB}, {Drive C:\ Total: 418.229GB, Used: 318.052GB, Free: 100.177GB}

Could you please enlighten me what has changed and if I still need to use ignore-unreadable? In the release there is a mention of updated documentation, could I please have the link to that, I seem unable to find it. Tx!

**Comment by mickem** [comment]
Well, the flag ignore-unreadable was "lost" somewhere in 0.5.x and yesterday I did some changes and realized this so I re added it.
This time as a filter... guess I need to change this a bit...
For now removing that flag will give you the same behavior as the previous version... If you really need the ignore unreadable you can add " and readable = 0" to the end of your filter...

But will try to fix this for next build...

**Comment by mickem** [comment]
As for the docs the commit is that the "source for the docs" have been updated (they are in a separate git repo), the actual docs can be found in the docs package (there is a docs zip file on the download site) but usually also on the docs site i.e. https://docs.nsclient.org or for the zip see the *docs*zip files here: http://www.nsclient.org/download/0.5.0/#0.5.0.32

The updates for check_drivesize in this case are: http://docs.nsclient.org/reference/windows/CheckDisk.html#CheckDisk.check_drivesize.filter (check the readable writable erasablae etc. flags.

But lately I have also update parts of the manual and such so for instance this page has gotten an overhaul as well as others: https://docs.nsclient.org/manual/checks.html
