### ISSUE TITLE
Order PerfData Response has changed after 0.4.1

### ISSUE THREAD

**Issue by philippjenni** [mickem/nscp#269]
After V.0.4.1 the performance data order has changed. In 0.4.1 is the order percent, value. In 0.4.2 is the order value, percent.

How i can change this order? The change order is a problem in combination with icinga and pnp4nagios.

The problem exists in the modules:
CheckDriveSize, checkmem

**Comment by mickem** [comment]
Don't think it is possible actually (you might force it by writing filters in certain orders).

But since they have names the order "should" not matter though?
The order is not stable though, so there is no guarantee

**Comment by philippjenni** [comment]
pnp4nagios imports the perfdata like the order it comes from the nsclient. Label are ignored.

**Comment by mickem** [comment]
Then I would raise an issue with pnp4nagios asking them to use the labels, from what I understand there is no ordering in the perfdata specification.

Not sure it is possible to handle ordering as it is based on the query...

**Comment by mickem** [comment]
Please reopen if this is a critical issue. Perfdata is not stable in nsclient++ but perf data could be sorted in a script if required.
