### ISSUE TITLE
0.5.0.18: check_process output detail assistance

### ISSUE THREAD

**Issue by Klang0340** [mickem/nscp#271]
Good morning all,
      I'm trying to understand the output syntax of check_process. My intent is to request a process count then have the current count included in the output.

With my current attempts, my output looks like 'CRITICAL: ' when my threshold is met/exceeded and it displays no detail. My preferred output would be similar to 'CRITICAL: 'x' processes found'. I believe the plugin can do this but I have difficulty understanding the syntax. Below is my current command line.

[monitor@opmaster1-corp-p1 /opt/plugins]$ /opt/plugins/check_nrpe -u -t 30 -H -c check_process -a process=powershell.exe 'warn=count>10' 'crit=count>25' 'detail-syntax=${state}=${total}'
CRITICAL: |'count'=33;10;25

Picture of output: 
![output](https://cloud.githubusercontent.com/assets/11839144/13955214/d4ed3dda-f011-11e5-9f31-b8f38308f2e5.GIF)

I know by extracting the performance data I could write a wrapper to complete this but I would like to better understand if this can be done with the original plugin. This is also to help me better understand how to use the syntax.

**Comment by mickem** [comment]
detail-syntax is used to render each item i.e. each process.
What you want is top-syntax which is the returned line.

Also be aware the ${} can be interpreted by the shell so often %() can be easier to use.

````
check_process process=chrome.exe "warn=count>10" "crit=count>25" "detail-syntax=detail->%(exe)=%(handles)" "top-syntax=top->%(count) (here comes details--> %(list))"
L        cli CRITICAL: top->26 (here comes details--> detail->chrome.exe=4361, detail->chrome.exe=722, detail->chrome.exe=229, detail->chrome.exe=249, detail->chrome.exe=229, detail->chrome.exe=224, detail->chrome.exe=264, detail->chrome.exe=222, detail->chrome.exe=222, detail->chrome.exe=227, detail->chrome.exe=291, detail->chrome.exe=366, detail->chrome.exe=223, detail->chrome.exe=371, detail->chrome.exe=276, detail->chrome.exe=223, detail->chrome.exe=222, detail->chrome.exe=261, detail->chrome.exe=403, detail->chrome.exe=285, detail->chrome.exe=222, detail->chrome.exe=263, detail->chrome.exe=243, detail->chrome.exe=279, detail->chrome.exe=283, detail->chrome.exe=285)
L        cli  Performance data: 'count'=26;10;25
``

**Comment by Klang0340** [comment]
Thanks Mickem,

    You provided the detail I needed to better understand, thanks again.
