### ISSUE TITLE
check_pdh and type=double not working

### ISSUE THREAD

**Issue by brunomartins** [mickem/nscp#272]
Just tried to check some Windows counters that return float values. To ensure check_pdh could handle the value I set the flag type=double. Here an extract of the check I setup.
    
    alias_checklogicaldisk_averagelatency_disk1=check_pdh "counter=\LogicalDisk(*)\Avg. Disk sec/Transfer" type=double

Running this manually ( nscp test )

    alias_checklogicaldisk_averagelatency_disk1
    L        cli OK: OK: \LogicalDisk(*)\Avg. Disk sec/Transfer = 0
    L        cli  Performance data: '\LogicalDisk(*)\Avg. Disk sec/Transfer_value'=0;0;0

Running the following Powershell whilst running CrystalDiskMark

    ( Get-Counter -Counter "\LogicalDisk(*)\Avg. Disk sec/Transfer" ).CounterSamples | select instancename, cookedvalue

 which returns 

    c:   0.00180013181927105
    f:    0.049985006338838

So the original check_pdh check should have returned  some decimals in the performance data and it didn't.

By the way I am using NSClient++ 0.4.4.15 but I have also tried this on version 0.5.0.32.

**Comment by brunomartins** [comment]
Thanks Mickem!

**Comment by mickem** [comment]
Nightly build is out: https://github.com/mickem/nscp/releases/tag/0.5.0.33

**Comment by brunomartins** [comment]
Just tested the 0.5.0.34 nightly build. Nearly there :)

The nagios message now contains a double. However, the performance data is still issuing rounded ints as can be seen at the end of the last line:

    alias_checklogicaldisk_averagelatency_disk1 0.01 0.02
    L        cli OK: \LogicalDisk(C:)\Avg. Disk sec/Transfer = 0.000120369
    L        cli  Performance data: '\LogicalDisk(C:)\Avg. Disk sec/Transfer_value'=0;0;0

**Comment by mickem** [comment]
Will fix this in next build...

**Comment by brunomartins** [comment]
Awesome thank you

Sent from Outlook<https://aka.ms/f818qx>



On Fri, Apr 1, 2016 at 3:08 AM -0700, "Michael Medin" <notifications@github.com<mailto:notifications@github.com>> wrote:


Will fix this in next build...

-
