### ISSUE TITLE
Settings finely the threshold values

### ISSUE THREAD

**Issue by szandras2524** [mickem/nscp#273]
Hi,

I was goolging around but couldn't find any real description about setting the threshold finely... I saw in the NagiosPlugins.vbs that it's excellently prepared, but couldn't really figure out howto pass the parameters to the script, as far i would need and warning and critical issue for value under an limit and not over. 

Can you assist me? 

Best wishes,

András

**Comment by mickem** [comment]
Not sure I mean, which command are you trying to set thresholds for?

For built in command this is probably a good starting point: https://docs.nsclient.org/manual/checks.html

**Comment by mickem** [comment]
Please reopen with more details...
