### ISSUE TITLE
[check_tasksched] Add a value for never executed task

### ISSUE THREAD

**Issue by garnier-quentin** [mickem/nscp#274]
Hi,

Could you add a value  when a task had never been executed ? The variable %(most_recent_run_time) contains the 1970 date. Would be better to have a value like (0 or 1): 
%(never_executed)

What do you think about it ?

**Comment by garnier-quentin** [comment]
has_run is better :) Thanks!

**Comment by mickem** [comment]
This is available in the last build BTW

**Comment by garnier-quentin** [comment]
It's working. Thanks :)
