### ISSUE TITLE
check_nrpe -c update-nsclient -a "msi-location=XXX"

### ISSUE THREAD

**Issue by ritouret** [mickem/nscp#282]
Hello,

Sorry if this has already been asked.

Should the agent be updated through a check_nrpe command with the msi file location in argument (format like \\\server_name\directory_location) ?

Thanks.

**Comment by mickem** [comment]
If should = could, for sure.
You create an external script which runs msiexec with the relevant options...

**Comment by ritouret** [comment]
Great !
I'll test it, thank you.
