### ISSUE TITLE
Is it possible to schedule non-checks ?

### ISSUE THREAD

**Issue by wojtek-dit** [mickem/nscp#284]
Hello.
I have a check that runs quite long. So not to risk timeouts on checks I want to schedule the script to run and write result to a file. Then the file would be read with active check. 

Is there a possibility to use the scheduler to run checks and not report them anywhere ?

This would be better than using the windows scheduler because all configuration will be contained in nsclient and would use its security context.

**Comment by mickem** [comment]
Yes it's the short answer...  Can give an example in a bit...

**Comment by wojtek-dit** [comment]
Hello Michael. 
That's great. Thanks!

**Comment by mickem** [comment]
Started some docs here but havent had time to finish yet: http://docs.nsclient.org/howto/run_commands.html

**Comment by wojtek-dit** [comment]
So You plan big.
I thought maybe there can be another target than nsca. Or a possibility to make a dummy nsca target, so that it would be treated as sent. That would use existing facilities with minimal changes.

**Comment by mickem** [comment]
You have Noop to discard  and file as well for the file writer...

**Comment by wojtek-dit** [comment]
Thanks. On which versions is this available ?

**Comment by mickem** [comment]
noop? 0.4.4 I think... 0.5.0 for sure...

**Comment by wojtek-dit** [comment]
4.4.19 performs check but logs :
2016-05-11 00:16:23: error:c:\source\nscp\modules\Scheduler\Scheduler.cpp:122: Failed to submit host_check: seems ok
2016-05-11 00:16:23: error:c:\source\nscp\modules\Scheduler\Scheduler.cpp:122: Failed to submit test: seems ok
What can I do ?

**Comment by mickem** [comment]
Could you proved the config you are using?

**Comment by wojtek-dit** [comment]
Sure :
test.bat forks notepad, which opens like expected. 

[/modules]
CheckDisk = 1
CheckEventLog = 1
CheckExternalScripts = 1
CheckHelpers = 1
CheckNSCP = 0
CheckSystem = 1
CheckWMI = 1
NSCAClient = 1
NRPEServer = 1
NSClientServer = 0
Scheduler = 1

[/settings/NRPE/server]
allow arguments = true
allow nasty characters = true
allowed hosts = 
port = 9657


[/settings/default]
allowed hosts = 

[/settings/log]
date format = %Y-%m-%d %H:%M:%S
file name = nsclient.log
level = info

[/settings/log/file]
max size = 100000

[/settings/external scripts/scripts]
t=test.bat

[/settings/scheduler/schedules/default]
interval=5s
channel=noop

[/settings/scheduler/schedules]
test=t

**Comment by mickem** [comment]
This works for me with 0.5.0 so try updating to that.

**Comment by mickem** [comment]
Please reopen if it still does not work
