### ISSUE TITLE
New feature request : nrdp client do not support SSL/TLS

### ISSUE THREAD

**Issue by guillaumechardin** [mickem/nscp#286]
Hello,
nsclient v0.4.4.23 do not support SSL, so monitoring info ca be sent in clear text.

I look briefly in /include/http/client.hpp and it seems that the execute method do not handle certificate.

Can it be added on next releases ?

thanks

**Comment by mickem** [comment]
For sure...  Am working on it at the moment so hopefully in a week or so...

**Comment by guillaumechardin** [comment]
Hello,

Is there any update regarding this feature ?

**Comment by mickem** [comment]
Sorry for the very very long delay...

ssl support is implemented in check_nscp now so I will setup an NRDP server and validate it in the next few days...

**Comment by guillaumechardin** [comment]
Did you achieve to test nrdp ?
If you want I can test it on my infrastructure for you and give you feedback/debug logs.
Just give me the right compiled client or version number to you.

Bye

**Comment by guillaumechardin** [comment]
Seems that nrdp is not working see doc attach (cannot upload it on pdf sorry)
Some settings are not used by nrdp channel

[Doc1.docx](https://github.com/mickem/nscp/files/357482/Doc1.docx)

**Comment by mickem** [comment]
Latest build supports https and regular NRDP was fixed as well a few builds ago...
So try the latest build and le me know any issues...

**Comment by JGGINC** [comment]
Good day Michael,

Trying to get submit_nrdp working on latest build (0.5.0.59) w/out success.  With HTTPS was always receiving "cli UNKNOWN: Error: Failed to fetch config: 400:".  Dumbed down to HTTP and receive "cli UNKNOWN: Error: Failed to fetch config: 404:"

nscp test mode renders successful run of the check used for same, but cannot submit.  NRDP server is working well via HTTPS for distributed Nagios; it is only NSClient++.

Could you kindly provide some additional info, examples, etc?

Obviously, we prefer to use 443.

Any further guidance is much appreciated...and happy to test nightly builds, etc.

Mny Thx

**Comment by JGGINC** [comment]
ssl_access_log shows "[26/Aug/2016:18:25:59 +0000] "GET / HTTP/1.0" 400 362" when using submit_nrdp build (0.5.0.59) vs. POST?

**Comment by mickem** [comment]
So sorry for this, there were a bunch of issues...
I have fixed it in the next build:

```
nscp test --log trace
...
exec NRDPClient submit_nrdp --address https://nrdp.server.com/nrdp/server --key secret --command foo --result ok --message bar

D       core Executing command is target for: NRDPClient
T       core Trying : CheckEventLog
T       core Trying : NRDPClient
D       core Executing command in: NRDPClient
T       nrdp Target configuration: address: https://nrdp.server.com/, timeout: 30, retry: 2, data: { retries: 3, token: secret, }
T       nrdp Connecting tuo: protocol: https, host: nrdp.server.com:443, port: 443, path: /nrdp/server, timeout: 30, token: secret, sender:
T       nrdp Sending: <?xml version="1.0" encoding="UTF-8"?>
<checkresults>
    <checkresult type="service">
        <hostname>mime-g501jw</hostname>
        <servicename>foo</servicename>
        <state>0</state>
        <output>bar</output>
    </checkresult>
</checkresults>

T       nrdp Happily ignoring: <?xml version="1.0" encoding="utf-8"?>
<result>
  <status>0</status>
  <message>OK</message>
    <meta>
       <output>1 checks processed.</output>
    </meta>
</result>

D       core Module handled execution request: NRDPClient
T       core Trying : CommandClient
L        cli Data presumably sent successfully
```

// Michael Medin
