### ISSUE TITLE
NSCP.EXE not working on Windows 2012 R2 Core

### ISSUE THREAD

**Issue by ejsiron** [mickem/nscp#289]
Hi,
I had two WS2012R2 servers running in Core mode in which the NSCP.EXE client would not operate. With any flags or switches, or with none at all, it would simply return a blank line. Also, when running the installer, it would error out on a custom action.
I rebuilt one of the hosts and it's working now, so I'm sure that it was something with configuration. I just don't have any idea what. They were both domain controllers with no third-party software. I'm going to leave the other one active for troubleshooting.

**Comment by mickem** [comment]
Just tried it got the same result.
Very very strange.

Only thing I noticed is that the %ERRORLEVEL% is 0xC0000135, I will investigate further and see if I can find out whats amiss...

**Comment by mickem** [comment]
Just noticed the vcredist dll:s are missing, if you use the zip.
Install them and it works (for me): https://www.microsoft.com/en-nz/download/confirmation.aspx?id=30679

**Comment by ejsiron** [comment]
Interesting. I wound up rebuilding that second one as well, as I had nowhere to store a copy of it. NSClient++ installed perfectly on both of the replacements, no vcredist. I'll be certain to try that if I ever encounter this issue again.
Thanks for looking at it!
