### ISSUE TITLE
"!=" still not working in "crit" for 0.4.4.19-x64

### ISSUE THREAD

**Issue by firstrose** [mickem/nscp#291]
I have many xxx.exe in different paths

e.g

C:\path1\xxx.exe              C:\path2\xxx.exe

I use this to detect whether one special xxx.exe started

./check_nrpe -H 192.168.102.71 -c check_process -a "process=xxx.exe" "filter= 'path1' like command_line " "crit=count!=1"

But the result seems odd:

1. path1 stop    
return is :  OK: No processes found|

2. path1 start   
return is:   CRITICAL: xxx.exe=started|

use this command:

./check_nrpe -H 192.168.102.71 -c check_process -a "process=xxx.exe" "filter= 'path1' like command_line " "crit=count=0"

all ok

1.path1  start
return is :   OK: all processes are ok.|'count'=1;0;0

2.path1 stop
return is :   CRITICAL: No processes found|'count'=0;0;0

Another problem is why there is no count in return when != is used.

**Comment by mickem** [comment]
Count is broken in 0.4.x, but fixed in 0.5.x so please try that and let us know...

**Comment by mickem** [comment]
Please reopen this if existing on 0.5.0
