### ISSUE TITLE
CheckCounter - Failed to validate filter see log for details - NSCP-0.4.4.19-Win32

### ISSUE THREAD

**Issue by pabszyk** [mickem/nscp#296]
I have issue with CheckCounter command and version NSCP-0.4.4.19-Win32 and 4.2/4.3:
/usr/lib/nagios/plugins/check_nrpe -H 10.6.24.254 -u -p 5666 -c CheckCounter -a "Counter:localhost=\\PhysicalDisk(_Total)\\Avg. Disk sec/Transfer" ShowAll "MaxWarn=0.2" "MaxCrit=0.3"
Failed to validate filter see log for details

and inside log:

2016-05-04 17:07:47: debug:c:\source\nscp\include\compat.cpp:22: Created command: warn=value>=0.2 crit=value>=0.3 show-all "counter:localhost=\PhysicalDisk(_Total)\Avg. Disk sec/Transfer" perf-config=*(suffix:none)
2016-05-04 17:07:47: debug:c:\source\nscp\include\parsers\filter\modern_filter.cpp:11: Parsing failed of 'value>=0.2' at: .2

but this is working with natural thresholds:
 /usr/lib/nagios/plugins/check_nrpe -H 10.6.27.254 -u -p 5666 -c CheckCounter -a "Counter:localhost=\\PhysicalDisk(_Total)\\Avg. Disk sec/Transfer" ShowAll "MaxWarn=2" "MaxCrit=3"
OK: localhost: 0.0120378|'localhost'=0.01203;2;3

and without thresholds:
 /usr/lib/nagios/plugins/check_nrpe -H 10.6.24.254 -u -p 5666 -c CheckCounter -a "Counter:localhost=\\PhysicalDisk(_Total)\\Avg. Disk sec/Transfer" ShowAll
OK: localhost = 0|'localhostnone'=0;0;0

as i understand there is problem with comma

with version NSCP-0.4.1.102-Win32 it is working like a charm:

/usr/lib/nagios/plugins/check_nrpe -H 10.6.27.254 -u -p 5666 -c CheckCounter -a "Counter:localhost=\\PhysicalDisk(_Total)\\Avg. Disk sec/Transfer" ShowAll "MaxWarn=0.2" "MaxCrit=0.3"
OK: localhost: 0.0124867|'localhost'=0.01248;0.2;0.29999

how to fix it ? please help !

**Comment by mickem** [comment]
Fixed in 0.5.0

**Comment by pabszyk** [comment]
I tried version NSCP-0.5.0.46-Win32.msi and in this version there is no error but counter always show 0 when in version NSCP-0.4.1.102-x64.msi it show correct values.

![image](https://cloud.githubusercontent.com/assets/19189226/16009542/75e47738-317d-11e6-857e-015b668bf44b.png)

**Comment by mickem** [comment]
You need to add type=double for it to work with floating points.

**Comment by box293** [comment]
Do you need type=double for it to collect the data, or is it just required if you use thresholds?

**Comment by mickem** [comment]
type=double is only required if you want to interpret the value as a floating point value...
