### ISSUE TITLE
Windows 2008 Server Reboot required to complete NSClinet installation

### ISSUE THREAD

**Issue by bsivavani** [mickem/nscp#298]
Hi Mickem,

We are doing NSClient 0.4.3.143 agent installation on physical and VM servers. Our environment has Win2k3,2008 and 2012 versions.
During agent installation on few physical servers, server requires reboot to complete the installation. All these servers are installed with Win 2008 OS.
This issue is not facing on other OS versions and Virtual Servers. 

Please let us know how to avoid this server reboot? Please advise if there is any option to enable/disable before NSClient installation.

**Comment by mickem** [comment]
Depends on what the issue is.

There is a network issue which forces a restart but the more common is the service needs to be stopped.
In which case stoping the service usually works.

I.e. net stop nscp

**Comment by bsivavani** [comment]
Hi Mickem,

Without installing NSClient++ how to stop nscp service. We are first time installing NSClient which is forcing me to restart.


Thanks,
Siva vani

**Comment by mickem** [comment]
If nsclient++ is not installed it should not require a reboot...

**Comment by mickem** [comment]
please reopen this with more details if you still have issues
