### ISSUE TITLE
0.5.0.45-x64 - Can't pass arguments with spaces using check_multi

### ISSUE THREAD

**Issue by dannywarren** [mickem/nscp#301]
Hi!  

I'm upgrading some older NSClient++ 3.x installations, and the only thing I can't get working under 4.x/5.x is whitespace handling with "check_multi".

If I'm reading CheckHelpers.cpp correctly, the behavior of "check_multi" is:

1. Each command and all its arguments have to be passed in to "check_multi" as a single string
2. Each command/argument string is then split on the space character, the first list item being the command and the rest being the arguments
3. The split doesn't do any special escape handling or argument grouping

If that is correct, I don't see how passing spaces through "check_multi" is going to work.  Do you have any ideas?  Here is what I've tried...

Vanilla quoting doesn't work:

    check_bar = check_ok message=">$ARG1$<"
    check_foo = check_multi command="check_bar $ARG1$"

    $ ./check_nrpe2 -H localhost -c check_foo -a "This argument has spaces"
    >This<

Single quoting doesn't work:

    check_bar = check_ok message=">$ARG1$<"
    check_foo = check_multi command="check_bar '$ARG1$'"

    $ ./check_nrpe2 -H localhost -c check_foo -a "This argument has spaces"
    >'This<

Escaping the single quotes doesn't work:

    check_bar = check_ok message=">$ARG1$<"
    check_foo = check_multi command="check_bar \'$ARG1$\'"

    $ ./check_nrpe2 -H localhost -c check_foo -a "This argument has spaces"
    Invalid command line: unrecognised option '\'This argument has spaces\'"'

Double quoting doesn't work:

    check_bar = check_ok message=">$ARG1$<"
    check_foo = check_multi command="check_bar "$ARG1$""

    $ ./check_nrpe2 -H localhost -c check_foo -a "This argument has spaces"
    >This<

Escaping the double quotes doesn't work:

    check_bar = check_ok message=">$ARG1$<"
    check_foo = check_multi command="check_bar \"$ARG1$\""

    $ ./check_nrpe2 -H localhost -c check_foo -a "This argument has spaces"
    >"This<

This is what I used to do with the old legacy "CheckMultiple" command, but this doesn't work with the new "check_multi" syntax:

    check_bar = check_ok message=">$ARG1$<"
    check_foo = check_multi command=check_bar "$ARG1$"

    $ ./check_nrpe2 -H localhost -c check_foo -a "This argument has spaces"
    Invalid command line: unrecognised option 'This argument has spaces'

Thanks!

**Comment by mickem** [comment]
Will be fixed in next build

**Comment by dannywarren** [comment]
Thanks for the fast response!  I'll keep an eye out for the next 0.5.0 nightly and re-test the above use cases.
