### ISSUE TITLE
Installing 0.4.4.19

### ISSUE THREAD

**Issue by pleegor** [mickem/nscp#302]
HI, 

I am trying to install 0.4.4.19 on W12R2 and it does not work. I suspect there is an issue with .ini file. When I am using one of the legacy clients everything works. I am wondering if you have an example of a basic .ini file I can use as template.

**Comment by box293** [comment]
Most likely you have not enabled insecure mode.

These steps will work:
http://sites.box293.com/nagios/guides/nrpe/installing-nrpe-client-agent/windows/0-4-x

or

http://sites.box293.com/nagios/guides/nrpe/installing-nrpe-client-agent/windows/0-4-x---creating-nsclient-ini-file

**Comment by pl33g0r** [comment]
thanks @box293 this is really helpful!!!

**Comment by box293** [comment]
Did this fix your problem?

**Comment by mickem** [comment]
Pleas reopen with more details if you still have issues with NSClient++...
