### ISSUE TITLE
Get percentage only in performance data

### ISSUE THREAD

**Issue by rdussin** [mickem/nscp#309]
Hi,

I'm trying to reduce the amount of characters after the pipe because of the nrpe limitation message length (MAX_PACKETBUFFER_LENGTH at 1024...).

My command is actually like this :

check_drivesize -a "drive=*" 'warning=used > 90% and free < 100G' 'critical=used > 93% and free < 80G' exclude='System Reserved' "filter=type in ('fixed')" ignore-unreadable "perf-config=free(ignored:true)"

And i'm trying to just keep the percentage value for used disk, but there is no documentation about the perf-config option. I'm looking for something like this :

"perf-config=free(ignored:true)used data(ignored:true)"

Thanks a lot for your answers.

**Comment by mickem** [comment]
Have a look at the documentation for wiring check where the perf-config option is discusses and let me know anything missing.

https://docs.nsclient.org/manual/checks.html#performance-data-configuration

**Comment by rdussin** [comment]
Thanks for the documentation.

I saw it's impossible to get only the percentage value, we have to choose both unit and percentage or unit only.

Actually to reduce the amount of datas I choose to ignore the percentage (but I don't really had the choice).

Thanks anyway, now i'm sure there is no way to do it :)

**Comment by mickem** [comment]
Only percentages like so:

```
check_drivesize "perf-config=used(ignored:true) used %(ignored:false)"
L        cli CRITICAL: CRITICAL C:\: 431.334GB/452.338GB used
L        cli  Performance data: 'C:\ used %'=95%;80;90;0;100 'D:\ used %'=42%;80;90;0;100 'E:\ used %'=33%;80;90;0;100
```
