### ISSUE TITLE
NSClient 0.4.2.93 – Pb install on W2003 32bits

### ISSUE THREAD

**Issue by cmeschin** [mickem/nscp#31]
Hello

Actually , I use NSClient 0.3.9.323.
Since few month we have some W2012 server’s and I installed 0.4.2.x to monitor them.
I want to update NSClient 0.3.9 to 0.4.2 on other hosts but I have a problem on Windows 2003 32 bits without Service Pack.
I have the message “Le point d’entrée de procédure EncodePointer est introuvable dans le bibliothèque de liaisons dynamique KERNEL32.dll” when i install it.
I haven’t problem on W2003 32bits with SP2
I try to install NSClient 0.4.1.105 on this server and works fine.

regards,
cedric

**Comment by mickem** [comment]
I have just verified that it works on windows 2003 (SP2) as well as XP (SP3) these are the oldest ones I have.
If it is important to get it to work on Windows 2003 without SP2 please reopen this ticket.

I think it is fairly reasonable to request SP:s right?
