### ISSUE TITLE
CheckCounter - always show 0 - nscp64-0.5.0.46

### ISSUE THREAD

**Issue by pabszyk** [mickem/nscp#310]
This issue is directly connected with https://github.com/mickem/nscp/issues/296#issuecomment-222542499 which you already close. When the counter is floatpoint  0.01 it always show 0

**Comment by pabszyk** [comment]
Also CheckFiles change its behavior - i have service:

/usr/local/nagios/libexec/check_nrpe -H $HOSTADDRESS$ -u -p 5666 -c CheckFiles -a path=C:/emailrelay pattern=*email* "filter=creation < -1d" "syntax=%filename%" MaxCrit=1

which check if there i no old undelivered emails in spool and in version NSCP-0.4.1.102-x64 if no old file is fount i have "OK: CheckFile ok" and with version 5 i have "UNKN: No files found" - can you change it to keep compatibility ?

**Comment by mickem** [comment]
You need to add type=double for it to work For checkCounter support for this is added in next 0.5.0 build (works for check_pdh).

As for the other issue there is an option empty-status which you can set to whatever you fancy.

**Comment by pabszyk** [comment]
Yes you have right i can use  type=double and check_pdh and empty-status but type=double + check_pdh and empty-status are not compatible with earlier version of nsclient. I have 500 remote servers which i monitor using one common command. What would you suggest me to do to move between nsclient versions ? Now i stuck on version 0.4.1.102

**Comment by mickem** [comment]
The problem here is that this is something which changed between 0.4.1 and 0.4.2 thus if I change this behavior anyone using the newer version will run into issues instead.

In your case perhaps the best solution is to defined two aliases in both version which works the same and use that?
It depends on what your strategy is for migrating things...

**Comment by pabszyk** [comment]
Thanks for the hint

**Comment by mickem** [comment]
One thought that comes to mind is that the next version (not 0.5.0) will support "custom defaults" then it would be possible to solve it that way I guess. i.e. customizing the defaults (this is planned to make emulating older version simpler)

**Comment by hecko** [comment]
We also came across this issue - with checkcounter such as: 

/usr/lib/nagios/plugins/check_nrpe -H x.x.x.x -p 5666 -c checkcounter -a "Counter=\PhysicalDisk(_Total)\Avg. Disk sec/Transfer" ShowAll MaxWarn=10 MaxCrit=50

Which returns 0 for values which are double typed - actually I dont think this particular counter should ever return zero.

@mickem  - we running 0.4.3.131 so I guess the type=double has not been implemented for this version; however Im happy to test the new release you sugget to get the proper results.

**Comment by hecko** [comment]
OK, I can confirm that my case works with 0.5.0.62 and defining type=double for CheckCounter

Thanks for hints, howewer Im  puzzled why you actually need to define the type of the output variable - what is the reasoning for an additional param?

**Comment by mickem** [comment]
PDH does not really define the types of the counter, so you are not defining the output value but rather how NSClient++ should read it...
