### ISSUE TITLE
check_service does not work at one of the services

### ISSUE THREAD

**Issue by winter1967** [mickem/nscp#313]
Hello,
wie have a service for printers, called "MyQ_ext":

When i stop this service, check_service tells me:

```
check_service service=myQ_ext
L        cli OK: OK: All 1 service(s) are ok.
```

Here the output of the powershell command get-service:

```
PS C:\Program Files\NSClient++> get-service myQ_ext

Status   Name               DisplayName
------   ----               -----------
Stopped  myQ_ext            MyQ EXT
```

Check_service from icinga2 tells me:

```
PS C:\Program Files\ICINGA2\sbin> .\check_service.exe -s myq_ext
SERVICE CRITICAL NOT RUNNING | service=1;;;1;7
```

Here is the version:

```
PS C:\Program Files\NSClient++> .\nscp.exe --version
NSClient++, Version: 0.4.4.19 2015-12-08, Platform: x64
```

It's a windows server 2012 R2 system.

**Comment by mickem** [comment]
Is it the same for all services?

**Comment by winter1967** [comment]
Hallo Michal,
it’s only one service,  at the other services, the check works.



Von: Michael Medin [mailto:notifications@github.com]
Gesendet: Freitag, 8. Juli 2016 06:35
An: mickem/nscp
Cc: Winter, Wolfgang; Author
Betreff: Re: [mickem/nscp] check_service does not work at one of the services (#313)


Is it the same for all services?

**Comment by mickem** [comment]
try adding filter=none

**Comment by mickem** [comment]
Please reopen this if the issue still exists.
