### ISSUE TITLE
Bad formed NSCA host check with last 0.5 version

### ISSUE THREAD

**Issue by mohierf** [mickem/nscp#315]
With former 0.4 version, the NSCA host check was sent for a scheduled task with an alias set to `host_check`. With the same registry configuration, NSClient 0.5 ignores this alias and do not send an host check...

 I did not found anything in the doc that explains if something changed ?

My registry configuration:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\NSClient++\settings\scheduler\schedules\check_alive]
"alias"="host_check"
"command"="check_uptime"
"interval"="30s"
```

**Edit:**
NSCA received from nscp 0.4:
```
 PROCESS_HOST_CHECK_RESULT;vm-win8;2;CRITICAL: uptime: 0:1h, boot: 2016-juil.-19 12:56:48 (UTC)|'uptime'=83s;172800;86400
```
NSCA received from nscp 0.5:
```
PROCESS_SERVICE_CHECK_RESULT;fvc320;host_check;0;OK: uptime: 1w 4d 07:45h, boot: 2016-juil.-08 05:09:36 (UTC)|'uptime'=978352s;172800;86400
```

**Comment by mohierf** [comment]
@mickem : any idea about this ?

**Comment by mickem** [comment]
Sorry, vacation time...

Will look into it in the next few days..

**Comment by mickem** [comment]
A build with this can be found here: https://github.com/mickem/nscp/releases/tag/0.5.0.52

**Comment by mohierf** [comment]
Thanks
