### ISSUE TITLE
NSCA issue

### ISSUE THREAD

**Issue by rioux602** [mickem/nscp#316]
Hello,

I'm trying to use NSCA client/server pair from nscp as I want to secure my connection using SSL/certificates, which the default nagios nsca plugin doesn't support.
I installed nscp on both my Windows server to monitor and my Ubuntu nagios server. I configured the nsca client on Windows, the nsca server on Ubuntu. Information is getting through from Windows to Ubuntu, but there is one part missing. How can I configure the nscp nsca server to write to the nagios.cmd file? I couldn't find the command_file configuration as in the classic nsca plugin or anything similar. I tried with the SimpleFileWriter, but output cannot be formatted to what nagios is expecting. Can you please assist?

**Comment by mickem** [comment]
You use the simple file writer module to do that...

**Comment by rioux602** [comment]
I wasn't able to configure the syntax parameter correctly to get the expected format : 
[<timestamp>] PROCESS_SERVICE_CHECK_RESULT;<host_name>;<svc_description>;<return_code>;<plugin_output>
https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/passivechecks.html

I used this : syntax=PROCESS_SERVICE_CHECK_RESULT;${host};${alias-or-command};${result};${message}

The output is : PROCESS_SERVICE_CHECK_RESULT;;Uptime;OK;OK: uptime: 2w 6d 22:27h, boot: 2016-Jul-19 19:03:09 (UTC)

Here are my issues :
1- Can't output TimeStamp
2- Host is always empty
3- According to the SimpleFileWriter documentation, {status} should be a number

**Comment by mickem** [comment]
are you sending this from nsclient++ or regular NSCA? (I just fixed an issue regarding hostname in last 0.5.0 build).

Anyways will setup a testcase and take a look...

**Comment by rioux602** [comment]
I have nsclient++ on both servers.
Nagios server :  Ubuntu 14.04.5 LTS x64 / NSClient++, Version: 0.5.0.46 2016-05-30, Platform: unknown
Monitored server : Windows Server 2012 Standard x64 / NSClient++, Version: 0.4.4.19 2015-12-08, Platform: x64

I will update NSClient++ to latest version on the Windows server and get back to you.

**Comment by mickem** [comment]
The fixed version can be found here: https://github.com/mickem/nscp/releases/tag/0.5.0.54

**Comment by mickem** [comment]
Forgot to add the config and result I tested with:

Client:
```
[/modules]
CheckHelpers=enabled
Scheduler = 1
NSCAClient=enabled

[/settings/scheduler/schedules/default]
interval=5s
channel=NSCA

[/settings/scheduler/schedules]
test=check_ok

[/settings/scheduler/schedules/host_check]
command=check_ok
alias=host_check

[/settings/nsca/client/targets/default]
host=127.0.0.127
encryption=none
password=mega-secret
```

Server:
```
[/modules]
NSCAServer=enabled
SimpleFileWriter=enabled

[/settings/nsca/server]
encryption=none
password=mega-secret
inbox=file

[/settings/writers/file]
syntax=PROCESS_SERVICE_CHECK_RESULT;${host};${alias-or-command};${result_number};${message}
```

Resulting file is:
```
PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;;0;No message
PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;;0;No message
PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;test;0;No message
PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;test;0;No message
PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;;0;No message
PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;test;0;No message
PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;;0;No message
PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;;0;No message
PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;test;0;No message
PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;test;0;No message
```


Two thoughts that struck me.

* should it not be prefixed with a timestamp?
* Should not host checks be different?

**Comment by rioux602** [comment]
Host checks are different, but I think they still can be achieved by using this syntax :
syntax=PROCESS_HOST_CHECK_RESULT;${host};${result_number};${message}
I'll test this tomorrow and let you know.

I think it would be better to prefix with timestamp. As I understand it, if the Nagios service is stopped for whatever reason, requests will be queued. When Nagios restarts, metrics will make no sense without the timestamp.

**Comment by rioux602** [comment]
Just realized what you meant. I can use only one syntax. So I don't see how I can prefix depending on the check (Host vs Service).

**Comment by mickem** [comment]
New server config:
```
[/modules]
NSCAServer=enabled
SimpleFileWriter=enabled

[/settings/nsca/server]
encryption=none
password=mega-secret
inbox=file

[/settings/writers/file]
service-syntax=${epoch} PROCESS_SERVICE_CHECK_RESULT;${host};${alias-or-command};${result_number};${message}
host-syntax=${epoch} PROCESS_HOST_CHECK_RESULT;${host};${result_number};${message}
```


Yields:
```
1470953735 PROCESS_HOST_CHECK_RESULT;mime-g501jw;0;No message
1470953736 PROCESS_HOST_CHECK_RESULT;mime-g501jw;0;No message
1470953736 PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;test;0;No message
1470953737 PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;test;0;No message
1470953738 PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;test;0;No message
1470953738 PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;test;0;No message
1470953740 PROCESS_HOST_CHECK_RESULT;mime-g501jw;0;No message
1470953740 PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;test;0;No message
1470953742 PROCESS_HOST_CHECK_RESULT;mime-g501jw;0;No message
1470953742 PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;test;0;No message
1470953743 PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;test;0;No message
1470953744 PROCESS_SERVICE_CHECK_RESULT;mime-g501jw;test;0;No message
1470953745 PROCESS_HOST_CHECK_RESULT;mime-g501jw;0;No message
```


Let me know if there is anything else ...

**Comment by mickem** [comment]
(new build out in a bit)

**Comment by rioux602** [comment]
After some tests, I though the timestamp was optional because of the brackets, but it seems like the brackets and the timestamp are needed.

Exemple of how I was able to make it work in Nagios :
echo "[1470947468] PROCESS_SERVICE_CHECK_RESULT;myserver;Uptime;OK;test" > /usr/local/nagios/var/rw/nagios.cmd

**Comment by mickem** [comment]
Then I guess this should work right?

``
service-syntax=[${epoch}] PROCESS_SERVICE_CHECK_RESULT;${host};${alias-or-command};${result_number};${message}
host-syntax=[${epoch}] PROCESS_HOST_CHECK_RESULT;${host};${result_number};${message}
```

**Comment by rioux602** [comment]
Yes it should. Let me get the Ubuntu build installed and I'll get back to you with my test results.

**Comment by rioux602** [comment]
Almost there! One last thing. The timestamp seems to not be in UTC.

I just got this : 1471010449, which translates to 08/12/2016 @ 14:00 (UTC)
But it is now 08/12/2016 @ 18:00 (UTC)

Both my servers are set to EDT (-4). All related settings set to default in nagios.cfg.

**Comment by mickem** [comment]
As long as both servers are in the same timezone should be good right?
Unless nagios translates from utc to some local time?

But no not sent in utc...

**Comment by mickem** [comment]
timezones are a pain so I try not to involve them...

**Comment by rioux602** [comment]
Just to confirm I was able to install the latest version and confirm the timestamp is now OK.

Thanks!
