### ISSUE TITLE
 CHECK_NRPE: Invalid packet type received from server.  

### ISSUE THREAD

**Issue by trgrassijr55** [mickem/nscp#318]
NSClient++ 0.4.3.143 2015-04-29  

Installed on a Windows 2003 Server 32 BIT

get this error  CHECK_NRPE: Invalid packet type received from server. 

I run a Nagios Core 4.1.1  

this is the config file entry

define service {
        host_name                       TGCS002
        service_description             Check All Service
        check_command                   check_nrpe!check_service! -a CheckAll "filter=name not like 'clr_optimization_v4.0.30319'" exclude=SysmonLog
        servicegroups                   AllServices
        check_interval                  1
        use                             generic-service
}

I have this on all my other servers and they all work fine 

All other servers are 64 bit and use 
NSClient++ 0,4,1,73 2012-12-17 

I needed to upgrade the NSCLIENT on this computer because the 32 bit machines had problems with other define services I made.

I posted this on the Nagios Forum but they had no answers only suggested I post on this site.

I saw they other post for this but it did not seem to fit my issue

Any ideas or suggestions 

Thank you
Tom

**Comment by mickem** [comment]
Sounds like the insecure option during the installer.

http://docs.nsclient.org/faq/#what-is-insecure-mode
