### ISSUE TITLE
check_eventlog - not like 

### ISSUE THREAD

**Issue by ghost** [mickem/nscp#32]
Hi All

We use check_eventlog, and now we have a problem with the syntax. We don't know what all of failures it can be

NSClient++ 0.4.1.102 - 64bit

This is the Syntax it goes:
message like 'HH6' 
message not like 'HH6' 

<br>

This is the positiv check to grep the current failure that we want exclude

``` bash
./check_nrpe -H HOST -c CheckEventLog -a file=application MaxWarn=2 MaxCrit=2 "filter=source like 'TCLKD' AND type IN ('error') AND message like 'HH6' AND generated > -1h" truncate=800 unique descriptions "syntax=%id%: %message% (%count%)"
```

Result: The ckeck found the error with paramenter "like 'HH6'"

```
15001: RFC Server can't register at gateway, RFC function: RfcAccept RFC error string
 KEY=RFC_IO5 STATUS=CODE=CM_PRODUCT_SPECIFIC_ERROR STATUS=??? DATA=??? 
ID=??? MESSAGE=Connect to DAT gateway failed Connect_PM  TPNAME=WHPC-XI9s.TPHA.HH6, 
GWHOST=isla919, GWSERV=7707  LOCATION    CPIC (TCP/IP) on local host ERROR       partner 
'172.32.14.9:7707' not reached TIME        Thu Sep 11 10:27:07 Especially check lines 
GWHOST= and GAWSERV= . (1)|'eventlog'=1;2;2directory).
```

<br><br>

This is the negativ check to exclude the HH6 message

``` bash
./check_nrpe -H HOST -c CheckEventLog -a file=application MaxWarn=2 MaxCrit=2 "filter=source like 'TCLKD' AND type IN ('error') AND message not like 'HH6' AND generated > -1h" truncate=800 unique descriptions "syntax=%id%: %message% (%count%)"
```

Verry strange output:

```
settings. Check trace output. Check user acount se...|'eventlog'=3;2;2of wrong  from the  start.initializing mail DLL"
```

<br><br>

This is the check with a "not like Text-that-is-not-EXIST" to check if the plugin works

``` bash
./check_nrpe -H HOST -c CheckEventLog -a file=application MaxWarn=2 MaxCrit=2 "filter=source like 'TCLKD' AND type IN ('error') AND message not like 'Text-that-is-not-EXIST' AND generated > -1h" truncate=800 unique descriptions "syntax=%id%: %message% (%count%)"
```

And verry good, it works, it show's me only the HH6, failure because there is no "Text-that-is-not-Exist" Error on the Event Log.

```
15001: RFC Server can't register at gateway, RFC function: RfcAccept RFC error string
KEY=RFC_IO5 STATUS=CODE=CM_PRODUCT_SPECIFIC_ERROR STATUS=??? DATA=???
ID=??? MESSAGE=Connect to DAT gateway failed Connect_PM  TPNAME=WHPC-XI9s.TPHA.HH6,
GWHOST=isla919, GWSERV=7707  LOCATION    CPIC (TCP/IP) on local host ERROR       partner
'172.32.14.9:7707' not reached TIME        Thu Sep 11 10:27:07 Especially check lines
GWHOST= and GAWSERV= . (1)|'eventlog'=1;2;2directory).
```

<br>

Any Idea?
Thanks

**Comment by gitpumawit** [comment]
Thanks, i didn’t find time to test .. sorry

[Würth ITensis AG]

Marcel Puschnig
ICT System Manager / Network Engineer
Aspermontstrasse 1
CH - 7000 Chur
Telefon:
Fax:
E-Mail:
Webseite:

+41 81 558 31 13
+41 81 558 34 13
marcel.puschnig@wuerth-itensis.com
www.wuerth-itensis.com


Von: Michael Medin [mailto:notifications@github.com]
Gesendet: Montag, 5. Januar 2015 21:16
An: mickem/nscp
Cc: Puschnig Marcel
Betreff: Re: [nscp] check_eventlog - not like (#32)


Please reopen if this is still a problem in 0.4.3
