### ISSUE TITLE
check_drivesize drive "S:"

### ISSUE THREAD

**Issue by itsul** [mickem/nscp#321]
Hi,

in the check_drivesize is a bug while using it without any argument. There is always a drive "S:" available which does not exist! Tested it on two different windows systems. If you use the argument "drive=all-volumes" (the S: drive is not shown, that is correct).

[root@xx plugins_app]# ./check_nrpe -H 172.xx.xxx.28 -c check_drivesize
OK All 2 drive(s) are ok|'C:\ used'=80.74133GB;190.33671;214.1288;0;237.92089 'C:\ used %'=34%;80;90;0;100 'S:\ used'=19.52693GB;31.58671;35.53505;0;39.48339 'S:\ used %'=49%;80;90;0;100
[root@xx plugins_app]# ./check_nrpe -H 172.xx.xxx.28 -c check_drivesize -a drive=C:
OK All 1 drive(s) are ok|'C: used'=80.74133GB;190.33671;214.1288;0;237.92089 'C: used %'=34%;80;90;0;100
[root@xx plugins_app]# ./check_nrpe -H 172.xx.xxx.28 -c check_drivesize -a drive=S:
OK All 1 drive(s) are ok|'S: used'=19.52693GB;31.58671;35.53505;0;39.48339 'S: used %'=49%;80;90;0;100
[root@xx plugins_app]# ./check_nrpe -H 172.xx.xxx.28 -c check_drivesize -a drive=all-volumes
OK All 1 drive(s) are ok|'C:\ used'=80.74208GB;190.33671;214.1288;0;237.92089 'C:\ used %'=34%;80;90;0;100

**Comment by mickem** [comment]
Are you sure you don't have a drive s?
I dont have any drive S on my test machines...

```
L        cli CRITICAL: CRITICAL C:\: 449.78GB/452.338GB used
L        cli  Performance data: 'C:\ used'=449.78005GB;361.8706;407.10443;0;452.33826 'C:\ used %'=99%;80;90;0;100 'D:\ used'=208.04415GB;372.6039;419.17939;0;465.75487 'D:\ used %'=45%;80;90;0;100 'E:\ used'=166.61972GB;372.60546;419.18114;0;465.75683 'E:\ used %'=36%;80;90;0;100
```

**Comment by itsul** [comment]
Yes I am sure. On the computer of my colleague the drive S: where also available.

![hdd](https://cloud.githubusercontent.com/assets/12328177/18539606/ec98fae0-7b18-11e6-9483-d779eb5c1326.PNG)

**Comment by mickem** [comment]
And it is not a mapped networkdrive or some such?

You can always change the syntax to see some more information about the drive...

**Comment by itsul** [comment]
There is no drive mapped with letter S only with Y and Z.

**Comment by mickem** [comment]
Most likely the drive you were seeing is some subst/network/* drive... nsclient++ wont invet drives which does not exist.
