### ISSUE TITLE
check_uptime warn and crit perameters ignored

### ISSUE THREAD

**Issue by troylb** [mickem/nscp#323]
Hello,

I just upgraded one of our machines to use version 0.5.0.60 2016-09-05 and I am able to get all the various check commands to work correctly with the exception of check_uptime. I am using check_nrpe -H <IP> -p <PORT> -c check_uptime "warning=uptime <1h" "critical=uptime <30m"

It does not matter what I put in the warning and critical fields, it completely ignores them. However on the server, I can run nscp.exe test and then run the same check_uptime command and it works correctly. 

CLI of our nagios server:
check_nrpe -H 66.181.29.34 -p 11850 -c check_uptime "warning=uptime < 1h" "critical=uptime < 30m"
CRITICAL: uptime: 11:36h, boot: 2016-09-08 06:59:51 (UTC)|'uptime'=41812s;172800;86400

CLI of Windows server nscp:
check_uptime "warning=uptime <1h" "critical=uptime <30m"
L        cli OK: OK: uptime: 13:16h, boot: 2016-09-08 06:59:51 (UTC)
L        cli  Performance data: 'uptime'=47766s;3600;1800

Has anyone else had this issue and is there a fix for it?

**Comment by mickem** [comment]
I recently fixced an issue related to rendering.

From what I can see the uptime is working for me:

```
# Less then 4 hours is ok (value is 17.xhours)
check_uptime "warn=uptime < 4h" crit=none
L        cli OK: OK: uptime: 17:41h, boot: 2016-09-15 01:33:36 (UTC)

# Less then 24 hours is warning (value is 17.xhours)
check_uptime "warn=uptime < 24h" crit=none
L        cli WARNING: WARNING: uptime: 17:41h, boot: 2016-09-15 01:33:37 (UTC)

# Less then 17 hours is ok (value is 17.xhours)
check_uptime "warn=uptime < 17h" crit=none
L        cli OK: OK: uptime: 17:41h, boot: 2016-09-15 01:33:36 (UTC)

# Less then 18 hours is warning (value is 17.xhours)
check_uptime "warn=uptime < 18h" crit=none
L        cli WARNING: WARNING: uptime: 17:41h, boot: 2016-09-15 01:33:36 (UTC)
L        cli  Performance data: 'uptime'=63710s;64800;0
```

**Comment by garnier-quentin** [comment]
I have also an issue with uptime and version 0.5.62. It doesn"t work if i used:
```
-c check_uptime -a "warning=" "critical="
Failed to validate filter see log for details: Warning expression is not valid
```

It should work without expression no ?

**Comment by mickem** [comment]
warning=none if you want to disable the warning/critical...

**Comment by garnier-quentin** [comment]
ok thanks

**Comment by tyler-earls** [comment]
Having a similar issue.  NSClient 0.5.0.62 x64 client OS Server 2012R2.  From nagios server CLI it is OK but Nagios does not warn or crit;

check_nrpe -H <IP> -c Check_Uptime  "warning=uptime>7d" "critical=uptime>14d"
warning(uptime: 1w 1d 03:41h, boot: 2016-12-06 17:33:02 (UTC))|'uptime'=704477s;604800;1209600

Nagios config: check_command check_nrpe!Check_Uptime! "warn=uptime > 7d" "crit=uptime >14d"

Nagios status info:OK: uptime: 1w 1d 03:42h, boot: 2016-12-06 17:33:03 (UTC)
Nagios performance data: 'uptime'=704522s;172800;86400

No warning or crit, any ideas?

**Comment by mickem** [comment]
But thats right right?

You want a warning if the server has been up more then 7 days and a critical if it has been up more then 14 days.
And after 8 days you get a warning in the check_nrpe command right?

The Nagios command has the wrong bounds (172800 seconds which is the default 2 days).
Check your escape syntax or better yet switch to the "safe syntax:

```
 check_command check_nrpe!Check_Uptime! "warn=uptime gt 7d" "crit=uptime gt 14d"
```

**Comment by mickem** [comment]
Please reopen this if you still have issues...
