### ISSUE TITLE
Cli: nscp web password set=... does not work

### ISSUE THREAD

**Issue by dnsmichi** [mickem/nscp#324]
I'm trying to set a password for the web server only. Thus I am failing on the syntax.

Running the command as administrator in cmd.exe does nothing - it just shows the help text again.
`nscp web install` for instance works fine. Looking at the source code I haven't found much differences for `install` and `password`. My current workaround is to manually editor the nsclient.ini configuration file.

Using the cli command isn't documented (at least not inside the webserver documentation), I've just looked into existing blog posts and forum questions asked.

Thanks for any hints/docs! :)

```
c:\Program Files\NSClient++>nscp web password set=icinga --debug
L     client Extra options: password
L     client Extra options: set=icinga
L     client Module: WEBServer
L     client Command:
L     client Extra Query:
L     client Mode: 3
L     client Boot: 0
L     client Load All: 0
L     client Arguments: password, set=icinga
D       core NSClient++ 0.5.0.62 2016-09-14 x64 Loading settings and logger...
D       core Settings not ready so we cant lookup: base-path
D       core Settings not ready so we cant lookup: exe-path
D   settings Boot.ini found in: c:\Program Files\NSClient++/boot.ini
D       core Settings not ready so we cant lookup: shared-path
D   settings Activating: ini://${shared-path}/nsclient.ini
D   settings Creating instance for: ini://${shared-path}/nsclient.ini
D       core Settings not ready so we cant lookup: shared-path
D   settings Loading: c:\Program Files\NSClient++/nsclient.ini
D       core NSClient++ 0.5.0.62 2016-09-14 x64 booting...
D       core Booted settings subsystem...
D       core On crash: restart: NSCP
D       core Archiving crash dumps in: c:\Program Files\NSClient++/crash-dumps
D       core c:\Program Files\NSClient++/modules\WEBServer.dll.dll
D       core adding c:\Program Files\NSClient++/modules\WEBServer.dll
D       core Loading plugin: WEBServer
D       core NSClient++ - 0.5.0.62 2016-09-14 Started!
D       core Found module: WEBServer...
D       core Attempting to stop all plugins
D       core Stopping all plugins
D       core Unloading plugin: WEBServer...
D       core Stopping: COM helper
D       core Stopping: Settings instance
  help                 Show help.
  set=ARG              Set the new password
  display              Display the current configured password
  only-web             Set the password for WebServer only (if not specified
                       the default password is used)
```

Program version: (Windows 10 latest, x64)

```
c:\Program Files\NSClient++>nscp --version
NSClient++, Version: 0.5.0.62 2016-09-14, Platform: x64
```

**Comment by mickem** [comment]
```
$ nscp web password -- --set icinga
Password updated successfully, please restart nsclient++ for changes to affect.
```


I will remove the need for the "double --" in the next version (BTW)

**Comment by dnsmichi** [comment]
Ah. I would've never found it, thanks for the quick response :)

**Comment by mickem** [comment]
I thought it liested that command in the "i forgot my password" dialog in the web ui?

**Comment by dnsmichi** [comment]
Oh. I would've never clicked that until you pointed me there. Guess I am more of the user who searches docs and google before looking at the obvious ;) 

![nsclient_web_password_help](https://cloud.githubusercontent.com/assets/382049/18632641/bf17de98-7e78-11e6-98c7-50282f75b54d.PNG)

I guess the documentation requires an update, not sure about its format though. Looks like asciidoc (?).

**Comment by mickem** [comment]
the docs? it is restructured text (some python(?) md alternative thingy).
Pretty odd and something I really regret this links are very complicated to maintain and the syntax is terrible...
So probably should swap over to md or some such...

**Comment by mickem** [comment]
Fixed so --set works without leading --
