### ISSUE TITLE
Return buffer to small to handle this command.

### ISSUE THREAD

**Issue by rajind2** [mickem/nscp#327]
Sorry for raising an issue for old version of NSClient. I am using NSClient++ - 0.3.8.76 2010-05-27 and 0.3.9.328 2011-08-16 in two different systems.

I am using a Powershell (PS) Script to check text within a file present in a folder. The command that is injected through NSC.ini is

_nrpe_backup=cmd /c echo scripts\check_tsm_backup.ps1; exit ($lastexitcode) | powershell.exe -command -_

I am using Centreon v2.6.6 with Centreon Engine 1.4.13 on CentOS to use check_nrpe command and subsequently running the PS script in the local system. The Centreon worked for some days with the script and gave return value as desired. 

My problem is now for last few days it shows -

_UNKNOWN: Return buffer to small to handle this command._

Being very new to these systems, I am surprised how monitoring system has stopped working, and what could be the reason behind this error.

One more thing when I inject the NRPE handler "nrpe_backup" through NSClient++ (x64,test) menu, the script runs very well in the system. 
![image](https://cloud.githubusercontent.com/assets/16461929/18739161/37f03124-80bf-11e6-86ee-c7c26221b5e4.png)

But when I execute through Centreon system it have me the "return buffer to small to handle this command" error.
![image](https://cloud.githubusercontent.com/assets/16461929/18739212/a4ff270c-80bf-11e6-8a10-98e70dbc615d.png)

Can someone help me on this, I am not sure if this is NSClient++ issue or Centreon issue. If needed I can provide more details.

**Comment by mickem** [comment]
0.3.9 and 0.3.8 are very very old, and the internals has many limits on payload length which has since been resolved.
