### ISSUE TITLE
check_uptime: incorrect result if uptime > 49,7d

### ISSUE THREAD

**Issue by WRatzka** [mickem/nscp#328]
- seen in version 0.4.4.23 on Win32

**Comment by WRatzka** [comment]
This looks as if millisecond time values are crammed into int32 variables somewhere.

**Comment by mickem** [comment]
This should be resolved in 0.5.0 I think...

**Comment by WRatzka** [comment]
I tried with version 0.5.0.65 (Win32) and the bug seems to be still there.
Kind regards
Wolfgang Ratzka

**Comment by mickem** [comment]
Can someone provide an example of a wrong one?

This is what I get myself:

```
check_uptime
L        cli OK: OK: uptime: 9w 3d 01:44h, boot: 2016-09-26 15:19:09 (UTC)
L        cli  Performance data: 'uptime'=5708663s;172800;86400
```

**Comment by mickem** [comment]
Please reopen if you can resproduce this

**Comment by WRatzka** [comment]
It seems to work OK on AMD64 but I can reproduce it on x86:
```
D       core NSClient++ 0.5.1.42 2017-08-20 w32 Loading settings and logger...
(...)
D        cli Enter command to execute, help for help or exit to exit...
check_uptime
L        cli OK: OK: uptime: 2d 18:34h, boot: 2017-08-20 20:56:36 (UTC)
L        cli  Performance data: 'uptime'=239652s;172800;86400
```
whereas wmic gives us:
```
C:\Program Files\NSClient++>wmic OS get LastBootUpTime
LastBootUpTime
20170513125048.109375+120
```

**Comment by ninioperdido** [comment]
Hi! I can reproduce this bug using 0.5.2.33 on 32B Windows 2003R2.
check_uptime:
```
check_uptime
L        cli OK: OK: uptime: 3d 03:9h, boot: 2018-01-19 10:00:14 (UTC)
L        cli  Performance data: 'uptime'=270576s;172800;86400
```

Wmic OS get LastBootUpTime:
```
C:\Program Files\NSClient++>  wmic OS get LastBootUpTime
LastBootUpTime
20170515164244.680270-240
```

**Comment by mickem** [comment]
The "64 bit function" is only available from windows 2008 and vista so on older OS:es the value will be capped at 47 days...

**Comment by mickem** [comment]
For details see this page: https://msdn.microsoft.com/en-us/library/windows/desktop/ms724411%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396
