### ISSUE TITLE
NRDP Client no longer sends a token from .ini file

### ISSUE THREAD

**Issue by segesmac** [mickem/nscp#331]
Was trying out version 0.5.0062 with the intention of using NRDP over SSL.  However, it wouldn't work over HTTP or SSL - after sniffing the http traffic with wireshark, I found it was going to the correct server and address, but the token is always empty.  Here's my .ini settings relevant to this feature:
[/settings/NRDP/client/targets/default]
address = http://ip.address.here.now/nrdp/
timeout = 30
token = mytoken

I've tried using password = mytoken, key = mytoken, and token = mytoken.  I should also mention I'm running this through Scheduler.

Anyway - the POST goes to the correct address (/nrdp/) but the end of the body is always:
`&cmd=submitcheck&token=`

The response from the server is:
`<status>-1</status> <message>NO TOKEN</message>`

**Comment by mickem** [comment]
Looks right, and I recently verified the NRDP over ssl so it should work...

Could you post the trace log (should give the payload from NSCLient++, please remember to obfuscate the token in the log)

**Comment by aaronpollock** [comment]
I have the same issue - the checks are being submitted properly, but there is no token being sent.

**Comment by mickem** [comment]
Sorry, you are all correct. This will be fixed in the next nightly build...
