### ISSUE TITLE
[check_cpu] Add min/max value in perfdata

### ISSUE THREAD

**Issue by garnier-quentin** [mickem/nscp#334]
Hi Michael,

Could you add the min/max value on perfdata ? cpu=value;warn;critical;0;100;

Thanks a lot

**Comment by mickem** [comment]
for %:ages there is no need to have max/min as the max and minimum is pretty obvious (this is as per the perf data specification I think...
I.e. the tool picking them up should understand that unit=% means max is 100...

// Michael Medin
