### ISSUE TITLE
send to graphite

### ISSUE THREAD

**Issue by sorin2343** [mickem/nscp#335]
Hi 
Can I have a configuration example ?
How can I verify that the metrics are sent to graphite server ?
nscp send data by udp or tcp ?

**Comment by mickem** [comment]
Sure, assuming your graphite server is 192.168.0.1:2003
```
[/modules]

GraphiteClient = enabled
CheckSystem = enabled
CheckDisk = enabled

[/settings/graphite/client/targets/default]
address=192.168.0.1:2003
```

Will give you some basic metrics in graphite...

And it only support tcp (carbon if i recall correctly) currently but feel free to request others.

Depending on what you want to send there are multiple ways to go from here...


// Michael Medin
