### ISSUE TITLE
[Check_drivesize] Option to see mouted drives only

### ISSUE THREAD

**Issue by holytoutant** [mickem/nscp#336]
Hi,

I just installed the latest version of NSClient++ (0.5.0062) and I find myself blocked at a point where I need to exclude system drives, but can't seem to achieve it.

Here is the result of check_drivesize:
L        cli OK: OK All 7 drive(s) are ok
L        cli  Performance data: 'A:\ used'=0B;0;0;0;0 'C:\ used'=21.36584GB;47.7
2499;53.69062;0;59.65624 'C:\ used %'=35%;79;89;0;100 'D:\ used'=593.1697GB;643.
99921;724.49911;0;804.99902 'D:\ used %'=73%;79;89;0;100 'E:\ used'=117.86207GB;
819.09843;921.48573;0;1023.87304 'E:\ used %'=11%;80;90;0;100 'F:\ used'=0B;0;0;
0;0 'Z:\ used'=21.7495GB;51.99921;58.49911;0;64.99902 'Z:\ used %'=33%;79;89;0;1
00 '\?\Volume{cb89ee52-532b-11e6-80ba-806e6f6e6963}\ used'=277.95312MB;279.9968
7;314.99648;0;349.99609 '\?\Volume{cb89ee52-532b-11e6-80ba-806e6f6e6963}\ used
%'=79%;79;89;0;100

I would like to exclude the following drives:
'\?\Volume{cb89ee52-532b-11e6-80ba-806e6f6e6963}\ used'=277.95312MB;279.9968
7;314.99648;0;349.99609
'\?\Volume{cb89ee52-532b-11e6-80ba-806e6f6e6963}\ used
%'=79%;79;89;0;100

I saw an issue opened last year adding the option "mounted", but the option, as written in the issue #147 and #149, it does not work. Here is the result:

check_drivesize mounted
L        cli Long message
UNKNOWN: Invalid command line: unrecognised option 'mounted'
help                                                    Show help screen (this screen)
help-pb                                         Show help screen as a protocol buffer payload
show-default                                            Show default values fora given command
help-short                                              Show help screen (shortformat).
debug                                           Show debugging information in the log
show-all                                                Show debugging information in the log
filter=                                         Filter which marks interesting items.
warning=used > 80%                                      Filter which marks items which generates a warning state.
warn=                                           Short alias for warning
critical=used > 90%                                     Filter which marks items which generates a critical state.
crit=                                           Short alias for critical.
ok=                                                     Filter which marks items which generates an ok state.
empty-state=unknown                                     Return status to use when nothing matched filter.
perf-config=                                            Performance data generation configuration
top-syntax=${status} ${problem_list}                    Top level syntax.
ok-syntax=%(status) All %(count) drive(s) are ok        ok syntax.
empty-syntax=%(status): No drives found         Empty syntax.
detail-syntax=${drive_or_name}: ${used}/${size} used    Detail level syntax.perf-syntax=${drive_or_id}                              Performance alias syntax
drive=                                          The drives to check.
ignore-unreadable                                       Ignore drives which arenot reachable by the current user.
magic=                                          Magic number for use with scaling drive sizes.
exclude=                                                A list of drives not tocheck
total                                           Include the total of all matching drives

**Comment by mickem** [comment]
Are you sure about the version?
This was added recently in 0.5.0 it is (by the way) the default behavior in 0.5.0

```
check_drivesize mounted
L        cli CRITICAL: CRITICAL C:\: 432.838GB/452.338GB used
L        cli  Performance data: 'C:\ used'=432.83809GB;361.8706;407.10443;0;452.33826 'C:\ used %'=96%;80;90;0;100 'D:\ used'=264.59458GB;372.6039;419.17939;0;465.75487 'D:\ used %'=57%;80;90;0;100 'E:\ used'=93.38544GB;372.60546;419.18114;0;465.75683 'E:\ used %'=20%;80;90;0;100
```

**Comment by mickem** [comment]
If you still have this issue please reopen
