### ISSUE TITLE
NSClient question - Service Timeout (Service check timed out)

### ISSUE THREAD

**Issue by rel0aded0ne** [mickem/nscp#337]
Hello, i have a question about my NSClient version.

Im using v0.3.5.1 and im wondering why the timeouts are not working. 
i wrote a script which runs more than 3 minutes but after 60 seconds im getting a critical
Error (Service check timed out). 

NSC.INI:

[External Script]
;# COMMAND TIMEOUT
;  This specifies the maximum number of seconds that the NRPE daemon will allow plug-ins to finish executing before killing them off.
command_timeout=360

[NRPE]
;# COMMAND TIMEOUT
;  This specifies the maximum number of seconds that the NRPE daemon will allow plug-ins to finish executing before killing them off.
command_timeout=360

As you can see, i increased the timeout in the NSC.ini on the machine to 6 minutes but the timeout is not working. Is it possible that the function is not implemented in my version of the NSClient?

Thanks for your help!

**Comment by box293** [comment]
If you're using Nagios then it's most likely the nagios global timeout you're running into.

https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/configmain.html
service_check_timeout=
host_check_timeout=
