### ISSUE TITLE
WEBServer raw output?

### ISSUE THREAD

**Issue by mintsoft** [mickem/nscp#338]
Hello,

We are attempting to replace our current check_nrpe checks with something using the new REST API on the WEBServer module. This would be much easier if the webserver had a setting to be able to get the raw output (i.e. `OK: CPU load is ok.|'total 5m'=15%;80;90 'total 1m'=17%;80;90 'total 30s'=18%;80;90`) from the check without having to re-concatenate the output from the `perf` block ourselves. I was thinking that the best solution might be an `raw_output` property on the `payload` property?

I think it would be easier for people to convert their existing checks that way 👍 

Thanks,
Rob

**Comment by mickem** [comment]
Sounds reasonable...

**Comment by mickem** [comment]
This is available in 0.5.2 via the new rest api

**Comment by mintsoft** [comment]
Awesome, I'll check it out on monday :)

**Comment by mintsoft** [comment]
@mickem Actually what version is that available in? I've just tested the output from `0.5.2.35` which I have installed and within payload there is still only `message` and `perf`, `result` only contains "OK". 
I can't see the full raw command output anywhere:

```
curl --header 'Password: password' --insecure https://server:8443/query/alias_disk;
{"header":{"source_id":""},"payload":[{"command":"checkdrivesize","lines":[{"message":"OK All 2 drive(s) are ok","perf":[{"alias":"C:\\ free","float_value":{"critical":6.8061521528288722,"maximum":136.12304306030273,"minimum":0.00000000000000000,"unit":"G","value":123.01979827880859,"warning":13.612304305657744}},{"alias":"C:\\ free %","float_value":{"critical":5.0000000000000000,"maximum":100.00000000000000,"minimum":0.00000000000000000,"unit":"%","value":90.000000000000000,"warning":10.000000000000000}},{"alias":"D:\\ free","float_value":{"critical":93.099902153015137,"maximum":1861.9980430603027,"minimum":0.00000000000000000,"unit":"G","value":1105.7679824829102,"warning":186.19980430603027}},{"alias":"D:\\ free %","float_value":{"critical":5.0000000000000000,"maximum":100.00000000000000,"minimum":0.00000000000000000,"unit":"%","value":59.000000000000000,"warning":10.000000000000000}}]}],"result":"OK"}]}
```

**Comment by mickem** [comment]
You need to use the new rest api documented here: https://docs.nsclient.org/api/rest/queries/#command-execute_nagios

**Comment by mintsoft** [comment]
@mickem Ah yes I see; thanks!
