### ISSUE TITLE
CHECK_NRPE Socket timeout after 10 seconds

### ISSUE THREAD

**Issue by kyungsookim** [mickem/nscp#340]
Hi, 

There are messages on Centreon 2.4.1 
CHECK_NRPE Socket timeout after 10 seconds
Is there any measure to fix this?
This messages are shown frequently but now constantly.

**Comment by mickem** [comment]
Which version of nsclient++ is it?

**Comment by kyungsookim** [comment]
Centreon 2.4.1
nscp-0.4.4.23-win32.msi

**Comment by mickem** [comment]
Ok,

Usually timeouts are related to invalid configuration, especially if they are intermittent.
Unfortunately there are a number of timeouts involved (see link below) and can thus be a bit of work to get right but in your case the timeout your looking at is most likely the -t for check_nrpe

This is assuming the script and/or check your running is "slow" i.e. takes time.
If that is not the case we need to check the nsclient++ logs and see if there are anything there which can point to a network issue...

http://docs.nsclient.org/faq/#timeout-issues

**Comment by mickem** [comment]
please reopen this if you still have issues
