### ISSUE TITLE
Windows server that has two NICs

### ISSUE THREAD

**Issue by borisv1979** [mickem/nscp#345]
Hi,
i'm using latest version of NSCP on Windows Server 2012 that has two physical network cards.
Is it possible to tell NSCP to only listen on specific physical network interface ?

**Comment by mickem** [comment]
Yes, there is a bind to option you can set: https://docs.nsclient.org/reference/client/NRPEServer.html#NRPEServer./settings/NRPE/server.bind to

**Comment by mickem** [comment]
please reopen this if you have further issues
