### ISSUE TITLE
[Scheduler] Questions about number of threads, concurrency of scheduler tasks 

### ISSUE THREAD

**Issue by Sims24** [mickem/nscp#347]
Hello, 

I'm actually using 0.4.3 and 0.5 NSClient version, just to be sure that I understand well what I've read here https://docs.nsclient.org/reference/generic/Scheduler.html and in the part NSClient / NSCA of the documentation.

- How could I avoid my scheduled and passive tasks to run simultaneously ? 
- Is setting thread option to 1 is the solution or am I totally wrong with this  ? 
- Are you aware of any tweaks to avoid this ? 

Sorry just to have a better idea of scheduler internals way of working. 
Thanks,

**Comment by mickem** [comment]
What are you trying to achieve?

But in theory one thread will only run one task so that ought to work.You can also use "cron schedule statements" in which case you can se them to run at different times I guess...
But please do tell me what your trying to achieve and I can perhaps come with a better idea...

**Comment by Sims24** [comment]
Hi @mickem ,

Thanks for your answer, I think you gave me the infos I need to understand better schedules. 

With 0.4.3 and 0.5, could you confirm that with the configuration below, schedule1 and schedule2 should never run in parallel ? Of course duration / timeout of the two tasks is around 1 or 2 minutes.

```
[/modules]
Scheduler = 1
NSCAClient=1

[/settings/scheduler]
threads=1

[/settings/scheduler/schedules/default]
interval=5m

[/settings/scheduler/schedules]
schedule1=do_one_thing.bat
schedule2=do_another_thing.bat
```

Thanks,

**Comment by mickem** [comment]
Not sure about guaranteeing it.

But it will starts 1 thread which will process work, and then sleep till the next job is available.
If they overlap you might get error messages about jobs running to late though.

But if you need a strong guarantee I would probably much rather create a script which runs them in sequence. That is "simpler"...

// Michael Medin

**Comment by mickem** [comment]
Just looked at this and the watchdog will create more threads (up to 10) if the tasks are executed slowly so this is probably not a good strategy...

**Comment by Sims24** [comment]
Ok thanks for digging around and your lights !
