### ISSUE TITLE
Check_WMI formatting performance data

### ISSUE THREAD

**Issue by wojtek-dit** [mickem/nscp#35]
Hello.
I would like to use check_WMI to check some performance counters. Please don't suggest using check_pdh - I will report my problems with it in another issue. 
The check runs fine and returns correct values but I am unable to configure the performance output. If for example I ask for avg disk queue length od physical disks, the result is as follows :
Avg Disk Queue:OK|'AvgDiskQueueLength'=0;0;2 'AvgDiskQueueLength'=0;0;2 'AvgDiskQueueLength'=0;0;2 'AvgDiskQueueLength'=0;0;2 'AvgDiskQueueLength'=0;0;2 'AvgDiskQueueLength'=0;0;2
Every instance returns the same key and the documentation is unclear on how to change the performance syntax. Maybe it would be better to state the property(instance) by default (apart of completing the functionality to change it and docs) ?

**Comment by mickem** [comment]
Sorry for the late response...

But you can actually achive this by using the various options for performance data...

# perf-syntax
This is used to format the entries and you can use any value you select in the expression for instance Name (name of the drive):

```
"perf-syntax=%(Name)"
```

# perf-config
This configure the overall performance data and here you can set various options such as suffix, prefix, etc etc. http://docs.nsclient.org/manual/nscp_checks.html#performance-data-configuration
For instance change the prefix to something else then the column value (time).

```
"perf-config=*(prefix:'time')"
```

All in all this is a full example of customize the performance data...
```
check_wmi "query=select Name, AvgDiskQueueLength from Win32_PerfFormattedData_PerfDisk_PhysicalDisk" "warn=AvgDiskQueueLength>0" "perf-syntax=%(Name)" "perf-config=*(prefix:'time')"
L        cli OK: 0, _Total, 0, 0 C:, 0, 1 D:
L        cli  Performance data: 'time_Total'=0;0;0 'time0 C:'=0;0;0 'time1 D:'=0;0;0
```
