### ISSUE TITLE
Vagrant Files are Obsolete

### ISSUE THREAD

**Issue by gitmopp** [mickem/nscp#350]
These config.vm.box_url do not exist anymore:
vagrant/centos/6.4_32: https://atlas.hashicorp.com/boxcutter/centos64-i386
vagrant/centos/6.4_64: https://atlas.hashicorp.com/boxcutter/centos64
vagrant/centos/6.5_64: https://atlas.hashicorp.com/puppetlabs/centos-6.5-64-puppet
vagrant/oracle-linux-6.4_32: https://dl.dropbox.com/sh/yim9oyqajopoiqs/cx4lB6NnZU/oracle64-32.box
vagrant/oracle-linux-6.4_64: https://dl.dropbox.com/sh/yim9oyqajopoiqs/G-XIEmQJMb/oracle64-64.box
vagrant/ubuntu/trusty32: https://cloud-images.ubuntu.com/vagrant/trusty/trusty-server-cloudimg-i386-juju-vagrant-disk1.box

In centos/6.6_32 and 64 in the package rpmdevtools is missing.
config.vm.provision "shell", inline: "sudo yum install -y cmake python-devel openssl-devel boost-devel lua-devel redhat-lsb rpmdevtools"

The centos biuld for 6.6 and 7 will fail.
I didn' t check the other vagrant images.

**Comment by gitmopp** [comment]
In Cent OS 6.6 with added rpmdevtools the make process fails:
```
n file included from /opt/nscp/include/settings/impl/settings_ini.hpp:28,
                 from /opt/nscp/libs/settings_manager/settings_manager_impl.cpp:3:
/opt/nscp/include/str/utils.hpp: In function ‘void str::utils::parse_command(std::string, std::string&, std::list<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)’:
/opt/nscp/include/str/utils.hpp:133: error: using ‘typename’ outside of template
In file included from /opt/nscp/libs/settings_manager/settings_manager_impl.cpp:3:
[...]
```
Cent OS 6.x latest gcc-c++-4.4.7 supports up to `-std=c++0x`, from what I' ve found in the internet `-std=c++11` is required to support "‘typename’ outside of template". I already tried to compile it with `-std=c++0x`, which didn' t work.

**Comment by gitmopp** [comment]
GCC 4.7.0 is available at [http://people.centos.org/tru/devtools/$releasever/$basearch/RPMS
](url) for CentOS 6.
```
yum install devtoolset-1.0-gcc devtoolset-1.0-gcc-c++
export CC=/opt/centos/devtoolset-1.0/root/usr/bin/gcc
export CXX=/opt/centos/devtoolset-1.0/root/usr/bin/g++
cmake
make
```
With gcc 4.7.0 the template problem from above is fixed. Next problem:
```
In file included from /opt/nscp/libs/settings_manager/settings_manager_impl.cpp:3:0:
/opt/nscp/include/settings/impl/settings_ini.hpp: In member function 'void settings::INISettings::load_data()':
/opt/nscp/include/settings/impl/settings_ini.hpp:283:36: error: 'boost::filesystem::basic_path<std::basic_string<char>, boost::filesystem::path_traits>::string_type' has no member named 'string'
In file included from /opt/nscp/include/settings/impl/settings_http.hpp:49:0,
                 from /opt/nscp/libs/settings_manager/settings_manager_impl.cpp:5:

```
Latest boost-devel for CentOS is 1.41.0-28, which seems not to support this function.

**Comment by mickem** [comment]
Sorry for the late reply, now 6-6 builds (and I have removed the others)
