### ISSUE TITLE
 Cant get Nagios/Op5 to connect via NSclient to windows Server nsclient++

### ISSUE THREAD

**Issue by srooprai** [mickem/nscp#351]
Hey guys
i have installed NSclient on a windows server and im trying to get it work.
But i just cant get it to work!

Im trying to test via OP5:
```
USER1_/check_nrpe -s -H 10.1.10.63 -c CheckUpTime -a ShowAll MinWarn=0s
Result code: UNKNOWN
CHECK_NRPE: Can not connect to a host over SSL.
```

and the logs on the server show in the nsclient log:
```
2016-11-29 14:20:14: error:c:\source\master\modules\NRPEServer\NRPEServer.cpp:123: CA not found: C:\Program Files\NSClient++/security/ca.pem (generating a default CA)
2016-11-29 14:30:44: error:c:\source\master\include\check_nt/server/protocol.hpp:64: Rejected connection from: 10.151.6.11
2016-11-29 14:35:45: error:c:\source\master\include\check_nt/server/protocol.hpp:64: Rejected connection from: 10.151.6.11
2016-11-29 14:35:55: error:c:\source\master\include\check_nt/server/protocol.hpp:64: Rejected connection from: 10.151.6.11
2016-11-29 15:03:46: error:c:\source\master\include\socket/connection.hpp:251: Seems we cant agree on SSL: no shared cipher
2016-11-29 15:03:46: error:c:\source\master\include\socket/connection.hpp:252: Please review the insecure options as well as ssl options in settings.
2016-11-29 15:06:57: error:c:\source\master\include\check_nt/server/protocol.hpp:64: Rejected connection from: 10.151.6.11
2016-11-29 15:07:00: error:c:\source\master\include\check_nt/server/protocol.hpp:64: Rejected connection from: 10.151.6.11
2016-11-29 15:12:42: error:c:\source\master\include\socket/connection.hpp:251: Seems we cant agree on SSL: no shared cipher
2016-11-29 15:12:42: error:c:\source\master\include\socket/connection.hpp:252: Please review the insecure options as well as ssl options in settings.
2016-11-29 15:12:43: error:c:\source\master\include\socket/connection.hpp:251: Seems we cant agree on SSL: no shared cipher
2016-11-29 15:12:43: error:c:\source\master\include\socket/connection.hpp:252: Please review the insecure options as well as ssl options in settings.
2016-11-29 15:13:28: error:c:\source\master\include\socket/server.hpp:239: Failed to handle incoming connection: remote_endpoint: The file handle supplied is not valid
```
.
What im i doing wrong ? i Can ping from the OP5 server to the Windows server.
Does anyone know ? Thanks for all you help

**Comment by mickem** [comment]
I am guessing you are facing issues with "default enabled real ssl" which "check_nrpe" does not support, you can disable this in the installer (or the confg): http://docs.nsclient.org/faq/#what-is-insecure-mode

**Comment by srooprai** [comment]
when lookin the config file for the NSclient i cant see that it should use SSL 
See the output from the config file : 

; VERIFY MODE - Comma separated list of verification flags to set on the SSL socket.  default-workarounds	Various workarounds for what I understand to be broken ssl implementations no-sslv2	Do not use the SSLv2 protocol. no-sslv3	Do not use the SSLv3 protocol. no-tlsv1	Do not use the TLSv1 protocol. single-dh-use	Always create a new key when using temporary/ephemeral DH parameters. This option must be used to prevent small subgroup attacks, when the DH parameters were not generated using "strong" primes (e.g. when using DSA-parameters).   
ssl options = 

; VERIFY MODE - Comma separated list of verification flags to set on the SSL socket.  none	The server will not send a client certificate request to the client, so the client will not send a certificate. peer	The server sends a client certificate request to the client and the certificate returned (if any) is checked. fail-if-no-cert	if the client did not return a certificate, the TLS/SSL handshake is immediately terminated. This flag must be used together with peer. peer-cert	Alias for peer and fail-if-no-cert. workarounds	Various bug workarounds. single	Always create a new key when using tmp_dh parameters. client-once	Only request a client certificate on the initial TLS/SSL handshake. This flag must be used together with verify-peer   
verify mode = none

; ALLOW INSECURE CHIPHERS and ENCRYPTION - Only enable this if you are using legacy check_nrpe client.
insecure = true
--
Also im not useing check_nrpe but insted using check_nt but it still does not seem to work : 
_USER1_/check_nt -H 10.1.10.63 -p 1248 -v CPULOAD -l5,80,90,10,80,90 Result code: WARNING could not fetch information from server

**Comment by JimKeating2** [comment]
Wouldn't the command above need to use port 12489 instead of port 1248.   Just a thought.
NRPE uses port 5666 by default.

**Comment by zyberpunker** [comment]
Did you select the OP5 Monitor config during the installation of nsclient? 
That configuration should work with the standard checks in OP5 Monitor. 

/Ola Sandström 
OP5 technical pre-sale

**Comment by srooprai** [comment]
Hello
Yes i did but i still cant get it to work.
Right now out of ide’s

Best regards / Med vänlig hälsning

Simarpal Rooprai Technical Service Engineer
simarpal.rooprai@networkservices.se<mailto:simarpal.rooprai@networkservices.se> mobile +46 (0) 723 73 21 20.

NETWORK SERVICES NORDEN AB
Fosievägen 13, SE-214 31 Malmö, Sweden.
Phone +46 (0)8-410 231 17. www.networkservices.se<http://www.networkservices.se/>

”ENABLING EVERYDAY COMMUNICATION”

[cid:EAE04F13-BA46-427C-A29B-F1425DF22D4F@ideon.se]

Från: Ola Sandström [mailto:notifications@github.com]
Skickat: den 8 december 2016 23:43
Till: mickem/nscp <nscp@noreply.github.com>
Kopia: Simarpal Rooprai <Simarpal.Rooprai@networkservices.se>; Author <author@noreply.github.com>
Ämne: Re: [mickem/nscp] Cant get Nagios/Op5 to connect via NSclient to windows Server nsclient++ (#351)


Did you select the OP5 Monitor config during the installation of nsclient?
That configuration should work with the standard checks in OP5 Monitor.

/Ola Sandström
OP5 technical pre-sale

**Comment by srooprai** [comment]
Im not quite sure. Perhaps, but so if i change the port,?

Best regards / Med vänlig hälsning

Simarpal Rooprai Technical Service Engineer
simarpal.rooprai@networkservices.se<mailto:simarpal.rooprai@networkservices.se> mobile +46 (0) 723 73 21 20.

NETWORK SERVICES NORDEN AB
Fosievägen 13, SE-214 31 Malmö, Sweden.
Phone +46 (0)8-410 231 17. www.networkservices.se<http://www.networkservices.se/>

”ENABLING EVERYDAY COMMUNICATION”

[cid:EAE04F13-BA46-427C-A29B-F1425DF22D4F@ideon.se]

Från: JimKeating2 [mailto:notifications@github.com]
Skickat: den 8 december 2016 23:02
Till: mickem/nscp <nscp@noreply.github.com>
Kopia: Simarpal Rooprai <Simarpal.Rooprai@networkservices.se>; Author <author@noreply.github.com>
Ämne: Re: [mickem/nscp] Cant get Nagios/Op5 to connect via NSclient to windows Server nsclient++ (#351)


Wouldn't the command above need to use port 12489 instead of port 1248. Just a thought.
NRPE uses port 5666 by default.

**Comment by mickem** [comment]
Just giving some random thoughts:

```
Rejected connection from: 10.151.6.11
```
My guess would be allowed hosts is incorrectly setup.

```
Seems we cant agree on SSL: no shared cipher
Please review the insecure options as well as ssl options in settings.
```
Most likely the insecure option (as the message suggests).
Best option is to redo the configuration from sratch especially if you have hand configured things.
On option is to scrap the NRPE config and use the command line for setting it up:

```
$ nscp nrpe -- install --insecure --allowed-hosts 123.45.6.7
Enabling NRPE via SSL from: 123.45.6.7 on port 5666
WARNING: NRPE is currently insecure.
Arguments are NOT allowed.
```

When it comes to check_nt that does not suport ssl so please be sure to disable ssl there...

**Comment by mickem** [comment]
Closing this, please reopen if problem is still present...
