### ISSUE TITLE
PowerShell Scripts Timeout afte 60 Seconds

### ISSUE THREAD

**Issue by JimKeating2** [mickem/nscp#352]
Hi,  I'm using NSClient++ along with NSCP to pull the status of Windows Updates into Nagios.  To do this I'm using a PowerShell script that runs in between 55 and 65 seconds on the Windows 2008 R2 VMs. The Server 2012 and 2016 VMs run the script in about 20 seconds.  I thought it might be a PowerShell version problem so I updated PowerShell to version 3 on the 2008 VMs.  It did not make a difference.  Every other time the script is run I get the message that the script timed out after 60.01 seconds.  I've visited the site:  "http://docs.nsclient.org/faq/#timeout-issues" and tried tweaking the timeout settings but nothing so far has worked.  Is there some kind of timeout setting that I can use on the PowerShell Wrapping?  Here's the NRPE section of the script:                                                Thank You!  JK

[NRPE]
allowed_arguments=1

[/settings/NRPE/server]
allow arguments=true
allow nasty characters = true
timeout=99
insecure = true

[NSClientListener]
port=12489

; CheckDisk - CheckDisk can check various file and disk related things. The current version has commands to check Size of hard drives and directories.
CheckDisk = 1

; Event log Checker. - Check for errors and warnings in the event log. This is only supported through NRPE so if you plan to use only NSClient this wont help you at all.
CheckEventLog = 1

; Check External Scripts - A simple wrapper to run external scripts and batch files.
CheckExternalScripts = 1

[/settings/external scripts]
timeout=120

[/settings/external scripts/server]
allow arguments=true

[/settings/external scripts/wrappings]
; POWERSHELL WRAPPING -
ps1=cmd /c echo scripts\%SCRIPT% %ARGS%; exit($lastexitcode) | powershell.exe -command -

[/settings/external scripts/wrapped scripts]
fwcheck=fwcheck.ps1
checkupdates=check_windows_updates.ps1
sqlcheck=sqlcheck.ps1

[Wrapped Scripts]
fwcheck=fwcheck.ps1
checkupdates=check_windows_updates.ps1
sqlcheck=sqlcheck.ps1
``

**Comment by JimKeating2** [comment]
This is Jim again...we are using versions:   NSClient++ 0,4,1,73 2012-12-17 and 
NSClient++ 0.5.0.62 2016-09-14
I've tried version 5 as shown above but the scripts still timeout.  Most all of our NSCLient versions are using version 4.1  
Thanks,  JK

**Comment by mickem** [comment]
What the error message when they timeout?

Anyways the following works for me:

check_long.ps1
```
Start-Sleep 90
write-host Works
exit 0
```

nsclient.ini
```
[/modules]
NRPEServer = enabled
CheckExternalScripts = enabled

[/settings/NRPE/server]
timeout=99
insecure = true
allowed hosts=127.0.0.1,::1

[/settings/external scripts]
timeout=120

[/settings/external scripts/wrappings]
ps1=cmd /c echo scripts\%SCRIPT% %ARGS%; exit($lastexitcode) | powershell.exe -command -

[/settings/external scripts/wrapped scripts]
check_long=check_long.ps1
```

Via check_nrpe from NSClient++:
```
$ check_nrpe --insecure --host localhost --timeout 120 --command check_long
Works
```

**Comment by JimKeating2** [comment]
I'm sorry to bother you on this Michael.   When running the check_nrpe command from the Nagios command line and from the nscp test on the Windows server I did not get timeouts on the PowerShell script.   It is a Nagios problem where any service check times out in 60 seconds regardless of the timeout setting used with check_nrpe.  I'm still researching.   Thanks for creating and maintaining the NSClient++ application!  JK

**Comment by mickem** [comment]
That's is actually mentioned in the FAQ you refereed:

```
service_check_timeout=80
```

**Comment by JimKeating2** [comment]
Found that yesterday and Nagios is showing all green again.  Thanks so much!
