### ISSUE TITLE
Bad XML on NRDP-Client

### ISSUE THREAD

**Issue by Mike-Sbg** [mickem/nscp#353]
When I send Data from den NSCLient (Version nscp-0.5.0.65-x64.zip) I get the answer "BAD XML" as answer.

Before I tried the Version nscp-0.5.0.62 which had the "no token" error 

Can you please help me

**Comment by mickem** [comment]
Could you show the payload (if you set og to trace it should be displayed).

```
nscp test --log trace
```

**Comment by Mike-Sbg** [comment]
Ich bin von Mi, 21.12.2016 bis Di, 27.12.2016 abwesend.

Ich werde Ihre Nachricht sobald wie möglich beantworten, jedoch bitte ich
gleich vorweg um Entschuldigung für etwaige Verzögerungen - eine
automatische Weiterleitung erfolgt nicht!
In dringenden Fällen bitte an Hr.Vitzthum (vit@wuestenrot.at) wenden!

Ich wünsche allen ein Frohes Weihnachtsfest und einen guten Rutsch ins neue
Jahr 2017!





























Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[mickem/nscp] Bad XML on NRDP-Client (#353)" gesendet am 21.12.2016
20:59:00.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by Mike-Sbg** [comment]
At the moment I've problems with my nagios system (update to version 4 made in unstable) ... I'll try to get the trace as soon as possible

**Comment by mickem** [comment]
Please reopen this if it is still an issue...
