### ISSUE TITLE
Problem with counter in NSClient++/NRPE

### ISSUE THREAD

**Issue by GeorgeWesso** [mickem/nscp#354]
Hello,
I have a problem with the count information in the NSClient++ 0.5.62 if there is calling a CheckEventLog from a Icinga 1 server. I check into the system eventlog a server restart, this is the event 1074. I found in some old Blogs the info that there is a difference for the syntax in the NSClient++ 0.4.xx and 0.5.xx. So I have written two different check commands but I get the same error.

If on the Windows Server is installed the NSClient 0.4.1.105 the result is correct. After a reboot the counter shows "Count: 2":
```
/usr/lib/nagios/plugins/check_nrpe -H myhost -p 5666 -t 300 -c CheckEventLog 
-a file=system MaxWarn=1 MaxCrit=25 "filter=id=1074 AND source='USER32' AND 
generated gt -30m" unique descriptions "syntax=ID: %id%, Count: %count%"

     ID: 1074, Count: 2, eventlog: 2 > warning|'eventlog'=2;1;25
```
Now I have changed the Client to NSClient 0.5.62. But I get with two different syntaxes the same error: "Count: 0" and instead of "eventlog" is written "count":

```
/usr/lib/nagios/plugins/check_nrpe -H myhost -p 5666 -t 300 -c CheckEventLog 
-a file=system MaxWarn=1 MaxCrit=25 "filter=id=1074 AND source='USER32' AND 
generated gt -30m" unique descriptions "syntax=ID: %id%, Count: %count%"

     ID: 1074, Count: 0|'count'=2;1;25

/usr/lib/nagios/plugins/check_nrpe -H myhost -p 5666 -t 300 -c CheckEventLog 
-a file=system MaxWarn=1 MaxCrit=25 "filter=id=1074 AND source='USER32' AND 
generated gt -30m" unique descriptions "syntax=ID: %(id), Count: %(count)"

     ID: 1074, Count: 0|'count'=2;1;25
```
Or is there another mistake in my syntax?
Many thanks for your help!

**Comment by mickem** [comment]
This is not using the new syntax:

Something along the lines of this:
```
check_eventlog file=system "warn=count>1" "crit=count > 25" "filter=id=1074 AND source='USER32' AND generated gt -30m" unique descriptions "detail-syntax=ID: %(id)" "top-syntax=%(list), Count: %(count)"
```
