### ISSUE TITLE
zmsg.hpp licensing bug

### ISSUE THREAD

**Issue by hyandell** [mickem/nscp#355]
Hi NSClient++ folk,

The inculde/zmsg.hpp file contains an LGPLv3 license header. I think this may be an error.

The zmsg.hpp code comes from the ZGuide: https://github.com/booksbyus/zguide/blob/4096d2bc75f4229d46b9168a3ff51be418123dd6/examples/C%2B%2B/zmsg.hpp

Historically I think the license on this was unclear and whomever copied the file over applied the license of the project as a whole (LGPLv3 w/ exception). Since then the ZGuide has been clarified in https://github.com/booksbyus/zguide/blob/master/README.md ( "The source code examples are licensed under MIT/X11 unless otherwise specified in the code. The tools in /bin are placed into the public domain. " ).

Reporting this in case you would like to simplify the licensing within nscp.

**Comment by mickem** [comment]
zeromq is no longer used so I guess it can actually be removed...

**Comment by mickem** [comment]
The file has not been removed
