### ISSUE TITLE
about check_process in nscp0.5.62

### ISSUE THREAD

**Issue by mjesse88** [mickem/nscp#356]
Hi mickem,
I meet problem about check_process,

D:\program files\NSClient++>nscp client --query check_process process=d.exe
CRITICAL: d.exe=stopped|'d.exe state'=0;0;0 'count'=1;0;0

D:\program files\NSClient++>nscp client --query check_process process=d.exe warn
="working_set>1000m" "crit=working_set>1500m"
OK: all processes are ok.|'d.exe ws_size'=0GB;0.97656;1.46484

if add working_set in warn and crit, it cannot check the d.exe is close. I think it's unreasonable

and
D:\program files\NSClient++>nscp client --query check_process process=d.exe warn
="count<1" "crit=count<1"
OK: all processes are ok.|'count'=1;1;1

Is the count is 1?  

Thanks
jesse

**Comment by mjesse88** [comment]
It is OK 
D:\program files\NSClient++>nscp client --query check_process "filter=state='sta
rted'" process=d.exe "warn=working_set>100m" "crit=working_set>1000m" "crit=count<
1"
CRITICAL: No processes found|'count'=0;0;1

**Comment by mickem** [comment]
to get around crit < 1 you can also set `empty-state=crit` which should yield the same result...

But I guess I can close this issue then?

**Comment by mjesse88** [comment]
sorry for long time dont respond.
yes, you can close this.

thank for respond too.
