### ISSUE TITLE
Installation not populating nsclient.ini

### ISSUE THREAD

**Issue by Brickius** [mickem/nscp#357]
I use the following command to install nsclient++

msiexec /passive /i NSCP-0.5.0.62-x64.msi INSTALLLOCATION="D:\Program Files\NSClient++" CONF_NRPE=1 CONF_CHECKS=1 NRPEMODE=LEGACY MONITORING_TOOL=none ALLOWED_HOSTS="XXXXXXXXX"

However this does not populate the nsclient.ini file- If I remove the passive and just click next next next finish it does populate the ini file... what am I missing?

I have tried 'ADD_DEFAULTS=1'

**Comment by mickem** [comment]
In 0.5.0 you need to add CONF_CAN_WRITE=1 or the config wont be written (this has already been fixed in 0.5.1)

**Comment by mickem** [comment]
This has been improved in last recent builds of 0.5.1 so most likely fixed there...

**Comment by mickem** [comment]
(if not reopen)
