### ISSUE TITLE
 Check_pagefile with server without pagefile

### ISSUE THREAD

**Issue by smutel** [mickem/nscp#361]
Hello,

I use this nrpe command to monitor pagefile on windows servers:

`check_nrpe -H XX.XX.XX.XX -c check_pagefile -a "filter=name = 'total'" 'warn=used > 102%' 'crit=used > 102%' 'detail-syntax=Total: %(size) - Used: %(used) - Free: %(free)' 'perf-syntax=page file'`

The issue is that for some servers we don't have pagefile setup.
In this case, the command returns a strange return code 141 without any message.

In addition I have crash-dumps directory created each time the command is executed.

Thanks.
Regards.

**Comment by robert-i** [comment]
What version are you running? This seems to be fixed in #341

**Comment by smutel** [comment]
Yes it is the same bug. I use version 0.5.0.65. And the fix seems to be implemented from version 0.5.1.8.

**Comment by mickem** [comment]
Closing this as it has been fixed in 0.5.1, please reopen if you encouter this after 0.5.1.8
