### ISSUE TITLE
Python sample script raise an error

### ISSUE THREAD

**Issue by mohierf** [mickem/nscp#368]
```
nscp py execute --script=sample.py

E     python close failed in file object destructor:
IOError: [Errno 0] Error
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd0 in position 1: invalid continuation byte
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd0 in position 1: invalid continuation byte
```

Note that when the registering of the `submit_metrics` feature  is commented, there is no more error!

I am running NSClient++ 0.5.0.62 2016-09-14 x64 on a French Windows 7

**Comment by mohierf** [comment]
I suppose that the metrics function are related to the GraphiteClient module, right ?

If so, sending the `world_status` that is a string as a metric value to Graphite is probably the source of the problem, no ?

**Comment by mickem** [comment]
metrics are not related to graphite, they can be used in graphite but also other modules (pyton script, web ui, rest api, collect-d etc etc).
But this sounds more like a bug somewhere usually these comes from error messages (especially in foreign langue windows)

**Comment by mohierf** [comment]
Thanks for the reply. My windows being a French release, I do agree with your analysis... Windows is not utf-8 friendly :/ Is there any solution to get more information about the underlying problem ?

**Comment by mickem** [comment]
I fixed a bunch of utf issues when I did some refactoring a week or so back, but in this case I will see if I can reproduce it so I can fix the specifics...

// Michael Medin

**Comment by mohierf** [comment]
Thanks. 
I take this opportunity of this issue to ask for the best doc source about Python scripting. I searched in the documentation and even in the source code to understand I can script, but it is really not easy to understand. I would appreciate any URL or file in the git repo that you may provide to help :wink:

**Comment by mickem** [comment]
There is a lot of scripts in git if thats what you looking for, as for scripting it is fairly straight forward (says I who wrote it)...

The best place to start is here: https://github.com/mickem/nscp/blob/master/scripts/python/sample.py
And more scripts can be found in that folder: https://github.com/mickem/nscp/blob/master/scripts/python

But I probably should write some information in the docs I guess...

**Comment by mohierf** [comment]
At least some few doc that will explain the main principles seems a must-have :wink: But I won't blame you, I known it is not always easy to maintain the do up-to-date

**Comment by itsul** [comment]
Hi Michael,

thanks for sharing the URLs. On the OSMC in Nürnberg you used a phyton file "events.py" for automated adding hosts to icinga. Could you upload it to github also? Furthermore the question, are all phyton scripts started once automatically at nsclient start up?

Regards

**Comment by mickem** [comment]
Yes all scripts are started on startup.

Requests can be used like normal modules, if you use the bundled python then they need to be installed into the lib folder:

The attachments section of the osmd demo was:

```
[/attachments]
unzip:${scripts}/python/lib=https://medin.name/requests-2.11.1-py2.py3-none-any.whl
unzip:${scripts}/python/=https://medin.name/icinga.zip
${base-path}/_ssl.pyd=https://medin.name/_ssl.pyd
```
Placing requests into python/lib

This is obviously not ideal and I am investigating better ways to handle this like fall back to an already installed python...

// Michael Medin

**Comment by fanooel** [comment]
OK. I cant fix this problem by comment line in sample.py:

`reg.submit_metrics(submit_metrics)`

in log file I've got:

```
2017-02-23 07:41:18: error:c:\source\nscp\modules\PythonScript\script_wrapper.cpp:173: close failed in file object destructor:
IOError: [Errno 0] Error
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb3 in position 1: invalid start byte
```

**Comment by mickem** [comment]
Could you provide the config and language you have on your system.

**Comment by fanooel** [comment]
1. Version:
`C:\Program Files\NSClient++>nscp.exe --version
NSClient++, Version: 0.5.0.65 2016-11-13, Platform: w32`

2. System:
`C:\Program Files\NSClient++>ver

Microsoft Windows [Version 6.1.7601]`

3. Language: English

4. Config:

Just add:
`[/settings/python/scripts]

cool_sample = sample.py`

**Comment by mickem** [comment]
Hmm, w32... I will see if that makes a difference...

What local is the windows machine running?

**Comment by fanooel** [comment]
Works fine on 5.1!.

**Comment by mickem** [comment]
guess I can close this then...
