### ISSUE TITLE
Status information for check_eventlog and checkEventLog do not work

### ISSUE THREAD

**Issue by krizb** [mickem/nscp#371]
Hi,
I have configured check, that IIS was restarted during last 24 hours. Expected behaviour was: if there was restart - OK state, no restart - CRITICAL. Results has text that is correct, but state value returned by plugin is always zero ("0"). 
I have no such problem when checking cpu, memory, services, ...

My original agent on server is version 0.4.4.19 and is running on Windows Server 2012:
```
[root@s-ddcb-sung01 ~]# /usr/lib64/nagios/plugins/check_nrpe -H 10.197.85.11 -p 5666
I (0.4.4.19 2015-12-08) seem to be doing fine...
```

I have tried on another client running on my workstation that has version 0.5.0.62 running on Windows 7sp1:
```
[krizb@kriznb ~]$ /usr/lib64/nagios/plugins/check_nrpe -H 192.168.56.11 -p 5666
I (0.5.0.62 2016-09-14) seem to be doing fine...
```
But the results was the same:

```
[krizb@kriznb ~]$ /usr/lib64/nagios/plugins/check_nrpe -H 192.168.56.11 -p 5666 -c checkEventLog -a file=System MinCrit=0 MinWarn=0 filter="generated > -24h AND id = 7036 AND message = 'The World Wide Web Publishing Service service entered the running state.'" syntax="%(status): IIS restarted in 24h"
CRITICAL: No entries found|'count'=0;0;0
[krizb@kriznb ~]$ echo $?
0
```

I also tried to use new format of check_eventlog, but the result was the same:
```
[krizb@kriznb ~]$ /usr/lib64/nagios/plugins/check_nrpe -H 192.168.56.11 -p 5666 -c checkEventLog -a file=System MinCrit=0 MinWarn=0 filter="generated > -24h AND id = 7036 AND message = 'The World Wide Web Publishing Service service entered the running state.'" syntax="%(status): IIS restarted in 24h"
CRITICAL: No entries found|'count'=0;0;0
[krizb@kriznb ~]$ echo $?
0
```

When I change warning and critical levels, it will say OK in text and zero in status value, that is ok.

Does anyone use check_eventlog function? It seems, that it is broken and nobody use it.

Regards, Bohumil

**Comment by mickem** [comment]
First off your using the old syntax so you probably what to upgrade to the new syntax if you run in test mode you can see the new command):
```
check_eventlog warn=count<=0 crit=count<=0 file=System "filter=written > -24h AND id = 7036 AND message = 'The World Wide Web Publishing Service service entered the running state.'" "detail-syntax=%(status): IIS restarted in 24h" "top-syntax=${list}"
```

But this says that the status is critical if you have 0 (or less) items and ok if you have 1 or more...
Effectively saying that if the message exists it is ok, otherwise it is a warning.
Now there is one final snag here which is the empty state (which I guess makes less sense now that count works correctly) which is why the empty status is wrong...

The empty syntax kicks in if there are no matches and the default value is "ok" this should be ignored in your case. Thus adding empty-state=ignored alleviates this:

```
check_eventlog warn=count<=0 crit=count<=0 file=System "filter=written > -24h AND id = 7036 AND message = 'The World Wide Web Publishing Service service entered the running state.'" "detail-syntax=%(status): IIS restarted in 24h" "top-syntax=${list}" empty-state=ignored
```

**Comment by krizb** [comment]
Hi Michael,

thank you for explanation. That solved my problem.

May be that in future it would be good to do something with empty-state (change default value?), so that confusion of having text "critical" and at the same time having state "0"/ok, will be suppressed.

But that is not so urgent for me, as it work now as I need.

Regards, Bohumil
