### ISSUE TITLE
--source-host no longer works for submit_nsca since 0.5.0.62

### ISSUE THREAD

**Issue by SteveLowe** [mickem/nscp#372]
Since upgrading to 0.5.0.62 the --source-host and --sender-host arguments no longer work for submit_nsca.

I am calling nscp with:

     .\nscp.exe nsca --result OK --message "Message Text" --source-host host1

however debug logs on the nsca server show the hostname sent is the actual hostname of the machine, not "host1".

The following is in nsclient.ini for NSCA
```
[/settings/NSCA/client/targets/default]
address = 1.2.3.4
encryption = aes
password = My_Password
```
With 0.4.4.23 this works fine (the hostname received by the nsca server is 'host1').

**Comment by mickem** [comment]
Could you try this in latest 0.5.1 version?
I fixed some nsca issue closely related to this recently...
