### ISSUE TITLE
Command in the the log is not the one in the configuration

### ISSUE THREAD

**Issue by mohierf** [mickem/nscp#373]
With this configuration:
```
; TODO
[/settings/scheduler/schedules/os_services]

; Undocumented key
alias = os_services

; SCHEDULE INTERAVAL - Time in seconds between each check
interval = 300s

; SCHEDULE COMMAND - Command to execute
command = check_service exclude=ShellHWDetection exclude=MMCSS exclude=clr_optimization_v4.0.30319_32 exclude=sppsvc exclude=StiSvc exclude=WMPNetworkSvc exclude=debugregsvc exclude=DoSvc exclude=MapsBroker exclude=CDPSvc exclude=WbioSrvc exclude=gpsvc exclude=tiledatamodelsvc exclude=wscsvc

```

I got this message in the log (nscp test):
```
D   schedule Adding scheduled item: os_services[-2088599168] = {tpl: {alias: os_services, path: /settings/scheduler/sche
dules/os_services, is_tpl: false, parent: default, value: , options : { } }, command: CheckServiceState, channel: NSCA,
source_id: , target_id: , duration: 300s}
```

**Note** the CheckServiceState legacy name ...

**Comment by mickem** [comment]
I would say this is neigh on impossible... Are you sure you have the correct configuration?

**Comment by mohierf** [comment]
I am pretty sure about this. I did the test several times, but I will give one more try and give you some feedback

**Comment by mohierf** [comment]
Ok. I understood what is happening (or I think so...). 

My boot.ini file contains 1. ini file, and 2. registry. The ini file uses `check_service` whereas the registry contains `CheckServiceState`... this may be an explanation?

**Comment by mickem** [comment]
Running 
```
nscp settings
```

Should show what setting will be loaded, you can also show the actual value used bu running:

```
nscp settings --show --path /modules --key CheckHelpers
enabled
```

**Comment by mickem** [comment]
Please reopen if this is still an issue
