### ISSUE TITLE
Documentation Broken

### ISSUE THREAD

**Issue by subfission** [mickem/nscp#375]
**For setting up NSClient++**
The entire documentation seems to have been damaged and is useless, unless this was intentional.  Try walking through the tutorial... 

https://docs.nsclient.org/tutorial/

**Comment by mickem** [comment]
Sorry my web deploy switched back to the old version...  It got go to https:// docs.nsclient.org/0.5.1

**Comment by mickem** [comment]
Now I have fixed so the new docs are back...

**Comment by subfission** [comment]
Thank you!  Everything looks good again :)
