### ISSUE TITLE
QUESTION: REST API

### ISSUE THREAD

**Issue by itsul** [mickem/nscp#376]
Hi @mickem ,

do you have any documenation from the REST API? 

normal CPU request is working well:
```
curl --insecure --header "password: HelloWorld" https://172.27.0.0:8443/query/check_cpu?show-all
{"header":{"source_id":""},"payload":[{"command":"check_cpu","lines":[{"message":"OK: 5m: 0%, 1m: 5%, 5s: 4%","perf":[{"alias":"total 5m","int_value":{"critical":90,"unit":"%","value":0,"warning":80}},{"alias":"total 1m","int_value":{"critical":90,"unit":"%","value":5,"warning":80}},{"alias":"total 5s","int_value":{"critical":90,"unit":"%","value":4,"warning":80}}]}],"result":"OK"}]}
```

Is it possible to use the REST API for config update and reload/restart?
Example:
```
curl --insecure --header "password: HelloWorld" https://172.27.0.0:8443/system/restart
```
or
```
curl --insecure --header "password: HelloWorld" https://172.27.0.0:8443/system/config  --data '{"config_http":"http://172.20.0.1/nsclient/NSC.ini"
```
Regards

**Comment by mickem** [comment]
Best bet currently is play around using the web interface (where you can use the chrome developer tab to see requests/replies)...

The only API documentation currently is this: https://docs.nsclient.org/api/plugin/ which is pretty terrible...
It reflects the messages sent internally (so really intended for plugins) but the REST interface is in most cases the same...

I have plans to create some better documentation in the future... but have not had time thus far...

**Comment by mickem** [comment]
(and yes, you can use the REST API for pretty much EVERYTHING from changing config, reloading, restarting, loading modules, etc etc...

Everything which can be done via the WEB UI can also be done via the REST API

**Comment by itsul** [comment]
Thanks for the response.

**Comment by dnsmichi** [comment]
See mickem/nscp-docs#4

**Comment by mickem** [comment]
Please reopen if you have further questions/issues
