### ISSUE TITLE
Automated installation

### ISSUE THREAD

**Issue by dgoeger** [mickem/nscp#377]
Hello,

i want to install the NSCP-Client automated.
Thats my command:

msiexec /qn /norestart /l* log.txt /i NSCP-0.5.0.62-x64.msi CONFIGURATION_TYPE=registry://HKEY_LOCAL_MACHINE/software/NSClient++ ADDDEFAULT=ALL REMOVE=PythonScript CONF_WEB=1 NSCLIENT_PWD="xxxxx" NRPEMODE=LEGACY ALLOWED_HOSTS="127.0.0.1,::1,xxx.xxx.xxx.xxx/16"

but the installation ignores the options.
Only Allowed_HOSTS optione done.

Can sombody help me with this Problem?

**Comment by mickem** [comment]
For 0.5.0 you need to set CONF_CAN_WRITE=1 and MONITORING_TOOL=none

**Comment by dgoeger** [comment]
Trank you i will try it.
Is there a part in the documentation sheet?

**Comment by dgoeger** [comment]
Second Problem nothing is written to registry.

**Comment by mickem** [comment]
It should be mentione din the 0.5.0 version documentation http://docs.nsclient.org/0.5.0/ (which seems broken, so I guess I need to fix that as well, but you should have the same in the installed version though)

Can you give me the exact command you have "now" i.e. the on you used when registry was not working and I will lok into it...

// Michael Medin

**Comment by anthony-poon** [comment]
I installed via GPO startup script in system user context. The msi is located in a share drive. The command I use is

msiexec /l* "C:\nscp_install.log" /qn /i "\\AMLAD\netlogon\msi\NSCP-0.5.0.62-x64.msi" INSTALLLOCATION="C:\Program Files\NSClient++\" CONFIGURATION_TYPE="ini://\\AMLAD\netlogon\nscp_config.ini" ADDDEFAULT=ALL REMOVE=PythonScript CONF_CAN_CHANGE=1 MONITORING_TOOL=none

If I put "CONF_CAN_CHANGE=1 MONITORING_TOOL=none" at the end, the installation destination will have nothing but a single "boot.ini" file.

If I remove either option or both, the config will be ${share-path}/nsclient.ini

By the way, what is the share-path variable? is it the environmental variable?

**Comment by mickem** [comment]
share-path is a hardcoded variable and currently the path of the exe file (https://github.com/mickem/nscp/blob/master/docs/docs/settings.md#paths )
I have fixed numerous bugs related to silent installeras so please try 0.5.1.35 first and see if that works better...

**Comment by mickem** [comment]
Please reopen this if you still have issues with 0.5.2
