### ISSUE TITLE
nsclient.ini via http is not loaded automatically

### ISSUE THREAD

**Issue by log1-c** [mickem/nscp#378]
Hi,

I have just configured my NSClient (0.5.0.62) to fetch it's config via http:
`nscp settings --switch http://192.168.63.35/NSClient/nsclient.ini`

If I understand the Docs correctly (https://docs.nsclient.org/settings/#http-settings) the config should get automatically applied after changes?!

For my config this does not seem to work. The config is fetched periodically (1min I think) and the files in NSCLient/cache change.
Problem is, that NSClient does not reload the config and is still using the old one.

Did I miss something or is this a bug?
boot.ini looks like this:

> [settings]
> 1=http://192.168.63.35/nsclient/nsclient.ini
> [main]
> write=http://192.168.63.35/nsclient/nsclient.ini

Also the Docs mention that it is possible to change the refresh interval, but not how or where to do it. Could you add this information?

Best regards,

Logic

**Comment by mickem** [comment]
Not a 100% sure if the reload thing is new in 0.5.1 or not...


```
[/settings/core]
settings maintenance interval=5m
```

**Comment by log1-c** [comment]
Thanks for your answer and the settings lines!
I added them to the boot.ini and now it (nearly) works as expected:

If I change the config it now takes 5m to download(?) it (nsclient.ini.tmp date:time changes) and after that the config is active!
Strange thing though: If I don't change the config after this, the .tmp file gets updated every minute for the next two minutes then it's back to the 5 minute interval.

Example:
- Change config at 8:12
- nsclient.ini.tmp gets updated at 8:17 and so does the nsclient.ini
- new config is active
- nsclient.ini.tmp gets updated at 8:18, 8:19 and then at 8:22 again

Example2:
- Change config at 8:22
- nsclient.ini.tmp gets updated at 8:24 and so does the nsclient.ini
- new config is active
- nsclient.ini.tmp gets updated at 8:25. then again at 8:29, 8:31, 8:35 and 8:39

But that is a very minor issue I think.

Best regards,

Logic

**Comment by mickem** [comment]
Pretty sure the config goes in the regular config (not boot ini)...

Expected behaviour is refreshing .tmp every 5 minutes and if there is a change (sha missmatch) update.ini and reload...

**Comment by gbpullen** [comment]
I am testing the HTTP configuration feature with NSClient 0.5.0.62 on a Windows server. It is downloading the nsclient.ini as expected, but every time there is an updated file a dump occurs.  I have the nscp running as a Windows service and so it automatically restarts.  The effect is that appears to reload automatically but only because of the dump and restart.   Has anyone else seen this behavior?

I have tried the latest build NSClient 0.5.1.31 and it does not dump with the updated file. However, it does not reload the updated configuration until I restart the service. So is there actually automatic reload that is supposed to occur? If so it does not appear to be working when NSClient is run as a Windows service.

**Comment by log1-c** [comment]
Ah, forgot about this thread/report. Should have closed it, as it is resolved 👍 

@gbpullen 
I think this is the expected behavior assuming that by "dump" you mean a download of the complete nsclient.ini?
As mickem states the default is refrehing the .tmp file of the ini every 5 min and put it in the normal .ini if it is different from the current loaded .ini. After this the nsclient reloads the new config.

As for you problem with version 0.5.1.31:
Can give you any feedback on this, I only use 0.5.0.62.

**Comment by gbpullen** [comment]
@log1-c 
By dump I mean it creates a *.dmp and *.txt file in the C:\Program Files\NSClient++\crash-dumps folder. 

The download is working as described, so it appears the dump occurs after the download and copy. 
 I can only assume this is during the attempted reload process.  With 0.5.1.31 there is no dump but the changes to the configuration are not put into place until I restart the service, which of course reloads the configuration

Are you not getting a dump upon nsclient.ini updates?

**Comment by log1-c** [comment]
Never looked out for that, but you are right.
There is a dump and txt file for every nsclient.ini update.

I'd suggest you open a new issue for the problem with 0.5.1.31 so that this does not drown here.

**Comment by mickem** [comment]
yeah, please open a new issue for that ...

**Comment by gbpullen** [comment]
Done! See issue https://github.com/mickem/nscp/issues/446.
