### ISSUE TITLE
 Check_TaskSched only check root folder, and casuing 100% cpu usage nscp

### ISSUE THREAD

**Issue by j-stoddart** [mickem/nscp#379]
I am working on upgrading to the latest version (0.5.0.62) but am having some trouble with the task schedule checker, we only want to check tasks that are in the root (/) directory in task scheduler.

I have tried setting "folder = /" "folder = '/'" "folder = "/"" and quite a lot of other combinations for this currently the check i have is set up like this (i have shortened it for all of the "folder ne /x/x/x", and will put the full version at the end)

>alias_sched_failed = Check_TaskSched "filter=folder ne '\Microsoft\Windows\Active Directory Rights Management Services Client' and folder ne '\x\x\x'(repeats many times) and task_status ne 'disabled' and task_status ne 'running'"`

This is causing 100% cpu usage on one of our machines and when i comment this check out the cpu usage goes back to 0, i would appreciate it if anyone could help with this.  This is the check i am using for windows 2k12, i have done the same thing on 2k8 and it is working fine due to there being a lot less folders inside task scheduler.

Thank you

Full one

> alias_sched_failed = Check_TaskSched "filter=folder ne '\Microsoft\Windows\Active Directory Rights Management Services Client' and folder ne '\Microsoft\Windows\Defrag' and folder ne '\Microsoft\Windows\NetTrace' and folder ne '\Microsoft\Windows\RAC' and folder ne '\Microsoft\Windows\Ras' and folder ne '\Microsoft\Windows\Tcpip' and folder ne '\Microsoft\Windows\UPnP' and folder ne '\Microsoft\Windows\Customer Experience Improvement Program' and folder ne '\Microsoft\Windows\NetCfg' and folder ne '\Microsoft\Windows\PI' and folder ne '\Microsoft\Windows\Power Efficiency Diagnostics' and folder ne '\Microsoft\Windows\SpacePort' and folder ne '\Microsoft\Windows\Storage Tiers Management' and folder ne '\Microsoft\Windows\TaskScheduler' and folder ne '\Microsoft\Windows\WindowsUpdate' and folder ne '\Microsoft\Windows\WS' and folder ne '\Microsoft\Windows\AppID' and folder ne '\Microsoft\Windows\Application Experience'  and folder ne '\Microsoft\Windows\ApplicationData' and folder ne '\Microsoft\Windows\Autochk' and folder ne '\Microsoft\Windows\CertificateServicesClient' and folder ne '\Microsoft\Windows\Chkdsk' and folder ne '\Microsoft\Windows\Customer Experience Improvement Program\Server' and folder ne '\Microsoft\Windows\Data Integrity Scan' and folder ne '\Microsoft\Windows\MUI' and folder ne '\Microsoft\Windows\Plug and Play' and folder ne '\Microsoft\Windows\Server Manager' and folder ne '\Microsoft\Windows\Servicing' and folder ne '\Microsoft\Windows\Time Synchronization' and folder ne '\Microsoft\Windows\Time Zone' and folder ne '\Microsoft\Windows\TPM' and folder ne '\Microsoft\Windows\Windows Error Reporting' and task_status ne 'disabled' and task_status ne 'running'"

**Comment by mickem** [comment]
Hmm, wouldn't this do what your looking for:

```
check_tasksched folder=\\ "filter=folder='\\'"
```

**Comment by mickem** [comment]
Please reopen if this is still an issue
