### ISSUE TITLE
CheckTaskSched - max_run_time usage

### ISSUE THREAD

**Issue by cmeschin** [mickem/nscp#380]
Hi Michael,

I would like to know how can I use the filter "max_run_time" because this variable always returns 0.
Does Max_run_time return the total execution time of the task or other information?

Otherwise, is it possible to capture "end_time" and make the difference between the start time and the end time and compare with thresholds?

regards,

**Comment by mickem** [comment]
max_run_time is (according to the nsclient++ docs): Retrieves the maximum length of time the task can run."

This in effect is a configured value you can find more details here: https://msdn.microsoft.com/en-us/library/windows/desktop/aa381874(v=vs.85).aspx

If you want how long it took to execute the task there is another value you can use most_recent_run_time which will show you the time the LAST execution took.

**Comment by cmeschin** [comment]
Thanks for your quickly response.
Understood for max_run_time.

It seems to be able to compare with actual time with this syntax:
"filter=status ne 'ready' AND title like 'test_notepad' AND most_recent_run_time > +120m"
but does not seem to work

I tried this syntax without success...
-c CheckTaskSched -a "filter=status ne 'ready' AND title like 'test_notepad' AND most_recent_run_time > -120m" "syntax=%title% (%(most_recent_run_time)) [exit_code:%exit_code%] statut:%status%" "crit=>0"
test_notepad (2017-f?vr.-08 15:29:45) [exit_code:267009] statut:running|'count'=1;0;0

local time is 16:31 (UTC+1 Europe/Paris)
I tried different operators and values:
> +120m
> -120m
< -120m
< +120m
...
I want to return a critical if task always running after 2 hours
can you help me with the good syntax?

**Comment by mickem** [comment]
Wait sorry, I was wrong... you cant get the time it took... most_recent_run_time  is mainly for checking if a task is running late i.e. "now" then you can see if it is running and start is longer then x...

Tasks running for more then 10 minutes:
```
check_tasksched "filter=most_recent_run_time < -10m and status = 'running'"
```

**Comment by cmeschin** [comment]
Hi,

I make some tests and don't work. :(
I use nscp 0.4.2.93... Yes I know it's an old version...

These are the tests i have make (on W2008R2 SP1 64 bits):
launched a task at 10:53 and always running 
![task_launch](https://cloud.githubusercontent.com/assets/8720203/22779113/b33e0942-eeb9-11e6-96d2-9e07a496103c.png)

the result of many tests:
[task_tests.txt](https://github.com/mickem/nscp/files/763384/task_tests.txt)

Can you check and tell me if some fixes have been made on this module to solve the problem?

thanks.

**Comment by mickem** [comment]
Some, notice the last line there (which was fixed I thin in 0.4.2.114 or possible 0.4.3)...

* Fixed folder support in tash scheduler
* Fixed #274 Added has_run to check_taskshed
* Fix for #215 added new option to check_tasksched to force using the old api
  check_tasksched force-old
* #215 Improved error reporting in check_taskshed
* Renamed status to task_status as it clashes with regular status
* Fixed #170
* New filters
* Implemented empty syntax as a proper syntax string (i.e replacement variables)
 * Fixed #730 check_tasksched / most_recent_run_time not working

**Comment by cmeschin** [comment]
Thanks, i try with a most recent release tomorrow.

**Comment by cmeschin** [comment]
Hi Michael,
It works with latest release 0.5.0.62 x64.
I try on few others windows distributions (32 and 64 bits) to validate this release on our IT.

thank you.
regards.
