### ISSUE TITLE
DotNet plugin crashes on NSCP 0.5.0.62 x64

### ISSUE THREAD

**Issue by firstrose** [mickem/nscp#384]
Even sample code crashes.

Test by `nscp test` with "trace" log level, still no detail shown :

![mstsc_2017-02-15_16-26-06](https://cloud.githubusercontent.com/assets/1551595/22966499/64a9bee6-f39d-11e6-9d3f-b675bc68fcc6.png)

OS:  Win 2008 Server R2 x64 Ent, SP1
NSCP: 0.5.0.62 x64
dump file:

[nscp-crash.zip](https://github.com/mickem/nscp/files/776470/nscp-crash.zip)

**Comment by mickem** [comment]
I managed to reproduce the issue with 0.5.0.62 but it seems fixed as it (for me) works with the 0.5.1.19 build found here: https://github.com/mickem/nscp/releases/tag/0.5.1.19 Please reopen if you can reproduce this with the new build.

**Comment by firstrose** [comment]
Excuse me, but do you have any other downloading mirror for nscp? It's too slow (hundreds of KBs per hour) to download from https://github.com/mickem/nscp/releases/ for me. So I preferred to download 'release' of nscp instead of 'pre-release' & 'rc'.

**Comment by mickem** [comment]
NSClient++ binaries are hosted on github which in turn hosts them on amazon.

0.5.1 is not released yet so there are not "non pre release" of it yet...
