### ISSUE TITLE
Automated Installation Password Option

### ISSUE THREAD

**Issue by davops** [mickem/nscp#386]
When deploying an unattended installation, the MSI option for NSCLIENT_PWD does not get applied. However, other options such as ALLOWED_HOSTS are applied correctly. The password that does appear is one automatically generated by nscp. I am installing version 0.4.4.23-x64.

Here's what I am running:
`msiexec /i C:\Users\User1\Downloads\NSCP-0.4.4.23-x64.msi /norestart /log c:\Users\User1\Downloads\install1.log ALLOWED_HOSTS=10.0.0.1,127.0.0.1 CONF_CHECKS=1 CONF_NSCLIENT=1 NSCLIENT_PWD=MyPass /passive`

Here are the parts that appear relevant from the install log:

> 1:Adding include:  
1: write_changed_key: CONF_NRPE; /modules.NRPEServer=1 
1: IGNORING property not changed: CONF_SCHEDULER; /modules.Scheduler= 
1: IGNORING property not changed: CONF_NSCA; /modules.NSCAClient= 
1: write_changed_key: CONF_NSCLIENT; /modules.NSClientServer=1 
1: IGNORING property not changed: CONF_WMI; /modules.CheckWMI= 
1: IGNORING property not changed: CONF_WEB; /modules.WEBSErver= 
1: write_key: /modules.CheckSystem=1 
1: write_key: /modules.CheckDisk=1 
1: write_key: /modules.CheckEventLog=1 
1: write_key: /modules.CheckHelpers=1 
1: write_key: /modules.CheckExternalScripts=1 
1: write_key: /modules.CheckNSCP=1 
1: write_key: /settings/NRPE/server.insecure=false 
1: write_key: /settings/NRPE/server.ssl options=no-sslv2,no-sslv3 
1: write_key: /settings/NRPE/server.verify mode=peer-cert 
1: write_changed_key: ALLOWED_HOSTS; /settings/default.allowed hosts=10.0.0.1,127.0.0.1 
1: write_changed_key: NSCLIENT_PWD; /settings/default.password=hEU5x7fHxHGOadVY 

And further towards the bottom:
>Property(S): WixUIRMOption = UseRM
Property(S): MONITORING_TOOL = GENERIC
Property(S): ALLOWED_HOSTS = 10.0.0.1,127.0.0.1
Property(S): NSCLIENT_PWD = hEU5x7fHxHGOadVY

**Comment by mickem** [comment]
You need to set CONF_CAN_CHANGE=1 and MONITORING_TOOL=none as well with 0.4.4.and 0.5.0

**Comment by mickem** [comment]
Ahh, thanks for letting me know, will add it...

**Comment by mickem** [comment]
This has been added to the next version of the docs...

**Comment by Zaheerkhan999** [comment]
Thanks it worked.
