### ISSUE TITLE
check_logfile always returns critical status

### ISSUE THREAD

**Issue by FQsqQ** [mickem/nscp#387]
Hello,

I'm trying to use check_logfile in real-time to check the first character of a line in a log file. The line syntax of the log file is **number:text:text**.  If the number is 1, the return status should be critical, if not, status is ok.

While check_logfile captures correctly any modification in the log file, whatever the number is, the returned status is critical.

Here is relevant configuration of nsclient.ini + debug log :  
`NSClient++ 0.5.0.62 2016-09-14 x64`

nsclient.ini :
 
`[/settings/logfile/real-time/checks/Etat_Onduleur]`
`file = c:/test/etat_onduleur.log`
`destination = NSCA,CACHE`
`critical = column1 like '1'`
`empty-state=ok`
`column-split=:`

debug log : 

`2017-02-20 17:16:54: debug:c:\source\master\include\parsers/filter/realtime_helper.hpp:214: Next miss time is in: 300s`
`2017-02-20 17:16:59: debug:c:\source\master\modules\SimpleCache\SimpleCache.cpp:219: Searching for index: Etat_Onduleur`
`2017-02-20 17:16:59: message:c:\source\master\modules\CommandClient\CommandClient.cpp:43: CRITICAL: c:/test/etat_onduleur.log: 1 (RIE:20/02/2017 17:16:54,70 , , )`
`2017-02-20 17:17:04: debug:c:\source\master\include\parsers/filter/realtime_helper.hpp:156: No filters changes detected: `
`2017-02-20 17:17:04: debug:c:\source\master\include\parsers/filter/realtime_helper.hpp:214: Next miss time is in: 290s`
`2017-02-20 17:17:04: debug:c:\source\master\include\parsers/filter/realtime_helper.hpp:156: No filters changes detected: `
`2017-02-20 17:17:04: debug:c:\source\master\include\parsers/filter/realtime_helper.hpp:214: Next miss time is in: 290s`
`2017-02-20 17:17:09: debug:c:\source\master\include\parsers\filter\modern_filter.cpp:14: count is most likely mutating: 2:passage en mode secteur:20/02/2017 17:17:09,73  like 1`
`2017-02-20 17:17:09: debug:c:\source\master\modules\SimpleCache\SimpleCache.cpp:181: Adding to index: Etat_Onduleur`
`2017-02-20 17:17:09: debug:c:\source\master\include\parsers/filter/realtime_helper.hpp:214: Next miss time is in: 300s`
`2017-02-20 17:17:09: debug:c:\source\master\include\parsers/filter/realtime_helper.hpp:156: No filters changes detected: `
`2017-02-20 17:17:09: debug:c:\source\master\include\parsers/filter/realtime_helper.hpp:214: Next miss time is in: 300s`
`2017-02-20 17:17:09: debug:c:\source\master\include\parsers/filter/realtime_helper.hpp:156: No filters changes detected: `
`2017-02-20 17:17:09: debug:c:\source\master\include\parsers/filter/realtime_helper.hpp:214: Next miss time is in: 300s`
`2017-02-20 17:17:13: debug:c:\source\master\modules\SimpleCache\SimpleCache.cpp:219: Searching for index: Etat_Onduleur`
`2017-02-20 17:17:13: message:c:\source\master\modules\CommandClient\CommandClient.cpp:43: CRITICAL: c:/test/etat_onduleur.log: 1 (2:passage en mode secteur:20/02/2017 17:17:09,73 , , )`
`2017-02-20 17:18:12: message:c:\source\master\modules\CommandClient\CommandClient.cpp:115: Ctrl+c is not exit...`

**Comment by FQsqQ** [comment]
After further investigation, seems like there is an issue with the column# parameter. Doesn't seems to stop where needed (column-split not honored ?)
So when checking against number 1 in column1 for critical status, any number 1 in other columns triggered the critical status (here because of the date and time added to the log line).
I got around this by putting terms like ON and OFF in column1 and modified nsclient.ini like this : 

`[/settings/logfile/real-time/checks/Etat_Onduleur]`
`file = c:/test/etat_onduleur.log`
`destination = NSCA,CACHE`
`critical = column1 like 'ON'`
`ok = column1 not like 'ON'`
`column-split=:`

Also the real-time event seems to be triggered only if a new line is added to the log file, but when there is only one line which is overwritten each time, it doesn't pick the change (so not checking for new content but only if new line added).

**Comment by mickem** [comment]
I can confirm that only new data is read unless the file size shrinks.

As for the other issue it should work but I will investigate...

**Comment by mickem** [comment]
It is 

```
column split=:
```
Not
```
column-split=:
```

I will add so dash works as well in the next version to make this simpler...

**Comment by FQsqQ** [comment]
Thanks a lot for the addition !

I used column-split with a dash according to the documentation here :
https://docs.nsclient.org/0.5.1/reference/check/CheckLogFile/#checklogfile 
and also from all the examples I've seen in the forum. Maybe that was for previous versions and changed afterwards ?

But since you modified it there's no more issue now.
