### ISSUE TITLE
QUESTION: PythonScript: Where can I find any information about using metric?

### ISSUE THREAD

**Issue by fanooel** [mickem/nscp#388]
In sample.py there are code:
```python
reg.submit_metrics(submit_metrics)
reg.fetch_metrics(fetch_metrics) sample.py
```
How is it works, how can I use it from nscp or remote clint, or where I can find any information about it?

**Comment by mickem** [comment]
If you enable the webui you can see the values there.
If you enable graphite, they will be sent there as well...

Not sure how you want to use them though...

**Comment by fanooel** [comment]
Ho can I access to metrics using python script? Read or write, sending back to nagios?

**Comment by mickem** [comment]
Providing metrics (i.e. send values to a server):

```
from NSCP import Registry

def fetch_metrics():
    return { "value.1": 42, "value.2": 24}

def init(pid, plugin_alias, script_alias):
    reg = Registry.get(plugin_id)
    reg.fetch_metrics(fetch_metrics)
```

Use metrics:
```
from NSCP import Registry, log

def submit_metrics(list, request):
    for k,v in list.iteritems():
        log("Got metrics: %s = %s"%(k,v))

def init(pid, plugin_alias, script_alias):
    reg = Registry.get(plugin_id)
    reg.submit_metrics(submit_metrics)
```

If you want to fetch metrics from a remote client you can fetch them via the WEBUI or the WebServer at `/metrics`

If you want to send to graphite/collectds you can configure respective modules.

**Comment by mickem** [comment]
Please reopen this if it still does not work
