### ISSUE TITLE
Password in WebServer did not work with an +

### ISSUE THREAD

**Issue by Fiiti** [mickem/nscp#389]
_### using NSCP-0.5.0.62-x64.msi_

Hi,
I am using a password like e. g.  **sA_Ka_ka+**  .
I can set this password and I can read them with `nscp web -- password --display`
But I cannot use them only in the Webclient.
If I remove the **+** char in the ini and restart the service, I can login.

_Unfortunately I am using this Password already on many Server and check_nrpe settings, so it is hard to change them overall._
Bug or feature?

Thanks in advanced for any hints.
Fitti

**Comment by mickem** [comment]
+ is uri encoded for space IIRC so that could be it...

I will check...

**Comment by mickem** [comment]
Will be fixed in the next build
