### ISSUE TITLE
CheckSystem.dll Causing Crash

### ISSUE THREAD

**Issue by tlimlytx** [mickem/nscp#393]
Hi,

We had the module CheckSystem.dll cause nsclient++ to crash. I didn't see anything in the nsclient log as the last error was from a day ago for a perf counter error. Nsclient: 0.3.9.328 2011-08-16. I understand this is an old version of nsclient. What version should we be using? There's two stable versions 0.5.0.62 and 0.4.4.23? Is there any chance to get the chocolatey packages updated to the current stable version?

Details from Event Viewer:
Exception code: 0x40000015
Fault offset: 0x00000000000be3de
Faulting process id: 0x8b70
Faulting application start time: 0x01d1e83c62b1d31e
Faulting application path: C:\Program Files\NSClient++\nsclient++.exe
Faulting module path: C:\Program Files\NSClient++\modules\CheckSystem.dll
Report Id: 22408cd7-01d4-11e7-a3be-02215e5ecac3

**Comment by mickem** [comment]
Could you send a crashdump to crash.nsclient.org ? (via the crash upload tool?)

```
reporter.exe send c888f702-6c02-441b-a616-980c506c70bd.dmp http://crash.nsclient.org/crash_upload
```

**Comment by mickem** [comment]
Please reopen this with a crash dump and/or upload one to the crash server
