### ISSUE TITLE
Some MSI Options not working with NSCP-0.5.0.62-x64.msi

### ISSUE THREAD

**Issue by alexj21** [mickem/nscp#395]
Hello,

I have notice that some MSI Options are not working with NSCP-0.5.0.62-x64.msi on a Win 2012 R2 server.

If I try to execute the command line in the documentation : 
`msiexec /qn /l* log.txt /i NSCP-0.5.0.62-x64.msi INSTALLLOCATION=c:\FooBar CONFIGURATION_TYPE=registry://HKEY_LOCAL_MACHINE/software/NSClient++ ADDDEFAULT=ALL REMOVE=PythonScript`

CONFIGURATION_TYPE is not managed and client installed with shared ini
REMOVE is not manage and PhytonScript is installed

I tried with an another command line and NSCLIENT_PWD, NRPEMODE are also not working

Regards,
Alex

**Comment by mickem** [comment]
You need to add CONF_CAN_CHANGE=1 and MONITORING_TOOL=none

**Comment by mickem** [comment]
Please reopen if you still have issues
