### ISSUE TITLE
[Check_TaskSched] state returned Warning when result is "OK: no tasks found"

### ISSUE THREAD

**Issue by cmeschin** [mickem/nscp#397]
Hi Michael,

I've tested 0.5.0.62  and works with most-recent-run-time option (#380) but when no tasks are on error, the message returned by check is "OK: No task found" and status monitoring is 1 (WARNING)

here is the command used:
`-bash-4.1$ /usr/lib64/nagios/plugins/check_nrpe -H X.X.X.X -p 5666  -t 90 -c CheckTaskSched -a "filter=enabled = 1 AND (task_status='running'  AND most_recent_run_time < -1m) AND folder not like '\\Microsoft'" "syntax= (%(most_recent_run_time) UTC) [exit_code:%exit_code%] statut:%status%" "crit=>0"
`
`CRITICAL: _test_notepad (2017-03-17 16:30:46 UTC) [exit_code:267009] statut:running|'_test_notepad_exit_code'=267009;0;0 'count'=1;0;0`

`-bash-4.1$ /usr/lib64/nagios/plugins/check_nrpe -H X.X.X.X -p 5666  -t 90 -c CheckTaskSched -a "filter=enabled = 1 AND (task_status='running'  AND most_recent_run_time < -5m) AND folder not like '\\Microsoft'" "syntax= (%(most_recent_run_time) UTC) [exit_code:%exit_code%] statut:%status%" "crit=>0"`
`OK: No tasks found|'count'=0;0;0`

```
-bash-4.1$ echo $?
1
```
How can I force returned code at 0 to the check_nrpe?

thanks,

**Comment by mickem** [comment]
Indeed you can:

```
check_tasksched show-default
L        cli OK: "filter=enabled = 1" "warning=exit_code != 0" "critical=exit_code < 0" "empty-state=warning" "top-syntax=${status}: ${problem_list}" "ok-syntax=%(status): All tasks are ok" "empty-syntax=%(status): No tasks found" "detail-syntax=${folder}/${title}: ${exit_code} != 0" "perf-syntax=${title}"
```

The culprit here is: "empty-state=warning" which in your case should be "empty-state=ok"

**Comment by cmeschin** [comment]
Hi Michael,
It's not work.
Some criterias seems not be taken by the module.
I have created a custom command in nsclient.ini to ensure syntax over check_nrpe like this:
`alias_sched_custom = CheckTaskSched "filter=enabled = 1 AND folder not like '\Microsoft'" "syntax=%title% (%(most_recent_run_time) UTC) [exit_code:%exit_code%] statut:%status%" "crit=most_recent_run_time < -$ARG1$ AND task_status = 'running'" "empty-state=ok"`

and when i call alias_sched_custom with ARG1=2m, i receive this in debug log:

`2017-03-27 17:08:27: debug:c:\source\master\modules\CheckTaskSched\CheckTaskSched.cpp:59: Created command: crit=count most_recent_run_time < -2m AND task_status = 'running' filter=enabled = 1 AND folder not like '\Microsoft' detail-syntax=${title} (%(most_recent_run_time) UTC) [exit_code:${exit_code}] statut:${task_status}`
`2017-03-27 17:08:27: debug:c:\source\master\include\parsers\filter\modern_filter.cpp:10: Parsing failed of 'count most_recent_run_time < -2m AND task_status = 'running'' at: most_recent_run_time < -2m AND task_status = 'running'`

When i replace "crit=" by "warn=", i receive no error's but the command passed is:
`2017-03-27 17:00:26: debug:c:\source\master\modules\CheckTaskSched\CheckTaskSched.cpp:59: Created command: filter=enabled = 1 AND folder not like '\Microsoft' detail-syntax=${title} (%(most_recent_run_time) UTC) [exit_code:${exit_code}] statut:${task_status}`

so I assume that the warn criteria is ignored...

Can we specify ore than one criterias in "warn" or "crit" filter?

If I resume my need:
 - check all enabled tasks and not in "Microsoft" directory
 - return a warning state if a task stay running more than 2 hours
 - return a critical state if task failed (exit_code != 0)
 - in all other cases, return ok

Thanks for your help.
regards

**Comment by mickem** [comment]
CamelCase commands use the old syntax and underscore commands use the new syntax so you need to replace CheckTaskSched with check_tasksched.

**Comment by cmeschin** [comment]
Hi Michael,

I used the Migrate option to generate nsclient.ini and this is probably why I maked a mix of the two syntaxes :( .

it works now with this syntax and ini configuration:
nsclient.ini:
 ```
 ;CheckTaskSched = 1
   check_tasksched=1
```
command:
`-c check_tasksched -a "filter=enabled = 1 AND (task_status='running'  AND most_recent_run_time < -120m) AND folder not like '\\Microsoft'" "detail-syntax= %(title) (%(most_recent_run_time) UTC) [exit_code:%(exit_code)] statut:%(task_status)" "crit=count>0" "empty-state=ok"`
Thank you very much for your help.
regards.

**Comment by mickem** [comment]
Module is still called CheckTaskSched.
Only the command have been changed to allow for backwards compatiblity.

Thus you shuld only replace -c CheckTasksched with -c check_tasksched
