### ISSUE TITLE
check_drivesize with multiple warn/crit thresholds does not work

### ISSUE THREAD

**Issue by gitmopp** [mickem/nscp#399]
I followed the instructions from [http://forums.nsclient.org/t/check-drivesize-multiple-warn-crit-thresholds/4227](url) but it does not work for me.
OS Windows 10:
nscp-0.4.4.23-x64:
```
check_drivesize "warning=(used > 55% and drive != 'C') or used > 77%"
L        cli CRITICAL: CRITICAL D:\: 56.619MB/56.619MB used, System-reserviert: 351.586MB/499.996MB used
L        cli  Performance data: 'C:\ used'=16.70755GB;17.33036;28.35878;0;31.50976 'C:\ used %'=53%;55;90;0;100 'D:\ used'=56.61914MB;31.14052;50.95722;0;56.61914 'D:\ used %'=100%;54;89;0;100 '\\?\Volume{b6b3bd03-0000-0000-0000-100000000000}\ used'=351.58593MB;274.99785;449.99648;0;499.99609 '\\?\Volume{b6b3bd03-0000-0000-0000-100000000000}\ used %'=70%;54;89;0;100
```
nscp-0.5.0.62-x64:
```check_drivesize "warning=(used > 55% and drive != 'C') or used > 77%"
L        cli CRITICAL: CRITICAL D:\: 56.619MB/56.619MB used
L        cli  Performance data: 'C:\ used'=16.70759GB;17.33036;28.35878;0;31.50976 'C:\ used %'=53%;55;90;0;100 'D:\ used'=56.61914MB;31.14052;50.95722;0;56.61914 'D:\ used %'=100%;55;90;0;100
```
I also tired used_pct
```
check_drivesize "warning=(used_pct gt 55 and drive != 'C') or used_pct gt 77"
L        cli CRITICAL: CRITICAL D:\: 56.619MB/56.619MB used
L        cli  Performance data: 'C:\ used'=16.71146GB;0;28.35878;0;31.50976 'C:\ used %'=53%;0;90;0;100 'C:\_used_pct'=54;55;0 'D:\ used'=56.61914MB;0;50.95722;0;56.61914 'D:\ used %'=100%;0;90;0;100 'D:\_used_pct'=100;55;0
```

**Comment by mickem** [comment]
What does not work?

**Comment by gitmopp** [comment]
This is the last example from above
```
heck_drivesize "warning=(used_pct gt 55 and drive != 'C') or used_pct gt 77"
L        cli CRITICAL: CRITICAL D:\: 56.619MB/56.619MB used
L        cli  Performance data: 'C:\ used'=16.71146GB;0;28.35878;0;31.50976 'C:\ used %'=53%;0;90;0;100 'C:\_used_pct'=54;55;0 'D:\ used'=56.61914MB;0;50.95722;0;56.61914 'D:\ used %'=100%;0;90;0;100 'D:\_used_pct'=100;55;0
```
Check the performance counter
```
C:\_used_pct'=54;55;0
D:\_used_pct'=100;55;0
```
The warning threshold for both drives is 55.
With the used filter: used_pct gt 55 and drive != 'C') or used_pct gt 77" I expect:
```
C:\_used_pct'=54;77;0
D:\_used_pct'=100;55;0
```
Drive C: should have 77%

**Comment by mickem** [comment]
Ahh, the performance bounds? (I am assuming the check is correct)

Well, currently that is not propagated for a few reasons.
Mainly as it would be next to impossible to implement fully...

What would you expect for performance bounds:
```
warning=(used_pct > 90) or (used_pct < 10)
```
So all in all I think the concept of a "warn" and "crit" threshold is outdated and thus I have opted not to spend too much time on making some possible edge cases...

Important to note: Checks still function, Performance data is still correct.
the only thing wrong is the warn/crit threshold lines.

That said, adding support for different thresholds for different drive letter is planned at some point...

**Comment by gitmopp** [comment]
Okay, got your point.
In my example above was an error, maybe it worked in older version of nscp. It will not work with `drive = 'C'` you have to use `drive = 'C:\\'`
On a test VM the following worked for me with nscp-0.5.0.62-x64 (it will check drive C: and F: with the non default warning theshold).

```
check_drivesize "warning=(used_pct gt 50 and drive = 'C:\\') or (used_pct gt 80 and drive = 'F:\\')"
L        cli WARNING: WARNING C:\: 16.301GB/31.51GB used, F:\: 16.165GB/19.9GB used
L        cli  Performance data: 'E:\ used'=30.3789MB;0;89.99648;0;99.99609 'E:\ used %'=30%;0;90;0;100 'E:\_used_pct'=31;50;0 'C:\ used'=16.30148GB;0;28.35878;0;31.50976 'C:\ used %'=52%;0;90;0;100 'C:\_used_pct'=52;50;0 'F:\ used'=16.16526GB;0;17.91034;0;19.90038 'F:\ used %'=81%;0;90;0;100 'F:\_used_pct'=82;50;0 'D:\ used'=0B;0;0;0;0 'D:\_used_pct'=100;50;0
```
To avoid nasty characters the following could be used:
`check_drivesize "warning=(used_pct gt 50 and drive like str(C:)) or (used_pct gt 80 and drive like str(F:))"`

**Comment by mickem** [comment]
Could be the drive checking logic has been through several iteration when I failed at adding volumes...
I have added a letter keyword you can use which will turn C:\ into C to make transitions easier perhaps. (and safe).
