### ISSUE TITLE
check_files Ignore folders

### ISSUE THREAD

**Issue by Brickius** [mickem/nscp#400]
I am running check_files with "warning= age > 300" to detect files that are older than 5 minutes

But the paths contain subfolders that I want to check the contents of, but not report on the actual age of the folder itself...

Is there a way I can tell the command to filter out folders and only check files?

**Comment by mickem** [comment]
Using the type expression in the filter should do that I guess (depending a bit on exactly what your trying to do)...

```
check_files path=c:\\windows\\system32 "filter=type='dir'"
L        cli OK: OK: All 2103 files are ok

check_files path=c:\\windows\\system32 "filter=type!='dir'"
L        cli OK: OK: All 25517 files are ok
```

**Comment by mickem** [comment]
Please reopen if you still have issues
