### ISSUE TITLE
NSClient++ >= 0.4.4 is causing high CPU load on the monitored server

### ISSUE THREAD

**Issue by op5-support** [mickem/nscp#403]
We have a user who after upgrading from NSClient++ 0.4.4 to 0.5.0_65 where the nscp process is constantly using about 5-10% cpu on the monitored server. They have turned of all checks against those servers but that had no effect at all.  They have tested with 0.5.0_62 as well but with same result.

Turning on debug loggin didn't gave us anything.

The servers has been rebooted since NSClient++ was upgraded but nothing there either.

The have tried this as well but that didn't help either:
`[/settings/core]`
`settings maintenance interval=1h`
`metrics interval=1h`

**Comment by box293** [comment]
Can you please post your nsclient.ini file.

**Comment by mintsoft** [comment]
@op5-support Are you using check_nt to monitor the CPU_LOAD ? If you are, in recent versions of NSClient++ the "1 minute average" is actually an instantaneous value: https://github.com/mickem/nscp/issues/251

If you switch to check_nrpe it doesn't do it for some reason

**Comment by mickem** [comment]
Please see if this version resolves the issue: https://github.com/mickem/nscp/releases/tag/0.5.1.22

**Comment by op5-support** [comment]
Hi!

Thank you for the answers. The cpu usage has been seen on the monitored windows server by using the Performance monitor.

Here is the configuration. The registry is used so this is the output from:
C:\Program Files\NSClient++>nscp settings --list
/modules.CheckDisk=1 
/modules.CheckEventLog=1 
/modules.CheckExternalScripts=1 
/modules.CheckHelpers=1 
/modules.CheckSystem=1 
/modules.CheckTaskSched=1 
/modules.NRPEServer=1 
/modules.NSClientServer=1 
/settings/NRPE/server.allow arguments=true 
/settings/NRPE/server.allow nasty characters=true 
/settings/NRPE/server.insecure=true 
/settings/NRPE/server.ssl options= 
/settings/NRPE/server.verify mode=none 
/settings/NSClient/Server.port=1248 
/settings/core.metrics interval=1h 
/settings/core.settings maintenance interval=1h 

/settings/default.allowed hosts=some ip's 
/settings/external scripts/scripts.some scripts 

/settings/external scripts/wrappings.bat=scripts\\%SCRIPT% %ARGS% 
/settings/external scripts/wrappings.ps1=cmd /c echo If (-Not (Test-Path "scripts\%SCRIPT%") ) { Write-Host "UNKNOWN: Script `"%SCRIPT%`" not found."; exit(3) }; scripts\%SCRIPT% $ARGS$; exit($lastexitcode) | powershell.exe /noprofile -command - 
/settings/external scripts/wrappings.vbs=cscript.exe //T:30 //NoLogo scripts\\lib\\wrapper.vbs %SCRIPT% %ARGS% 
/settings/external scripts.allow arguments=true 
/settings/external scripts.allow nasty characters=true 
/settings/external scripts/wrappings.bat=scripts\\%SCRIPT% %ARGS% 
/settings/external scripts/wrappings.ps1=cmd /c echo If (-Not (Test-Path "scripts\%SCRIPT%") ) { Write-Host "UNKNOWN: Script `"%SCRIPT%`" not found."; exit(3) }; scripts\%SCRIPT% $ARGS$; exit($lastexitcode) | powershell.exe /noprofile -command - 
/settings/external scripts/wrappings.vbs=cscript.exe //T:30 //NoLogo scripts\\lib\\wrapper.vbs %SCRIPT% %ARGS% 
/settings/log/file.max size=10485760 
/settings/modules.CheckExternalScripts=enabled

The last news from our user is that they have removed a bunch of windows patches. That made the NSClient++ calm. So now they are testing to see if they can find out which patch is involved in causing this

**Comment by mickem** [comment]
The nit is not related to the check_nt CPU interval.

Do you know which os version it is?

**Comment by op5-support** [comment]
2012 R2

**Comment by op5-support** [comment]
The customer ran a tool called **procmon** från Microsoft/Sysinternals and attempted to isolate nscp.exe. Not sure if this is useful, but I'm attaching the log (that has been obfuscated slightly regarding company details).
[logfile.csv.txt](https://github.com/mickem/nscp/files/969731/logfile.csv.txt)

**Comment by op5-support** [comment]
Oh, and by the way, our client was unable to install https://github.com/mickem/nscp/releases/tag/0.5.1.22. They received an error message (attached) and after clicking it away, the installation was simply aborted and nothing more happened.
![nynsclient](https://cloud.githubusercontent.com/assets/23208981/25936705/28c51334-3629-11e7-8df1-6390f36e075b.png)

Any other version we can try?

**Comment by mickem** [comment]
https://github.com/mickem/nscp/releases/tag/0.5.1.24 fixes the installer issues...
