### ISSUE TITLE
[check_drivesize] Error: Filter processing failed: Failed to get size for

### ISSUE THREAD

**Issue by Tontonitch** [mickem/nscp#404]
Hello, 

I face a similar problem than #276

Sometime, so not always, I receive the message: 
```
Filter processing failed: Failed to get size for \\?\Volume{f35df341-b623-11e6-80d0-806e6f6e6963}\: 87: The parameter is incorrect.
: 0 > convert(0) and 0 < convert(1073741824)
```

I use NSCP 0.5.0.62
And the default filter on mounted = 1

BR,
Yannick

**Comment by Tontonitch** [comment]
attached an extract of the service history, showing that it's not a permanent result but that it happens quite often.
![history of failed to get size](https://cloud.githubusercontent.com/assets/600025/24860310/4ad318e2-1df4-11e7-91a5-9d1fc10fc7d2.png)

**Comment by mickem** [comment]
My guess would be that the volume (\\?\Volume{f35df341-b623-11e6-80d0-806e6f6e6963}\) "comes and goes" what is that volume?

**Comment by Tontonitch** [comment]
That's a vmware virtual floppy drive, not used but there.
It should not switch from available to non available, that might be a virtualization issue of the floppy drive in our current VMWare Infrastructure version.

I can use the filter "filter=type in ('fixed', 'remote')" to avoid the check of the floppy drive, but the default filter "filter=mounted = 1" is then replaced and non wanted drives come back. Is it possible to filter on multiple clauses?

BR,
Yannick

**Comment by mickem** [comment]
Yes you can add and/or etc in the filter to filter on any number of expressions: https://docs.nsclient.org/howto/checks/#filters
