### ISSUE TITLE
Real-time syntax not working as expected?

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#408]
Whatever syntax I'm trying for the real-time eventlog filters, the events are always sent in the same format.

`Application: 1 (error: )`
`System: 1 (error: Reboot Required: Test 1a)`
`Application: 1 (error: Invalid Trace Directory. Additional Info:[ Invalid Trace Directory (Reporting Process:Trace Diretory is Null. TraceSettings: {Filename: ,FileCountSuffix:1 ,TraceFileSize:10485760 ,TraceDirectory: ,TracingCallStack:No ,IsTracingOff:Yes ,LoadState:LoadSuccessfulUnreported ,RefreshTraceInt:-1 ,SiteWideRefreshTraceInt:-1 ,RegistryRefreshTraceInt:-1 ,Precedence:Default} ] , AppDomain:w3wp))
`

These were my original settings: (from 0.4.1.105)

```
[/settings/eventlog/real-time/filters/default]
destination=NSCA
maximum age= 3d
ok message= eventlog found no records test default
syntax=%type% %id% %source%: %message% 
```

I tried playing around with top-syntax and detail-syntax, but nothing changed for the outgoing events. It also seem so that the event id is not in the output? It seems like the '1' stands for the event count, which is always 1...

```
[/settings/eventlog/real-time/filters/default]
destination=NSCA
maximum age= 3d
ok message= eventlog found no records test default
top-syntax=${status}: ${problem_list}
detail-syntax=${file} ${source} (${message})
```

Any suggestions are welcome. :)

**Comment by willemdh** [comment]
Did some more testes, tried putting the top-syntax en detail-syntax in `[/settings/eventlog]` , in `[/settings/eventlog/real-time]`, in `[/settings/eventlog/real-time/filters/default]` and in `[/settings/eventlog/real-time/filters/EVT_Application]`

```
top-syntax = ${status}: ${count} message(s) ${problem_list}
detail-syntax = ${file} ${id} ${source} (${message})
```

But have not been able to find out how to add the event id in the output.

![image](https://cloud.githubusercontent.com/assets/6462991/25482451/28e1c326-2b52-11e7-910a-ddae127a01bd.png)

As a reference, this is the Powershell code I'm using to test even generation:

```
$evt = new-object System.Diagnostics.EventLog("System")
$evt.Source = "Test2"
$infoevent = [System.Diagnostics.EventLogEntryType]::Error
$evt.WriteEntry("Decription Test Message 3",$infoevent,70)
```

**Comment by willemdh** [comment]
@mickem Any chance you see what I'm doing wrong here?

**Comment by mickem** [comment]
Just guessing from the couch here... But it is top syntax not top-syntax... 

Well actually read this  tomorrow when I have some time...

**Comment by willemdh** [comment]
Didn't try it yet with 'top syntax', I'm at a course all week. I'll test this next week! Tx

**Comment by willemdh** [comment]
Just tested with:

    top syntax = ${status}: ${problem_list}
    detail syntax = ${file} ${id} ${source} (${message})

And the only thing it seems to return is ${status}:

**Comment by willemdh** [comment]
@mickem Did some more tests and I'm one step further atm. So it seems that the issue I was having was
- of course the hyphen between top and syntax (checked it and seems I got that from the check_eventlog documentation where top-syntax is used.)
- but it seems that `${problem_list}` does not returns any results

The moment I add all the variables in `top syntax` like this:

    top syntax=${status}: ${count}: TEST ${problem_list} ${id} ${source} (${message})

I get:

![image](https://cloud.githubusercontent.com/assets/6462991/26441250/11b56f4c-4130-11e7-8de3-4cd39aaf300f.png)

**Comment by willemdh** [comment]
Just fyi, I update my blog post I created in 2015, so it work now for the modern NSClient++. Check out https://outsideit.net/real-time-eventlog-monitoring/

Thanks for the top syntax tip! It seems to work as expected now, so I'll close this one.
