### ISSUE TITLE
Can't make, flag error

### ISSUE THREAD

**Issue by Kneas** [mickem/nscp#409]
Hello !

I'm trying to install the NSCP client on a Ubuntu 10.04.4, but can't. cMake ran without problem and here are the logs of the make, which ends on an error caused by the "--lua_out" flag. 

I figured I'm doing something wrong, so if anyone knows what that is I would be really glad to hear it !

Thank you

[log.txt](https://github.com/mickem/nscp/files/928749/log.txt)

**Comment by mickem** [comment]
Looks like an issue with protobuf compiler not finding the lua generator.
Did you clone with --recursive?

Do you have the output of the cmake run?

**Comment by mickem** [comment]
Please reopen if you still have issues
