### ISSUE TITLE
Queries via Webserver lead to memory hogging

### ISSUE THREAD

**Issue by m-kraus** [mickem/nscp#411]
At several customer sites i use check_nsc_web (https://github.com/m-kraus/check_nsc_web) which queries NSClient via the integrated webserver instead of e.g. NRPE.

This works fine in terms of functionality.

But habing a lot of queries leads to a constantly rising memory consumption of the monitored server.

I tried to build a scenario to test this:
1) I setup two virtual machines, one with Windows 2008R2 and one with Windows 2012R2. I installed NSCLient 0.5.0.62 with an identical nsclient.ini on both machines.

2) After restarting NSClient service, I do 40 consecutive checks via check_nrpe/NRPE and then measure the physical memory consumption of the two machines. This is repeated 500 times, all values are written to InfluxDB.

3) After restarting NSClient service, I do 40 consecutive checks via check_nsc_web/Webserver and then measure the physical memory consumption of the two machines. This is repeated 500 times, all values are written to InfluxDB.

Graphing the measured values in Grafana lead to this:
![2017-04-25_1127](https://cloud.githubusercontent.com/assets/3293494/25379293/da7c2678-29ac-11e7-8041-67e6bc6cf178.png)

The green line shows the memory consumption on the Win2008-Server when querying via NRPE: memory consumption stays the same over time.
The blue line shows the memory consumption on the Win2008-Server when querying via Webserver: memory consumption is constantly rising over time.

The yellow line shows the memory consumption on the Win2012-Server when querying via NRPE and the red line shows the memory consumption on the Win2012-Server when querying via Webserver: the conclusions are not as as on Windows 2008 clear here, but the trend of the red line may point to a rising memory consumption.

In conslusion: at least on Windows 2008 querying the Webserver seems to hog memory over time. This may be also true for Windows 2012.

Please tell me, how can i further assist you in debugging this issue.

Best regards, Michael

**Comment by mickem** [comment]
Please try the latest build and see if this is fixed, I will need to run some more validations myself. but one memory leak has been fixed in the webserver: https://github.com/mickem/nscp/releases/tag/0.5.1.25

**Comment by mickem** [comment]
I have done some tests now and running about 10.000 queries via web does not seem to affect memory in an great deal so if you still have this issue in 0.5.1.25 I would need to now which queries you are running and some more details lie that:

![image](https://cloud.githubusercontent.com/assets/1434697/26042110/ba61cf6a-3932-11e7-9739-b79d6aeb7409.png)

**Comment by mickem** [comment]
Just thought I'd update, another 100.000 requests later and memory is still flat, 14.3Mb when I started, and between 14.3-14.4 Mb now...

**Comment by mickem** [comment]
The graph: 
![image](https://cloud.githubusercontent.com/assets/1434697/26043346/c0196698-393c-11e7-93a0-973aaf41e2b8.png)

**Comment by m-kraus** [comment]
I can confirm, that memory consumption is now flat with 0.5.1.25 - in my case 23.8 MB for nscp.exe. The measurements of overall physical memory usage also show nothing anymore.

Thank you very much!

**Comment by m-kraus** [comment]
Closing this issue al resolved
