### ISSUE TITLE
Nagios «Status Information» doesn’t show the drive status when status is OK

### ISSUE THREAD

**Issue by mcargodi** [mickem/nscp#412]
Hello,
We use «Nagios Core 4.2.4» and plugin «check_npre 3.0.1», with «NSClient++ 0.5.0.62» on Windows servers.
When we check space on a single drive or volume, we want to obtain the following data in Status Information: drive status (OK, Warning or Critical) - according to thresholds set with «warn» and «crit» options - and drive total, free (GB and %) and used (GB and %) space.
We are using the following syntax:

./check_nrpe -H <host address> -c check_drivesize -a "warn=used gt 90%" "crit=used gt 95%" show-all "detail-syntax=%(drive): Total: %(size) - Used: %(total_used) (%(total_used_pct)%) - Free: %(total_free) (%(total_free_pct)%)" drive=C

Unfortunately, with this syntax, «Status Information» doesn’t show the drive status when it’s OK, although it shows the drive status when it’s «Warning» or «Critical». Here are Status Information examples in these 3 different situations:

- C:: Total: 79.656GB - Used: 61.292GB (77%) - Free: 18.364GB (23%)			[result for "warn=used gt 90%" "crit=used gt 95%"]
- warning(C:: Total: 79.656GB - Used: 61.292GB (77%) - Free: 18.364GB (23%))	[result for "warn=used gt 75%" "crit=used gt 95%"]
- critical(C:: Total: 79.656GB - Used: 61.292GB (77%) - Free: 18.364GB (23%))	[result for "warn=used gt 75%" "crit=used gt 75%"]

We use:
a) «show-all» option, to obtain drive total, free and used space when status is OK. If this option is not used and status is OK, «Status Information» is «OK All 1 drive(s) are ok»;
b) «top-syntax» option, not to obtain a duplicated drive status when it’s «warning» or «critical». In fact, without this option, «Status Information» is like this:

- OK C:: Total: 79.656GB - Used: 61.298GB (77%) - Free: 18.358GB (23%)
- WARNING warning(C:: Total: 79.656GB - Used: 61.297GB (77%) - Free: 18.36GB (23%))
- CRITICAL critical(C:: Total: 79.656GB - Used: 61.297GB (77%) - Free: 18.36GB (23%))

Thanks in advance!

**Comment by mickem** [comment]
You can change the "ok-syntax" to be the same as the "top-syntax" in which case the results will be the same.

**Comment by mcargodi** [comment]
Thanks, mickem, for your answer!
We have tried the syntax you suggested ("ok-syntax" = "top-syntax") but we still don't get drive status in «Status Information» when drive status is OK:

./check_nrpe -H XXX -c check_drivesize -a "warn=used gt 90%" "crit=used gt 95%" show-all **"top-syntax=%(status) %(problem_list)"** **"ok-syntax=%(status) %(problem_list)"** "detail-syntax=%(drive): Total: %(size) - Used: %(total_used) (%(total_used_pct)%) - Free: %(total_free) (%(total_free_pct)%)" drive=C
C:: Total: 79.656GB - Used: 12.41GB (16%) - Free: 67.247GB (84%)|'C: used'=12.40968GB;71.69062;75.67343;0;79.65624 'C: used %'=16%;90;95;0;100

I remember that we use «top-syntax» just to avoid a duplicated drive status when status is «warning» or «critical», as we refer at the end of our last message: WARNING warning(..), CRITICAL critical(...).
Should we change «top-syntax»?

We apologize for not having included the top-syntax option in the syntax referred on that message.
Thanks again!

**Comment by mcargodi** [comment]
I'm sorry for having closed this issue by mistake!

**Comment by mickem** [comment]
Sorry I miss understood your question...
And not sure I understand you have the details in all your examples so when it is missing?

**Comment by mcargodi** [comment]
Sorry for not having explained our issue clearly. We will try to improve our explanation.

So, when we use the following sysntax:

- check_nrpe -H <hostname> -c check_drivesize -a "warn=used gt 90%" "crit=used gt 95%" show-all "top-syntax=%(status) %(problem_list)" "detail-syntax=%(drive): Total: %(size) - Used: %(total_used) (%(total_used_pct)%) - Free: %(total_free) (%(total_free_pct)%)" drive=C

we get all the data we want in the «Status Information» **except** drive status, **when status is OK**:

- C:: Total: 79.656GB - Used: 12.423GB (16%) - Free: 67.233GB (84%)

As you can see, «Status Information» **doesn't begin with the word "OK"**, as it should.

**Comment by mickem** [comment]
It is a bug in the handling of show-all which resets the top-syntax.

If you drop show-all doing the substitution manually it works:

```
check_drivesize "warn=used gt 99%" "crit=used gt 99%" "top-syntax=%(status) %(list)" "detail-syntax=%(drive): Total: %(size) - Used: %(total_used) (%(total_used_pct)%) - Free: %(total_free) (%(total_free_pct)%)"
```

What show-all does is attempt to replace problem_list with list.
But as it cant find it in your string since you use %() it fails and assumes the syntax is empty.

**Comment by mcargodi** [comment]
You solved our issue!

We are very grateful for your help!
