### ISSUE TITLE
check_eventlog no perf data

### ISSUE THREAD

**Issue by MHP47** [mickem/nscp#416]
When using check_eventlog, it seems to not print performance data if both WARNING and CRITICAL are defined in the check. See below for example:

```
# /usr/local/nagios/libexec/check_nrpe -H HOSTNAME
I (0.5.0.62 2016-09-14) seem to be doing fine...

# /usr/local/nagios/libexec/check_nrpe -H HOSTNAME -c check_eventlog -a "critical=level in ('error', 'critical')"
CRITICAL: 1 message(s) System TermDD (The Terminal Server security layer detected an error in the protocol stream and has disconnected the client.)|'problem_count'=1;0;0

# /usr/local/nagios/libexec/check_nrpe -H HOSTNAME -c check_eventlog -a "warning=none" "critical=level in ('error', 'critical')"
CRITICAL: 1 message(s) System TermDD (The Terminal Server security layer detected an error in the protocol stream and has disconnected the client.)
```

Also, not sure if this is just me misusing the command, but this behaviour also seems odd:

```
# /usr/local/nagios/libexec/check_nrpe -H HOSTNAME -c check_eventlog -a "critical=level in ('error', 'critical')"
CRITICAL: 1 message(s) System TermDD (The Terminal Server security layer detected an error in the protocol stream and has disconnected the client.)|'problem_count'=1;0;0

# /usr/local/nagios/libexec/check_nrpe -H HOSTNAME -c check_eventlog -a "critical=level in ('error', 'critical') and problem_count > 0"
OK: Event log seems fine|'problem_count'=0;0;0
```

**Comment by mickem** [comment]
Performance data is derived from your check, here you override the default checks and and replace them with your own (which do not gernate performance data) so if you add-in the default ones  you will get performance data for your checks as well.


Something along the lines of:
```
# /usr/local/nagios/libexec/check_nrpe -H HOSTNAME -c check_eventlog -a "warning=count > 0" "critical=level in ('error', 'critical')"
```

**Comment by mickem** [comment]
critical=level in ('error', 'critical') and problem_count > 0

Is not that strange really....
In essence your saying "It is a problem if I have have already found a problem".
Thus nothing is a problem as you dont start-out with any problems...

**Comment by mickem** [comment]
You can see the full default command via:

```
check_eventlog show-default
```

**Comment by mickem** [comment]
Please reopen this if you still have issues
