### ISSUE TITLE
Installation error: Failed to boot settings

### ISSUE THREAD

**Issue by eyala01** [mickem/nscp#421]
Hi,

During installation of NSClient++ 0.5.1.22 x64 on Windows 2012 R2 Standard machine we get a popup error message:

> 1: Failed to boot settings: ++++

After closing this popup, the installation completes, the service is up and running, but we can't access https://localhost:8443.
nsclient.log file contains only one line:
> <date & time>: debug:c:\source\master\service\logger\nsclient_logger.cpp:51: Creating logger: threaded-file

We suspect the problem is with the global security policy.
How can we fix this?

Thanks,
Eyal

**Comment by mickem** [comment]
This has been fixed in 0.5.1.24

**Comment by eyala01** [comment]
Thanks, that was quick.
