### ISSUE TITLE
Windows 2012R2 "trigger start" services are reported as stopped

### ISSUE THREAD

**Issue by mortomanos** [mickem/nscp#424]
In Version 0.5.0.62 Services that are set to "Trigger Start" (e.g. RemoteRegistry) are reported as stopped when using CheckAll.
This already was the case in 0.4.3.88, see #92.

**Comment by mickem** [comment]
Well, they are stopped...

What I usually do is exclude them...
(which I think is the default, but I would have to check)

**Comment by mickem** [comment]
((the default if you use check_service not CheckService))

**Comment by mickem** [comment]
Please reopen this if you still have issues
