### ISSUE TITLE
check_eventlog and problem_count

### ISSUE THREAD

**Issue by ShaggyPG** [mickem/nscp#425]
I'm trying to find if there are to many "logon failed" events in event log (I'm looking for event with ID=4625) but it seems that something is wrong with my query or problem_count or count variable.

Please look at following examples:
1)
check_eventlog scan-range=-15m "filter=id=4625" "file=Security" "critical=count > 3" unique debug truncate=1
After call I get on output:
Crit/warn/ok did not match: Security Microsoft-Windows-Security-Auditing (A)

2)
check_eventlog scan-range=-15m "filter=id=4625" "file=Security" "critical=id=4625, problem_count > 3" unique debug truncate=1
Is not working - expression is not valid

3)
check_eventlog scan-range=-15m "filter=id=4625" "file=Security" "critical=id=4625 or problem_count > 3" unique debug truncate=1
Is returning critical even if there is only one error. If I use "and" operator instead "or" I get "Crit/warn/ok did not match"

4)
check_eventlog scan-range=-15m "filter=none" "file=Security" "critical=id=4625 or problem_count > 3" unique debug truncate=1
is returning
Ignoring unsure result: 4624 = 4625 or 0? > 3

How should I define this check to get critical if there are 3 or more events with specific ID?

I'm referring to manual:
https://docs.nsclient.org/reference/windows/CheckEventLog/#modern-windows-channels
chapter: modern-windows-channels
paragraph: Checking for non errors

there is an example of default filter for warning state:
level = ‘warning’ or problem_count > 0

but changing value at "problem_count > 0"
what I made at my examples 3) and 4) is not giving desired result.

I think it would be cool if we can go back to use old fashioned MaxWarn and MaxCrit arguments to get desired state based on count of filtered events.

**Comment by mickem** [comment]
The first example should work handsomely if you add warning=none.
Please note that most likely wont work in 0.4.x and will be much improved in 0.5.1.

```
check_eventlog scan-range=-15m "filter=id=4625" "file=Security" "critical=count > 3" warning=none unique debug truncate=1
```

The default options can be shown using the following command:
```
check_eventlog show-default
L        cli OK: "filter=level in ('warning', 'error', 'critical')" "warning=level = 'warning', problem_count > 0" "critical=level in ('error', 'critical')" "empty-state=ok" "perf-config=level(ignored:true)" "top-syntax=${status}: ${count} message(s) ${problem_list}" "ok-syntax=%(status): Event log seems fine" "empty-syntax=%(status): No entries found" "detail-syntax=${file} ${source} (${message})" "perf-syntax=${file}_${source}" "unique=1"
```

A working example:
```
check_eventlog "filter=source = 'MYEVENTSOURCE'" warn=none "crit=count > 10" top-syntax="%(count) messages was found" "ok-syntax=No messages found"
L        cli CRITICAL: 16 messages was found
L        cli  Performance data: 'count'=16;0;10
```

```
check_eventlog "filter=source = 'MYEVENTSOURCE'" warn=none "crit=count > 20" top-syntax="%(count) messages was found" "ok-syntax=No messages found"
L        cli OK: No messages found
L        cli  Performance data: 'count'=16;0;20
```

To add some sample messages:
```
eventcreate /ID 1 /L APPLICATION /T ERROR /SO MYEVENTSOURCE /D "Hello"
```
