### ISSUE TITLE
CheckEventLog real-time monitoring: always truncate message by 512 bytes

### ISSUE THREAD

**Issue by maokita** [mickem/nscp#426]
I'm trying to use check eventlog real-time monitoring on Windows Server 2012 R2 to record whole event log message.
I realized that message is always truncated around 500 bytes with real-time filter, but it doesn't huppen with NPRE queries. 
(also the function to truncate message seems to break 2-bytes character like Japanese)

I suspects the following hard-coded value (512) is the root cause of limiting the message length.
Is it possible to increase the value or make it to the variable so as users can change in the next relase?

nscp / modules / CheckEventLog / eventlog_wrapper.cpp:124:
 return eventlog_filter::filter::object_type(new eventlog_filter::new_filter_obj(ltime, name, hEvents[0], hContext, 512));

**Comment by mickem** [comment]
Will be fixed in next build
