### ISSUE TITLE
Installer issues when nsclient.ini file exists

### ISSUE THREAD

**Issue by box293** [mickem/nscp#428]
The issues explained here occur when you do an install of NSClient++ and the nsclient.ini file from a previous install already exists on the computer. To be very clear, only the nsclient.ini file exists in the C:\Program Files\NSClient++\ directory, this issue was not tested against an existing installation.

The issue is that if the nsclient.ini file exists, some of the existing options are used by the installer however the final configuration file created by the installer is incorrect, options are missing.

The configuration items missing are:

```
allowed hosts = xxxx
NSClientServer = 1
```

The first step to reproduce is to perform a clean install of 0.5.0.65, at the installer screen the following (Typical) options are defined and selected:

![selection_034](https://cloud.githubusercontent.com/assets/8356113/26814575/f5ccd6c8-4ac9-11e7-8337-99736cb4abfb.png)

This creates the following config (correct):

```
# If you want to fill this file with all available options run the following command:
#   nscp settings --generate --add-defaults --load-all
# If you want to activate a module and bring in all its options use:
#   nscp settings --activate-module <MODULE NAME> --add-defaults
# For details run: nscp settings --help


; TODO
[/settings/default]

; Undocumented key
password = Str0ngPassw0rd

; Undocumented key
allowed hosts = 127.0.0.1,::1,10.25.5.12


; TODO
[/settings/NRPE/server]

; Undocumented key
verify mode = none

; Undocumented key
insecure = true


; TODO
[/modules]

; Undocumented key
CheckExternalScripts = 1

; Undocumented key
CheckHelpers = 1

; Undocumented key
CheckEventLog = 1

; Undocumented key
CheckNSCP = 1

; Undocumented key
CheckDisk = 1

; Undocumented key
CheckSystem = 1

; Undocumented key
NSClientServer = 1

; Undocumented key
NRPEServer = 1
```

After the installation take a copy of C:\Program Files\NSClient++\nsclient.ini and put it in C:\Temp\

Now uninstall NSClient++.
After it is uninstalled create the directory C:\Program Files\NSClient++\ and place the copy of nsclient.ini in it.

Now run the NSClient++ installer. After selecting Typical the options presented are:

![selection_035](https://cloud.githubusercontent.com/assets/8356113/26814603/1cc03676-4aca-11e7-8650-869a88550307.png)

The `Allowed hosts` has been correctly read from the config file.
A random password is generated, it was not read from the config file.
Enable common check plugins is checked (this is by default)
Enable nsclient server (check_nt) is checked which means it is reading this from the config file (this is NOT a default option)
Enable NRPE server (check_nrpe) is checked (this is by default)
Safe mode is selected (the default selection) however the ini file has Insecure so it is not being read from the config file.

So I make the required changes:

![selection_034](https://cloud.githubusercontent.com/assets/8356113/26814575/f5ccd6c8-4ac9-11e7-8337-99736cb4abfb.png)

After completting the install the following nsclient.ini file replaces the existing one:

```
# If you want to fill this file with all available options run the following command:
#   nscp settings --generate --add-defaults --load-all
# If you want to activate a module and bring in all its options use:
#   nscp settings --activate-module <MODULE NAME> --add-defaults
# For details run: nscp settings --help


; TODO
[/settings/default]

; Undocumented key
password = Str0ngPassw0rd


; TODO
[/settings/NRPE/server]

; Undocumented key
verify mode = none

; Undocumented key
insecure = true


; TODO
[/modules]

; Undocumented key
CheckExternalScripts = 1

; Undocumented key
CheckHelpers = 1

; Undocumented key
CheckEventLog = 1

; Undocumented key
CheckNSCP = 1

; Undocumented key
CheckDisk = 1

; Undocumented key
CheckSystem = 1

; Undocumented key
NRPEServer = 1
```

So you can see that the following configuration items missing are:

```
allowed hosts = 127.0.0.1,::1,10.25.5.12
NSClientServer = 1
```

The problems are:
 - If an nsclient.ini file exists, some values are taken from the ini file and others are not. This is confusing.
 - Options `allowed hosts` and `NSClientServer` are not defined in the ini file if an nsclient.ini file exists

This was identified with 0.4.4.23 originally and tests with 0.5.0.62 and 0.5.0.65 produce the same issue. Tested on Windows 7 32bit OS, Windows 7 64bit OS and Server 2016.

**Comment by mickem** [comment]
Fixed in the next version
