### ISSUE TITLE
about nscp CheckExternalScripts some error?

### ISSUE THREAD

**Issue by mjesse88** [mickem/nscp#430]
Hi mickem,
I have a strange problem:
1.I configure the nsclient to monitor windows with NSCA.many machines are OK
2.but one machine all my script return  -1073741502  in my nagios
![image](https://user-images.githubusercontent.com/19406155/26858206-7c9f0caa-4b62-11e7-9229-f4b5188c665c.png)

I use test:
1.nscp client --query check_log It is OK
![image](https://user-images.githubusercontent.com/19406155/26858276-cca12b2a-4b62-11e7-850f-62e98baf71d9.png)
2.I net stop nscp then nscp test all thing is ok
![image](https://user-images.githubusercontent.com/19406155/26858503-20ce96b4-4b64-11e7-8ae9-ce8fbfebf817.png)

do I miss something or some mistake?

btw:
the log only show:
c:\source\nscp\modules\Scheduler\Scheduler.cpp:88: Ran scheduled item 3 13 seconds to late from thread x
I can not find what's happen.

and I try test on 0.4.4.19 and 0.5.0.62

Thanks
Jesse

**Comment by mickem** [comment]
If the scheduler is late it could be due to commands timing out maybe?
But all i all, I dont really know what could be causing it, do a "simple bat script work"?

**Comment by mjesse88** [comment]
mickem,
Thanks for you respone.
1).if It appear this problem. I try to use easy scrip to test it. the  problem also exist.
script:
 @echo off
  echo "This is test"
  return 0

2)I try to I reboot the computer. This problem is gone, but It sometime appear again. so It could be a false alert for me.


3.I will try to do something too

Thanks again
Jesse

**Comment by mickem** [comment]
Not sure I understand but I think you mean the problem was resolved when you rebooted? If not reopen the ticket with a bit more details...
