### ISSUE TITLE
Downloading script attachments without restart

### ISSUE THREAD

**Issue by MHP47** [mickem/nscp#431]
This is just a question, please tag as appropriate.

I'm using the `[/attachments]` section of the config file, hosted on a web server. This works fine, the clients are pulling the changed config, and it appears to apply correctly.

The problem I'm having is, the script itself doesn't seem to be downloaded, and thus available to be executed, until the service is restarted. Is there anyway to work around this? I've got NSClient deployed to hundreds of machines, and if there's a way to not require a service restart of each of them when a new script is added, that'd be great :)

The relevant part of my config:
```
[/attachments]
scripts/myscript.bat = http://web_server/myscript.bat

[/settings/external scripts/scripts]
foo=scripts\myscript.bat
```

And running the `foo` command on a server without a restart gives:
`Failed to execute foo: 2: The system cannot find the file specified.`
After a service restart, it works fine:
`OK: Things are working`

**Comment by mickem** [comment]
0.5.1 should periodically poll the servers and restart when there are changes...

**Comment by MHP47** [comment]
Hey mickem, that sounds like an awesome feature :)
Do you have any rough timeline when 0.5.1 will be a stable release?

**Comment by mickem** [comment]
I'd say soon, but I have been saying that for quite some time... My plan is to spend some time over the next few weeks to finish off the last few things I am working on and then release a new RC and we shall see what happens from there...

If you ask me it is pretty stable, but I have tinkered with the installer which can cause all sort of unexpected incompatibilities for people with automatic installers...


// Michael Medin

**Comment by mickem** [comment]
This has been out now for quite some time...
