### ISSUE TITLE
API: Add support for X-HTTP-Method-Override to send a request body

### ISSUE THREAD

**Issue by dnsmichi** [mickem/nscp#435]
This would allow you to send additional URL arguments as JSON body. That way you don't have to care about URL encoding in URL parameters.

```
$ curl -k -s -H 'password: icinga' -H 'X-HTTP-Method-Override: GET' -X POST 'https://192.168.2.109:8443/query/check_drivesize' -d '{ "drive": "E:"}'
```

**Comment by dnsmichi** [comment]
❤️

**Comment by mickem** [comment]
To be honest I only implemented the verb not any json parsing to query string, so you might wanna reopen this once you actually try it :)

**Comment by dnsmichi** [comment]
Heyyyy :-P

**Comment by dnsmichi** [comment]
I'm looking forward to your OSMC talk showing exactly this :-)
