### ISSUE TITLE
Windows Firewall rule naming issue

### ISSUE THREAD

**Issue by freni59** [mickem/nscp#436]
I'm working in a pretty automated environment so our nsclient++ package is distributed through Chocolatey and configuration in handled through Puppet. Some time ago one colleague mentioned that the Windows Firewall rule was a little "loose" and as default specified the remote address to "any". Of course one would like to change this to a specified address (or array of addresses), I assume you can limit access to the agent it self through "allowed hosts", but I also assume that this is not reflected in the Firewall rule and in some environment it would be desirable to tighten the firewall rule it self as well.
That is where my problem have arisen. The firewall rule has a pretty good DisplayName being "NSClient++ Monitoring Agent" but it seems like the Name is not set to anything so Windows assigns it a GUID-looking ID as Name instead. The DSC resource xFirewall, which seems a good way to interact and tighten the rule needs the Name parameter to be set i believe it's needed to make a positive match with an existing rule. This kind of gets a little difficult when the name is individual to each machine. From this point of view it would be desirable if the name was set to a less individual value, in short given a better name.

DisplayName : NSClient++ Monitoring Agent
Name             : {655301AD-67A3-4D80-AC69-47EC8A4A5F74}

I'm gonna work around this with a custom fact, so I can no the Name on beforehand, but I think it would be nice with a better name...

**Comment by mickem** [comment]
I have looked into this and I cant find any way with WIX http://wixtoolset.org/documentation/manual/v3/xsd/firewall/firewallexception.html to control the name.

So I am not sure it is possible...

**Comment by mickem** [comment]
Please also note that NSClient++ will itself do address validation, but of course the firewall is a more secure option...

**Comment by mickem** [comment]
Please reopen this if you need further help or using the name is not possible...
