### ISSUE TITLE
Powershell commands return an invalid return code: -1073741502

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#437]
Hello,

I have one Windows Server 2012 R2 with NSClient 0.5.1.28 which regularely runs into weird problems when executing Powershell commands. All native NSCLient++ checks keep working, only Powershell scripts fail. 
When I try to execute the Powershell scripts manually on the Windows server, it works normally.

The only solution I found is to reboot the server. Restarting NSClient++ doesn't help. After a reboot the Powershell script work again for +- 5-7 days.

In the Windows application eventlog I can see this error 1000:

```
Faulting application name: cmd.exe, version: 6.3.9600.17415, time stamp: 0x545042b1
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18438, time stamp: 0x57ae642e
Exception code: 0xc0000142
Fault offset: 0x00000000000ecdd0
Faulting process id: 0xf78
Faulting application start time: 0x01d2f0fe881fcd7d
Faulting application path: C:\Windows\system32\cmd.exe
Faulting module path: KERNELBASE.dll
Report Id: c621c11b-5cf1-11e7-80d0-901b0e825510
Faulting package full name: 
Faulting package-relative application ID: 
```

In the Windows System eventlog I can see this error 10010:

```
The server {73E709EA-5D93-4B2E-BBB0-99B7938DA9E4} did not register with DCOM within the required timeout.
```

We tried to repait WMI but it didn't help. Anyone experienced this before?

Grtz

Willem

**Comment by mickem** [comment]
Does the powershell script timeout by nsclient++? (sounds like an issue with timeouts)
(i.e. is it taking long to execute).

All powershell commands are "forked" so sounds fishy that they should stop working....

**Comment by willemdh** [comment]
Closing this, as it's a bit old and as a workaround we are using an alternative agent on servers experiencing issues with nsclient
