### ISSUE TITLE
check_updates.vbs returns ok if Windows Update service is disabled

### ISSUE THREAD

**Issue by sz-blacky** [mickem/nscp#438]
If the Windows Update service is disabled, running the check_updates.vbs script fails with an error message explaining that the service could not be started, but the wrapper script still returns a zero exit code.

The attached patch adds an extra check using WMI at the beginning of the script to ensure that the service is not disabled. If the service is disabled, it returns UNKNOWN.
[Check_WU_Service-patch.txt](https://github.com/mickem/nscp/files/1117136/Check_WU_Service-patch.txt)

**Comment by mickem** [comment]
Applied, thank you...
