### ISSUE TITLE
API: Add fine grained permissions

### ISSUE THREAD

**Issue by dnsmichi** [mickem/nscp#449]
Based on #448 it would be great to have fine grained permissions on API queries.

Most of them are covered in the documentation: https://github.com/mickem/nscp-docs/blob/master/docs/api/index.md#query-endpoint

Permissions should be defined as array

Example

- `*` - do anything, dangerous
- `query/*` - any query
- `query/check_drivesize` specific queries only
- `settings/status`
- `core/reload`

We use a similar system in Icinga 2, if you are interested in sharing code or ideas.

The default should be "nothing", i.e. the admin must explicitly define permissions for the created user. If a user explicitly requires admin privileges such as `core/reload`, those must be set then. A normal check plugin called from remote normally does not need this for read-only requests.

This should also be taken into account for future plans on a more RESTful API :)

**Comment by mickem** [comment]
Implemented
