### ISSUE TITLE
External script works in test mode, not when NSClient++ is run as a service

### ISSUE THREAD

**Issue by LeroyTennison** [mickem/nscp#457]
This is the script:

extrnl.bat
@echo off
:: Get the number of threads associated with the service, should be > 14
for /f "usebackq" %%a in (`D:\cygwin\home\admin\bin\pslist -d ourservice 2^>nul ^| d:\cygwin\bin\grep ^^[0-9]{3} ^| d:\cygwin\bin\wc -l`) do set threads=%%a
if %threads% GTR 14 goto next
echo Number of threads: %threads%
exit 2
:next
:: Get current date/time in seconds
for /f "usebackq" %%b in (`D:\cygwin\bin\date +%%s`) do set numsec=%%b
:: Get YYYYMMDD for use in filename
for /f "usebackq" %%c in (`D:\cygwin\bin\date +%%Y%%m%%d`) do set curdate=%%c
:: Get file update date/time in seconds for the log file
for /f "usebackq" %%d in (`D:\cygwin\bin\stat -c %%X /cygdrive/d/ourapp/Logs/ourservice/ourservice_%curdate%.log`) do set filesec=%%d
set /A difsec= %numsec%-%filesec%
:: File should have been updated in the last 15 minutes, add 15 seconds to be safe
if %difsec% LSS 915 goto ok
echo Log file age %difsec% seconds
exit 2
:ok
echo OurService OK
exit 0

nsclient.ini has (originally used wrapped scripts, converted to non-wrapped as an alternative):
[/settings/external scripts/scripts]
check_ourservice=c:\\ourapp/extrnl.bat

Running the current 32-bit version of nscp ("nscp test") on Windows Server 2003 (I know, really old, extenuating circumstances) at an administrative prompt starts successfully, entering check_ourservice returns the correct path/filename along with the expected results, returning to the prompt within 2 seconds.  '/usr/lib/nagios/plugins/check_nrpe -H <IP address> -c check_ourservice' from the server (current icinga version for Ubuntu 16.04 LTS) produces the same result.  Shutting down test mode and starting NSClient++ from Windows Services (Log on as Local System Account) produces "CHECK_NRPE: Socket timeout after 10 seconds."  Pinging the NSClient++ system from the server returns times in the 3-4 millisecond range.

The only other clue I have is in the log (set to debug level): error:c:\source\master\include\socket/connection.hpp:120: Socket was unexpectedly closed trying to send data (possibly check your timeout settings)".  I'm not setting any values on the client or server and the script completes in well under 10 seconds.

Anything else I can do to isolate the issue or resolve the problem?  Thanks for your help.

**Comment by mickem** [comment]
Works for me with windows 2003 (SP2)
Fresh NSClient 0.5.62 install:

Then:

```
cd "c:\program files\nsclient++"
del nsclient.ini
nscp ext install --script scripts\check_ok.bat
nscp nrpe install --insecure --allowed-hosts 127.0.0.1,::1
nscp service restart

check_nrpe --insecure --host 127.0.0.1 --command check_ok
OK: Everything is going to be fine
```

So this means scripts are working... then *YOUR* scripts needs to be working which might require privileges and what not but that is unfortunately not something I can help with :)

So, please reopen with more details if you still have issues with simple scripts on windows 2003 or some other specific feature of NSClient++.
// Michael Medin
