### ISSUE TITLE
NSClient Forum: No login/sign-up via GitHub

### ISSUE THREAD

**Issue by log1-c** [mickem/nscp#463]
I know this probably is not the right place for this, but I hope it is okay:

I just tried to sign up/login to the Nsclient-Forum using my github account.
When clicking on the GitHub icon I get redirected to the gitHub login, enter username and password and then get redirected back to the forum and get this message:
![image](https://user-images.githubusercontent.com/24474580/29764162-665e70c0-8bd6-11e7-932f-cce72dcbf1c2.png)

After logging into github there is no possibility to allow/deny access as I get instantly redirected back to the forum.

I hope I described this understandably.

Greetings!

**Comment by mickem** [comment]
Sorry, I hope I have fixed this now, please do let me know, and pleas verify it works for BOTH http (should be redirected to https now) and https... Feel free to also verify twitter and google...

I have verified them but I already had accounts so you never know...

**Comment by log1-c** [comment]
Thanks for the quick fix :)
Redirect to https works!
Signup with GitHub also works!
Can't verify the other to, sorry.
