### ISSUE TITLE
key value keeps strange characters for allowed hosts - (0.5.0.65 -> 0.5.1.44)

### ISSUE THREAD

**Issue by nmat** [mickem/nscp#464]
I just tested to upgrade from 0.5.0.65 -> 0.5.1.44 and noticed special characters removed in includes but are kept in allowed hosts

Name                           Property
----                           --------
default                        allowed hosts : 127.0.0.1,::1 Ȁ   Ͽ 澬愆∀

I upgraded using the commandline with:
msiexec /qn /l* log.txt /i NSCP-0.5.1.44-x64.msi MONITORING_TOOL=OP5

Standard first install was done with wizard.

![capture](https://user-images.githubusercontent.com/383031/29897121-cd08d6b6-8ddf-11e7-97d9-cea6e3356bb7.PNG)

OS: Windows server 2016

**Comment by mickem** [comment]
Upgrading wont change existing keys (unless you override them).

The fix for invalid chars is when you write new keys...

**Comment by nmat** [comment]
that makes sense. I will close this ticket.

**Comment by mickem** [comment]
If you want to clean up you can migrate to/from ini files and it should be cleaned up...

```
nscp settings --migrate-to ini
nscp settings --migrate-to registry
```
