### ISSUE TITLE
Help on CheckEventLog

### ISSUE THREAD

**Issue by sder73** [mickem/nscp#468]
Hello
I am trying to use real time CheckEventLog on a windows system to send information to our Centreon Linux Server
The NSCA part seems OK
Have some example of nsclient.ini with implementation CheckEventLog in real time and some examples of event filtering
I found nothing on tis subject on the net (May be I do not look at the right place)
Thank you

**Comment by mickem** [comment]
Have you read the documentation: https://docs.nsclient.org/reference/windows/CheckEventLog/#using-real-time-monitoring
Let me know if there is something missing in it or something which needs to be explained better...
