### ISSUE TITLE
check_memory - spikes over the total physical memory

### ISSUE THREAD

**Issue by nmat** [mickem/nscp#471]
Noticed the memory usage checked spiked. However the percent did not and it goes above the value of how much memory is actually on the server: 8GB is the memory total on the server but the graph shows a usage of 800GB?

NSClient++ version: 0.5.1.45
Monitoring system: OP5
Template: default template

**command used:**
`$USER1$/check_nrpe -H $HOSTADDRESS$ -c "check_memory" -a "type=$ARG1$" "detail-syntax=%(type): Total: %(size) - Used: %(used) (%(used_pct)%) - Free: %(free) (%(free_pct)%)" "warn=$ARG2$" "crit=$ARG3$"`

**Input (services.cfg):**
```
# service 'Memory Usage - Physical'
define service{
    use                            default-service
    host_name                      xxxx
    service_description            Memory Usage - Physical
    check_command                  check_nrpe_win_memory!physical!free < 800M!free < 500M
    ...
    }
```

See screenshot.
![wrong_value_on_memory_used](https://user-images.githubusercontent.com/383031/30741506-4feabe98-9f95-11e7-9ade-2d11a7c89110.PNG)

**Comment by mickem** [comment]
Do you have the textual value from when it spiked? The units scale so if the grapher does not respect the chaning units that could be it?

**Comment by nmat** [comment]
forcing perf-config=*(unit:G) did solve it. Might be good to have the docs however?
