### ISSUE TITLE
check_drivesize perf-config gets ignored when using warn=free<xxx

### ISSUE THREAD

**Issue by peter-funktionIT** [mickem/nscp#473]
I want to change the performance data output for check_drivesize, so I am using 
`"perf-config=used(suffix;unit:m) used %(ignored:true)"`

But when combined with both warn=free<xxx% or crit=free<yyy% the perf-config gets changed.

I was running 0.5.1.22 and just upgraded to 0.5.1.45, but the behaviour seems to be the same.

This works:
`check_drivesize drive=C: "perf-config=used(suffix;unit:m) used %(ignored:true)" warn=used>85% crit=used>95%`
`L        cli OK: OK All 1 drive(s) are ok`
`L        cli  Performance data: 'C:'=26581.11718m;48870.39687;54979.19648;0;61087.99609`

This gives wrong performance output:
`check_drivesize drive=C: "perf-config=used(suffix;unit:m) used %(ignored:true)" warn=free<15% crit=free<5%`
`L        cli OK: OK All 1 drive(s) are ok`
`L        cli  Performance data: 'C: free'=33.69811GB;11.93124;0;0;59.65624 'C: free %'=56%;20;0;0;100`

It gets even weirder if I try to ignore "free" and "free %" in perf-config;

If I only pass one of warn or crit, it works:
`check_drivesize drive=C: warn=free<15% "perf-config=used(suffix;unit:m) used %(ignored:true) free(ignored:true) free %(ignored:true)" "top-syntax=DISK %(status) - %(list)"`
`L        cli OK: DISK OK - C:: 21.479GB/39.656GB used`
`OK: DISK OK - C:: 21.479GB/39.656GB used`
`L        cli  Performance data: 'C:'=21994.96875m;0;36547.19648;0;40607.99609`

If I pass both warn AND critical, I get no performance data at all:
`check_drivesize drive=C: warn=free<15% crit=free<5% "perf-config=used(suffix;unit:m) used %(ignored:true) free(ignored:true) free %(ignored:true)" "top-syntax=DISK %(status) - %(list)"`
`L        cli OK: DISK OK - C:: 21.479GB/39.656GB used`
`OK: DISK OK - C:: 21.479GB/39.656GB used`

**Comment by mickem** [comment]
This is expected...

Lets break down your config:
```
... "perf-config=used(suffix;unit:m) used %(ignored:true) free(ignored:true) free %(ignored:true)" ...
```
* used: empty suffix, uni m
* used %: removed
* free: removed
* free %: removed

Performance data is generated from the bound you have (or explicit config).

In the regular case there is a default check which is:

```
check_drivesize show-default
L        cli OK: "filter=mounted = 1" "warning=used > 80%" "critical=used > 90%" "empty-state=unknown" "top-syntax=${status} ${problem_list}" "ok-syntax=%(status) All %(count) drive(s) are ok" "empty-syntax=%(status): No drives found" "detail-syntax=${drive_or_name}: ${used}/${size} used" "perf-syntax=${drive_or_id}"
```
The interesting bit here is:
* warning=used > 80%
* critical=used > 90%

This means you get `used` and `used %`performance data (which in your case means used gets renamed, and used % gets removed.

Now if you change the warning bound you get:
* warning=used > 80%
* critical=free > 90%

This will give you `used` and `used %`as well as `free`and `free %`performance data (which in your case means used gets renamed, and used %, free, and free % gets removed.

Now for the final case:
* warning=free > 80%
* critical=free > 90%

This means only get `free`and `free %`performance data (which in your case means they both get removed as you ignore all free...
