### ISSUE TITLE
NSClient Error: invalid password

### ISSUE THREAD

**Issue by Sface20** [mickem/nscp#474]
Im currently using Nagios XI 5.4.10 to monitor both linux and windows machines. However i encounter this error when trying to monitor CPU, Disk usage , and Memory usage on a windows 7 laptop. I have already edited the password in the nclient.ini file and made sure the same password was applied to the Nagios server via the web console but still to no avail. I have also tried leaving the passwords blank but it didnt change a thing. 

P.S its my first time with nagios so knowledge is limited.

**Comment by box293** [comment]
Could you please create a post in the Nagios Support Forums here:
https://support.nagios.com/forum/viewforum.php?f=6

When creating the forum post can you please paste the `nsclient.ini` file into a code block and provide the exact error messages you are experiencing. Screenshots help.

**Comment by Sface20** [comment]
Alright ill post over there
