### ISSUE TITLE
Arguments problem with check_nscp_nrpe 

### ISSUE THREAD

**Issue by plessier** [mickem/nscp#475]
Hello,

I use alias with argument on my nsclient++, I can use it with nagios check_nrpe but not with check_nscp_nrpe because it can use only one argument, it didn't pars on each variables
 
exemple
In nsclient.ini
alias_memory = CheckMEM MaxWarn=$ARG1$ MaxCrit=$ARG2$ ShowAll type=$ARG3$
Command
check_nscp_nrpe address=vw8fr04ps:5666 allowed-ciphers=ADH command=alias_memory argument=90l
returne
Failed to validate filter see log for details: Critical expression is not valid:used>=$ARG2$
in log client
2017-10-05 19:33:58: debug:c:\source\master\include\compat.cpp:40: Created command: warn=used>=90 crit=used>=$ARG2$ show-all "detail-syntax=%(type): Total: %(size) - Used: %(used) (%(used_pct)%) - Free: %(free) (%(free_pct)%)" type=$ARG3$
2017-10-05 19:33:58: debug:c:\source\master\include\parsers\filter\modern_filter.cpp:29: Parsing failed of 'used>=$ARG2$' at: >=$ARG2$
For me it's a good 
but when more than one argument
Command
check_nscp_nrpe address=vw8fr04ps:5666 allowed-ciphers=ADH command=alias_memory argument=90 95 physical
check_nscp_nrpe address=vw8fr04ps:5666 allowed-ciphers=ADH command=alias_memory argument="90 95 physical"
there is no return and no trace in client for the two command

How, I can use more than one arguments

Cheers

**Comment by plessier** [comment]
I think to solved my problem is to used batch option but i have a problem, my arg are seperate by a space and not a | and when I change separator nothing change
exemple 
Command
 check_nscp_nrpe address=vw8fr04ps:5666 allowed-ciphers=ADH batch="alias_memory|90|95|physical"
return
physical: Total: 4GB - Used: 2.264GB (56%) - Free: 1.735GB (43%)|'physical'=2.26406GB;3.5996;3.79958;0;3.99955 'physical %'=57%;90;95;0;100#
Command with other separator
check_nscp_nrpe address=vw8fr04ps:5666 allowed-ciphers=ADH separator=" " batch="alias_memory 90 95 physical"
return
Unknown command(s): alias_memory 90 95 physica]#
Same result with a coma

**Comment by mickem** [comment]
Standard "-a" handling should work just fine...

```
check_nscp_nrpe --address vw8fr04ps:5666 --allowed-ciphers ADH --argument alias_memory 90 95 physical
```

Should work just fine (pretty much like regular check_nrpe)

**Comment by plessier** [comment]
Hello,
I tested with --argument but withou succes, with -a it's work perfectly
check_nscp_nrpe --address vw8fr04ps:5666 --allowed-ciphers ADH  --command alias_memory -a 90 95 physical

Thanks you for your help. I think it could be interesting to display this option when you call help command (check_nscp_nrpe --help). I'm courious why -a and not --a?

You have created a very good product.

**Comment by mickem** [comment]
Both work for me:

![image](https://user-images.githubusercontent.com/1434697/31627855-0bd26f62-b2af-11e7-8062-9bbdaab651af.png)


most --something have a shorthand -s unfortunately the documentation is geared more towards the internal nsclient client commands and thus does not show the -- and -

**Comment by plessier** [comment]
Bonjour,

my apologies, it works, I had to mix two tests
What does not work is with the argument without dash and with equalities.
Command
check_nscp_nrpe --host vw8fr04ps --port 5666 --allowed-ciphers ADH 
--timeout 120 --command alias_memory --arg 90 95 physical
return 
physical: Total: 4GB - Used: 2.602GB (65%) - Free: 1.398GB 
(34%)|'physical'=2.60189GB;3.5996;3.79958;0;3.99955 'physical 
%'=65%;90;95;0;100
Command
check_nscp_nrpe host=vw8fr04ps port=5666 allowed-ciphers=ADH timeout=120 
command=alias_memory arg=90 95 physical
Return 
Failed to parse command line re-run with help to get help: unknown option 
95

Just for your information --ar and --arg and --argu .... return the goog 
result


Cordialement

David PLESSIER
System Administrator, Dailycer SAS - D. PLESSIER@DAILYCER-FR.COM
Phone : +33 (0) 322 787 644 / FAX: +33 (0) 322 783 290


WARNING: information & attached files of this mail are only intended for 
the above mentioned addressees. Review, dissemination or disclosure is 
strictly prohibited. If you receive this email by error, please destroy it 
immediately. Thank you.
