### ISSUE TITLE
check_process: Invalid packet type received from server.

### ISSUE THREAD

**Issue by eroji** [mickem/nscp#480]
I am trying perform my checks using the latest NSClient++ 5.1.44 via NRPE with SSL authentication required for security. I am using the latest NRPE v3.2.1 on my Nagios server, which is running 4.3.1. Previously the checks were done via check_nt, but that appears to be deprecated so I am working on replacing the checks using check_nrpe. It looks like the equivalent of SERVICESTATE is now check_process.

```
/opt/nagios/libexec/docmagic/check_nrpe -A /opt/nagios/ssl/nrpe_ca.pem -C /opt/nagios/ssl/nrpe_check.pem -K /opt/nagios/ssl/nrpe_check.key -H sqlserver -p 5666 -c check_process process=sqlservr.exe
```
It should return back with the service state but this is the result I get.

```
CHECK_NRPE: Invalid packet type received from server.
```

**Comment by mickem** [comment]
`SERVICESTATE` would be `check_service`

As for this:
```
CHECK_NRPE: Invalid packet type received from server.
``` 

Try with check_nrpe 2.x instead of 3.x or better yet switch to REST...

**Comment by mickem** [comment]
please reopen if you have issues with supported NRPE client
