### ISSUE TITLE
compatibility matrix between client and server

### ISSUE THREAD

**Issue by plessier** [mickem/nscp#482]
Hello,

I had lof ot stranges returns with check_nrpe, at the beginning I thinked it was a problem with the nsclient. For me the check_nrpe 2.x return some time diffrent error with no sense.
After test with the version check_nrpe 3 some of "Invalid packet type received from server" has  replace by an answer of the nsclient.
Since I use the check_nscp_nrpe this type of problem has been solved.
 I think some version aren't compatible between them.

Have you a compatibility matrix between client and server ?

**Comment by mickem** [comment]
You mean something along the lines of:

**Supported NSClient++ 0.2.x, 0.3.x, 0.4.x:**
* "vanilla" check_nrpe 2.x (requires insecure flag in 0.4.3 and later)
* check_nt

**Supported clients NSClient++ 0.4.3:**
* "vanilla" check_nrpe 2.x (requires insecure flag in 0.4.3 and later)
* check_nt
* check_nscp_nrpe

**Supported clients 0.5.0:**
* "vanilla" check_nrpe 2.x (requires insecure flag in 0.4.3 and later)
* check_nt
* check_nscp_web

**Supported clients 0.5.2:**
* "vanilla" check_nrpe 2.x (requires insecure flag in 0.4.3 and later)
* check_nt
* check_nscp_web
* check_nscp

**Supported clients 0.6.0:**
* check_nscp_web
* check_nscp

**Comment by mickem** [comment]
NSClient++ | check_nt | check_nrpe 2.x | check_nscp_nrpe | check_nscp_web | check_nscp
--|--|--|--|--|--
0.2.x | X | X | | | | 
0.3.x | X | X | | | | 
0.4.0 | X | X | | | | 
0.4.1 | X | X | | | | 
0.4.2 | X | X | | | | 
0.4.3 | X | X | X | | | 
0.4.4 | X | X | X | | | 
0.5.0 | X | X | X | X | | 
0.5.1 | X | X | X | X | | 
0.5.2 | X | X | X | X | X | 
0.6.0 |   |   |   |   | X |

**Comment by mickem** [comment]
And FIY **I will NOT "remove" support for the older protocol in 0.6.0** but I will deprecate them as they are insecure and I would like to move forwards with rest, but they will still be supported for the foreseeable future...

Also please note this list does not include, SMTP, NSCA, check_mk, NRDP, SysLog, Graphite, CollectD etc etc...
