### ISSUE TITLE
NSClient++0.5.1.45 - Install Insufficient Privileges

### ISSUE THREAD

**Issue by selleryp** [mickem/nscp#483]
I am having some difficulties installing NSClient++0.5.1.45.
Half way through the install it fails with the following:

'Service 'NSClient++ Monitoring Agent' (nscp) could not be installed. Verify that you have sufficient privileges to install system services'.

I am part of the local admins on this server and have tried running as Admin. I have even tried running the .msi file from an elevated command prompt.

The server is running Windows Server 2008R2 Standard
It was running NSClient++ 4.3.8 without any issues, but I am upgrading the plugin to use a newer feature.

Thanks
Paul

**Comment by plessier** [comment]
Hello,

did you try with a low uac?
verify if you don't have a lock on the file. right click on the right bottowm under advanced "unclock". This lock can display the message.

**Comment by selleryp** [comment]
Lowering UAC settings seems to have resolved the issue and the client has now installed successfully.
Thanks for the advice @plessier 

Paul
