### ISSUE TITLE
explorer.exe not running

### ISSUE THREAD

**Issue by nickprice121** [mickem/nscp#484]
when running NSCP 0.5.0.62 on windows machines and testing with nagios NRPE for explorer.exe is running or not it shows it as running after updating to 0.5.1.44 it now shows it as not running even though it is.

Using Nagios latest version on a Linux server

nothing else has changed only updated NSCP.

any help please

**Comment by mickem** [comment]
Which command do you use?

**Comment by nickprice121** [comment]
Hi Michael


We had a maintenance day on our PC 's yesterday this required a restart.

The restart has cured the problem.


I don't understand why as explorer.exe was running before the restart


Thanks


Nick Price


________________________________

**Comment by mickem** [comment]
Strange indeed, if you have som more details and/or it happens again, please do reopen this issue...

**Comment by nickprice121** [comment]
Hi Michael


Update.


If I reboot the PC I need to restart the exeploer.exe process after rebooting is finished to clear the error.


I have this on all PC's that have been updated to latest version.


All PC's have the config from the previous versions.





________________________________
