### ISSUE TITLE
0.5.2.11 has spurious log and (possibly) problematic authentication

### ISSUE THREAD

**Issue by mintsoft** [mickem/nscp#485]
### Issue and Steps to Reproduce

Enable webserver and use set a password; there is still a log like :
```
2017-10-19 17:04:28: debug:c:\source\master\service\logger\nsclient_logger.cpp:52: Creating logger: threaded-file
2017-10-19 17:04:28: error:c:\source\master\modules\WEBServer\WEBServer.cpp:179: No password set please run nscp web --help
```
despite having in the nsclient.ini:
```
[/settings/WEB/server]
password = myverysecurepassword
```

Secondly, the password works when logging in through the webUI (despite the log) however it doesn't seem to work through check_nsc_web v0.4.2 :

```
/omd/sites/default/lib/nagios/plugins/check_nsc_web -v -p myverysecurepassword -u https://server:8443 -k alias_cpu
REQUEST:
"GET /query/alias_cpu HTTP/1.1\r\nHost: server:8443\r\nUser-Agent: Go-http-client/1.1\r\nPassword: myverysecurepassword\r\nAccept-Encoding: gzip\r\n\r\n"
RESPONSE:
"HTTP/1.1 403 \r\nContent-Length: 22\r\n\r\n403 Please login first"
QUERY RESULT:
&{Header:{SourceID:} Payload:[]}
UNKNOWN: The resultpayload size is 0
```

`check_nsc_web` command works fine under the previous version we had installed (`0.5.1.31`)

Minor nit: the metadata is wrong in the msi:

![wrongmetadata](https://user-images.githubusercontent.com/978048/31781539-9c1a5a9c-b4f0-11e7-9e30-30f1adf875d0.png)

### Details

* NSClient++ version: 0.5.2.11
* OS and Version: Windows Server 2012 R2
* Checking from: OMD Labs 2.40
* Checking with: check_nsc_web/curl/firefox

**Comment by mickem** [comment]
Yes, this is correct...
I switched the auth schemes around to more "standard ones" (i.e. basic auth and authentication bearer)... 

I will add back support for the "Old" one as well, sorry...

// Michael Medin

**Comment by mintsoft** [comment]
I've just confirmed that the spurious `No password set` in the log has gone in 5.2.19. The `check_nsc_web` still doesn't work, however judging by the commits, that's expected
