### ISSUE TITLE
check_process count not working correctly for me

### ISSUE THREAD

**Issue by klaypigeon** [mickem/nscp#486]
### Issue and Steps to Reproduce

I am trying to test for a java process count that should alert if there are less than 5 processes. Syntax is based on Opsview.

```
check_nrpe -H wsqual20.utl.cdphp.com -c check_process -a process=java.exe filter="command_line like 'D:\IBM\WebSphere\AppServer'" "crit=count<5"
```

### Expected Behavior
If there are less than five processes java.exe that have D:\IBM\WebSphere\AppServer in their command path then we should alert critical.

### Actual Behavior
**Count seems to have no affect. First lets make sure the filter produces returns:**
$  check_nrpe -H wsqual20.utl.cdphp.com -c check_process -a process=java.exe filter="command_line like 'D:\IBM\WebSphere\AppServer'"
Output: OK: all processes are ok.|'java.exe state'=1;0;0 'java.exe state'=1;0;0 'java.exe state'=1;0;0 'java.exe state'=1;0;0 'java.exe state'=1;0;0 'count'=5;0;0
Errors:
Return code: 0

**Next we add a critical condition count < 5 which should return OK**
$  check_nrpe -H wsqual20.utl.cdphp.com -c check_process -a process=java.exe filter="command_line like 'D:\IBM\WebSphere\AppServer'" "crit=count<5"
Output: CRITICAL: java.exe=started, java.exe=started, java.exe=started, java.exe=started|'count'=5;0;5
Errors:
Return code: 2

**Then for S&Gs we set the filter to 2 and this continues to alert critical even though there are 5 processes running**
$  check_nrpe -H wsqual20.utl.cdphp.com -c check_process -a process=java.exe filter="command_line like 'D:\IBM\WebSphere\AppServer'" "crit=count<2"
Output: CRITICAL: java.exe=started|'count'=5;0;2
Errors:
Return code: 2

### Details

* NSClient++ version:  Version: 0.4.3.143 2015-04-29, Platform: x64

* OS and Version: Windows Server 2008

* Checking from: Opsview

* Checking with: check_nrpe.

### Additional Details

NSClient++ log:
```
PLEASE PASTE LOG HERE
```

**Comment by mickem** [comment]
Count does not work in 0.4.3 it is fixed in 0.5.1
