### ISSUE TITLE
check_eventlog - keyword parameter not working?

### ISSUE THREAD

**Issue by selleryp** [mickem/nscp#488]
Hi,

Op5 support have suggested raising a ticket here, as the inclusion of the "AND keyword = 'Audit Failure'" seems to have stopped this check from flagging up entires.

I have the following configured - 

$USER1$/check_nrpe -H $HOSTADDRESS$ -c check_eventlog -a file=Security "scan-range=-$ARG1$m" "filter=id = '$ARG2$' AND keyword = 'Audit Failure' AND message like '$ARG3$'" "crit=count >= $ARG4$"

However, the output is showing 'no entires found', despite evidence of an Audit Failure event entry in the event viewer.

_USER1_/check_nrpe -H $HOSTADDRESS$ -c check_eventlog -a file=Security "scan-range=-120m" "filter=id = '4673' AND keyword = 'Audit Failure' AND message like 'privileged'" "crit=count >= 1"
Result code: 0
OK: No entries found|'count'=0;0;1 'problem_count'=0;0;0

There is an 'Audit Failure' entry that matches these parameters (screenshot below) and is within the "scan-range=-120m".
Any ideas why this might not be picked up?

![audit failure screeshot](https://user-images.githubusercontent.com/32900598/31990618-84aa0d54-b96d-11e7-9f19-030c8b4ef0f3.PNG)

If I remove the "AND keyword = 'Audit Failure'" parameter then entries are found:

_USER1_/check_nrpe -H $HOSTADDRESS$ -c check_eventlog -a file=Security "scan-range=-120m" "filter=id = '4673' AND message like 'privileged'" "crit=count >= 1"
Result code: 2
CRITICAL: 3 message(s) Security Microsoft-Windows-Security-Auditing (A privileged service was called.  Subject:  Security ID: S-1-5-18  Account Name: ??  Account Domain: ??  Logon ID: 0x3E7  Service:  Server: NT Local Security Authority / Authentication Service  Service Name: LsaRegisterLogonProcess()  Process:  Process ID: 0x218  Process Name: C:\Windows\System32\lsass.exe  Service Request Information:  Privileges: SeTcbPrivilege),

Security Microsoft-Windows-Security-Auditing (A privileged service was called.  Subject:  Security ID: S-1-5-21-252135351-2960911752-2449223186-1153  Account Name: ??  Account Domain: ??  Logon ID: 0x5F000F5E  Service:  Server: Security  Service Name: -  Process:  Process ID: 0xe00  Process Name: C:\Windows\System32\consent.exe  Service Request Information:  Privileges: SeTcbPrivilege),

Security Microsoft-Windows-Security-Auditing (A privileged service was called.  Subject:  Security ID: S-1-5-18  Account Name: ??  Account Domain: ??  Logon ID: 0x3E7  Service:  Server: NT Local Security Authority / Authentication Service  Service Name: LsaRegisterLogonProcess()  Process:  Process ID: 0x218  Process Name: C:\Windows\System32\lsass.exe  Service Request Information:  Privileges: SeTcbPrivilege)|'count'=3;0;1 'problem_count'=0;0;0

However, this is showing both Audit Success and Audit Failure entires, where I want to just highlight the Audit Failures, hence trying to use "AND keyword = 'Audit Failure'"

Details - 
NSClient++ version: 0.5.1045
OS and Version: Windows Server 2012 R2 Standard
Checking from: OP5
Checking with: check_eventlog

Thanks,
Paul

**Comment by mickem** [comment]
Keywords work like a coma separated list so = wont work for single fields.

The simplest way to work with eventlog is to first display the field your looking for.
In my case I found a random item with keywords:
![image](https://user-images.githubusercontent.com/1434697/32071839-de00d29c-ba90-11e7-966c-dd858ed97a63.png)

The first step is to display the value of the keywords (as they are in usually in english):
Thus what I do is disable all warn/crit, show all items and then I filter out my id:

```
check_eventlog log=System "filter=id = '19'" warn=none crit=none "detail-syntax=%(id): %(keyword)" show-all
L        cli OK: OK: 3 message(s) 19: install,success, 19: install,success, 19: install,success
```
This shows me the string value of keyword.
Next I can use the values I have to create the filter I actually need like so:

```
check_eventlog log=System "filter=keyword like 'install'" warn=none crit=none show-all
L        cli OK: OK: 6 message(s) System Microsoft-Windows-WindowsUpdateClient (...
```

So in the end I end up with:

```
...keyword like 'whatever'...
```

like is for substring matching... beware  though that it matches substring so if they keywords ends up as `foo,foobar,barfoo` looking for `foo`would in fact match all of them...

**Comment by op5-support** [comment]
Hi,

I'm helping Paul with this issue.

Just tested this and got no keywords, only event id:

check_nrpe -s -H IP -c check_eventlog -a file=Security "scan-range=-90m" "filter=id = '4625'" "warn=none" "crit=none" "detail-syntax=%(id): %(keyword)" show-all
OK: 3 message(s) 4625: , 4625: , 4625

Tested directly with nscp.exe test too.

Any ideas?

Regards

Mikael Österdahl
OP5 Support

**Comment by mickem** [comment]
Then it is something else...

Do you have the XML for the eventlog record (specifically the numerical value for keyword).

Keywords are loaded from the event provider so it could be an issue with that...

Which version of windows is it?

**Comment by op5-support** [comment]
Here it is:

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-A5BA-3E3B0328C30D}" /> 
  <EventID>4625</EventID> 
  <Version>0</Version> 
  <Level>0</Level> 
  <Task>12544</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8010000000000000</Keywords> 
  <TimeCreated SystemTime="2017-10-27T06:51:38.472099500Z" /> 
  <EventRecordID>15648993</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="488" ThreadID="620" /> 
  <Channel>Security</Channel> 
  <Computer>COMPUTERNAME</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="SubjectUserSid">S-1-0-0</Data> 
  <Data Name="SubjectUserName">-</Data> 
  <Data Name="SubjectDomainName">-</Data> 
  <Data Name="SubjectLogonId">0x0</Data> 
  <Data Name="TargetUserSid">S-1-0-0</Data> 
  <Data Name="TargetUserName">USERNAME</Data> 
  <Data Name="TargetDomainName">DOMAINNAME</Data> 
  <Data Name="Status">0xc000006d</Data> 
  <Data Name="FailureReason">%%2313</Data> 
  <Data Name="SubStatus">0xc0000064</Data> 
  <Data Name="LogonType">3</Data> 
  <Data Name="LogonProcessName">NtLmSsp</Data> 
  <Data Name="AuthenticationPackageName">NTLM</Data> 
  <Data Name="WorkstationName">WORKSTATIONNAME</Data> 
  <Data Name="TransmittedServices">-</Data> 
  <Data Name="LmPackageName">-</Data> 
  <Data Name="KeyLength">0</Data> 
  <Data Name="ProcessId">0x0</Data> 
  <Data Name="ProcessName">-</Data> 
  <Data Name="IpAddress">-</Data> 
  <Data Name="IpPort">-</Data> 
  </EventData>
  </Event>

Windows 2012 R2

![screen shot 2017-10-27 at 09 26 17](https://user-images.githubusercontent.com/23208981/32092474-00887848-baf9-11e7-80c9-8cc0ce7b2566.png)

**Comment by selleryp** [comment]
Any feedback on this @mickem ?

Thanks

**Comment by mickem** [comment]
Sorry for the late reply alas the keywords you were looking for seems to be "broken" in the API. The module in question `Microsoft-Windows-Security-Auditing` does not provide any keyword strings.
Why this is I do not know, I would argue it is a bug in Windows but it could be there is some special voodoo involved somewhere I am missing...

I have however added the ones you are looking for as hard coded keywords so with the next version (hopefully out soon) this should work as expected.

As a reference one can list keywords for a given provider (source) like so:
```
nscp eventlog list-providers --publisher Microsoft-Windows-Security-Auditing --keywords
```

Thus the next build will hopefully proide the following:

```
eck_eventlog log=Security "detail-syntax=%(source): %(keyword)" filter=none show-all unique
L        cli OK: OK: 811 message(s) Microsoft-Windows-Security-Auditing: Audit Success, Microsoft-Windows-Security-Auditing: Audit Success, Microsoft-Windows-Security-Auditing: Audit Success, Microsoft-Windows-Security-Auditing: Audit Success, Microsoft-Windows-Security-Auditing: Audit Success, Microsoft-Windows-Security-Auditing: Audit Success, Microsoft-Windows-Security-Auditing: Audit Success, Microsoft-Windows-Security-Auditing: Audit Success, Microsoft-Windows-Security-Auditing: Audit Success, Microsoft-Windows-Security-Auditing: Audit Success, Microsoft-Windows-Security-Auditing: Audit Success, Microsoft-Windows-Security-Auditing: Audit Success
L        cli  Performance data: 'problem_count'=0;0;0
```

**Comment by mickem** [comment]
FIY, Had some issues with the python script changes so new version will have to wait a few days,...
Will try to remeber to update here once it is out...

**Comment by op5-support** [comment]
Great, thanks for the info.

/Mikael

**Comment by mickem** [comment]
https://github.com/mickem/nscp/releases/tag/0.5.2.14 There you can find a new build, please let me know if this works

**Comment by mickem** [comment]
(reopen if not, also reopen if you need this backported)

**Comment by selleryp** [comment]
Hi @mickem,

I have downloaded and tested on the server that I was originally having difficulties with and I am pleased to report that everything is working OK now.

Thanks very much for your help with this.

Paul
