### ISSUE TITLE
check_cpu returns 0% almost always

### ISSUE THREAD

**Issue by Tontonitch** [mickem/nscp#489]
### Issue and Steps to Reproduce

Describe your issue and tell us how to reproduce it.
check_cpu doesn't return correct information.
It returns 0% even if the cpu usage is at 80%. In fact it returns 0% almost always, and sometimes a few percents (may be also wrong).
```
C:\Program Files\NSClient++>"C:\Program Files\NSClient++\nscp.exe" client --modu
le CheckSystem --show-all -b -q check_cpu
OK: 5m: 0%, 1m: 0%, 5s: 0%|'total 5m'=0%;80;90 'total 1m'=0%;80;90 'total 5s'=0%
;80;90

C:\Program Files\NSClient++>
```

### Expected Behavior

I expect to have correct values.

### Actual Behavior

Wrong CPU usage reported

### Details

* NSClient++ version: 0.5.0062 and 0.5.1046 (x64)
* OS and Version: Windows Server 2012 R2 Standard
* Checking from: Icinga2, and tried directly in command line
* Checking with: Icinga2 launchs nscp.exe directy with "client" argument

### Additional Details

NSClient++ log:
```
PLEASE PASTE LOG HERE
```

**Comment by Tontonitch** [comment]
![image](https://user-images.githubusercontent.com/600025/32099340-36b9b49c-bb10-11e7-9f55-a0ca4176f4a2.png)

**Comment by Tontonitch** [comment]
Debug run
```
C:\Program Files\NSClient++>"C:\Program Files\NSClient++\nscp.exe" client --modu
le CheckSystem --show-all -b -q check_cpu --log debug
L     client Extra options: --show-all
D       core NSClient++ 0.5.1.46 2017-09-24 x64 Loading settings and logger...
D       core Settings not ready so we cant lookup: base-path
D       core Settings not ready so we cant lookup: exe-path
D   settings Boot.ini found in: C:\Program Files\NSClient++/boot.ini
D       core Settings not ready so we cant lookup: shared-path
D   settings Activating: ini://${shared-path}/nsclient.ini
D   settings Creating instance for: ini://${shared-path}/nsclient.ini
D       core Settings not ready so we cant lookup: shared-path
D   settings Loading: C:\Program Files\NSClient++/nsclient.ini
D       core NSClient++ 0.5.1.46 2017-09-24 x64 booting...
D       core Booted settings subsystem...
D       core On crash: restart: NSCP
D       core Archiving crash dumps in: C:\Program Files\NSClient++/crash-dumps
D       core C:\Program Files\NSClient++/modules\CheckSystem.dll.dll
D       core adding C:\Program Files\NSClient++/modules\CheckSystem.dll
D       core Loading plugin: CheckSystem
D       core NSClient++ - 0.5.1.46 2017-09-24 Started!
D       core Found module: CheckSystem...
D  w32system Loading counter: disk_queue_length_0 C: = \\HOSTNAME\PhysicalD
isk(0 C:)\% Disk Time
D  w32system Loading counter: disk_queue_length__Total = \\HOSTNAME\Physica
lDisk(_Total)\% Disk Time
D       core Attempting to stop all plugins
D       core Stopping all plugins
D       core Unloading plugin: CheckSystem...
D       core Stopping: COM helper
D       core Stopping: Settings instance
OK: 5m: 0%, 1m: 0%, 5s: 0%|'total 5m'=0%;80;90 'total 1m'=0%;80;90 'total 5s'=0%
;80;90

C:\Program Files\NSClient++>
```

**Comment by Tontonitch** [comment]
Tried with --load-all, I can see that the cpu usage reported is higher, but still lower than the reality (30% reported but the real usage was 80%

Tried also with filter=none, same. Hereunder the result of `C:\Program Files\NSClient++>"C:\Program Files\NSClient++\nscp.exe" client --module CheckSystem --show-all -b -q check_cpu --log debug --load-all -a filter=none`
:
![image](https://user-images.githubusercontent.com/600025/32100499-3edcf95a-bb14-11e7-9f5b-894abfb289c8.png)

Please also see the cpu config: this is a vmware virtual machine with 1 socket and 4 virtual processors configured.

Also, I have this behavior apparently on all you servers (virtual)

The previous version of nscp was working fine, I guess it was 0.3.9 with checkCPU, as you can see below with some stat history:
![image](https://user-images.githubusercontent.com/600025/32100781-70dcd690-bb15-11e7-905b-fdd2811103aa.png)

**Comment by Tontonitch** [comment]
Found these discussions:
https://monitoring-portal.org/index.php?thread/36962-nscp-local-cpu-liefert-falsche-werte/
https://forums.nsclient.org/t/check-cpu-showing-wrong-values-when-called-by-icinga-2-agent/3777

So it seems to be due to the fact that I use icinga2 who call the nscp.exe in client mode, right?
Is there a solution in order to retrieve correct values from check_cpu in client mode?

BR

**Comment by mickem** [comment]
Indeed client mode wont produce accurate historical cpu metrics as historical cpu metrics require the agent running to collect samples over time...

**Comment by Tontonitch** [comment]
Thanks Michael.
I'm switching to REST API queries through check_nscp_api (icinga2 integration) and an always running NSCP agent.

**Comment by stestaz** [comment]
> 
> 
> Indeed client mode `nscp client...` wont produce accurate historical cpu metrics as historical cpu metrics require the agent running to collect samples over time...
> 
> The way to do this properly is to start the agent and fectch the accurate values via one of the remote protocols like, nrpe, rest, nsclient, etc etc etc...

Hi, so how to have the correct CPU utilization?

**Comment by blevans33** [comment]
> Indeed client mode `nscp client...` wont produce accurate historical cpu metrics as historical cpu metrics require the agent running to collect samples over time...
> 
> The way to do this properly is to start the agent and fectch the accurate values via one of the remote protocols like, nrpe, rest, nsclient, etc etc etc...

Can anyone elaborate on how to do this?
I am able to get historical CPU stats on Linux using tools like 'top', queried from a custom NSClient script, which can be accessed immediately without prior initiation of the NSClient agent.
Is this not possible on Windows?
