### ISSUE TITLE
NSClient++ – 0,4,2,93 pulling wrong numbers from performance counters

### ISSUE THREAD

**Issue by jmatis** [mickem/nscp#49]
Hi, I’m trying to pull data from some performance counters with check_nt and whilst most of it seems ok, the numbers that are nice and round (like 70 ) seem to be loosing a 0 :

/usr/lib64/nagios/plugins/check_nt -H database1010 -v COUNTER -l “\\LogicalDisk(D:\\LG1015_Data)\\% Free Space”
which returns resilt of 7 (seven)

but i know that value of that particular counter is 70 ( i checked it out with perfmon )

when i add some files to change from round number (free space from 70 to 69 % ) it returns correct number :

/usr/lib64/nagios/plugins/check_nt -H database1010 -v COUNTER -l “\\LogicalDisk(D:\\LG1015_Data)\\% Free Space”
69

**Comment by mickem** [comment]
Will be fixed in the next build

**Comment by mickem** [comment]
Broken fix will be fixed in the next build :)

**Comment by mickem** [comment]
0.4.3.102 should fix this issue, please reopen if issue still persists...
