### ISSUE TITLE
NSClient refusing connections

### ISSUE THREAD

**Issue by eyala01** [mickem/nscp#491]
### Issue and Steps to Reproduce
We're using a URL sampling tool together with NSClient++ 0.5.1.29 to monitor a Windows 2012 R2 machine.
The configuration file contains default options, and also enables the internal web server on port 8443.

It has been working great for quite some time now, but suddenly, all samples fail with this error:

> dial tcp 127.0.0.1:8443: connectex: No connection could be made because the target machine actively refused it.

### Expected Behavior
HTTP status 200 OK

### Actual Behavior
Target machine actively refusing the connection

### Details
* NSClient++ version: 0.5.1.29
* OS and Version: Windows Server 2012 R2
* Checking from: a URL sampling tool
* Checking with: check_always_ok

### Additional Details
On NSClient's log file we noticed these errors:

> error:c:\source\master\service\NSClient++.cpp:837: Failed to process command: Library is not loaded
> error:c:\source\master\include\nscapi\nscapi_core_wrapper.cpp:189: Failed to execute query

**Comment by mickem** [comment]
Have you verified there is no firewall in the way?
please note there is also a allowed hosts directive to look out for but it should log the failure...

**Comment by mickem** [comment]
Please reopen this if you have verified this is not a firewall issue
