### ISSUE TITLE
Does 'unique-index' count reset after a certain time interval?

### ISSUE THREAD

**Issue by IBMerSteve** [mickem/nscp#493]
### Objective: 
Prevent a flood of alarms being sent to Nagios and down-stream systems if a end-point server starts spewing eventlog messages. 

### Proposed Approach: 
Use 'unique-index' to send messages only after a certain count of the '${log}-${source}-${id}' combination appears.  For example: **unique-index=10**

### Question: 
Is there a time interval associated with 'unique-index'?  If I set **unique-index=10** does it apply to eventlog messages since since the agent was last started, or is there a time interval after which the count resets?

### Details

* NSClient++ version: 0.5.1.46
* OS and Version: Windows Server 2008 and up

**Comment by mickem** [comment]
It is "per query! i.e. check_eventlog will not report an error twice so it resets every-time you run the query again.

**Comment by mickem** [comment]
Pleas reopen if you need more info

**Comment by IBMerSteve** [comment]
Let's say I have an condition that causes a new event to be written to the event log every 5 minutes.  I am using real-time event log monitoring to forward events to Nagios XI.  I don't want the nscp agent to forward this same alarm every 5 minutes, but rather to suppress alerts after the first one for some period of time, maybe one hour, and then send again if still occurring.  Is there a way to do this?

**Comment by mickem** [comment]
Not "out of the box" you could create a fairly simple script which suppresses duplicate messages.

**Comment by IBMerSteve** [comment]
Thanks. How would that script be implemented to intercept messages between nscp and nrdp?
 Sent from my iPhone using IBM Verse
 
 On Nov 16, 2017, 12:13:50 PM, notifications@github.com wrote:

**Comment by mickem** [comment]
A very crude sample:

script\python\filter_nsca.py
```
from NSCP import Registry, Core, status, log

g_last_message = ''
g_plugin_id = 0

def filter_nsca(channel, source, command, status, message, perf):
  global g_last_message, g_plugin_id
  if not message == g_last_message:
    g_last_message = message
    log("Sending: %s"%message)
    core = Core.get(g_plugin_id)
    core.simple_submit('NSCA', command, status.CRITICAL, message.encode('utf-8'), perf)
  else:
    log("Supressing duplicte message")

def init(plugin_id, plugin_alias, script_alias):
  global g_plugin_id
  g_plugin_id = plugin_id
  reg = Registry.get(plugin_id)
  reg.simple_subscription('filter_nsca', filter_nsca)
```

```
[/modules]
PythonScript=enabled
CheckEventLog=enabled
NSCAClient=enabled

[/settings/python/scripts]
filter_nsca=filter_nsca.py

[/settings/eventlog/real-time]
enabled = true

[/settings/eventlog/real-time/filters/login]
log=Security
filter=id=4624
target=filter_nsca
detail syntax=%(id)
```
