### ISSUE TITLE
On using check_process

### ISSUE THREAD

**Issue by sder73** [mickem/nscp#494]
Hello

I run this command 

[root@tstisimcm ~]# /usr/lib/nagios/plugins/check_nagios_nrpe -H 192.168.1.119 -p 15666 -t 5  -c check_process -a 'process=java.exe'  "critical=count>1 or count=0" 'top-syntax=${status}: ${total} processus' 'detail-syntax=${exe}=${state}' 'filter=started'
CRITICAL: No processes found|'count'=0;0;1
[root@tstisimcm ~]# echo $?
3

why the plug-in  message is critical and the status is unknown ?

Thank for your help

**Comment by mickem** [comment]
It is dues to the default `empty-status` is set to `empty-state=unknown `

```
check_process show-default
L        cli OK: "filter=state != 'unreadable'" "warning=state not in ('started')" "critical=state = 'stopped', count = 0" "empty-state=unknown" "top-syntax=${status}: ${problem_list}" "ok-syntax=%(status): all processes are ok." "empty-syntax=%(status): No processes found" "detail-syntax=${exe}=${state}" "perf-syntax=${exe}"
```
