### ISSUE TITLE
Completly lost

### ISSUE THREAD

**Issue by sder73** [mickem/nscp#496]
Hello
I have no process titi.exe on the windows server and I do not understand how work check_process

/usr/lib/nagios/plugins/check_nagios_nrpe --host 192.168.1.119 -p 15666 -t 5 --command check_process -a 'process=titi.exe' 'warning=count=0 ' 'critical=count=0' 'empty-state=critical' show-all
OK: titi.exe=stopped|'count'=1;0;0

Thank you for your help

**Comment by mickem** [comment]
Google `titi.exe` lists it as spyware perhaps it is not showing up in task manager?
NSClient++ will not make up processes so if it is listed it is running...

**Comment by mickem** [comment]
Sorry, I dont understand your question-

You have a check which checks for a process... Why you have that I do not know...

**Comment by mickem** [comment]
Please reopen with more details...
