### ISSUE TITLE
perf data in check_cpu (and check_pdh) not displayed when more than 1 argument is given

### ISSUE THREAD

**Issue by cxcv** [mickem/nscp#499]
### Issue and Steps to Reproduce

check_cpu and check_pdh dont print perfdata when more than 1 argument is given

```
nscp test
load CheckSystem
check_cpu
L        cli OK: OK: CPU load is ok.
L        cli  Performance data: 'total 5m'=0%;80;90 'total 1m'=2%;80;90 'total 5s'=19%;80;90
check_cpu warn=0 crit=0
L        cli OK: OK: CPU load is ok.
check_cpu warn=0
L        cli OK: OK: CPU load is ok.
L        cli  Performance data: 'total 5m'=0%;0;90 'total 1m'=5%;0;90 'total 5s'=26%;0;90
check_cpu warn=0
L        cli OK: OK: CPU load is ok.
L        cli  Performance data: 'total 5m'=2%;0;90 'total 1m'=11%;0;90 'total 5s'=4%;0;90
check_cpu warn=0 crit=0
L        cli OK: OK: CPU load is ok.
```

### Expected Behavior

Regardless of the number of arguments given, the perf data should be printed.

### Actual Behavior

perfdata is not printed when more than 1 argument within test mode (and within client mode)

### Details

* NSClient++ version: 0.5.2.14
* OS and Version: Windows Server 2016
* Checking from: Test Mode and Client Mode
* Checking with: Test Mode and Client Mode

### Additional Details

NSClient++ log:
```
nothing was added to this file during the test
```

**Comment by Tontonitch** [comment]
I've the same issue.

I've also tried multiple combinaisons, and it seems that the perf data disappear when using warning and critical:
check_cpu time=1m time=5m time=15m "warning=10" show-all
=> perfdata printed
check_cpu time=1m time=5m time=15m "warning=10" "warning=20" show-all
=> perfdata NOT printed

**Comment by Tontonitch** [comment]
a working workaround:
check_cpu "warn=(load>80)" "crit=(load>90)"

**Comment by mickem** [comment]
What is `warn=0 crit=0` this turns warn and critical into invalid filters which in turn removes the performance data...

So not really sure what you expect warn / crit to take for arguments?

**Comment by Tontonitch** [comment]
Indeed, check_cpu warn=50 returns a 0% as warning in the perfdata. And no warning status even if the load is up to 50%. 
Nevertheless, as this argument seems to be incorrect, I would expect the a "UNKNOWN: Invalid command line: ..." instead of letting the user think that the use of such an argument is correct. Does it seems okay for you, or the logic behind the module doesn't allow that?

**Comment by mickem** [comment]
The command line is not invalid per see (just not a valid expression)...

A warning expression is an expression which evaluates to 0 or something else. So setting warn=0 will essentially set warning to always false (i.e. always ok). Normally you have something along the lines of "warn=load > 50%"

The performance data is generated by the things you check in your expression.
For instance "load>50%" will add performance data for load to your expression.

So your command line is valid and your result is the expected result...

**Comment by cxcv** [comment]
Thanks for explaining; having a more verbose explanation at query level would be nice. Cheers Benjamin
