### ISSUE TITLE
.NET compatibility

### ISSUE THREAD

**Issue by SimonHoenscheid** [mickem/nscp#507]
### Issue and Steps to Reproduce

Describe your issue and tell us how to reproduce it.

Can not install NSCP on hosts without .NET 3.5

### Expected Behavior

NSCP will work with more recent Versions of .NET

Tell us what you think should happen.

Make NSCP compatible

### Actual Behavior
I can not install NSCP

### Details

* NSClient++ version: 0.5.2
* OS and Version: Windows Server 2016

**Comment by mickem** [comment]
NSClient++ does not use nor require dot-net at all so not sure why it would require .NET 3.5
Or are you trying to use .net modules with NSClient++?
