### ISSUE TITLE
build failes on ubuntu 16.04 "protoc-gen-md: program not found "

### ISSUE THREAD

**Issue by bvanleenhoff** [mickem/nscp#508]
### Issue and Steps to Reproduce

protoc-gen-md should be part of protobuf-compiler, which is installed on my machine:
 apt list protobuf-compiler
Listing... Done
protobuf-compiler/xenial,now 2.6.1-1.3 amd64 [installed]
root@dmshost:~/gitclonerei/nscp_/build# find / -name protoc-gen-md
/root/gitclonerei/nscp_/nscp/ext/md-protobuf/protoc-gen-md

but find or which do not yield any result when executed with "protoc-gen-md" other than the build directory.

I followed the installation guide exactly
only issue while installing required packages: 

```
apt install libcrypto++

```

fails with:

```
The following packages have unmet dependencies:
 libcryptokit-ocaml : Depends: ocaml-base-nox-4.02.3
                      Conflicts: libcryptokit-ocaml:i386 but 1.10-1build1 is to be installed
 libcryptokit-ocaml:i386 : Conflicts: libcryptokit-ocaml but 1.10-1build1 is to be installed
 libcryptokit-ocaml-dev : Depends: ocaml-nox-4.02.3
                          Conflicts: libcryptokit-ocaml-dev:i386 but 1.10-1build1 is to be installed
 libcryptokit-ocaml-dev:i386 : Depends: ocaml-nox-4.02.3:i386
                               Conflicts: libcryptokit-ocaml-dev but 1.10-1build1 is to be installed
```

maybe there is a connection?

actual error occures when running make: 
```
...
[  4%] Linking CXX shared library libnscp_mongoose.so
[  4%] Built target nscp_mongoose
[  5%] Running protocol buffer compiler on plugin.proto - /usr/bin/protoc
/root/gitclonerei/nscp_/nscp/ext/md-protobuf/protoc-gen-md: program not found or is not executable
--md_out: protoc-gen-md: Plugin failed with status code 1.
libs/protobuf/CMakeFiles/nscp_protobuf.dir/build.make:61: recipe for target 'libs/protobuf/plugin.pb.cc' faid
make[2]: *** [libs/protobuf/plugin.pb.cc] Error 1
CMakeFiles/Makefile2:912: recipe for target 'libs/protobuf/CMakeFiles/nscp_protobuf.dir/all' failed
make[1]: *** [libs/protobuf/CMakeFiles/nscp_protobuf.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

```
hope you can help, thank you!

**Comment by sjwk** [comment]
protoc-gen-md is a script within the nscp folder.  But when downloaded from git it has the wrong permissions so the file is not executable.  
If you run:
`chmod +x ../ext/md-protobuf/protoc-gen-md`
from the build directory, that should sort it.

**Comment by mickem** [comment]
This should have been fixed with the last commit to master
