### ISSUE TITLE
Docs: Formatting for mkdocs (headings, etc.)

### ISSUE THREAD

**Issue by dnsmichi** [mickem/nscp#513]
I've seen that with Icinga docs too, so here are some thoughts.

## TOC and headings

MKDocs generates the TOC from

- filename
- only one `#` heading (everything else is in the file, but cut off in the TOC)

Example in faq.md -> that's not shown in the TOC.

```
# 7. NRPE

## 7.1 What is insecure mode
```

## Anchors and headings

MKDocs and Github automatically create short headings. If you really want to cross link between chapters, you'll need reliable naming schemas.

MKDocs doesn't like it when anchors are put between `#` and the chapter name, you'll have to add them after the chapter title like this:

```
# Troubleshooting <a id="troubleshooting"></a>
```

This should be an ongoing issue to format chapters on by one. I'll see what I can do in the next weeks.

**Comment by mickem** [comment]
Should be all good now, thanks...
