### ISSUE TITLE
nsclient.ini settings to check drivesize

### ISSUE THREAD

**Issue by IBMerSteve** [mickem/nscp#515]
### Issue and Steps to Reproduce

I am using nsclient++ ver 5.1 for real-time event log monitoring, sending events to a Nagios XI server using NRDP.   I want to add passive monitoring for other resources, for example monitoring disk space using the CheckDisk module.  I have not been able to find documentation online for how to configure the nsclient.ini file to do this.   https://docs.nsclient.org/reference/windows/CheckDisk/ shows sample commands but not the ini configuration. 

I believe I would add the **CheckDisk** module to my modules section, like so:

**[/modules]
NRDPClient = enabled
CheckEventLog = enabled
CheckDisk = enabled**

...and then I am sure I need a section to add the check something like this:
**check_drivesize "crit=free<10%" drive=c:**

...but I cannot determine what the section should be named to contain this (and similar) command.   Can you provide a sample of what the ini file would look like to run check_drivesize?

**Comment by box293** [comment]
Have you seen this documentation:
https://assets.nagios.com/downloads/nagiosxi/docs/Using_NSClient_For_Passive_Checks.pdf

Page 7 has some examples, like:
```
[/settings/scheduler/schedules]
host_check = Check_OK "Everything is working fine"
CPU Load = checkCPU warn=80 crit=90 time=5m time=1m time=30s
Memory Usage = checkMem MaxWarn=80% MaxCrit=90% ShowAll=long type=physical type=virtual type=paged type=page
Drive C: Disk Usage = CheckDriveSize MinWarn=10% MinCrit=5% Drive=C: ShowAll
Uptime = CheckUptime MinCrit=12h ShowAll
Print Spooler Service = check_service service=spooler
```

You might also be interested in the "Check Library" in the Support Knowledgebase:
https://support.nagios.com/kb/category.php?id=186

Does this help?

**Comment by IBMerSteve** [comment]
Thanks Troy!  That got me enough information to get it working!

Regards,
Steve
