### ISSUE TITLE
V0.5.1.46: Failed to get network metrics

### ISSUE THREAD

**Issue by R-Sommer** [mickem/nscp#516]
I've several machines configured in the same manner and one is complaining:

2017-12-06 10:42:57: error:c:\source\0.5.1\modules\CheckSystem\pdh_thread.cpp:307: Failed to get network metrics: Failed to fetch network metrics: ConnectServer failed: namespace=root\cimv2, user=:80010114: The requested object does not exist.

**Comment by nmat** [comment]
Can you provide a bit more information about what operating system and version you are using?

Are you fetching using nrpe or any other protocol?

**Comment by R-Sommer** [comment]
OS: Windows Storage Server 2012 R2 Standard by HP

This error occurs without any check every 12s (until I stop nscp).

**Comment by R-Sommer** [comment]
Any news on this?

**Comment by bhozar** [comment]
I'm seeing the same issue while using nscp.exe test
                    c:\source\master\modules\CheckSystem\pdh_thread.cpp:247 E  w32system Failed to get network metrics: Failed to fetch network metrics: ExecQuery of 'select NetConnectionID, MACAddress, Name, NetConnectionStatus, NetEnabled, Speed from Win32_NetworkAdapter where PhysicalAdapter=True and MACAddress<> null' failed: , WinMgmt - :failed to lookup error code: 2147749904 (reason: 317)

Server is Windows Server 2012 R2, running as a VM on Azure.

**Comment by mintsoft** [comment]
@bhozar what happens if you try to query that using powershell?

```
get-wmiobject -Query 'select NetConnectionID, MACAddress, Name, NetConnectionStatus, NetEnabled, Speed from Win32_NetworkAdapter where PhysicalAdapter=True and MAC
Address<> null'
```

**Comment by mintsoft** [comment]
@R-Sommer Have you tried rebuilding the performance counters (https://support.microsoft.com/en-us/help/2554336/how-to-manually-rebuild-performance-counters-for-windows-server-2008-6 - basically use ` lodctr /R`). I've had an error similiar to that previously on Server 2008 and that fixed it

**Comment by bhozar** [comment]
Tried running it and ended with an error:
get-wmiobject : Invalid class "Win32_NetworkAdapter"

Same results after a rebuilt.

**Comment by mintsoft** [comment]
@bhozar unless you're on < Server 2008 (https://msdn.microsoft.com/en-us/library/aa394216(v=vs.85).aspx)  I'm reasonably sure something is broken with your WMI on that machine. I'd suggest WMIDiag (http://www.microsoft.com/downloads/details.aspx?familyid=D7BA3CD6-18D1-4D05-B11E-4C64192AE97D&displaylang=en) and following through anything that's wrong on there

**Comment by bhozar** [comment]
Looks like it was an issue with WMI on the local system. Fixed by rebuilding it:

@echo off
sc config winmgmt start= disabled
net stop winmgmt /y
%systemdrive%
cd %windir%\system32\wbem
for /f %%s in (‘dir /b *.dll’) do regsvr32 /s %%s
wmiprvse /regserver
winmgmt /regserver
sc config winmgmt start= auto
net start winmgmt
for /f %%s in (‘dir /s /b *.mof *.mfl’) do mofcomp %%s

**Comment by mintsoft** [comment]
@R-Sommer any chance that WMIDiag can highlight any issues for you too?

**Comment by R-Sommer** [comment]
In the meantime the second system at the same customer raise errors.

**Trying get-wmiobject on both systems results in:**
get-wmiobject : The requested object does not exist. (Exception from HRESULT: 0x80010114)
At line:1 char:1
+ get-wmiobject -Query 'select NetConnectionID, MACAddress, Name, NetConnectionSta ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-WmiObject], COMException
    + FullyQualifiedErrorId : GetWMICOMException,Microsoft.PowerShell.Commands.GetWmiObjectCommand

**WMIDiag on the first system:**
!! ERROR: WMI MONIKER CONNECTION errors occured for the following namespaces: .......................................... 1 ERROR(S)!
* - Root, 0x80010114 - The requested object does not exist..

**WMIDiag on the second system:**
!! ERROR: WMI GET operation errors reported: ........................................................................... 39 ERROR(S)!
* - Root/CIMv2, Win32_Process.Handle=3568, 0x80041024 - (WBEM_E_PROVIDER_NOT_CAPABLE) Provider cannot perform the requested operation.

Obviously, this is not a NSClient++ error. Hence, this issue could be closed.

**Comment by mintsoft** [comment]
@R-Sommer Thanks, I figured that was the case. You can close the issue yourself otherwise we'll have to wait for @mickem to close it
