### ISSUE TITLE
Special character

### ISSUE THREAD

**Issue by boogaaloo** [mickem/nscp#519]
Hello,

I use the check_nt plugin to test a service. But a windows service contains a special character $.
I tried different possibilities ;)
/usr/lib/nagios/plugins/check_nt -H xxx 12489 -s xxx -v SERVICESTATE -l MSSQL$DEV
/usr/lib/nagios/plugins/check_nt -H xxx 12489 -s xxx -v SERVICESTATE -l MSSQL\$DEV
/usr/lib/nagios/plugins/check_nt -H xxx 12489 -s xxx -v SERVICESTATE -l MSSQL"$"DEV
/usr/lib/nagios/plugins/check_nt -H xxx 12489 -s xxx -v SERVICESTATE -l "MSSQL"$"DEV"
/usr/lib/nagios/plugins/check_nt -H xxx 12489 -s xxx -v SERVICESTATE -l MSSQL$$DEV
/usr/lib/nagios/plugins/check_nt -H xxx 12489 -s xxx -v SERVICESTATE -l MSSQL\\\$$DEV

In fact, the result of the command is an error.

Would you know what is the good escape character?

Thank you

**Comment by box293** [comment]
https://support.nagios.com/kb/article/nagios-xi-problems-with-$-signs-in-the-check-command-168.html

You will need a backslash `\` and two `$$` signs.
```
MSSQL\$$DEV
```

**Comment by boogaaloo** [comment]
Thank you !!
