### ISSUE TITLE
check_eventlog "No entries found" returns CRITICAL but reports exit code 0

### ISSUE THREAD

**Issue by ZaiusDR** [mickem/nscp#523]
### Issue and Steps to Reproduce

I'm interested in using check_eventlog with "count" threshold types, so when an event hasn't being logged in X Hours a Critical status is returned. However, when the event hasn't occurred, check_eventlog reports "No entries found" (which is correct). But it returns a message like:

CRITICAL: No entries found|'count'=0;0;1 'problem_count'=0;0;0

and a 0 exit code (which in Nagios is OK Status).
```
/opt/plugins/check_nrpe -s -H X.X.X.X -t 30 -p 5666 -c check_eventlog -a log=System scan-range=-25h "filter=id = 700 and provider = 'System'" "critical=count < 1"; echo $?
CRITICAL: No entries found|'count'=0;0;1 'problem_count'=0;0;0
0
```

### Expected Behavior

Since there is a threshold such as "critical=count < 1" I'd expect to get a 2 as exit code.

### Actual Behavior

The check returns a 0. I guess this is because of the "empty-state" default value, which is "ok", this mess with the Critical Threshold.

### Details

* NSClient++ version: 0.5.0.62-x64
* OS and Version: Windows Server 2016
* Checking from: OP5
* Checking with: check_nrpe

**Comment by eduardosuarez-ntt** [comment]
Tested with latest NSClient++ 0.5.2 as well. Same behavior.

**Comment by mickem** [comment]
Unfortunately count does not override the default behavior which is that "no matches" has a different message and return code.
You can however change these:  https://docs.nsclient.org/reference/windows/CheckEventLog/#check_eventlog_empty-state and https://docs.nsclient.org/reference/windows/CheckEventLog/#check_eventlog_empty-syntax
