### ISSUE TITLE
check_eventlog - Assistance Required

### ISSUE THREAD

**Issue by selleryp** [mickem/nscp#532]
I am trying to configure a check to flag up when a Scheduled Task does now complete successfully, using the newer check_eventlog command, as opposed to the older checkeventlog command.

Currently trying the following command:

$USER1$/check_nrpe -H $HOSTADDRESS$ -c check_eventlog -a file=Microsoft-Windows-TaskScheduler/Operational crit=$ARG1$ "scan-range=-$ARG2$m" "filter=id = '$ARG3$' AND message not like '$ARG4$'"

However, when testing, this does not appear to be flagging up instances that I would expect it to:

_USER1_/check_nrpe -H HOST_IP -c check_eventlog -a file=Microsoft-Windows-TaskScheduler/Operational crit=0 "scan-range=-30m" "filter=id = 201 AND message not like 'return code 12'”
Result code: 0
OK: No entries found|'problem_count'=0;0;0

In the last 30minutes there are no entries with 'return code 12':

![screenshot](https://user-images.githubusercontent.com/32900598/34609839-3b192ef4-f216-11e7-83d8-e71037d6d739.png)

so I would expect it to flag up a CRITICAL, but it shows an OK status.

I also tried "crit=0" (in quotes), but got the same output.

The level of this entry is Information. Tried with a "filter=level = 'Information'", but still got the same output.
$USER1$/check_nrpe -H HOST_IP -c check_eventlog -a file=Microsoft-Windows-TaskScheduler/Operational "crit=0" "scan-range=-30m" "filter=id = 201 AND level = 'info' AND message not like 'return code 12'"

Any ideas where I am going wrong?

Details -
NSClient++ version: 0.5.2.14
OS and Version: Windows Server 2012 R2 Standard
Checking from: OP5
Checking with: check_eventlog

**Comment by op5-support** [comment]
I have tested this and have come to the following conclusions:

It works if I run the command against a message with level = warning. I cannot get it to work with a message that has level = information, no matter how I try. I have tried the following filters:

level = 'information'
level = 'informational'
level = 'info'

I can find the message with "filter = none" but then I get all messages since I cannot filter them.

Michael, do you have any ideas here?

Version is 0.5.1.45.

Regards

Mikael Österdahl
OP5

**Comment by mickem** [comment]
I sometimes wonder level is "broken" it uses the old codes which sometimes are the same but not always...

Anyways, the way to diagnose this is to "print" the value, i.e. check all messages and print the value for level like so:
```
check_eventlog -a file=Microsoft-Windows-TaskScheduler/Operational "crit=0" "scan-range=-30m" "filter=id = 201 AND message not like 'return code 12'" "detail-syntax=%level%"
```

**Comment by op5-support** [comment]
Thanks but doesn't seem to work:

```
check_eventlog -a "file=Microsoft-Windows-TaskScheduler/Operational" "scan-range=-30m" "filter=id = 200" "detail-syntax=%level%" "warn=none" "crit=none" show-all
OK: 4 message(s) %level%, %level%, %level%, %level%
```

**Comment by mickem** [comment]
Sorry...

it should be `%(level)` not `%level%`...


```
check_eventlog -a file=Microsoft-Windows-TaskScheduler/Operational "crit=0" "scan-range=-30m" "filter=id = 201 AND message not like 'return code 12'" "detail-syntax=%(level)"
```

**Comment by selleryp** [comment]
Currently getting the following:

_USER1_/check_nrpe -H HOSTIP -c check_eventlog -a "file=Microsoft-Windows-TaskScheduler/Operational" "scan-range=-30m" "filter=id = 201" "detail-syntax=%(level)" "warn=none" "crit=none" show-all
Result code: 0
OK: 2 message(s) information, information

Thanks,
Paul

**Comment by op5-support** [comment]
Thanks, I got the following response:

`OK: 1 message(s) information`

However I cannot get it to give me a warning or critical state when level is information.

`check_eventlog -a "file=Microsoft-Windows-TaskScheduler/Operational" "scan-range=-30m" "filter=id = 200 and level = 'information' and message not like 'foo'"`

**Comment by mickem** [comment]
Can you provide the xml for the event log message in question?

**Comment by op5-support** [comment]
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-TaskScheduler" Guid="{DE7B24EA-73C8-4A09-985D-5BDADCFA9017}" /> 
  <EventID>200</EventID> 
  <Version>1</Version> 
  <Level>4</Level> 
  <Task>200</Task> 
  <Opcode>1</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2018-01-10T10:29:52.016109000Z" /> 
  <EventRecordID>753152</EventRecordID> 
  <Correlation ActivityID="{C25C3B70-504D-43E8-BD3C-5D1AFDEA956B}" /> 
  <Execution ProcessID="844" ThreadID="1876" /> 
  <Channel>Microsoft-Windows-TaskScheduler/Operational</Channel> 
  <Computer>win2012-ad.example.com</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
- <EventData Name="ActionStart">
  <Data Name="TaskName">\Microsoft\Windows\Shell\CreateObjectTask</Data> 
  <Data Name="ActionName">Shell Create Object Task Delegate</Data> 
  <Data Name="TaskInstanceId">{C25C3B70-504D-43E8-BD3C-5D1AFDEA956B}</Data> 
  <Data Name="EnginePID">4876</Data> 
  </EventData>
  </Event>
```

**Comment by mickem** [comment]
The level is correct (BTW)...

But just noticed you said warning/error and they ceom from the "warn=none" "crit=none" which if set to none means nothing is an error or a warning...  The default values for them is to check for warning/critical so you probably want to set them to count > 0 or some such...

i.e. 

```
check_eventlog "filter=level = 'info'"
L        cli OK: OK: Event log seems fine
```

```
check_eventlog "filter=level = 'info'" "warn=count gt 0"
L        cli WARNING: WARNING: 124 message(s) Application ...
```

**Comment by op5-support** [comment]
That works! Thanks a lot!

**Comment by mickem** [comment]
Great, and sorry for my confusion...
