### ISSUE TITLE
Certifacate Error on NSC Client ++

### ISSUE THREAD

**Issue by Miriana92** [mickem/nscp#541]
Hi,
we have installed NSC Client ++(NSCP-0.5.2.35-x64.msi) on my Server Windows (Server 2008 R2 Datacenter).
I have enabled the WEB UI during installation. I managed to open the homepage and I can navigate on it. 
Ma in "log" tab, I visualize many logs of this type:

Certificate not found: C:\Program Files\NSClient++/security/certificate.pem (generating a default certificate)

What am I wrong?
How do I install a valide certificate?
May you provide a link for the download?

If I select one module and enable it in the  Module/Name_Module/Queries section I don't visualize any queries to be run.
How to set them?
Please provide feedback also on the followiing email:

miri.castaldo@gmail.com

Best Regards,
Miriana

**Comment by mickem** [comment]
It is a notification that there was no certificate and one was created so it can be safely ignored...

**Comment by mickem** [comment]
Can we close this or do you need further assistance?

**Comment by weipah** [comment]
@Miriana92 
> Certificate not found: C:\Program Files\NSClient++/security/certificate.pem

You're also mixing windows and linux folder formats. Be sure to use the backslash for windows. In configuration files you might also have to escape them properly with "\\".
