### ISSUE TITLE
[check_tasksched] - How to disable perfdata

### ISSUE THREAD

**Issue by cmeschin** [mickem/nscp#543]
Hi,

I use NSClient 0.5.0.62 and I want to disable perfdata for module check_tasksched but I don't find how to do this.
Is there an option for that?

Regards.

**Comment by cmeschin** [comment]
Hi,
by adding this in nrpe command "perf-config=*(ignored:true)" it works.
is this the better way?

Thanks.

**Comment by mickem** [comment]
thats how you disable it yes...
