### ISSUE TITLE
disk_queue_length: Invalid strategy: UNKNOWN

### ISSUE THREAD

**Issue by NikolaySh1** [mickem/nscp#551]
### Issue and Steps to Reproduce
Hello!
Tell me pliase, how to fix error from module CheckSystem: "disk_queue_length: Invalid strategy: UNKNOWN"?
```
PLEASE PROVIDE COMMAND HERE
```
1. Сreate a new configuration file:
`nscp settings --generate ini --add-defaults --load-all`
2. Turn on the CheckinSystem module:
CheckSystem = enabled
3. Test the configuration:
nscp.exe test
### Expected Behavior

I expect that there will be no mistakes.

### Actual Behavior

I get an error.

> E  w32system Failed to load: disk_queue_length: Invalid strategy: UNKNOWN
> c:\source\master\modules\CheckSystem\CheckSystem.cpp:226

### Details

* NSClient++ version: 0.5.2.35.
* OS and Version: Windows Server 2016
* Checking from: Nagios

### Additional Details

NSClient++ log:
```
2018-03-05 18:43:27: error:c:\source\master\modules\CheckSystem\CheckSystem.cpp:226: Failed to load: disk_queue_length: Invalid strategy: UNKNOWN
2018-03-05 18:43:27: info:c:\source\master\modules\CheckSystem\pdh_thread.cpp:236: Not checking PDH data

**Comment by mickem** [comment]
You can most likely ignore this error, the problem stems from your performance counters which seem to have some issue.
The check is not required and the drawback is the WEB UI will not show drive metrics (as well as not sent to graphite et. al.)
You can disable this auto check if you want: https://docs.nsclient.org/reference/windows/CheckSystem/#disable-automatic-checks

[/settings/system/windows]
# Disable automatic checks
disable=pdh
