### ISSUE TITLE
Remove space between drive_or_id and curves name in perfdata 

### ISSUE THREAD

**Issue by grosbedos** [mickem/nscp#553]
### Issue and Steps to Reproduce
Hi,

I would like to remove the space in the names of the curves in perfdata's output.
How can I succeed?

```
check_nrpe -H somehost -c xform_perf -a mode=extract field=max replace=used=total command=Check_Drivesize arguments drive=c: "warn=( used > 90% )" "crit=( used > 95% )" "top-syntax=%(detail_list)" "detail-syntax=Total: %(size), Used: %(used), Free: %(free)" "perf-config=*(prefix:none) used %(ignored:true)" "perf-syntax=none"
```

### Expected Behavior

Total: 465.76GB, Used: 261.575GB, Free: 204.184GB|'used'=261.57542GB;419.18378;442.47177;0;465.75976 'total'=465.75976GB;419.18378;442.47177;0;465.75976

### Actual Behavior

Total: 465.76GB, Used: 261.575GB, Free: 204.184GB|' used'=261.57542GB;419.18378;442.47177;0;465.75976 ' total'=465.75976GB;419.18378;442.47177;0;465.75976

### Details

* NSClient++ version: 0.5.1
* OS and Version: Windows Seven
* Checking from: Command line (CentOS 6)
* Checking with: check_nrpe

Best regard.

**Comment by mickem** [comment]
What I guess you want is to get rid of both the prefix and the suffix (which has a leading space) like so: `"perf-config=*(prefix:none;suffix:none) used %(ignored:true)"`

```
Check_Drivesize drive=c: "warn=( used > 90% )" "crit=( used > 95% )" "top-syntax=%(detail_list)" "detail-syntax=Total: %(size), Used: %(used), Free: %(free)" "perf-config=*(prefix:none;suffix:none) us
ed %(ignored:true)"
L        cli OK: Total: 451.566GB, Used: 404.731GB, Free: 46.835GB
L        cli  Performance data: 'c:'=404.73104GB;406.40908;428.98736;0;451.56564
```

Or with your xform thingy:
```
xform_perf mode=extract field=max replace=used=total command=Check_Drivesize arguments drive=c: "warn=( used > 90% )" "crit=( used > 95% )" "top-syntax=%(detail_list)" "detail-syntax=Total: %(size), U
sed: %(used), Free: %(free)" "perf-config=*(prefix:none;suffix:none) used %(ignored:true)"
L        cli OK: Total: 451.566GB, Used: 404.731GB, Free: 46.835GB
L        cli  Performance data: 'c:'=404.73094GB;406.40908;428.98736;0;451.56564 'c:'=451.56564GB;406.40908;428.98736;0;451.56564
```
