### ISSUE TITLE
response of external commands are not logged on trace level

### ISSUE THREAD

**Issue by af9999** [mickem/nscp#558]
Hello,

i’ve updated from nsclient++ 03 to 05.

Version 03: Settings debug=1 In the Logfile the response of my Script is 2017-03-02 14:55:08: debug:NSClient++.cpp:1144: Injecting: check_fileageaf: g, C:\Program Files (x86)\Trend Micro\OfficeScan Client\Reserve, 11520, 15840 2017-03-02 14:55:08: debug:NSClient++.cpp:1180: Injected Result: OK ‘OK - Datei ist 25 Minuten alt.’

Version 05: Settings: [/settings/log] file name = nsclient.log level = trace or debug (i’ve testet both) In the Logfile the response of my Script is 2018-03-23 10:48:16: debug:c:\source\master\modules\CheckExternalScripts\CheckExternalScripts.cpp:371: Command line: C:\Programme\NSClient++\scripts\AF_Scripts\fileage.exe g “C:\Program Files (x86)\Trend Micro\OfficeScan Client\Reserve” 11520 15840

Where is the Result ‘OK - Datei ist 25 Minuten alt.’ of my Script?

Thanks for Help Andreas

### Details

* NSClient++ version: 0.5.2
* OS and Version: Windows Server 2012
* Checking from: Nagios
* Checking with: check_nrpe

**Comment by mickem** [comment]
Not sure I understand...

But external scripts work in 0.5.2 as well.

Could you provide the relevant config (external scripts sections).

You can use the command line to add a script like so:

```
c:\source\build\x64\dev
$ nscp ext-scr install
Arguments are NOT allowed.


c:\source\build\x64\dev
$ nscp ext-scr add --script scripts\check_ok.bat
L       core Duplicate commandfor command: check_ok
Added check_ok as scripts\check_ok.bat
```

The resulting config:
```
[/settings/external scripts/server]
allow arguments = false
allow nasty characters = false

[/modules]
CheckExternalScripts = enabled

[/settings/external scripts/wrappings]
bat = scripts\\%SCRIPT% %ARGS%
vbs = cscript.exe //T:30 //NoLogo scripts\\lib\\wrapper.vbs %SCRIPT% %ARGS%
ps1 = cmd /c echo If (-Not (Test-Path "scripts\%SCRIPT%") ) { Write-Host "UNKNOWN: Script `"%SCRIPT%`" not found."; exit(3) }; scripts\%SCRIPT% $ARGS$; exit($lastexitcode) | powershell.exe /noprofile -command -

[/settings/external scripts/scripts]
check_ok = scripts\check_ok.bat 
```

**Comment by af9999** [comment]
yes the script work as well but in the nsclient logfile i've missing the answer of the script.
in the old nsclient++ version in the logfile is written
...
 OK ‘OK - Datei ist 25 Minuten alt.’
...
this is the returmessage from my script

in the new version from nsclient++ in the logfile this returnmessig is missing.

i've excecute the commands but i need the 
	allow arguments = true
	allow nasty characters = true 

so my nsclient.ini looks so

# If you want to fill this file with all available options run the following command:
#   nscp settings --generate --add-defaults --load-all
# If you want to activate a module and bring in all its options use:
#   nscp settings --activate-module <MODULE NAME> --add-defaults
# For details run: nscp settings --help


[/settings/default]
allowed hosts = XXXXXXXXXXXXXXX


[/settings/NRPE/server]
allowed hosts = XXXXXXXXXXXXXXXXX
verify mode = none
insecure = true
use ssl = 0
allow arguments = true
allow nasty characters = true
port = 5666


; NSCLIENT SERVER SECTION - Section for NSClient (NSClientServer.dll) (check_nt) protocol options.
[/settings/NSClient/server]
use ssl = false
performance data = true
port = 12489


[/settings/log]
file name = nsclient.log

; LOG LEVEL - Log level to use. Available levels are error,warning,info,debug,trace
level = trace


[/modules]
NSClientServer = enabled
CheckExternalScripts = enabled
CheckHelpers = enabled
CheckEventLog = enabled
CheckNSCP = enabled
CheckDisk = enabled
CheckSystem = enabled
NRPEServer = enabled

[/settings/external scripts]
	allow arguments = true
	allow nasty characters = true 

[/settings/external scripts/scripts]
check_logfiles = C:\Programme\NSClient++\scripts\check_logfiles --config="$ARG1$"
check_anzdat = C:\Programme\NSClient++\scripts\AF_Scripts\check_anzdat.exe $ARG1$ "$ARG2$" $ARG3$ $ARG4$ $ARG5$ $ARG6$ $ARG7$
check_anzdat_minuten = C:\Programme\NSClient++\scripts\AF_Scripts\check_anzdat_minuten.exe "$ARG1$" $ARG2$ $ARG3$ $ARG4$ $ARG5$ $ARG6$ $ARG7$
check_fileageaf = C:\Programme\NSClient++\scripts\AF_Scripts\fileage.exe $ARG1$ "$ARG2$" $ARG3$ $ARG4$

; in flight - TODO
[/settings/external scripts/server]

; Undocumented key
allow arguments = true

; Undocumented key
allow nasty characters = true


; Script wrappings - A list of templates for defining script commands. Enter any command line here and they will be expanded by scripts placed under the wrapped scripts section. %SCRIPT% will be replaced by the actual script an %ARGS% will be replaced by any given arguments.
[/settings/external scripts/wrappings]

; Batch file - Command used for executing wrapped batch files
bat = scripts\\%SCRIPT% %ARGS%

; Visual basic script - Command line used for wrapped vbs scripts
vbs = cscript.exe //T:30 //NoLogo scripts\\lib\\wrapper.vbs %SCRIPT% %ARGS%

; POWERSHELL WRAPPING - Command line used for executing wrapped ps1 (powershell) scripts
ps1 = cmd /c echo If (-Not (Test-Path "scripts\%SCRIPT%") ) { Write-Host "UNKNOWN: Script `"%SCRIPT%`" not found."; exit(3) }; scripts\%SCRIPT% $ARGS$; exit($lastexitcode) | powershell.exe /noprofile -command -

**Comment by mickem** [comment]
Why do you need it in the log file?
Not sure if it is logged that, maybe on debug or trace level?

**Comment by af9999** [comment]
for debugging. it is also not shown in level trace or debug

**Comment by mickem** [comment]
I might consider adding it on trace level...

**Comment by af9999** [comment]
it will be great
