### ISSUE TITLE
How many parallel connections does NsClient support?

### ISSUE THREAD

**Issue by SnappsProject** [mickem/nscp#609]
Hello,
I am balancing the nrpe control on two Windows nodes, some connections end randomly in timeout, but the nodes are not overloaded.

Is there a maximum number of requests for nsclient? or should I configure the nodes better?

Currently there are about 6000 services.

Thank you.
Snapps.

### Details

* NSClient++ version: 0.5.2.35
* OS and Version: Windows Server 2008/Windows Server 2012
* Checking from: Icinga,Nagios
* Checking with: check_nrpe,

**Comment by mintsoft** [comment]
I've generally found that `check_nt` scales better than both `check_nrpe` or `check_nsc_web`; even though it is deprecated :(

**Comment by mickem** [comment]
You can set number of response threads if you have very large stups, but with correct config you can have thousands of requests per second without ny issues...
It will also depend on what your checks are doing.

https://docs.nsclient.org/reference/client/NRPEServer/#thread-pool

Let me know if this does not answer your question.
