### ISSUE TITLE
Nagios Monitoring Windows Memory Problem on Virtual Machine 

### ISSUE THREAD

**Issue by 9428H** [mickem/nscp#612]
In virtual machine, Nagios is used to monitor the memory of windows host. The memory display monitored is inconsistent with the memory information of windows host. The memory monitored is twice as much as the real memory of windows. What is the reason?

**Comment by mintsoft** [comment]
@9428H That's probably also showing the page file; the differences are discussed here: https://github.com/mickem/nscp/issues/234
