### ISSUE TITLE
check_eventlog filter range doesn't provide valid result at all

### ISSUE THREAD

**Issue by Wintermute2k6** [mickem/nscp#623]
### Issue and Steps to Reproduce
While using check nrpe mode with nsclient++ and query for event id results the filter doesn't seem to work as expected.

Describe your issue and tell us how to reproduce it.

```
nscp test

check_eventlog "filter=id NOT in (starting range id, ending range id)"
...
Result = full list of all events
...
```

### Expected Behavior

As check used above it would list all event id's not included in a specific range.

### Actual Behavior

Even when you specify an broad or small range you always get the full event id result of all actual event id's.

Tell us what happens instead.

### Details

* NSClient++ version: 0.5.0.62
* OS and Version: Windows Server 2012, 2012 R2, 2016
* Checking from: Icinga2,
* Checking with: check_nrpe, check_nt, ...

### Additional Details

When initiated with the following command

sudo -u icinga ./check_nrpe -H dummy.host.com -c CheckEventlog -a "filter=id not in (10014,10016)" (it just filters for all critical events. filter doesn't seem to work???) 

NSClient++ log:
```
PLEASE PASTE LOG HERE
```

**Comment by BoWolf** [comment]
I have tried the same checks with the NRPE-Client 5.3.4
That looks much better.
Is there any Time-Line setting this beta - nightly Build to a stable-Version?
(Nightly build since April 2018)

**Comment by mickem** [comment]
In is not a range but a list, if you want to do ranges I guess you have to do > and <:

``` 
check_eventlog "detail-syntax=%(id)" "filter=source = 'Microsoft-Windows-DistributedCOM'"
L        cli WARNING: WARNING: 57 message(s) 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016, 10016
L        cli  Performance data: 'problem_count'=57;0;0
check_eventlog "detail-syntax=%(id)" "filter=source = 'Microsoft-Windows-DistributedCOM' and id lt 10000 and id gt 11000"
L        cli OK: OK: No entries found
L        cli  Performance data: 'problem_count'=0;0;0
```
Please do let me know if this resolved your issue.

**Comment by BoWolf** [comment]
Thank you, that resolves my Problem.
