### ISSUE TITLE
check_eventlog message filtering

### ISSUE THREAD

**Issue by Brickius** [mickem/nscp#629]
I am trying to filter an event log for multiple different messages-

check_eventlog -a scan-range=-2m file=application "filter=source like 'Feed' AND message like in ('Error','Error2')"

I'm struggling to find the right syntax to use a 'like' and an 'or' in the message field

**Comment by twilson-asg** [comment]
There isn't an 'in' operator. So you need something like

`check_eventlog -a scan-range=-2m file=application "filter=source like 'Feed' AND message like 'Error' OR message like 'Error2'"`

For a list of valid operators, see: https://docs.nsclient.org/checks/#expressions (the same operators logic is used for bother expressions and filters).

**Comment by mickem** [comment]
With newer versions you can have multiple filters which might make this simpler.
then you can have a series of filter=... filter=...

Also in general there is no reason to filter on message (unless you want to filter on a pare,eter) as the message is (normally) bound to a id/source combination.

See for instance the following:
```
check_eventlog 
   "detail-syntax=%(source) - %(id)" 
   "filter=source = 'Microsoft-Windows-USB-USBHUB3' and id = 196" 
   "filter=source = 'Microsoft-Windows-DistributedCOM' and id = 10016"
```
