### ISSUE TITLE
Separate performance data from values being checked?

### ISSUE THREAD

**Issue by bonki** [mickem/nscp#630]
Is it possible to force certain performance data but not consider the values when checking thresholds?
E.g. I'd like `check_cpu` to generate events against a single average, say 15m, but have performance data returned for multiple periods, say 1m, 5m and 15m.

**Comment by mintsoft** [comment]
@bonki If I interpret what you mean correctly, you want to have thresholds/alerts on the 15minute average, but want the perfdata for 1m, 5m, 15m?

**Comment by bonki** [comment]
@mintsoft Exactly that. As far as I understand it you can only remove/change things which are already selected, not add "additional" performance data (i.e. the opposite from what I want). If what I want is indeed is possible via perf-config I'll have to admit I don't understand the documentation which I find a bit lacking.

**Comment by mintsoft** [comment]
@bonki Yeah I've been playing around. I don't think you can do it with `check_cpu` in one command; the filters will only let you remove or mutate the perfdata not add new dimensions; and it looks like the threholds apply to everything no matter what: https://github.com/mickem/nscp/blob/85d3bcbfc04e3746f20af15a7b19a96317425718/modules/CheckSystem/CheckSystem.cpp#L586

I think I'd do it in 2 checks, one with `1m, 5m` then  a seperate one with `15m` with the thresholds you want.

**Comment by mickem** [comment]
You can limit the checks to check only certain values, each time is an entry in the list so if you specify a given time in your check you will only check that while getting performance data for all of them:

```
check_cpu "warn=time='5m' and load > 20"
L        cli OK: OK: CPU load is ok.
L        cli  Performance data: 'total 5m'=16%;20;90 'total 1m'=24%;20;90 'total 5s'=11%;20;90
```

Notice how the CPU load is 24% for the 1m time above yet we still return an ok.

Let me know if this is what your looking for.
