### ISSUE TITLE
How bad are inexistent predefined counters?

### ISSUE THREAD

**Issue by avezinaATastus** [mickem/nscp#631]
### Issue and Steps to Reproduce

Add an inexistent predefined counter to your config

### Actual Behavior

Error : c0000bc6: The data is not valid.

### Details

* NSClient++ version: 0.5.2
* OS and Version: Windows Server 2016
* Checking from: Nagios 4.4.X
* Checking with: check_nt, 

### Additional Details

Hi,

I just wanna know if there is any downside to have an inexistent counter specified in the config?

I deploy my NSClient++ config via GPO/registry, and so far I have been able to use only one GPO for my NSClient setup.

**Comment by mintsoft** [comment]
The only real downside is that NSClient may slowly eat all your RAM; unfortunately allocating memory to access a non-existant counter can result in a memory leak. Personally, I'd recommend only running NSClient with an error-free output log

**Comment by avezinaATastus** [comment]
Great! Thanks for the answer.

I will then take some time to make some AD groups and GPO filtering.
