### ISSUE TITLE
(Process.exe)/% Processor Time is not the correct value, documentation TODO

### ISSUE THREAD

**Issue by avezinaATastus** [mickem/nscp#632]
https://docs.nsclient.org/howto/counters/#some-counters-does-not-return-the-correct-value

What is the correct argument for scaled/capped counter. I guess this is the reason I only get 100 on a counter, instead of the possible 0-800 values (because 8 core system)

**Comment by mickem** [comment]
You can use the flags parameter described here: https://docs.nsclient.org/reference/windows/CheckSystem/#command-line-arguments_5

i.e. flags=nocap100 etc.
What you need to do depends on the counter so you need to play around a bit.

**Comment by avezinaATastus** [comment]
I now understand. Since I was using predefined counters, and testing them by using their names, I couldn't add args to the test since it is predefined.

I had to add the flags=nocap100 to the predefined counter definition. 

You cannot do (within `nscp.exe test`) :
`check_pdh counter=counter1 flags=nocap100`
