### ISSUE TITLE
Failed to add counter

### ISSUE THREAD

**Issue by avezinaATastus** [mickem/nscp#634]
### Issue and Steps to Reproduce

Frankly, I don't know. It happens sometimes, and sometimes not.

This time, some servers rebooted during the night, and I come this morning to a Nagios full of "Failed to get value".

My counters are predefined via ini file And those counters are .

```
 	$USER1$/check_nrpe -u -t 30 -2 -n -H $HOSTADDRESS$ -c check_pdh -a "counter=AutomationService" "time=60s"
```

```
[/settings/system/windows/counters/AutomationService]
counter=\Process(AutomationService)\% Processor Time
collection strategy=rrd
flags=nocap100
```

```
E  w32system Exception in Failed to add counter AutomationService:
                    c:\source\master\modules\CheckSystem\pdh_thread.cpp:147
```

### Expected Behavior

No error on nscp start, and correct values returned to Nagios

### Actual Behavior

The counters are not loaded, and I can't get any values

### Details

* NSClient++ version: 0.5.2
* OS and Version: Windows Server 2016
* Checking from: Nagios
* Checking with: check_nrpe

### Additional Details

NSClient++ log:
```
2019-09-25 07:14:00: error:c:\source\master\modules\CheckSystem\pdh_thread.cpp:147: Exception in Failed to add counter AutomationService: 
```

Oh yeah, while I'm here, the documentation on Performance Counters in NSClient is really incomplete. There's options I have no idea what they do, and I setup multiple counters, looking at the same counter, but with different settings, and I still can't understand the different settings

**Comment by avezinaATastus** [comment]
Hey! Found it! Invalid predefined counters (missing counters ) breaks valid predefined counters.

**Comment by mintsoft** [comment]
I think that's expected isn't it @avezinaATastus . If I'm interpreting what you're saying correctly, if the counter doesn't exist when NSClient is started, then NSClient can't read the counter? 

Is it a startup order thing? I.e if NSClient starts before the AutomationService then the counter is broken, otherwise it works fine? If you restart NSClient when it's in the error state does it resolve itself?

**Comment by mickem** [comment]
You can reload counters on failures which will solve such raise conditions.

Check reload here: https://docs.nsclient.org/reference/windows/CheckSystem/#check_pdh

Regarding the documentation do you have an example of something which is missing?

**Comment by avezinaATastus** [comment]
Well, just now I'm looking to add a min/max to performance data, and I think what I'm looking for might be configurable via perf-config, but the documentation is TODO.

https://docs.nsclient.org/reference/windows/CheckSystem/#check_pdh_perf-config
