### ISSUE TITLE
Exit code for a CheckExternalScripts module

### ISSUE THREAD

**Issue by infraweavers** [mickem/nscp#637]
### Issue and Steps to Reproduce

Using check_nsc_web against NSClient++ will output some error information but returns with an exit code of '0' when running an external script from the CheckExternalScripts module if the script you are attempting to run doesn't exist. 

nsclient.ini
```
myscript=cmd /c echo scripts\myscript.ps1; exit($lastexitcode) | powershell.exe -command 
```
check_nsc_web
```
/omd/sites/default/lib/monitoring-plugins/check_nsc_web -p mypassword-u https://myhost:8443 -k myscript; echo $?
```
This outputs 0. This is not just with check_nsc_web but also NRPE and through the web interface directly.

### Expected Behavior

The above command should return a non-zero exit code.

### Actual Behavior

The above command returned exit code 0.

### Details

* NSClient++ version: 0.5.2.41
* OS and Version: Windows Server 2012 R2
* Checking from: Nagios/OMD
* Checking with: check_nsc_web, nrpe

**Comment by mickem** [comment]
How does the script look?

**Comment by infraweavers** [comment]
@mickem The script didn't exist on disk, that was the point :)

**Comment by mickem** [comment]
Ohh... yes, there are some snags with powershell which are resolved by the CheckPowerShell module.

```
ps1
D            Running: ./missing.ps1 from C:\src\build\dev
E            The term './missing.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
                    C:\src\nscp\modules\CheckPowershell\CheckPowershell.cpp:168
L        cli UNKNOWN: The term './missing.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
L        cli  Performance data:
```
