### ISSUE TITLE
Check_nt plugin for memory check returning inaccurate result.

### ISSUE THREAD

**Issue by Zaheerkhan999** [mickem/nscp#638]
### COMMAND
**/usr/local/nagios/libexec/check_nt -H 1.2.3.4 -p 12489 -v MEMUSE**

### Expected Behavior

Total memory should be the same as per the allotted memory of the server but it is showing just double of it.
In my case server is having total memory of 16 GB so output should come  around 16000 MB 
but it is giving 32608.21 MB. 
Used and free percentage are also differed. 

### Current Behavior
Command Output- 
Memory usage: **total:32608.21 MB** - used: 8796.76 MB (27%) - free: 23811.45 MB (73%) | 'Memory usage'=8796.76MB;0.00;0.00;0.00;32608.21

### Details

* NSClient++ version: 0.5.2
* OS and Version: Windows Server 2012
* Checking with: check_nt

### Additional Details

![image](https://user-images.githubusercontent.com/55441372/67577420-0edf1c00-f75e-11e9-8635-1ed16f01dd8c.png)

**Comment by mintsoft** [comment]
@Zaheerkhan999 `MEMUSE` includes the page file; if you want free physical memory there's a performance counter for that

**Comment by Zaheerkhan999** [comment]
Thanks for the reply, but this is only for the available bytes can we make it similar to the output like memuse or NCPA.

I tried it using the NCPA which is giving the proper output below.

OK: Used memory was 21.80 % (Available: 12.51 GiB, Total: 16.00 GiB, Free: 12.51 GiB, Used: 3.49 GiB) | 'available'=12.51GiB;;; 'total'=16.00GiB;;; 'free'=12.51GiB;;; 'used'=3.49GiB;;;

Please let me know if we can have some other alternative or workaround for the MEMUSE by using  NSCLIENT+

Thanks,
Zaheer Khan

**Comment by Zaheerkhan999** [comment]
> @Zaheerkhan999 `MEMUSE` includes the page file; if you want free physical memory there's a performance counter for that

Thanks for the reply, but this is only for the available bytes can we make it similar to the output like memuse or NCPA.

I tried it using the NCPA which is giving the proper output below.

OK: Used memory was 21.80 % (Available: 12.51 GiB, Total: 16.00 GiB, Free: 12.51 GiB, Used: 3.49 GiB) | 'available'=12.51GiB;;; 'total'=16.00GiB;;; 'free'=12.51GiB;;; 'used'=3.49GiB;;;

Please let me know if we can have some other alternative or workaround for the MEMUSE by using NSCLIENT+

Thanks,
Zaheer Khan

**Comment by mintsoft** [comment]
@Zaheerkhan999 I think `check_memory` will do what you want : https://docs.nsclient.org/reference/windows/CheckSystem/#check_memory

**Comment by Zaheerkhan999** [comment]
This is only available with check_nrpe not for check_nt and also not giving the same output including total memory, only tells free memory.

**Comment by mintsoft** [comment]
@Zaheerkhan999 Perfectly possible that it can't be done with `check_nt` at all then. It'd definitely be possible with either `check_nrpe` or `check_nsc_web` though as they're far more flexible.

**Comment by box293** [comment]
These two KB articles should help explain how to achieve what you want:

https://support.nagios.com/kb/article/nagios-xi-windows-memory-usage-physical-169.html
https://support.nagios.com/kb/article/memory-checks-774.html

**Comment by mickem** [comment]
check_nt s not designed to be extensible and allow configuring monitoring so changing this would break existing usecases even though it would make more sense.
But in general I would advocate switching away from check_nt as it is very limited.
