### ISSUE TITLE
CheckEventLog Ok status ignored

### ISSUE THREAD

**Issue by mjnewland** [mickem/nscp#639]
### Description
I have an application that writes to the Application Event Log. It will send a Critical(1), or Warning(3), or Success(4) with ID=3772. However, if I have any warnings or critical entries for 3772, any subsequent success are ignored.  I want to send to the log any warning/critical issues so that Nagios will notify appropriate people. Then when the issue is corrected an Ok is posted to the event log and Nagios posts an Ok.  Seems that CheckEventLog is not send the Ok message after a warning or Critical posting. I am running NSClient++.exe version 0.5.2.35. 

Here is the latest command (I have tried many different variants):
check_eventlog log=Application filter=id=3772 ok=level=4  ok-syntax="Both in range" debug

The log currently has these entries:
Information	10/25/2019 8:52:44 AM	EBCMONITOR	3772	None
Warning	        10/25/2019 8:51:58 AM	EBCMONITOR	3772	(1)

### Expected Behavior

I expect to get: Ok: Both in Range

### Actual Behavior

WARNING: WARNING: 2 message(s) Application EBCMONITOR (Refrigerator Normal (79.2F) ), Application EBCMONITOR (Refrigerator Warning (79.2F) )

### Details

L        cli WARNING: WARNING: 2 message(s) Application EBCMONITOR (Refrigerator Normal (79.2F) ), Application EBCMONITOR (Refrigerator Warning (79.2F) )
L        cli  Performance data: 'problem_count'=1;0;0

### Additional Details

NSClient++ log:
```
check_eventlog log=Application filter=id=3772 ok=level=4  ok-syntax="Both in range" debug
D   eventlog Parsing: ${status}: ${count} message(s) ${problem_list}
D   eventlog Parsing: ${file} ${source} (${message})
D   eventlog Parsing: ${file}_${source}
D   eventlog Parsing: Both in range
D   eventlog Parsing: %(status): No entries found
D   eventlog Parsing: id=3772
D   eventlog Parsing succeeded: (tbd){(int)var:id = (i){3772}}
D   eventlog Type resolution succeeded: (bool){(int)var:id = (i){3772}}
D   eventlog Binding succeeded: (bool){(int)var:id = (i){3772}}
D   eventlog Static evaluation succeeded: (bool){(int)var:id = (i){3772}}
D   eventlog Parsing: level = 'warning'
D   eventlog Parsing succeeded: (tbd){(int)var:level = (s){warning}}
D   eventlog Type resolution succeeded: (bool){(int)var:level = {ui:2}convert((s){warning})}
D   eventlog Binding succeeded: (bool){(int)var:level = {ui:2}convert((s){warning})}
D   eventlog Static evaluation succeeded: (bool){(int)var:level = {ui:2}convert((s){warning})}
D   eventlog Parsing: problem_count > 0
D   eventlog Parsing succeeded: (tbd){(int)var:problem_count > (i){0}}
D   eventlog Type resolution succeeded: (bool){(int)var:problem_count > (i){0}}
D   eventlog Binding succeeded: (bool){(int)var:problem_count > (i){0}}
D   eventlog Static evaluation succeeded: (bool){(int)var:problem_count > (i){0}}
D   eventlog Parsing: level in ('error', 'critical')
D   eventlog Parsing succeeded: (tbd){(int)var:level in (s){error}, (s){critical}}
D   eventlog Type resolution succeeded: (bool){(int)var:level in {ui:2}convert((s){error}, (s){critical})}
D   eventlog Binding succeeded: (bool){(int)var:level in {ui:2}convert((s){error}, (s){critical})}
D   eventlog Static evaluation succeeded: (bool){(int)var:level in {ui:2}convert((s){error}, (s){critical})}
D   eventlog Parsing: level=4
D   eventlog Parsing succeeded: (tbd){(int)var:level = (i){4}}
D   eventlog Type resolution succeeded: (bool){(int)var:level = {ui:2}convert((i){4})}
D   eventlog Binding succeeded: (bool){(int)var:level = {ui:2}convert((i){4})}
D   eventlog Static evaluation succeeded: (bool){(int)var:level = {ui:2}convert((i){4})}
D   eventlog Ok match: Application EBCMONITOR (Refrigerator Normal (79.2F) )
D   eventlog Warn match: Application EBCMONITOR (Refrigerator Warning (79.2F) )
L        cli WARNING: WARNING: 2 message(s) Application EBCMONITOR (Refrigerator Normal (79.2F) ), Application EBCMONITOR (Refrigerator Warning (79.2F) )
L        cli  Performance data: 'problem_count'=1;0;0
```

**Comment by mintsoft** [comment]
@mjnewland I think the problem is here that you want to output only the latest result? `check_eventlog log=Application filter=id=3772 ok=level=4 ok-syntax="Both in range" debug` checks the whole event log for any event. You could put a time limit on it so that you are looking for logs in the last n minutes? If you align that with your `check_interval` in nagios then it should only alert once? It's a bit round-about, but should achieve what you want?

**Comment by mjnewland** [comment]
Yes I am getting close and I have added a 30min interval.  The command
details I forwarded was from the test environment on the host. On the
server side it looks like the command is being executed, but the command
line is not being transferred - another problem altogether.

Thanks for the input.  Mark


*Mark Newland */ Director, Technology
mnewland@emmaus.edu <mnewland@elearn.emmaus.edu>
<mnewland@elearn.emmaus.edu>
Office: 563-588-8000 x3019 <%28563%29%20588-8000>, Cell: 620-770-2491
<%28620%29%20770-2491>

Emmaus Bible College
2570 Asbury RoadDubuque, IA 52001
www.emmaus.edu

**Comment by mickem** [comment]
You can achieve this via "rea time filtering" having one alert for setting the error and another for re-setting it.
It will be a bit more complicated to setup though.

I wrote about how to do this here: https://www.medin.name/blog/2012/09/09/self-resetting-event-log-alerts/
