### ISSUE TITLE
check separate service - is it possible

### ISSUE THREAD

**Issue by kucharst** [mickem/nscp#674]
### Issue and Steps to Reproduce

Hello,

I would like to ask if there is a possibility to check a separate service?
I'm mainly interested to check by my nagios core server the RDP service (Termservice) placed on windows terminal server.
I can easily check all services with some exceptions:
```
_alias_service_ex = checkServiceState CheckAll "exclude=RemoteRegistry" "exclude=WbioSrvc" "exclude=gupdate" "exclude=BITS" "exclude=MapsBroker" "exclude=OneSyncSvc_284643e4e" "exclude=SCardSvr"
`_``

But have no idea how to check just one service, this command doesn't work for me at all:

```
_alias_service checkServiceState "service=Termservice"_ 
```

it just showing all services, not the one i'm interested in.

### Details

* NSClient++ version: 0.5.2.35
* OS and Version: Windows Server 2016 Standard
* Checking with: check_nrpe, check_nt, ...

Thanks for any help.
Regards
Tomek

**Comment by mintsoft** [comment]
@kucharst I think the command you want is like:
```
check_service service=Termservice
```

checkServiceState is deprecated and doesn't have the same syntax.

**Comment by kucharst** [comment]
Thanks @mintsoft, 

Unfortunately it didn't worked :(
It just shows status of all services, not the one i want to check. :(
I tried with and without quotes, setting warn and crit,

 _**./check_nrpe -H rds_windows_server -c check_service service=Termservice**_
     _CRITICAL: RemoteRegistry=stopped (auto), WbioSrvc=stopped (auto), delayed (gupdate=stopped (delayed), MapsBroker=stopped (delayed))_

**Comment by mintsoft** [comment]
@kucharst The `service=Termservice` is an argument to the command, so either `-a service=Termservice`  or add it into the nsclient.ini as an alias. I can't remember the exact format for `check_nrpe` but it's something like that

**Comment by kucharst** [comment]
Thank you so much for help and patience :)
it works with an alias :)

Have a nice week!
