### ISSUE TITLE
Spelling mistakes / inconsistencies in nscp binary settings section (0.4.3.73)

### ISSUE THREAD

**Issue by box293** [mickem/nscp#68]
extract from "nscp settings"
<pre>--help                produce help message</pre>
produce should probably have a captial <b>P</b>

<br>
<pre>--show                       Set a value given a key and path.</pre>
This should say:
<b>Show</b> a value given a key and path.

<br>
<pre>--list                       Set all keys below the path (or root).</pre>
This should say:
<b>List</b> all keys below the path (or root).

<br>
<pre>--use-samples                Some commands (generate) can alsu se sample 
                               values</pre>
I *think* this should say:
Some commands (generate) can <b>also use</b> sample values.

**Comment by mickem** [comment]
Resolved in next build
