### ISSUE TITLE
0.4.3.77 - check_pdh.cpp:242 - Exception in Failed to poll counter - network_Bytes

### ISSUE THREAD

**Issue by mathieuchateau** [mickem/nscp#72]
Hello,

i upgraded a server to test the new version, from 0.4.1.90 to 0.4.3.77. 2 things stopped working;
-Check for scheduled task (i will check deeper why)
-One performance counter (and not the others one)

The broken counter is for network card:

error:D:\source\nscp\modules\CheckSystem\check_pdh.cpp:242: Exception in Failed to poll counter: network_Bytes Failed to poll counter \Network Interface(*)\Bytes Total/sec: c0000bba: The returned data is not valid.

**Comment by mathieuchateau** [comment]
testing locally from nsclient:

checkCounter -a Counter:'network_Bytes'=\"\\Network Interface(*)\\Bytes Total/sec\" MaxWarn=25000000 MaxCrit=50000000 MinWarn=-1 MinCrit=-1 ShowAll
INF: Detected crash...
INF: Running: "C:\Program Files\NSClient++\reporter.exe" "archive" "C:\Users\TEMP~1.PMS\AppData\Local\Temp\\c8725f76-024
6-40a5-b430-c6d5c6ca6b1a.dmp" "NSClient++" "0,4,3,77" "2015-01-04" "C:\Program Files\NSClient++/crash-dumps"
Created folder: C:\Program Files\NSClient++/crash-dumps
INF: Running: "C:\Program Files\NSClient++\reporter.exe" "send" "C:\Users\TEMP~1.PMS\AppData\Local\Temp\\c8725f76-0246-4
0a5-b430-c6d5c6ca6b1a.dmp" "NSClient++" "0,4,3,77" "2015-01-04" "C:\Program Files\NSClient++/crash-dumps"
00007FF6D31D7B10Failed sending report to server:
INF: Running: "C:\Program Files\NSClient++\reporter.exe" "restart" "NSClientpp"

**Comment by mickem** [comment]
I cant replicate this, can you send me the dump file? michael AT medin DOT name

**Comment by mickem** [comment]
Strange checked the dump and the crash comes from the boost library which is parsing the command line, it is surrounded with a catch so should not be able to crash.

Exactly how did you create this?

nscp test and then just paste the command as is in?

**Comment by mathieuchateau** [comment]
yes

i don't why just the network perf counter is not working.
When it's through nrpe i don't think it crashes.


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-06 20:55 GMT+01:00 Michael Medin <notifications@github.com>:

**Comment by mickem** [comment]
Could be it has the "wrong type" in 0.4.2 you can configure the type which is used to poll the value, the error code indicates this, I shall try this.

But the crash seems odd, maybe you got some "strange char" when you pasted it in?

**Comment by mathieuchateau** [comment]
new try:

1 server with 0.4.1:

checkCounter Counter:"network_Bytes"="\\Network Interface(*)\\Bytes Total/sec" MaxWarn=25000000 MaxCrit=50000000
d rvice\NSClient++.cpp:960  Injecting: checkcounter...
d rvice\NSClient++.cpp:985  Result checkcounter: OK
l ce\simple_client.hpp:80   OK:OK all counters within bounds.
l ce\simple_client.hpp:82    Performance data: 'network_Bytes'=304919.01696;25000000;50000000


The server with 0.4.3

checkCounter Counter:"network_Bytes"="\\Network Interface(*)\\Bytes Total/sec" MaxWarn=25000000 MaxCrit=50000000
D  w32system Created command: warn=value>=25000000 crit=value>=50000000 "counter:network_Bytes=\Network Interface(*)\Byt
es Total/sec"
E  w32system Exception in Failed to poll counter: network_Bytes Failed to poll counter \Network Interface(*)\Bytes Total
/sec: c0000bba: Les donnÃ©es renvoyÃ©es ne sont pas valides.

                    D:\source\nscp\modules\CheckSystem\check_pdh.cpp:242
L        cli Long message
UNKNOWN: Failed to poll counter: network_Bytes Failed to poll counter \Network Interface(*)\Bytes Total/sec: c0000bba: Les donnÃ©es renvoyÃ©es ne sont pas valides.


It was both from RDP, copying and paste same command
0.4.3 server is english with french language installed

**Comment by mickem** [comment]
Was due to rate copunter, will be fixed in the next build (and a workaround now is adding averages on the command line)

**Comment by mickem** [comment]
You can test build 0.4.3.86 here: http://www.nsclient.org/download/nightly/

**Comment by mathieuchateau** [comment]
with 0.4.3.86, all performance counter test fails
Unknown command(s): checkcounter

even the ones working before

error:D:\source\nscp\include\nscapi\nscapi_core_helper.cpp:95: Failed to execute command: checkCounter
ü2015-01-08 09:32:19: error:D:\source\nscp\service\NSClient++.cpp:890: Unknown command(s): checkcounter available commands: commands {, check_logfile, check_tasksched, check_wmi, checklogfile, checktasksched, checkwmi}, plugins {, 0, 1, 2, 3}
ü2015-01-08 09:32:19: error:D:\source\nscp\include\nscapi\nscapi_core_wrapper.cpp:159: Failed to execute command
2015-01-08 09:32:19: error:D:\source\nscp\include\nscapi\nscapi_core_helper.cpp:95: Failed to execute command: checkCounter

**Comment by mickem** [comment]
seems CheckSYstem has not loaded, is it configure? (if so please check log during startup)

Good thing I did not replace the released version :)

**Comment by mathieuchateau** [comment]
After setting checkSystem to 1, performance counter works again, even the
network one!

I just installed over the existing one, how could checkSystem goes back to
0 ?

The status information is still empty, but the perf counter name is now
back without "_value"


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-08 9:37 GMT+01:00 Michael Medin <notifications@github.com>:

**Comment by mickem** [comment]
CheckCounter gives you _value in the perf datat? strange... check_pdh will given you that, but CheckCOunter hsould not... will investigate...

**Comment by mathieuchateau** [comment]
it was with 0.4.3.77, but looks like it's good now.

Need some time to check graphes


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-08 10:08 GMT+01:00 Michael Medin <notifications@github.com>:

**Comment by mickem** [comment]
ahhh... sorry, with*out*... read it as "back with" :)
Does this mean we are all good (apart from the status text?)

**Comment by mathieuchateau** [comment]
yes, all gooooooddd !! thanks a lot !

Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-08 10:13 GMT+01:00 Michael Medin <notifications@github.com>:
