### ISSUE TITLE
0.4.3.77 - Performance data returned

### ISSUE THREAD

**Issue by mathieuchateau** [mickem/nscp#73]
Since the upgrade from 0.4.1.90 to 0.4.3.77, the performance data behaviour changed:
-I now just get "OK" instead of "OK: countername: perfvalue"
-the counter name changed and now "_value" is appended. So it's a new perfdata in graph, loosing history.

screenshot before:
![image](https://cloud.githubusercontent.com/assets/4478521/5626667/d3e70120-958e-11e4-88b8-da098c5b4c62.png)

screenshot after:
![image](https://cloud.githubusercontent.com/assets/4478521/5626671/e67e444c-958e-11e4-8483-edc005cbc4d6.png)

**Comment by mickem** [comment]
Yes, this is true...Should be fixed in the next build

**Comment by mickem** [comment]
You can test build 0.4.3.86 here: http://www.nsclient.org/download/nightly/

**Comment by mathieuchateau** [comment]
fix confirmed
