### ISSUE TITLE
Empty list after filter processing of check_process generates an OK state

### ISSUE THREAD

**Issue by davmik** [mickem/nscp#74]
If a special filter (for example for command_line matching) is used with default warn and crit criteria there is a bug when the filter results in an empty process list (as it probably will when the process is not running). The return state is always OK.

If I extend the default critical criteria to "critical=state = 'stopped' OR count=0" it still results in:
OK: |'count'=0;0;0

If I use "crit=count = 0" it results correctly for the count but a state is not checked anymore if there is a non empty list:
CRITICAL: |'count'=0;0;0

**Comment by davmik** [comment]
"empty-state=critical" or "empty-state='critical'" doesn't work, too.

**Comment by mickem** [comment]
Should be fixed in the next build

**Comment by mickem** [comment]
You can test build 0.4.3.86 here: http://www.nsclient.org/download/nightly/

**Comment by davmik** [comment]
Still does not work with the mentioned build:

> /usr/lib64/nagios/plugins$ ./check_nrpe8192 -H xxx.xxx.xxx.xxx -c check_process -a "filter=state ne 'unreadable' AND command_line regexp '.*C.*jre7.*java.*-Xmx1024m.*JDBC.*TEST'" "process=java.exe" "empty-state=critical"
> OK: |'count'=0;0;0
