### ISSUE TITLE
NSClient++ Vers. 4.2.93 reporter.exe Virus warning

### ISSUE THREAD

**Issue by fiete** [mickem/nscp#75]
After executing NSCP-0.4.2.93-Win32.msi (http://www.nsclient.org/files/released/NSCP-0.4.2.93-Win32.msi), the install directory folder "NSClient++/" contains a "reporter.exe" (among "nscp.exe", "nsclient.ini" and others).
Our anti virus software "G Data Virus Scan" identifies this file to be a gen:variant:kazy malware trojan. Microsoft Defender and Avast Antivirus, as well as Avira do not identify any security issues (see overview attached).
Please check this executable for security issues.

![reporter_exe_scan](https://cloud.githubusercontent.com/assets/6479706/5646390/de6df426-967b-11e4-941e-1bca8e090795.png)

**Comment by mickem** [comment]
Do you get the same warning in any other versions?

**Comment by mickem** [comment]
I have not been able to find any alerts (using the same web page) on other files or versions trying both 0.4.3, 0.4.2, w32, x64, etc. 
It is a only the w32 version of 0.4.2.93 which shows this issues, and a binary diff with the previous version of reporter.exe (which is not changed much) shows only a 3x3 bytes + 16bytes diff. So it is a very small virus/male-ware if it is one.

So I would guess on a false positive, but please do help me verify this!
No idea really how to go about verifying it myself...

![image](https://cloud.githubusercontent.com/assets/1434697/5646943/abb1310a-9681-11e4-8b49-07651a124cbb.png)

![image](https://cloud.githubusercontent.com/assets/1434697/5646945/b4589ec4-9681-11e4-973d-f453d5c44bad.png)

![image](https://cloud.githubusercontent.com/assets/1434697/5646946/b88fdfc0-9681-11e4-8a86-89ae7219b752.png)

**Comment by mathieuchateau** [comment]
where does the binary comes form ?
is it part of nsclient dev or third party ?
![image](https://cloud.githubusercontent.com/assets/4478521/5647111/1cb15082-9683-11e4-8f87-685a44e8f43a.png)

**Comment by fiete** [comment]
There is no warning for the latest version with GData(4.3.77 Win32), but still we are using 4.2.93 Win32. There seem to be two possibilities: 
A) virus scan is too sensitive /  false alarm or 
B) trojan?

I am still uncertain about it, trying to analyze the file..

**Comment by mickem** [comment]
I build the binary... same as I build nscp.exe (built after each other) so same compiler and same libs...

**Comment by mickem** [comment]
I'll try rebuilding it when I get home and see if that makes things better or the same...
Also submitted the file for review at bitdefender

**Comment by mathieuchateau** [comment]
Could you also add informations on the executable so it becomes obvious its part of nsclient ?
like the information you set on the main binary:
![image](https://cloud.githubusercontent.com/assets/4478521/5647663/4dfd7274-9688-11e4-9ebe-9c9ab4a35844.png)

Would be great to have that and good version number for others DLL too.
MSI engine compare dll versions to detect if an upgrade is needed.

Example:
![image](https://cloud.githubusercontent.com/assets/4478521/5647681/79d42ef6-9688-11e4-8d00-688e417569fa.png)

**Comment by mickem** [comment]
Next build of 0.4.3 will have versions and such (not interesting for you maybe, but will backport to 0.4.2 in a bit) Though I would say 0.4.2 -> 0.4.3 is a pretty small step.

**Comment by mickem** [comment]
I did a rebuild of the reporter.exe file and warning went away (https://www.virustotal.com/sv/file/16020470444a55046c018f9d74089433bdebcb13c1b4ca5a0827949d9a45f871/analysis/1420671612/), so will backport some fixes to 0.4.2 in the next few days and re-release it and hopefully the alert will go away...
If it is urgent let me know and I can rebuild as-is and re-build again when I have backported...

**Comment by mickem** [comment]
New 0.4.2 build in progress (you can grab the nightly right now, it is the same apart from changelog) which is fine through the scan: https://www.virustotal.com/sv/file/fb501395ae04d9b58f1c57b96bbcc69f3de1ad59687178a3bb72fd920c619675/analysis/1420755676/ and also containes all nice information.

I will remove the 93 build in a week or so "just to be sure" (I think it is a false positive) once I have gotten some feedback on the new 0.4.2 build.

**Comment by mickem** [comment]
FIY,. build 112 can be found here https://www.nsclient.org/download/nightly/ (look further down under 0.4.2) and 113 is in progress but only change is updates to the changelog.

**Comment by mickem** [comment]
Closing this since the 93 build has now been removed.

**Comment by mickem** [comment]
Just for the sake of it I never heard back from ANY of the anti virus tools I reported the false positive to so I cannot confirm but given back story I am convinced it was a false positive...

**Comment by tlundi** [comment]
I would like to add on version 4.3.9 still got warning. Our Antivirus programs is F-secure, and when unzipped my zip files last time on November it didnt say anything, but now got warning "Gen:Variant.Kazy.518013".

**Comment by mickem** [comment]
Get anything from newer versions?

**Comment by tlundi** [comment]
at least on version 4.3.98 didnt got warning from F-secure. But seems that I dont need reporter.exe anyway, so dont mind
