### ISSUE TITLE
NSCP-0.4.3.88-x64 - Access Denied on nsclient.ini

### ISSUE THREAD

**Issue by nagwindmon** [mickem/nscp#79]
I have just stated using Nagios to monitor Windows machines, after installation of latest NSClient Agent, to my understanding I need to enable to use NRPE plugin:
; ALLOWED HOSTS - A comaseparated list of allowed hosts. You can use netmasks (/ syntax) or * to create ranges.
allowed hosts = 11.48.23.67
 allow arguments=1
port=5666
allow nasty characters=1 
But I cannot save the changes!!!
Please advice
Thank you

**Comment by mickem** [comment]
You need to edit with admin privileges since the file is store under program files.

**Comment by nagwindmon** [comment]
thank you for prompt reply! I believe I log in as admin... however when I first loaded this version before I notice a new release NSCP-0.4.1.105-x64 - I have no issues to modify ini file at all?

**Comment by mathieuchateau** [comment]
Hello,

This is linked to UAC and Windows Security.
If you log in with the "true" first administrator (SID -500), then your
security token is not filtered, or if you disable UAC on computer.

But normally, admin "loose" admin privileges when opening session. Then UAC
detect when you need it and give it back to you after elevation.

Generally speaking, Program files folder is protected. You should right
click on notepad and choose "run as administrator". Then from notepad go to
the nsclient.ini to open it.

If you forgot, you can save the file to the desktop, and then copy it over
to the good place in program files. You will see the shield icon on the
confirmation.


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-13 14:43 GMT+01:00 nagwindmon <notifications@github.com>:

**Comment by nagwindmon** [comment]
but it still looks like something changed in latest version, because once again I had no problems modify ini file and save it on old version

**Comment by mathieuchateau** [comment]
If you created the file from your profile before, the ntfs rights were
kept. With the upgrade, this right may have been lost.

Having to elevate to edit file in program files is the normal behavior,
nothing specific to nsclient.

If you want to, you can change ntfs right on the ini file so standard users
can edit the file. And so you without elevating notepad. It would create a
security risks, especially if a citrix/RDP server.



Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-13 15:04 GMT+01:00 nagwindmon <notifications@github.com>:

**Comment by nagwindmon** [comment]
any way I thank you for your help, another question: how can I check which version is running on remote Machine?

**Comment by nagwindmon** [comment]
Everything worked! Reboot my Laptop and all good go to! Merci beaucoup! sorry if missed spell :)

**Comment by mathieuchateau** [comment]
If you do an nrpe call without any command, nsclient reply vith version:
I (0.4.3.86 2015-01-08) seem to be doing fine..


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-13 15:09 GMT+01:00 nagwindmon <notifications@github.com>:

**Comment by nagwindmon** [comment]
Mathieu, sorry I just begin using NSClient, where I put that command in? I did check during installation on "Enable NRPE server (check_nrpe)" and I believe I need to enable it, right? so I did this:
; Undocumented section
[/settings/NRPE/server]
allowed hosts = 11.48.23.67
 allow arguments=1
 port=5666
 allow nasty characters=1

**Comment by mathieuchateau** [comment]
who will request/poll nsclient ? nagios/centreon ?
who is 11.48.23.67 ?

Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-13 16:33 GMT+01:00 nagwindmon <notifications@github.com>:

**Comment by nagwindmon** [comment]
11.48.23.67 is Nagios Server

**Comment by mickem** [comment]
FIY, 0.4.1 (and I think 0.4.2?) had an option in the installer to make the config "user writable" this was removed in 0.4.3 as I deemed the WEB UI and the new command line interface to be better ways to edit the configuration.

**Comment by mathieuchateau** [comment]
on your nagios server, you will use check_nrpe to poll nsclient.
if you try from nagios plugins check_nrpe -H myNSclientServer it will
return version of nsclient

Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-13 16:42 GMT+01:00 nagwindmon <notifications@github.com>:

**Comment by nagwindmon** [comment]
thank you again! Like I said, just started, can you please provide more details, where exactly and how in NSClient Agent I use that plugin check_nrpe -H myNSclientServer?

**Comment by mathieuchateau** [comment]
nagios is the monitoring system.
To monitor deeper Windows, nagios will poll test to windows machine through
the nsclient, using nrpe protocol.
the command check_nrpe is on the nagios box, it's a nagios plugin. From
there, with this plugin, you can poll your windows server, like performance
counter, execute scripts, check windows update state & co



Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-13 18:32 GMT+01:00 nagwindmon <notifications@github.com>:

**Comment by nagwindmon** [comment]
Thank you again for everything! Let me read more, our company just purchased Nagios XI so all new to me...
is this good place to ask specific question in near future when I have one, Im sure I will have more :)

**Comment by mathieuchateau** [comment]
not a good place, this is a bug tracking system...

Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-13 19:04 GMT+01:00 nagwindmon <notifications@github.com>:

**Comment by nagwindmon** [comment]
oh ok, understand, this is for bugs only
