### ISSUE TITLE
check_memory: faulty perfdata values and faulty threshold checks

### ISSUE THREAD

**Issue by davmik** [mickem/nscp#80]
First example (perfdata wrong):
> /usr/lib64/nagios/plugins/check_nrpe8192 -t 30 -H 172.30.11.5 -p 5666 -c check_memory -a "warn=used > 50%" "crit=used > 60%" type=physical
> OK: |'physical'=3GB;3;4;0;7 'physical %'=47%;50;59;0;100

Threshold checking works well but perfdata isn't calculated/returned correctly. As you can see it returns 59 instead of 60 for crit value perfdata of 'physical %'. Furthermore it shows perf-data for 'physical' in GB. This is not precise enough. It should be MB.

Second example (faulty threshold checking and perfdata wrong):
> /usr/lib64/nagios/plugins/check_nrpe8192 -t 30 -H 172.30.11.5 -p 5666 -c check_memory -a "warn=used > 5G" "crit=used > 5632M" type=physical
> WARNING: physical = 3.798GB|'physical'=3GB;0;450;0;7 'physical %'=47%;4;5631;0;100

As you can see it returns a WARNING state but used threshold isn't reached. Furthermore the perf-data looks completly wrong.

**Comment by mickem** [comment]
Performance data is rounded so it is not exact (this is a known issue).

As for the other part you can set the perf data suffix if you want something else, the default it to "automatically scale it" ie. use the lowest value.

You can use the following to change the unit: perf-config=value(unit:B)"

**Comment by davmik** [comment]
Hi micken. Thanks the perf-config parameter works for maximum and current perfdata values. They are now shown in megabytes when "perf-config=value(unit:MB)" is used. Thanks for that.

But there are two further problems:

Example command:
> /usr/lib64/nagios/plugins/check_nrpe8192 -t 30 -H xxx.xxx.xxx.xxx -p 5666 -c check_memory -a "warn=used > 5G" "crit=used > 5632M" type=physical "perf-config=used(unit:M)"

It returns:
> WARNING: physical = 3.714GB|'physical'=3803M;409;461344;0;8191 'physical %'=46%;4;5631;0;100

But it should return the following:
> OK: physical = 3.714GB|'physical'=3803M;5120;5632;0;8191 'physical %'=46%;62;69;0;100

So there are two issues:
1. Threshold checking doesn't work. (WARNING returned but should be OK)
2. Perfdata calculation for the used and for the used_pct perfdata values do not work. (see perf-data values)

**Comment by davmik** [comment]
> "2. Perfdata calculation for the used and for the used_pct perfdata values do not work. (see perf-data values)"

Excuse me, I meant: It doesn't work for warn and crit perfdata values of used and used_pct.

**Comment by mickem** [comment]
Are you sure that the command is the one you actually used?

The numbers dont match and it does not behave that way for me.

I think the command you actually used was:

```
/usr/lib64/nagios/plugins/check_nrpe8192 -t 30 -H xxx.xxx.xxx.xxx -p 5666 -c check_memory -a "warn=used > 5G" "crit=used > 5632" type=physical "perf-config=used(unit:M)"
```
Notice the missing M.

The reason for this is the 5632 ends up in 'physical %'=46%;4;5631;0;100.
And if you do not specify a unit it is treated as %

So could you please verify the command?

**Comment by davmik** [comment]
Hello Michael,

I verified the command I used and it was the one I posted.

I've found the reason for the issue. It is because of the used version:

On version 0,4,2,93 2014-04-22 you get the numbermismatch.
On version 0.4.3.86 2015-01-08 everything is okay.

Command used:
> /usr/lib64/nagios/plugins/check_nrpe8192 -t 30 -H armat-web-1 -p 5666 -c check_memory -a "warn=used > 5G" "crit=used > 5632M" type=physical "perf-config=used(unit:M)"

I will update the old version now. Thx for your help!
