### ISSUE TITLE
Option for disabling deprecated TLS 1.1

### ISSUE THREAD

**Issue by alexgit2k** [mickem/nscp#814]
### Issue and Steps to Reproduce

It is possible to disable SSL 2, 3, TLS 1.0 via `ssl options`:
https://github.com/mickem/nscp/blob/a0bf0985471d8956409079515c5199a0b0b84fa4/docs/docs/reference/windows/NSClientServer.md?plain=1#L704-L712

As TLS 1.1 has been deprecated since 2021 (see https://datatracker.ietf.org/doc/html/rfc8996) there should be also a switch to disable TLS 1.1.

```
PLEASE PROVIDE COMMAND HERE
```

### Expected Behavior

Tell us what you think should happen.

### Actual Behavior

Tell us what happens instead.

### Details

* NSClient++ version: 0.5.2
* OS and Version: Windows Server 2012
* Checking from: Centreon, Icinga, OP5, ...
* Checking with: check_nrpe, check_nt, ...

### Additional Details

NSClient++ log:
```
PLEASE PASTE LOG HERE
```

**Comment by louwar** [comment]
Hi,
I have the same question and I opened a discussion today
https://github.com/mickem/nscp/discussions/815

Is there a switch to disable also TLSv1,1 and keep/use just TLSv1.2 ?

Thanks

**Comment by alexgit2k** [comment]
I searched the whole code, but NSClient++ can only disable SSL 2, 3 and TLS 1.0.

However, I discovered [SNClient+](https://github.com/ConSol-Monitoring/snclient) which is a drop-in-replacement and is able to set the minimal-version of TLS up to TLS 1.3 (https://omd.consol.de/docs/snclient/security/#tls-13).

**Comment by mickem** [comment]
This will be in the next nightly build (out in later today or tomorrow)

**Comment by louwar** [comment]
Hi there,
any news about this topic?
Our customers are pressing us, regarding that "security issue" as they see the problem.
And they're asking us to change client, but I said them to wait....

Let me know please.
Thanks

**Comment by alexgit2k** [comment]
@louwar I created a rule in the windows-firewall which blocks incoming requests:
- Rule type: Port
- Protocols and ports: TCP, 8443
- Action: Block connection
- Profile: All
- Name: NSClient++ web interface

Local connections on the machine are still possible.

Another way would be to set "allowed hosts" to 127.0.0.1, but this requires NSClient++ 0.5.3 and we are using an older version.

**Comment by mickem** [comment]
You can find latest build here: https://github.com/mickem/nscp/actions/runs/6797913278
I still have some issues with the NRPE test before I can merge this...

**Comment by louwar** [comment]
Hello.It's not that easy.The problem is not on the TCP port 8443.The problem is on TCP port 5666 which responds with SSL/TLS.It may not be a problem for us, but it is for our customers when they run their vulnerability tests and notice that their servers (Windows and Linux) respond on TCP port 5666 with SSLv2 SSLv3 TLS1 and TLS1.1
On Linux, where NRPE runs, we solved it by setting the ssl_version=TLSv1.2+ option which prevents the use of old protocols and responds only to TLS1.2 and above.With NSClient++ we can disable up to TLS1 but not TLS1.1.And it is not acceptable from our customer.We have lots of server to manage, from different customers, it is not simple to change globally firewall rules, etc.
Thanks & Regards


 
 
  Il Mar, 7 Nov, 2023 alle 19:58, ***@***.***> ha scritto:   


@louwar I created a rule in the windows-firewall which blocks incoming requests:
   
   - Rule type: Port
   - Protocols and ports: TCP, 8443
   - Action: Block connection
   - Profile: All
   - Name: NSClient++ web interface

Local connections on the machine are still possible.

Another way would be to set "allowed hosts" to 127.0.0.1, but this requires NSClient++ 0.5.3 and we are using an older version.

**Comment by mrunknownpbu** [comment]
@mickem 
would like to ask when is the new bulid will be publish

**Comment by mickem** [comment]
Unless something happens later today we will have new builds... They lack Lua and dot net as well as we ui bu apart from that everything should be working....

**Comment by mickem** [comment]
You can find the release here: https://github.com/mickem/nscp/releases/tag/0.6.0.0 It is marked as pre release due to missing features mentioned, and please do let me know any issue you experience... There is a lot of changes in thies version so some bugs are expected.

**Comment by mickem** [comment]
You can find the release here: https://github.com/mickem/nscp/releases/tag/0.6.0.0 It is marked as pre release due to mising features mentions

**Comment by mrunknownpbu** [comment]
Hi @mickem 
after install the above release 0.6.0.0
we encounter error as below

```
2023-11-22 19:52:15: error:D:\a\nscp\nscp\include\socket/connection.hpp:270: Seems we cant agree on SSL: no shared cipher (SSL routines, tls_post_process_client_hello)
2023-11-22 19:52:15: error:D:\a\nscp\nscp\include\socket/connection.hpp:271: Please review the insecure options as well as ssl options in settings.
```

below are current nsclient config

```
[/settings/NRPE/server]
allow arguments = true
allow nasty characters = true
port = 5666
payload length = 1024
allowed ciphers = ALL:!ADH:!LOW:!EXP:!MD5:!3DES:!IDEA:@STRENGTH
ssl = true
ssl options = no-sslv3,no-sslv2,no-tlsv1,no-tlsv1_1
dh = ${certificate-path}/nrpe_dh_2048.pem

[/settings/external scripts]
allow arguments = true
allow nasty characters = true
script path = 
timeout = 50


[/settings/default]
; ALLOWED CIPHERS - A better value is: ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH
allowed ciphers = ALL:!ADH:!LOW:!EXP:!MD5:!3DES:!IDEA:@STRENGTH
allowed hosts = 127.0.0.1

cache allowed hosts = true
certificate = 
timeout = 50
use ssl = true
ssl options = no-sslv3,no-sslv2,no-tlsv1,no-tlsv1_1
verify mode = none
debug = false
insecure = false

```

**Comment by mickem** [comment]
What are you useing on the remote end to check this? I.e. whats the command/config of the NRPE setup on the "other side"?

**Comment by mickem** [comment]
Try setting

```
[/settings/NRPE/server]

allowed ciphers = ALL:!MD5:@STRENGTH:@SECLEVEL=0
```

**Comment by mrunknownpbu** [comment]
@mickem 
able to server the issue 
thank you for your assistance

**Comment by louwar** [comment]
Hi @mickem 
with this option

ssl options=no-sslv2,no-sslv3,no-tlsv1,no-tlsv1_1

we blocked also TLS1.2 and TLS1.3 (still not implemented but....)
and it should not be.

![image](https://github.com/mickem/nscp/assets/149166853/b1670ac7-892a-4816-a1e4-8c082edad75b)

Why?
The goal is the ability to specify which protocol we want to use and in this moment, we should still use TLS1.2
 
Thanks

**Comment by mickem** [comment]
Not really sure what -S does, my check_nrpe has no such option.

When I run [testssl.sh](https://testssl.sh/) with the following config:
```ini
[/modules]
NRPEServer = enabled
[/settings/NRPE/server]
allowed ciphers = ALL:!MD5:@STRENGTH:@SECLEVEL=0
insecure = true
ssl = true
ssl options = no-sslv3,no-sslv2,no-tlsv1,no-tlsv1_1
```


I get:
![image](https://github.com/mickem/nscp/assets/1434697/29f7e4ca-aa93-4d03-991d-2a3b8d24c7a8)

**Comment by louwar** [comment]
![image](https://github.com/mickem/nscp/assets/149166853/871c75dc-acbb-4f49-ad7c-c1cc2e89cce0)
![image](https://github.com/mickem/nscp/assets/149166853/f8af2780-4450-48e8-8e4f-b29dabf3a9ec)

**Comment by mickem** [comment]
Great
