### ISSUE TITLE
Firewall blocking Drive and Memory Usage!?

### ISSUE THREAD

**Issue by nagwindmon** [mickem/nscp#82]
Installed NSClient Agent (ver NSCP-0.4.3.88-x64) on Windows OS machines, 2 of them are behind firewall

Machines NOT behind Firewall behaving as expected, reporting CPU, Uptime, Memory, Disk usages:
![memorycpuallgood](https://cloud.githubusercontent.com/assets/10515775/5778484/9afeeb42-9d69-11e4-9376-5c67c15b85f2.jpg)

2 servers behind Firewall are struggling to get Status for Disk and Memory Usage, but CPU Status available:
![diskmemoryusage](https://cloud.githubusercontent.com/assets/10515775/5778432/40c5cbc8-9d69-11e4-9ba9-e07a4dae26cb.jpg)

I have confirmed that both ports are open 12489 and 5666
Any ideas, Should I go back to version v0.4.1.105? 
Thank you

**Comment by mathieuchateau** [comment]
Hello,

invalid drive suggest nagios reached the nsclient but issue in config

For memory, maybe this one use or not SSL option in nrpe check?

Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-16 16:46 GMT+01:00 nagwindmon <notifications@github.com>:

**Comment by nagwindmon** [comment]
Here is nsclient.ini:

# If you want to fill this file with all avalible options run the following command:
#   nscp settings --generate --add-defaults --load-all
# If you want to activate a module and bring in all its options use:
#   nscp settings --activate-module <MODULE NAME> --add-defaults
# For details run: nscp settings --help


; Undocumented section
[/settings/default]

; ALLOWED HOSTS - A comaseparated list of allowed hosts. You can use netmasks (/ syntax) or * to create ranges.
allowed hosts = 11.48.23.67


; Undocumented section
[/settings/NRPE/server]

; VERIFY MODE - Comma separated list of verification flags to set on the SSL socket.  none	The server will not send a client certificate request to the client, so the client will not send a certificate. peer	The server sends a client certificate request to the client and the certificate returned (if any) is checked. fail-if-no-cert	if the client did not return a certificate, the TLS/SSL handshake is immediately terminated. This flag must be used together with peer. peer-cert	Alias for peer and fail-if-no-cert. workarounds	Various bug workarounds. single	Always create a new key when using tmp_dh parameters. client-once	Only request a client certificate on the initial TLS/SSL handshake. This flag must be used together with verify-peer   
verify mode = peer-cert

; ALLOW INSECURE CHIPHERS and ENCRYPTION - Only enable this if you are using legacy check_nrpe client.
insecure = false


; Undocumented section
[/modules]

; NRPEServer - A server that listens for incoming NRPE connection and processes incoming requests.
NRPEServer = 1

; CheckSystem - Various system related checks, such as CPU load, process state, service state memory usage and PDH counters.
CheckSystem = 1

; NSClientServer - A server that listens for incoming check_nt connection and processes incoming requests.
NSClientServer = 1

; CheckExternalScripts - Execute external scripts
CheckExternalScripts = 1

; CheckHelpers - Various helper function to extend other checks.
CheckHelpers = 1

; CheckEventLog - Check for errors and warnings in the event log.
CheckEventLog = 1

; CheckNSCP - Use this module to check the healt and status of NSClient++ it self
CheckNSCP = 1

; CheckDisk - CheckDisk can check various file and disk related things.
CheckDisk = 1


; A list of templates for wrapped scripts.
%SCRIPT% will be replaced by the actual script an %ARGS% will be replaced by any given arguments.
[/settings/external scripts/wrappings]

; POWERSHELL WRAPPING - 
ps1 = cmd /c echo scripts\\%SCRIPT% %ARGS%; exit($lastexitcode) | powershell.exe -command -

; BATCH FILE WRAPPING - 
bat = scripts\\%SCRIPT% %ARGS%

; VISUAL BASIC WRAPPING - 
vbs = cscript.exe //T:30 //NoLogo scripts\\lib\\wrapper.vbs %SCRIPT% %ARGS%


; A list of aliases available.
An alias is an internal command that has been predefined to provide a single command without arguments. Be careful so you don't create loops (ie check_loop=check_a, check_a=check_loop)
[/settings/external scripts/alias]

; alias_volumes_loose - Alias for alias_volumes_loose. To configure this item add a section called: /settings/external scripts/alias/alias_volumes_loose
alias_volumes_loose = check_drivesize

; alias_volumes - Alias for alias_volumes. To configure this item add a section called: /settings/external scripts/alias/alias_volumes
alias_volumes = check_drivesize

; alias_up - Alias for alias_up. To configure this item add a section called: /settings/external scripts/alias/alias_up
alias_up = check_uptime

; alias_sched_all - Alias for alias_sched_all. To configure this item add a section called: /settings/external scripts/alias/alias_sched_all
alias_sched_all = check_tasksched show-all "syntax=${title}: ${exit_code}" "crit=exit_code ne 0"

; alias_process_stopped - Alias for alias_process_stopped. To configure this item add a section called: /settings/external scripts/alias/alias_process_stopped
alias_process_stopped = check_process "process=$ARG1$" "crit=state != 'stopped'"

; alias_service - Alias for alias_service. To configure this item add a section called: /settings/external scripts/alias/alias_service
alias_service = check_service

; alias_process_hung - Alias for alias_process_hung. To configure this item add a section called: /settings/external scripts/alias/alias_process_hung
alias_process_hung = check_process "filter=is_hung" "crit=count>0"

; alias_process_count - Alias for alias_process_count. To configure this item add a section called: /settings/external scripts/alias/alias_process_count
alias_process_count = check_process "process=$ARG1$" "warn=count > $ARG2$" "crit=count > $ARG3$"

; alias_process - Alias for alias_process. To configure this item add a section called: /settings/external scripts/alias/alias_process
alias_process = check_process "process=$ARG1$" "crit=state != 'started'"

; alias_mem - Alias for alias_mem. To configure this item add a section called: /settings/external scripts/alias/alias_mem
alias_mem = check_memory

; alias_file_size - Alias for alias_file_size. To configure this item add a section called: /settings/external scripts/alias/alias_file_size
alias_file_size = check_files "path=$ARG1$" "crit=size > $ARG2$" "top-syntax=${list}" "detail-syntax=${filename] ${size}" max-dir-depth=10

; alias_event_log - Alias for alias_event_log. To configure this item add a section called: /settings/external scripts/alias/alias_event_log
alias_event_log = check_eventlog

; alias_service_ex - Alias for alias_service_ex. To configure this item add a section called: /settings/external scripts/alias/alias_service_ex
alias_service_ex = check_service "exclude=Net Driver HPZ12" "exclude=Pml Driver HPZ12" exclude=stisvc

; alias_disk - Alias for alias_disk. To configure this item add a section called: /settings/external scripts/alias/alias_disk
alias_disk = check_drivesize

; alias_cpu_ex - Alias for alias_cpu_ex. To configure this item add a section called: /settings/external scripts/alias/alias_cpu_ex
alias_cpu_ex = check_cpu "warn=load > $ARG1$" "crit=load > $ARG2$" time=5m time=1m time=30s

; alias_file_age - Alias for alias_file_age. To configure this item add a section called: /settings/external scripts/alias/alias_file_age
alias_file_age = check_files "path=$ARG1$" "crit=written > $ARG2$" "top-syntax=${list}" "detail-syntax=${filename] ${written}" max-dir-depth=10

; alias_cpu - Alias for alias_cpu. To configure this item add a section called: /settings/external scripts/alias/alias_cpu
alias_cpu = check_cpu

; alias_disk_loose - Alias for alias_disk_loose. To configure this item add a section called: /settings/external scripts/alias/alias_disk_loose
alias_disk_loose = check_drivesize

; alias_sched_task - Alias for alias_sched_task. To configure this item add a section called: /settings/external scripts/alias/alias_sched_task
alias_sched_task = check_tasksched show-all "filter=title eq '$ARG1$'" "detail-syntax=${title} (${exit_code})" "crit=exit_code ne 0"

; alias_sched_long - Alias for alias_sched_long. To configure this item add a section called: /settings/external scripts/alias/alias_sched_long
alias_sched_long = check_tasksched "filter=status = 'running'" "detail-syntax=${title} (${most_recent_run_time})" "crit=most_recent_run_time < -$ARG1$"

**Comment by mathieuchateau** [comment]
I would rather do these tests:


   - from nagios: manually try the check_nrpe call, corresponding to your
   nagios one
   - from windows: call nscp test and then try manually commands it should
   receive from nagios



Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-16 17:21 GMT+01:00 nagwindmon <notifications@github.com>:

**Comment by nagwindmon** [comment]
- from windows: call nscp test and then try manually commands it should
   receive from nagios
Unfortunately not sure how to do that, is it somewhere from this screen:?
![nagiosadminwinui](https://cloud.githubusercontent.com/assets/10515775/5781106/f7a7bbbc-9d7d-11e4-8eb5-d9cb550a1d04.png)

Please let me know how can I perform this test!

**Comment by mathieuchateau** [comment]
from nagios: check_nrpe -H X.X.X.X alias_disk

from windows:
launch cmd with "run as administrator"
go to nsclient++ install folder
from there: nscp test
once loaded, type in alias_disk + press enter

this way you can try sending from nagios, and execute locally what is
expected


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-16 18:50 GMT+01:00 nagwindmon <notifications@github.com>:

**Comment by nagwindmon** [comment]
ok, got it
here what I get back:
alias_disk +
d rvice\NSClient++.cpp:933  Injecting: alias_disk...
d kExternalScripts.cpp:257  Arguments: MinWarn=10% MinCrit=5% CheckAll FilterType=FIXED
d rvice\NSClient++.cpp:933  Injecting: checkdrivesize...
d rvice\NSClient++.cpp:958  Result checkdrivesize: OK
d rvice\NSClient++.cpp:958  Result alias_disk: OK
l ce\simple_client.hpp:80   OK:OK: All drives within bounds.
l ce\simple_client.hpp:82    Performance data: 'C:\ %'=56%;10;5 'C:\'=102.9G;23.28;11.64;0;232.88

But this is executed locally, on Win server I'm at right now, to do so for one of those Remote Servers, I need remote in or I can do so remotely providing IP from where I'm now?

**Comment by mathieuchateau** [comment]
better going to the remote one through rdp and execute again locally.

then do the same from nagios with check_nrpe

then if all ok, check which command is using your nagios

Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-16 19:14 GMT+01:00 nagwindmon <notifications@github.com>:

**Comment by nagwindmon** [comment]
thank you Mathieu for working with me! appreciate it... just one more question: how/where can I check on exact command my Nagios is using for Disk and Memory metrics?

**Comment by mathieuchateau** [comment]
I am not using nagios XI, but i guess it generates config files in the end.
in something like /etc/nagios/services.conf, you should find your test
You should of course too from the web interface, but i don't know where to
look for in nagios XI

Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-16 19:25 GMT+01:00 nagwindmon <notifications@github.com>:

**Comment by nagwindmon** [comment]
Nagios Linux server is managed by someone else, I will check, thanks again!

**Comment by nagwindmon** [comment]
Update:
Going back with v0.4.1.105 did make a difference.
Disk space and Memory usages are now being reported along with all other metrics.
Merci encore une fois!

**Comment by mathieuchateau** [comment]
Hello,

main differences are on settings and security by crypting communication
through SSL by default.

You now have 2 ways:

   - Keep on 0.4.1:
      - You won't have any real support (answer would be "please upgrade
      first")
      - You won't have new features
   - Upgrade to 0.4.3:
      - As you didn't go on 0.4.2, the upgrade path is significant
      - You will need at least one computer (test one as possible), to get
      the new right configuration

Did you read this ?
http://www.nsclient.org/2015/01/05/0-4-3-released-a-few-weeks-ago/

To be successful, both nagios side and nsclient side need to be checked and
updated so everything expected will work

I was on 0.4.1 for long time, i switched to 0.4.3 earlier this month. some
hours of work were needed to get both ok


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-17 3:10 GMT+01:00 nagwindmon <notifications@github.com>:

**Comment by mickem** [comment]
To diagnose this I would need the actual commands your executing as well as which protocol your using.

I have just verified that check dick (and what not) works handsomly via check_nt (which I think your using) on 0.4.3:

```
check_nt -H 192.168.0.193 -p 12489 -v USEDDISKSPACE -l c -w 80 -c 90
c:\ - total: 223.47 Gb - used: 210.29 Gb (94%) - free 13.18 Gb (6%) | 'c:\ Used Space'=210.29Gb;178.78;201.12;0.00;223.47
```

So it is not a general problem...

**Comment by mickem** [comment]
Closing this, please reopen with more details

**Comment by StanleyDerLurch** [comment]
Hi,
I've a funny error with check_nt.
If I run "./check_nt -H xxx -p 12489 -s xxx -v USEDDISKSPACE -l e", I get NSClient - Error: Invalid return from command: check_drivesize.
If I run "./check_nt -H xxx -p 12489 -s xxx -v USEDDISKSPACE -l f", I get f:\ total: bla seems to working fine.

Installed NSClient version is 0.4.3, both logical harddrives are bigger than 3TB... I don't know why f:\ works and e:\ not

hope, some1 can help, thx
