### ISSUE TITLE
%(status) in %(detail-list) giving OK, while CRITICAL?

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#89]
Hello,

I created the following check to check all drivesizes. I made a test disk (E:) and copied some stuff on it, to make the service go critical.

 /usr/local/nagios/libexec/check_nrpe -H windows_server -t 30 -c Check_Drivesize -a ignore-unreadable drive=* "filter=(type in('fixed') AND drive NOT LIKE '\\?\')" "warn=( free < 20% )" "crit=( free < 10% )" 'top-syntax=%(status): Drivesizes {%(detail_list)}' 'detail-syntax={%(status): Drive %(drive) Total: %(size), Used: %(used), Free: %(free)}'
CRITICAL: Drivesizes {critical({OK: Drive E:\ Total: 1.997GB, Used: 1.807GB, Free: 195.031MB}), {OK: Drive C:\ Total: 39.656GB, Used: 13.08GB, Free: 26.577GB}}|'C:\ free'=26.57663GB;7.93124;3.96562;0;39.65624 'C:\ free %'=67%;19;9;0;100 'E:\ free'=195.03125MB;408.99921;204.4996;0;2044.99609 'E:\ free %'=9%;19;9;0;100

As you can see I set detail-syntax like this: 'detail-syntax={%(status): Drive %(drive) Total: %(size), Used: %(used), Free: %(free)}'

But the output is CRITICAL: Drivesizes {critical({OK: Drive E:\ Total: 1.997GB, Used: 1.807GB, Free: 195.031MB}), {OK: Drive C:\ Total: 39.656GB, Used: 13.08GB, Free: 26.577GB}}

So it seems in detail-syntax status is always set and if we specify the status with %(status) it syas OK, while in fact it it CRITICAL?

Or am I doing something wrong? I would like the status at the start of each detail, is it possible?

Thanks and grtz.

Willem

**Comment by mickem** [comment]
Ahh...

The %(status) (and various other keywords like list, and such) are only applicable on the "top level" so they will not do what you want (currently).

Perhaps support for details levels should be added?
Not sure why it is useful?

But then again right now it makes little or no sense as it will reflect the current worst state as the list is iterated through...

So is this something we want?

**Comment by willemdh** [comment]
Hey Michael,

I thought it was possible, as I saw this in check_cpu documentation as possible value. (http://docs.nsclient.org/reference/CheckSystem.html#CheckSystem.check_cpu)

Now I know it is not supported, it's not something I would choose as high priority. What I would like to be developped is the perf-config
(CheckSystem, check_cpu)
Performance data generation configuration
TODO: obj ( key: value; key: value) obj (key:valuer;key:value)

In your documentation it is said "to do".

Because for example for check_disksize monitoring we won't really need the percentage diskspace used, ony the used in GB perfdata and the total disksize in GB. Am I right this is not possible yet? 

Grtz and thanks.

Willem

**Comment by mickem** [comment]
The TODO is really that it is undocumented... So it works, and you can find some refernce to it here and there in various comments...
I just opened #91 to track that issue

**Comment by willemdh** [comment]
Thanks michael, 

I'll close this issue and will leave it up to you if you want to give us the %(status) option in the detail syntax or not. 

Grtz

Willem
