### ISSUE TITLE
Add documentation about perf-config

### ISSUE THREAD

**Issue by mickem** [mickem/nscp#91]
Performance data configuration is missing from the documntation

**Comment by willemdh** [comment]
Michael,

Could you please give me an example how I would reconfigure this check_drivesize:

/usr/local/nagios/libexec/check_nrpe -H windows-server -t 30 -c Check_Drivesize -a ignore-unreadable drive=* "filter=(type in('fixed') AND drive NOT LIKE '\\?\')" "warn=( free < 10% )" "crit=( free < 5% )" 'top-syntax=%(status): Drivesizes {%(detail_list)}' 'detail-syntax= {Drive %(drive) Total: %(size), Used: %(used), Free: %(free)}'
OK: Drivesizes { {Drive C:\ Total: 39.656GB, Used: 13.198GB, Free: 26.458GB},  {Drive E:\ Total: 1.997GB, Used: 1.407GB, Free: 604.027MB}}|'C:\ free'=26.45827GB;3.96562;1.98281;0;39.65624 'C:\ free %'=66%;9;4;0;100 'E:\ free'=604.02734MB;204.4996;102.2498;0;2044.99609 'E:\ free %'=29%;9;4;0;100

So that the perfdata only contains the used space in GB and the total space in GB for both disks. As you can see the above check returns one disk in GB and one disk in MB, which makes the graphs very confusing.

Thanks!

Willem

**Comment by mickem** [comment]
Like:
```
check_drivesize "perf-config=*(unit:g)"
```

**Comment by willemdh** [comment]
"perf-config=*(unit:g)" => Did not do the trick Michael => Output is like this:
|'C:\ free'=0.00002g;0;0;0;0.00003 'C:\ free %'=67%;9;4;0;100 'E:\ free'=0g;0;0;0;0 'E:\ free %'=29%;9;4;0;100

"perf-config=*(unit:GB)" => Kind of did the trick
|'C:\ free'=26.92205GB;3.96562;1.98281;0;39.65624 'C:\ free %'=67%;9;4;0;100 'E:\ free'=0.58987GB;0.1997;0.09985;0;1.99706 'E:\ free %'=29%;9;4;0;100

Except for the part where i do not need perfdata in percentages. How would I omit the 'free %' perfdata?

Grtz

Willem

**Comment by mickem** [comment]
Not 100% sure here (can check tonight) something along the lines of:

```
check_drivesize ... "perf-config=*(unit:g),%(ignore)"
```

In essence this works a bit like "css": <keyword> matches the name of the performance data, <option> is the "option" to set, and <value> is the value (can be omitted for boolean flags.

The syntax is:
```
perf-config=<keyword>(<option>:<value>),<keyword>(<option>:<value>)"
```

I think I will have time to write up a documentation section about this tonight...

**Comment by mickem** [comment]
The correct syntax is:
```
check_drivesize ... "perf-config=*(unit:G) used %(ignored:true)"
```

Units were case sensetive (upper case) which I will be fixed in the next build.

// Michael Medin

**Comment by mickem** [comment]
FIY, documentation has now been written and will be updated as soon as I have done the next build...
Will ping you back with a link...

**Comment by mickem** [comment]
Docs are now live: http://docs.nsclient.org/manual/nscp_checks.html#performance-data-configuration

**Comment by willemdh** [comment]
Thanks Michael, I got the perfdata without the % working, but you never answered my question concerning the total space of the disk. 
Is it possible to pass the total disk space in the perfdata for each disk? If so how? :)

**Comment by mickem** [comment]
Not sure I understand, do you mean the total size of each disk? You have that in max/min now right?
Or do you mean the sum of all disks? (which you can get if you add the totals (or some such) option)

**Comment by willemdh** [comment]
I mean the total size of each disk in for example:
Check_Drivesize -a ignore-unreadable drive=* "filter=(type in('fixed') AND drive NOT LIKE '\?\')" 

We discussed htis internally and colleagues  would like to know when a disk was expanded. The graph should show the total disk space of each disk together with the used space.

**Comment by mickem** [comment]
The maximum line is the disk size right?
So if you plot the maximum you will see the change?

**Comment by willemdh** [comment]
I'm not quite sure what you mean with plot the maximum line? The maximum of what? At this time the only perfdata I can pull is free space and used space, in GB or in %. I just want the total disk size.

**Comment by mickem** [comment]
Your C drive:
```
...'C:\ free'=26.92205GB;3.96562;1.98281;0;39.65624...
```
Thats interpreted as:
26.9Gb free
We warn if there is less then 3.96Gb
We give a critical alert if there is less then 1.98Gb
The minimum value (bottom of the graf) is 0Gb
The maximum value (top of the graph) is 39.6Gb <--- This is the drive size...

The maximum value is the size of the drive, so plotting that would give you a graph showing the maximum, if the drive is changed (bigger/smaller) the line would shift...

So if you graph that line you should see the size of the drive right?

// Michael Medin

**Comment by willemdh** [comment]
I'll have to discuss this on the Nagios forum as I don't know if I can plot the max value with Highcharts. I'll come back when I have more information.

**Comment by mickem** [comment]
I can probably make a wrapper command which unpacks the maximum value as a separate performance counter if you cant just modify the graph..

**Comment by willemdh** [comment]
Well, I discussed this on the Nagios forum and apparently it is not possible to plot the maximum with Highcharts. As we would like to continue usign Highcharts, a wrapper command would probably be nice. :)

**Comment by mickem** [comment]
I'll see what I can do...

Probably something along the lines of
```
transform_perf mode=extract field=max "replace=free=max" command=check_drivesize
...'C:\ free'=26.92205GB;3.96562;1.98281;0;39.65624 'C:\ max'=39.65624GB;0;0;0;39.65624...
```

Would that do it?

**Comment by willemdh** [comment]
It seems that would do it indeed, except that we would need 'C:\ used' and 'C:\max', which is more logical to read in a graph. I'm not sure how to put your example in use however. Or is this something for a next version of nsclient?

At this moment I have:

check_nrpe -H $HOSTADDRESS$ -t 30 -c Check_Drivesize -a
ignore-unreadable drive=* "filter=(type in('fixed') AND drive NOT LIKE '\\?\')" "warn=( used > 90% )" "crit=( used > 95% )" 'top-syntax=%(status): Drivesizes {%(detail_list)}' 'detail-syntax= {Drive %(drive) Total: %(size), Used: %(used), Free: %(free)}' "perf-config=*(unit:G) used %(ignored:true)"

How would I use "transform_perf mode=extract field=max "replace=free=max" command=check_drivesize" in my example?

**Comment by mickem** [comment]
Added the command now (will be in the next nightly build, which will be out in few hours)...

Works like this:
```
xform_perf mode=extract field=max replace=used=max command=Check_Drivesize arguments ignore-unreadable drive=* "filter=(type in('fixed') AND drive NOT LIKE '\\?\\')" "warn=( used > 90% )" "crit=( used > 95% )" "top-syntax=%(status): Drivesizes {%(detail_list)}" "detail-syntax= {Drive %(drive) Total: %(size), Used: %(used), Free: %(free)}" "perf-config=*(unit:G) used %(ignored:true)"
L        cli OK: OK:
L        cli  Performance data: 'C:\ used'=207.99598G;201.12362;212.29716;0;223.47069 'D:\ used'=403.77336G;419.1829;442.47084;0;465.75878 'C:\ max'=223.47069G;201.12362;212.29716;0;223.47069 'D:\ max'=465.75878G;419.1829;442.47084;0;465.75878
```

**Comment by mickem** [comment]
This should be fixed in nightly build 0.4.3.104.

**Comment by willemdh** [comment]
Hey Michael,

i'm not reall sure how I would have to use this new command. I've tried using it in the command. Should I use it in the Nagios command or is this something for in the nsclient.ini?
CheckHelper is set to 1 in the nsclient.ini

Could you please provide an example hos to make use of this checkhelper command form the Nagios command line?

/usr/local/nagios/libexec/check_nrpe -H <windows-server> -t 30 -c xform_perf mode=extract field=max replace=used=max command=Check_Drivesize arguments ignore-unreadable drive=* "filter=(type in('fixed') AND drive NOT LIKE '\\?\\')" "warn=( used > 90% )" "crit=( used > 95% )" "top-syntax=%(status): Drivesizes {%(detail_list)}" "detail-syntax= {Drive %(drive) Total: %(size), Used: %(used), Free: %(free)}" "perf-config=*(unit:G) used %(ignored:true)"

Gives Missing command
I'm a bit lost how and where to use "xform_perf mode=extract field=max replace=used=max"

Thanks.

Grtz

**Comment by mickem** [comment]
(Sorry, forgot to click send)

Looks like your missing a -a, but the sample I gave should work:

With -a
```
/usr/local/nagios/libexec/check_nrpe -H -t 30 -c xform_perf -a mode=extract field=max replace=used=max command=Check_Drivesize arguments ignore-unreadable drive=* "filter=(type in('fixed') AND drive NOT LIKE '\?\')" "warn=( used > 90% )" "crit=( used > 95% )" "top-syntax=%(status): Drivesizes {%(detail_list)}" "detail-syntax= {Drive %(drive) Total: %(size), Used: %(used), Free: %(free)}" "perf-config=*(unit:G) used %(ignored:true)"
```

My command above would be:
```
/usr/local/nagios/libexec/check_nrpe -H -t 30 -c xform_perf -a mode=extract field=max replace=used=max command=Check_Drivesize arguments ignore-unreadable drive=* "filter=(type in('fixed') AND drive NOT LIKE '\\?\\')" "warn=( used > 90% )" "crit=( used > 95% )" "top-syntax=%(status): Drivesizes {%(detail_list)}" "detail-syntax= {Drive %(drive) Total: %(size), Used: %(used), Free: %(free)}" "perf-config=*(unit:G) used %(ignored:true)"
```

**Comment by willemdh** [comment]
Hey Michael,

Sorry for the late answer. I've been trying your latest command on 0.4.3.143 and although it does seem to output max perfdata, it is no longer showing any top or detail syntax.
```text
sudo /usr/local/nagios/libexec/check_nrpe -H server -t 30 -c xform_perf -a mode=extract field=max replace=used=max command=Check_Drivesize arguments drive=c: "warn=( used > 90% )" "crit=( used > 95% )" "top-syntax=%(status): Drivesizes {%(detail_list)}" "detail-syntax= {Drive %(drive) Total: %(size), Used: %(used), Free: %(free)}" "perf-config=*(unit:G) used %(ignored:true)"
```
Results in:
```text
OK:  |'c: used'=273.53474G;376.80116;397.73456;0;418.66796 'c: max'=418.66796G;376.80116;397.73456;0;418.66796
```

While I was expecting:
```text
OK: Drivesizes { {Drive c: Total: 418.668GB, Used: 273.536GB, Free: 145.132GB}}|'c: used'=273.53571G;376.80116;397.73456;0;418.66796 'c: max'=418.66796G;376.80116;397.73456;0;418.66796
```

Am I missing something?
