### ISSUE TITLE
Windows 2012 "trigger start" services are reported as stopped.

### ISSUE THREAD

**Issue by snkutlu** [mickem/nscp#92]
Hi,

Issue #700 in http://www.nsclient.org/nscp/ticket/700 states that this was fixed in v0.4.2.77 but with 0.4.3.88 I get "critical" when I execute following from Nagios server to the Windows2012: 

 /usr/lib64/nagios/plugins/check_nrpe -H winhost -c CheckServiceState -a CheckAll
CRITICAL: RemoteRegistry: stopped delayed ()

RemoteRegistry service indeed set to "Automatic (Trigger Start)"

Is the fix introduced with v0.4.2.77 somehow disappeared with the latest release or am I missing some special configuration to ignore "Trigger Start" services?

Thanks in advance...
-Suleyman Kutlu

**Comment by mickem** [comment]
Will be fixed in the next build (out int a bit)

**Comment by mickem** [comment]
Build 0.4.3.92 (under nightly builds) should fix this issue, please confirm and reopen if not fixed.

**Comment by snkutlu** [comment]
Yes, fixed. Thx for quick resolution.
