### ISSUE TITLE
0.4.3.88 - nsclient.log is put in C:\

### ISSUE THREAD

**Issue by box293** [mickem/nscp#94]
Standard Install

```
/settings/log
file name = /nsclient.log
```

The file ends up in the root of the drive on a Windows machine.

**Comment by mickem** [comment]
Sorry, my bad...

**Comment by mickem** [comment]
Will be fixed in the next build

**Comment by mickem** [comment]
0.4.3.102 should fix (and mitigate) this issue, please reopen if issue still persists...
