### ISSUE TITLE
Output different in 0.4.3.106, top-syntax and detail-syntax issue?

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#98]
Hey,

Just updated an agent from 0.4.3.86 to 0.4.3.106 and the output of all my checks is all like this now: "OK All 2 drive(s) are ok" "OK: CPU load is ok."
Where before it was
"OK: Drivesizes { {Drive C:\ Total: 39.656GB, Used: 13.27GB, Free: 26.386GB}, {Drive E:\ Total: 1.997GB, Used: 1.407GB, Free: 604.004MB}}"
"OK: CPU Stats {(total, avg 1m: 8%), (total, avg 5m: 3%)}"

Argument for the check_cpu is this:
"filter=core = 'total'" time=1m time=5m "warn=load > 90" "crit=load > 95"  'top-syntax=%(status): CPU Stats {%(list)}' 'detail-syntax=(%(core), avg %(time): %(load)%)'
For check_drivesize
ignore-unreadable drive=* "filter=(type in('fixed') AND drive NOT LIKE '\\?\')" "warn=( free < 10% )" "crit=( free < 5% )" 'top-syntax=%(status): Drivesizes {%(detail_list)}' 'detail-syntax= {Drive %(drive) Total: %(size), Used: %(used), Free: %(free)}'

It seems like top-syntax and detail-syntax are no longer working?

Grtz

**Comment by mickem** [comment]
hrumph... I am starting to feel a little ashamed 0.4.3... 

Maybe I broke them, will fix ASAP... 
The idea was only the empty ones should have changed... ie where you got "ok" only...

// Michael Medin

**Comment by willemdh** [comment]
Don't be ashamed. It's a nightly build. Accidents happen. This was only on a test machine. I'll wait for the fix and will let you know if it works.

**Comment by mickem** [comment]
0.4.3.108 should fix this, please reopen if not...

**Comment by willemdh** [comment]
I just confirmed syntax is working again as intended on 0.4.3.127. Thanks for the quick fix.
