### ISSUE TITLE
Disk I/O Read/Write Performance Data lack a UOM

### ISSUE THREAD

**Issue by Kyle0341** [mickem/nscp#99]
I am currently using NSClient++ with Op5 Monitor to track Disk I/O Read and Write statistics but the performance data lacks the 'seconds' unit of measurement on the performance data. I believe this is causing my graphs to look rather difficult to read.

When I look at the graphs, the Last, Max and Average values within the chart show numbers in the teens to the thousands with a UOM of 'm' and I am not sure what to make of this.

Command:
$USER1$/check_nrpe -u -s -H $HOSTADDRESS$ -t 20 -c CheckCounter -a "Counter=\PhysicalDisk(_Total)\Avg. Disk sec/Read" ShowAll MaxWarn=1 MaxCrit=5

Output:
_USER1_/check_nrpe -u -s -H 10.212.78.235 -t 20 -c CheckCounter -a "Counter=\PhysicalDisk(_Total)\Avg. Disk sec/Read" ShowAll MaxWarn=1 MaxCrit=5
Result code: 0
OK: \PhysicalDisk(_Total)\Avg. Disk sec/Read: 0.0336375|'\PhysicalDisk(_Total)\Avg. Disk sec/Read'=0.033637485275209225;1;5

I believe it should be "\PhysicalDisk(_Total)\Avg. Disk sec/Read'=0.033637485275209225 Seconds;1;5"

Am I possibly misunderstanding something or missing a flag in my command line? I thought a UOM is needed to make the graphing appropriate to the data being gathered.

**Comment by mickem** [comment]
It would be all but impossible to provide the UOM automatically since the performance data can be anything.

I could add a perf-config option to define the UOM though: perf-config=*(unit:Seconds)

First you need to move over to the new syntax:
```
USER1/check_nrpe -u -s -H IP -t 20 -c check_pdh -a "counter=\PhysicalDisk(_Total)\Avg. Disk sec/Read" show-all "warn=value>1" "crit=value>2" perf-config=*(suffix:none)
```

Then you could extend this with the UOM:
```
USER1/check_nrpe -u -s -H IP -t 20 -c check_pdh -a "counter=\PhysicalDisk(_Total)\Avg. Disk sec/Read" show-all "warn=value>1" "crit=value>2" perf-config=*(suffix:none;unit:Seconds)
```

**Please note:** This is a suggestion, it currently does not work this way.

**Comment by Kyle0341** [comment]
Mickem, 

      I'm a little confused by your note, not sure why to suggest something which doesn't work. Second, It appears I won't be able to use this at this time as your perf-config option was added on '2015-01-06' according to 'http://docs.nsclient.org/whatsnew/changelog.html' and I believe we are on version 3.9 so the option isn't available. I will speak to our vendor about an updated client.

Either way I do appreciate the response and hope I can find a way to test this on a 4.3 client soon.

**Comment by mickem** [comment]
Would adding an option like I described solve your problem?

**Comment by mickem** [comment]
Ohh...
This actually already works...

````
check_pdh "counter=\\700(_Total)\\702" "warn=value>80" "critical=value!=90" perf-config=*(suffix:none;unit:Seconds)
L        cli CRITICAL: CRITICAL: \700(_Total)\702 = 1
L        cli  Performance data: '\700(_Total)\702none'=1Seconds;80;90
```

**Comment by Kyle0341** [comment]
Mickem,

     What you did is exactly what I needed, I won't be able to test as I need a newer client but as long as the graph reflects the UOM, then I am all set. Thanks!
